### ISSUE TITLE
Rendering into child's named outlet "blanks out" content in parent's named outlet

### ISSUE THREAD

**Issue by kalmanh** [emberjs/ember.js#10104]
Named outlet in the parent that is overwritten in a child is blank when you go back to the parent

See the following JSBIN - http://emberjs.jsbin.com/poquyo/1/edit?html,js,console,output

Steps to reproduce:

1. Notice SIDEBAR being displayed
2. Click Settings link - ADMIN is displayed instead
3. Click Home link to go back to 'application'
4. SIDEBAR is gone!!!

This was asked on SO - http://stackoverflow.com/questions/27727232/ember-sidebar-returning-from-admin-sidebar-to-normal

**Comment by kalmanh** [comment]
I came up with a "workaround" using a component instead of a named outlet

http://emberjs.jsbin.com/cuzuxu/3/edit?html,js,output

**Comment by stefanpenner** [comment]
@ef4 is this handled by your recent implements?

@kalmanh can you confirm this on canary/release?

**Comment by ef4** [comment]
This is not really a bug so much as a fundamental limitation with named outlets. They are painfully stateful and tricky, and switching to a component was the right solution.

When you enter the admin route, it chooses to render its own content into the sidebar. When you leave the admin route, that content gets cleaned up as it should. But you are not re-entering the application route (you never left it), so it is not appropriate for the application route's renderTemplate to run again. So an empty sidebar is the "correct" outcome.

Personally, I favor deprecating named outlets entirely so that they stop confusing people. I can't think of anything they can do that components and services can't do better.

**Comment by kalmanh** [comment]
Switching to component definitely "felt" right, but I thought I was missing something about named outlets. I am glad that switching to a component was the right thing to do. :+1:
