### ISSUE TITLE
queryParams + route.refresh() + debounce: Ember.js reverts a property.

### ISSUE THREAD

**Issue by bfreis** [emberjs/ember.js#10120]
Hello,

Here's the scenario:
- a controller with a property
- the property is bound to the queryParams
- the property is also bound to a text field
- the property is observed for changes
- the observer sends an action through Ember.run.debounce (to avoid sending multiple times the action while the user is typing on the text field)
- the action is handled in the Route, and does a refresh()
- the Route's model hook calls some Ember.$.getJSON, and this call takes some time to complete

In this scenario, while I type on the text field, Ember will sometimes overwrite whatever I'm typing.

The issue seems to be extremely timing sensitive -- sometimes I observe it, sometimes I don't, depending on the speed I type. I created a jsbin that tries to simulate the issue. I've tuned the timings on the simulation such that I observe the issue every single time. Things might differ on your machines, so please adjust the timings accordingly.

Here's the simulation: http://jsbin.com/befivulafe/1/edit?html,js,output

The simulation works by simulating me typing the string "aaaa", then selecting everything (cmd+a), then typing the string "bbbb". When the issue is triggered, you'll see that "aaaa" is typed, then "bbbb" is typed, but the final value on the text field is "aaaa".

---

I did some debugging, but I'm not sure I'm on the right track -- especially because my first contact ever with Ember was like 2 days ago.

From my debugging session, the issue seems to be caused by line 24590 of ember.js v1.9.1 (the one that's linked to in that jsbin). It is inside  `Route#setup`:

```
if (transition) {
  var qpValues = getQueryParamsFor(this, transition.state);
  controller.setProperties(qpValues);
}
```

This `transition.state` object seems to contain 2 sets of queryParams. One is called `queryParamsFor`, the other is called `fullQueryParams` (or something like that). The first one, which is quickly returned by `getQueryParamsFor` contains _the old_ value of the query params, while the other one contains the correct value.

Hope this is enough for you to analyze further this issue.

Thanks!
ps: just so you know, the goal of my code is to have a "filter" text field on a list. When the user types in that text field, I need to debounce the typing, and then send a request to the server, and refresh the list based on the results -- in case my intent wasn't clear...

**Comment by bfreis** [comment]
FYI I tried with 1.10.0-beta.3 as well as Canary and I see the same issue.

**Comment by ahacking** [comment]
This kind of question is probably best asked on StackOverflow.

My guess is the route is probably setting the query params on the controller when the transition completes, overwriting the value the user has entered in the meantime.

When you have two sources of truth, ie the user input and the route/url param you will have unavoidable timing issues to deal with.  You may want to think about separating the user property from the route param property so that you can better control which one is authoritative at any time. You already debounce the user input so you can control propagation of the user input value to the route param.

**Comment by bfreis** [comment]
I believe I understand what you mean. However I'm still inclined to think this is an issue in Ember.js (hence continuing the discussion here, instead of asking on StackOverflow). Keep reading for the reasoning behind this statement.

I was able to work around the issue. To solve it, I had to introduce 2 new properties on the controller. *Now I have 3 properties to handle that use case*. The properties are:

 - `tfFilter`, bound to the text field
 - `qpFilter`, bound to the query param
 - `initialized`, not bound to anything.

The idea is to observe `tfFilter` and send debounced actions to the router (just like before), but with one crucial difference: the debounced notifications are only sent if `initialized == true`.

To initialize the `tfFilter` property on the controller based on the query param, I needed a hook in which I have access to the query params and the controller. I used `setupController` on the Route (it seems something that is the Route's responsibility). Then the code is something like: `if (!controller.initialized) { controller.initialized = true; controller.set('tfFilter', controller.get('qpFilter')); }`.

This works, but it truly smells.

The thing is: even though there are 2 sources of truth, the user is editing at most one at a time. The one the user is modifying should be the authoritative one. The new value should flow from the *thing* the user is editing, to the property, to all the other *things* bound to the same property. Doesn't it make sense?

Since apparently there's no notion of "flowing changes from one source to the other bound things", I had to use and manage 3 properties, add a hook and deal with 2 branches. Feels counter intuitive.

Am I missing something?

Thanks,
Bruno

**Comment by ahacking** [comment]
Yes I feel your pain. I'm just an Ember user who has come to the conclusion computed properties (CPs) and observers are the path to hell in part because of some of problems you are dealing with here.

When do you set ``initialized``?  Be aware that route driven controllers only get created once and persist for the life of the application. The model/content is changed by the router so make sure you observe the model/content property to reset your ininitialized flag or do this from the router. Its all very ugly but largely the Ember way due to the CP and observer side effect architecture.

With enough shenanigans, use of private functions to suspend observers, run loop deferred processing and run once guards you can eventually get something that works and avoids multiple recomputations with Ember but its fragile and takes an immense amount of time dealing with corner cases and feedback loops. Don't use Embers array computed properties either as they're broken in many surprising ways.

You may like to review the Ember 2.0 RFC  and put your experiences and views forward there as I've been rather critical of computed properties and observers based on my experiences with Ember and think they should be deprecated with a unidirectional data flow adopted to tame the complexity.

**Comment by mmun** [comment]
Can someone verify if this bug is still present in latest 2.x? There is a JSBin in the original issue.

**Comment by pixelhandler** [comment]
@bfreis can you recreate the reproduction of this issue using a current release of Ember, or the LTS release (2.4.6)?

**Comment by Serabe** [comment]
@mmun it is, [see twiddle](https://ember-twiddle.com/935fff8be36960afd4cbf9543fc064d5?openFiles=twiddle.json%2C&route=%2F%3Ffilter%3Daaaa)

**Comment by arthur5005** [comment]
Hmm this should be an exemplary use case of all of Ember's key features (using a very common pattern in resource searching), but unfortunately there's no way to prevent the query params from being reset by the refreshing route. :(

**Comment by pixelhandler** [comment]
@ahacking @arthur5005 @bfreis @mmun @wagenet is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by pixelhandler** [comment]
Closing for now, feel free to re-open if you can reproduce in the current release of Ember.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
