### ISSUE TITLE
Inconsistent behaviour linked to component instantiation and its properties

### ISSUE THREAD

**Issue by shripathee** [emberjs/ember.js#10165]
There exists some inconsistent behaviour in components, when accessing a property in a setter of another property.
For eg.

```
{{!some-template.hbs}}
{{foo-bar content=someProperty result=someString}}
```

```
//foo-bar.js
App.FooBarComponent = Ember.Component.extend({
  content: null,

  result: function(key, value) {
    var content;
    if(arguments.length > 1) {
      content = this.get('content');
      console.log(content); //prints null
      return value;
    }
    //....   
  }.property('content.[]')
});    
```

In Ember 1.8.1, the content property can be retrieved inside the setter of the result computed property.
[Working] JSBin: http://emberjs.jsbin.com/jayewuhese/1/edit?html,js,console

In Ember 1.9.1, the content property is not accessible.
[Not working] JSBin: http://emberjs.jsbin.com/zinokusuzu/1/edit

The strange thing is that when I changed the usage of the component in the template to:
{{foo-bar result=someString content=someProperty}}

it works!
[Working] [Ember 1.9.1] JSBin: http://emberjs.jsbin.com/yawizuvoxi/1/edit?html,js,console,output

Now I tried setting 'result' a static value in the template. And it breaks again.
[Not working] [Ember 1.9.1] JSBin: http://emberjs.jsbin.com/cefotiluve/1/edit?html,js,console,output

Not sure if these issues are independent of each other or not.

This volatile behaviour is preventing us from upgrading to Ember 1.9.1.

**Comment by shripathee** [comment]
@mmun @stefanpenner

**Comment by mmun** [comment]
@shripathee This seems to be fixed on canary: http://emberjs.jsbin.com/femazu/1/edit

**Comment by shripathee** [comment]
@mmun Changing the order of component properties during instantiation breaks in canary. I believe the behaviour should not be dependent on the order of properties.

http://emberjs.jsbin.com/vabenuqibe/1/edit?html,js,console,output.


Also, the issue when I set a static value to the component property still exists in canary
http://emberjs.jsbin.com/zuwibevavo/1/edit?html,js,console,output

**Comment by mmun** [comment]
It's the same behaviour as in 1.8 though, correct?

**Comment by mmun** [comment]
I don't see how you could change the behaviour to be order independent when you're working with setters.

**Comment by ahacking** [comment]
This is another specific example of dependent property indeterminism in CPs. I can recall also having the same issue dealing with undefined inputs on CPs due to assignment order from the object create which occurs before init is called.

@mmun that example cant really work reliably as its clear mutual dependence/circular dependency so I regard that as impossible.

This kind of thing is not going to be easy to address given how CPs work without maintaining a DAG ordering of dependencies so assignment could be applied in a proper order. You could possibly detect both direct and indirect circular deps but I feat that any attemot to do this will be a sink hole for performance.

**Comment by mmun** [comment]
@ahacking This really has nothing to do with CPs. The same problems would arise if you were using setters.

**Comment by manoharank** [comment]
@mmun Then, is this something related to template compiler? Look at the order of hash in compiled template

![template-compileer](https://cloud.githubusercontent.com/assets/1687297/5660691/281680ca-9749-11e4-987e-d6bfc9df6f31.jpg)

**Comment by mmun** [comment]
Yes, there must have been a bug in Handlebars 2.0 (which is what Ember 1.9 depended on). Regardless, it's fixed in HTMLBars.

**Comment by ahacking** [comment]
@mmun honestly I didnt look into the minute detail on this particular issue but what happens if a is set before b and a depends on b and b is just a regular property? I know I've had this problem from inside Object.create where it assigns passed props where property a's setter would get undefined for b as it hadn't been set yet...

**Comment by ahacking** [comment]
Also since js doesn't have defined order for object keys is this likely to get different assignment ordering on different browsers?
