### ISSUE TITLE
value as a attributeBinding is not rendered as an attribute

### ISSUE THREAD

**Issue by kiwiupover** [emberjs/ember.js#10183]
In a component if `value` is used for the `attributeBinding` ember doesn't render attribute.

http://jsbin.com/sowegu/4/edit

Interestingly if you use `valuE` as an attributeBinding ember will render `value` as an attribute. 

http://jsbin.com/sowegu/5/edit

**Comment by rwjblue** [comment]
This is happening because Ember is special casing the attribute named `value` [here](https://github.com/emberjs/ember.js/blob/b53fd7b876c4b91f43acdedbcc5d502944b99c2e/packages/ember-views/lib/views/view.js#L2184-2197).  This whole code-path is being removed in https://github.com/emberjs/ember.js/pull/10186.

**Comment by kiwiupover** [comment]
Thanks @rwjblue
