### ISSUE TITLE
Ember.Map: You must use Ember.set() to set the `size` property

### ISSUE THREAD

**Issue by frederikbosch** [emberjs/ember.js#10209]
You must use Ember.set() to set the `size` property (of [object Object]) to `2`.

I receive this error when adding a value to a map. I am on version 1.8.1. Upgrading to 1.9.* is not an option for me at this stage.

Trace:
Ember assert...
https://github.com/emberjs/ember.js/blob/v1.8.1/packages/ember-metal/lib/properties.js#L35
https://github.com/emberjs/ember.js/blob/v1.8.1/packages/ember-metal/lib/map.js#L326

I do not get why the mandatory setter is complaining. Is the value wrong? Why was it not a problem to insert the first item? How do I overcome this without upgrading?

**Comment by stefanpenner** [comment]
size is non-observable, this currently does mean that observing it in a template likely causes issues, which seems really crappy...

**Comment by frederikbosch** [comment]
@stefanpenner Crappy by me? :)

**Comment by frederikbosch** [comment]
I am indeed observing the size property.

**Comment by fivetanley** [comment]
Not crappy by you, crappy by the framework. This is kind of a bummer of mandatory setter; you can't really use or manipulate POJOs if you ever put them in a template either.

**Comment by frederikbosch** [comment]
Good to know! I cannot remember this was a problem for me before. The code worked (or that is what I believe). This exceptions is being thrown to me just now. I am lucky: all callers of the map are in the same class: so I can observe the changes manually.

**Comment by frederikbosch** [comment]
@fivetanley @stefanpenner Thanks for the explanation, I can create a workaround for this issue now. Unfortunately, I do not qualify myself good enough to contribute to the source. Otherwise I would have done a PR to resolve the issue. Thanks for the wonderful job you have done already!

**Comment by knownasilya** [comment]
Just encountered this issue as well.

**Comment by stefanpenner** [comment]
You can iterate it current. So you just want to observe the size?

**Comment by knownasilya** [comment]
What do you mean by 'you can iterate it'?
On Feb 12, 2015 4:46 PM, "Stefan Penner" <notifications@github.com> wrote:

> You can iterate it current. So you just want to observe the size?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emberjs/ember.js/issues/10209#issuecomment-74159520>.
>

-- 
This e-mail message and any attachments may contain confidential or legally 
privileged information. If you are not an intended recipient or otherwise 
authorized to receive this message, you should not use, copy, distribute, 
disclose or take any action based on the information contained in this 
e-mail or any attachments. If you have received this message and material 
in error, please advise the sender immediately by reply e-mail and delete 
this message. Thank you on behalf of Applied Geographics, Inc. (AppGeo).

**Comment by stefanpenner** [comment]
You can't iterate it with an each today.

**Comment by knownasilya** [comment]
Ok, but that doesn't solve the problem of how I know when to iterate it.
I'd have to keep another property and set it every time I add or remove
from the map.
On Feb 12, 2015 5:42 PM, "Stefan Penner" <notifications@github.com> wrote:

> You can't iterate it with an each today.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/emberjs/ember.js/issues/10209#issuecomment-74169345>.
>

-- 
This e-mail message and any attachments may contain confidential or legally 
privileged information. If you are not an intended recipient or otherwise 
authorized to receive this message, you should not use, copy, distribute, 
disclose or take any action based on the information contained in this 
e-mail or any attachments. If you have received this message and material 
in error, please advise the sender immediately by reply e-mail and delete 
this message. Thank you on behalf of Applied Geographics, Inc. (AppGeo).

**Comment by frederikbosch** [comment]
Or you extend the class and create your own counter variable. This wil make it easier to upgrade when the bug is fixed.

**Comment by krisselden** [comment]
@fivetanley you can observe POJOs now you just have to call Ember.set(obj, 'foo', value) when modifying them

**Comment by frederikbosch** [comment]
@krisselden Do I understand your comment correctly with the suggestions in my pull request. If so, I can fix the issue and add some tests too.

**Comment by rwjblue** [comment]
I'm unsure that we want `Ember.Map.prototype.size` to be observable...

**Comment by frederikbosch** [comment]
Why not? In my opinion it is logical to observe a collection. This enables you to execute a function when the composition of the collection changes. Or maybe I do not understand your comment to the full extent. What would be your alternative?

**Comment by stefanpenner** [comment]
> This enables you to execute a function when the composition of the collection changes

Observing `size` is insufficient, as mutation of the Map or Set doesn't just include `add` `remove`, but also `replace`, which results in no `size` change event.

For now, Map and OrderedSet are meant as a fast partial polyfills for ES2015 `Map` and `Set`. So that, we can swap them out for native implementations when a sufficient number of vendors support them.

Additionally, we are currently re-evaluating our current array change detection strategies, as the approach is extremely likely to change any additional observation plans for `Map` and `OrderedSet` remain on hold.

**Comment by frederikbosch** [comment]
@stefanpenner Thank you for your reply. This is very clear now. I will remove my pull request but leave this bug report open.

**Comment by stefanpenner** [comment]
As es6 map is not observable neither should use partial polyfil.

**Comment by frederikbosch** [comment]
:+1:
