### ISSUE TITLE
Overly aggressive AutoLocation rootURL assertion

### ISSUE THREAD

**Issue by tomdale** [emberjs/ember.js#10201]
There are two invariants maintained by AutoLocation via assertions that have caused a regression in Skylight. I don't know exactly what change caused this to break, and I'm trying to untangle the thread, but the bottom line is I believe AutoLocation is too aggressive and should handle this case more gracefully.

The two invariants causing problems are:

1. AutoLocation enforces that `rootURL` must always end with a slash `/`. So, for example, if we set the `rootURL` to `/app`, it will raise an exception unless we change it to `/app/`.
2. AutoLocation verifies that the `rootURL` is contained in the URL inside `_getHistoryPath()`, and raises an exception if not (https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/location/auto_location.js#L240)

This is problematic because our Ember app is served by our Rails app, and links generated by Rails link to, you guessed it, `/app` (no trailing slash).

At some point, our app started throwing exceptions when hitting `localhost:4200/app` directly instead of `/app/`. Perversely, everything works fine if I comment out the above-linked assertion, so it seems like it's not doing much. (In that case, Ember automatically redirects to `/app/` from `/app`.)

I don't know the most robust way to handle this case, but it seems like we should loosen the constraints on `rootURL` and automatically do the normalization in code, rather than pushing complexity to the user.

cc/ @cibernox @jayphelps

**Comment by jayphelps** [comment]
@tomdale I'll dig up all the old convos explaining why these choices were made.

**Comment by jayphelps** [comment]
@tomdale 

https://github.com/emberjs/ember.js/pull/4717#issuecomment-40333602
https://github.com/emberjs/ember.js/issues/4751
https://github.com/emberjs/ember.js/issues/4793

The tl;dr is that both history/hash location classes assume `/app` and `/app/` are *different* paths (cause they are) so extra history states are created and several reported redirect issues. This is because `/app/` is an index path, but `/app` is a path to app, not an index inside app.

When you comment out the assertions and try it, you noted that it redirected to `/app/`. Did you try this on a non-history supported browser like IE9? On many servers, this will be cause an infinite redirect battle, where the visitor lands on `/app`, ember redirects to `/app/` via `window.location.replace` (no `pushState` support) then the server redirects back to `/app`, etc, etc.

**Comment by tomdale** [comment]
@jayphelps I did not try it on IE9 (we only support browsers with `pushState`). I naively had not considered carefully the case with hash routes and, in particular, the index state. Given that, it probably makes sense for us to either mandate the trailing slash in Rails (which seems pretty easy via http://stackoverflow.com/questions/16218670/enforce-trailing-slash-in-rails-routing) or, more likely, just always use the history location.

Thanks again for the info!

**Comment by jayphelps** [comment]
@tomdale no problem! It's a very complex situation we've had to explain to many..wish there was an easy way to support it.

btw, I would guess you don't want to serve *all* routes with trailing slashes (via `default_url_options`), only the `/app/` one:

```ruby
get 'app/' => 'app#index', :trailing_slash => true
```

Otherwise your normal ember-route URLs will get the trailing slash too, incorrectly. `/app/users/123` => `/app/users/123/` (wrong)

**Comment by rwjblue** [comment]
> I did not try it on IE9 (we only support browsers with pushState).

Then why use AutoLocation at all?
