### ISSUE TITLE
EmberJS 2.0: The Future Of Ember Views

### ISSUE THREAD

**Issue by agentVargas2012R** [emberjs/ember.js#10232]
I apologize if this isnt the correct forum but I really do need to speak with the authors of this framework to figure out upcoming changes that may affect us significantly. Recently, there has been a huge debate at my current contract related to Components vs. Views. 

I am aware that "components" are preferred over views, however, we have an extremely complicated presentation layer. Views have been able to deal with all of that complexity so far. 

What is the future of views? Specifically in Ember 2.0 ? When is Ember 2.0 expected to be released? Are there any upcoming plans to begin deprecated views if they are not going to be supported?

**Comment by joostdevries** [comment]
You might want to look at http://github.com/emberjs/rfcs and perhaps http://ember.zone/the-confusion-around-ember-views-and-components/ (scroll down down for comment by Tom Dale)

**Comment by pixelhandler** [comment]
@agentVargas2012R here is a gist that highlights the upcoming shifts for Ember 2.0 https://gist.github.com/pixelhandler/9fd4c3cf220621da5043 In the gist you will find links to various presentations, videos, and links on the topic of Ember 2.0. Ember.js releases up to 1.12 have plans for the items in the 2.0 roadmap and no commitment is made to the date of a 2.0 release. There may be more releases between 1.12 and 2.0. You can use feature flags to opt-in to new features that are in beta if you want to try them out early and give feedback. As far as I know the 1.X series of releases will not prevent you from continuing to use Views. The links in the gist have info on using components and address the why behind the shift toward components. Tom, Robert and Stefan have given talks with details on the changes that Ember 2.0 will bring. The RFC post highlights the roadmap and invites your comments... https://github.com/emberjs/rfcs/pull/15 This is a good listen as well... http://thechangelog.com/131/

**Comment by fivetanley** [comment]
I think @pixelhandler and @joostdevries have pointed out some great resources. emberjs/rfcs#15 is probably the correct venue for this.

**Comment by agentVargas2012R** [comment]
@pixelhandler @joostdevries @fivetanley - Thanks for the wealth of information. It has been very helpful. 

I am trying still trying to get make sense of some references;

Routeable Components
Many people have noticed that controllers in Ember look a lot like components, but with an arbitrary division of responsibilities. We agree!
In current versions of Ember, when a route is entered, it builds a controller, associates a model with it, and hands it off to an (old-style) view for rendering. The view itself is invisible; you just write a template with the correct name.
We plan to transition to: when a route is entered, it renders a component, passing along the model as an attr. This eliminates a vestigial use of old-style views, and associates the top-level template with a regular component.


Here is our biggest challenge switching to components in our application:

How is business logic shared between components?
My only concern is that controllers represented a place to put common business logic for one action which had multiple views. Views could contain UI specific computed properties / validation and controllers had the business logic specific computed properties / validation set up.
I want to echo what @Pradeek wrote. I use the same view & controller with different templates:

{{render 'course-date' this.courseDate}}


{{render 'course-date-mobile' this.courseDate controller="courseDate" view="courseDate"}}
I also use the same controller with different views & different templates.

{{render 'sections' model.sections}}


{{render 'sections-toc' model.sections controller="sections"}}
As Ember moves to 2.0, I'm really interested in seeing how I can use components to achieve the same encapsulation and reusability. With my current & rudimentary understanding of components, it seems they don't support this.

We find ourselves in a similiar manner:
Our presentation layer is very complex and we truly need a way for components to have the ability to communicate with each other which is the challenge with using components since they are isolated by default, they have no knowledge of each other. This is where views shined for us in the past. Our UI has many things that need to observer each other and react based on selections we make. 

In situations like this, have there been any talks about the new ways to handle this?

**Comment by pixelhandler** [comment]
@agentVargas2012R in a ember-cli addon I chose to use custom DOM events for components to communicate, see https://github.com/pixelhandler/ember-off-canvas-components repo. There are a few components ( https://github.com/pixelhandler/ember-off-canvas-components/tree/master/addon/components ), the eoc-viewport is the parent of them all and listens for the custom events that the components fire https://github.com/pixelhandler/ember-off-canvas-components/blob/master/addon/components/eoc-viewport.js#L35-L47 So, instead of the event handler in the component converting the event to an ember action, I simply convert the click event to a custom DOM event which bubbles up to the parent component. This type of communication between components uses an event pooling approach which uses custom events so that the components can work together (similar to this post http://blog.michaelhamrah.com/index.php/2008/12/event-pooling-with-jquery-using-bind-and-trigger-managing-complex-javascript/ ) I have the opinion that Ember's actions are very powerful and useful, but sometimes just using native DOM events instead may be the right contextual solution for a problem. We still have choices... we can mix up what Ember provides with what the browser provides.

**Comment by agentVargas2012R** [comment]
I wanted to sprinkle some alfredo sauce on this and call it done. I do appreciate how considerate the ember community is. 

For those interested, here's what the word is on the street:
https://www.youtube.com/watch?v=r1Ot6oPGeh0

Checkout: 1:30
