### ISSUE TITLE
Document path based component/helper names

### ISSUE THREAD

**Issue by sglanzer** [emberjs/ember.js#10243]
Handlebars 2.0 allows path based helper names (e.g. my-component/sub).  I started using this feature as soon as it was available to organize code (very nice organization with ember-cli and pods).

The ability to use this naming structure isn't documented for components anywhere that I can find.  In addition, to use path based names and provide parameters the helper must be wrapped in [ ].  Like nested components, I found that answer in an issue thread https://github.com/wycats/handlebars.js/issues/912.

I believe it would be helpful to document both the ability to nest component paths and the stipulations for using paths correctly.

As an example:
````
{{[sample-table/row] model=rowModel}}
{{[sample-table/cell] model=cellModel}}
````

**Comment by wagenet** [comment]
@sglanzer We definitely should look into this. I know that not every Handlebars feature is actually supported in Ember, but it sounds like you've already used this without issue. However, we should verify that there aren't any unknown side-effects before we document this.

**Comment by rwjblue** [comment]
Nested helpers/components are definitely supported as of Ember 1.9.0 (when we upgraded to Handlebars 2.0.0).  

We are still not quite sure what the API for nested angle bracket components, but will likely have some syntax specified (since it is an important issue).

Closing as this issue is somewhat old and isn't really describing a "bug" (but I would gladly accept a PR adding documentation).
