### ISSUE TITLE
Handlebars Subexpressions don't pass values to helpers

### ISSUE THREAD

**Issue by hinok** [emberjs/ember.js#10247]
Demo: http://emberjs.jsbin.com/casisetoka/1/edit?js,output

Value returned from nested helper `diff` is not passed to `pluralize`.
```
{{pluralize (diff model.date2 model.date1) 'day'}}
```

Current result:
```
10undefined days
```

Should be:
```
10 days
```

I cannot reproduce this issue in 1.11 canary.
Can I fix it somehow in ember 1.9.1?

**Comment by mixonic** [comment]
I might be mistaken, but I don't believe we've ever made custom sub-expressions a public API. Before Ember 1.10, they were indeed not bound correctly due to limitations of Handlebars. 1.10 and forward they are expected to work, and will become more common in template code.

I'm not at all sure what you might need to do to get them working as you want on 1.9.

**Comment by rwjblue** [comment]
@mixonic is correct. Bound subexpressions are not able to be supported in versions prior to 1.10.

**Comment by rwjblue** [comment]
Sorry, but there is roughly no way to implement this for 1.9 without massive changes.  Closing as this is supported in 1.10-beta's.
