### ISSUE TITLE
RouteRecognizer.VERSION is incorrectly set to ember's version

### ISSUE THREAD

**Issue by jayphelps** [emberjs/ember.js#10269]
Since #10268 was merged, there was a change in the way [route-recognizer](https://github.com/tildeio/route-recognizer) is built, which uses a similar string replacement to add its `RouteRecognizer.VERSION` number property but since [emberjs-build](https://github.com/emberjs/emberjs-build) consumes the package via bower as an ES6 module, it doesn't get that chance and is instead replaced with ember's `VERSION`.

```javascript
RouteRecognizer.VERSION = '1.11.0-beta.1+canary.6f7b1c48';
```

Though we don't believe any internal code depends on this version being correct...it's clearly wrong...so probably should fix it some how.

Change can be found here: https://github.com/tildeio/route-recognizer/compare/8e1058e29de741b8e05690c69da9ec402a167c69...404b8485948120330f4c262a5cc997ac782d5466#diff-3cd8d4dfb826ed2ebdceb9c43e729d8eR534

**Comment by rwjblue** [comment]
For anyone interested in working on this, here is a rough outline of what needs to change:

* route-recognizer needs to generate a dist/es6/ folder that contains the preprocessed ES6 (aka version string is replaced). This should be part of the prepublish script. 
* update emberjs-build to pull route-recognizer from NPM, and use the dist/es6 as the source tree (instead of bower_components)

This is how HTMLBars is pulled in (and works well).
