### ISSUE TITLE
`router` is undefined in wait() test helper

### ISSUE THREAD

**Issue by kevinansfield** [emberjs/ember.js#10263]
When using this [authenticateSession](https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth-testing/lib/simple-auth-testing/test-helpers.js#L4) test helper, my test suite crashes.

The crash happens inside the `wait()` method of `ember-testing/lib/helpers.js`, where `lookup('router:main').router` returns undefined on this line: https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/helpers.js#L211

My acceptance test is very basic:

```coffeescript
`import Ember from 'ember'`
`import startApp from '../helpers/start-app'`

App = null

module 'Acceptance: Login',
  setup: ->
    App = startApp()

  teardown: ->
    Ember.run App, 'destroy'

test 'It redirects if already logged in', ->
  authenticateSession()
  visit '/login'

  andThen ->
    equal currentPath(), '/'
```

If I remove the `authenticateSession()` call then the test runs without issue.

Are there any known conditions that may cause `router` to be undefined? Is there anything I can do to get further information for debugging?

> Ember: 1.11.0-beta.1+canary.8ca36b56
> Ember Data: 1.0.0-beta.14.1
> jQuery: 1.11.2
> Ember Simple Auth: 0.7.2
> Ember Simple Auth Devise: 0.7.2

**Comment by rwjblue** [comment]
IIRC, the router is not setup and running until after the first `visit` call.

**Comment by kevinansfield** [comment]
Thanks, adding a `visit '/'` call before `authenticateSession()` fixes this particular error. I'll open a pull request for updates to the ember-simple-auth-testing docs.

**Comment by marcoow** [comment]
I think this should be fixed. There's usually no point in visiting a route before the session is authenticated (except only to activate the router as described above), e.g. in a [test like this](https://github.com/simplabs/ember-cli-simple-auth-example/blob/master/tests/integration/authentication-test.js#L44). I guess it would be ok to change https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/helpers.js#L211 so that it just doesn't perform the check for an active transition if the router isn't running yet?

**Comment by rwjblue** [comment]
Fixed by https://github.com/emberjs/ember.js/pull/10266.

**Comment by marcoow** [comment]
thanks!
