### ISSUE TITLE
Sticky Query Params very confusing

### ISSUE THREAD

**Issue by eccegordo** [emberjs/ember.js#10260]
After using query params for awhile the default stickiness seems to cause a lot subtle and non obvious sides effects.

It is not completely obvious how to consistently reset query params between transitions.

I would suggest either or both of the following.

1.) provide global non-sticky option for all params. In other words provide an easy to configure flag that forces all query params to be set to `null` during a transition and possibly during the model hooks.

If feasible perhaps something along the lines of 
```
this.transitionTo('posts', {queryParams: {resetAllQueryParams: true}});
```

2.) Provide more clear documentation or guide on how to reset all params. I have googled around but this behavior should be front and center in the documentation section of query params.

**Comment by machty** [comment]
The answer here is to make use of the [resetController](http://emberjs.com/api/classes/Ember.Route.html#method_resetController) hook. Presently, there's no API for resetting to defaults; you have to just manually set the controller QP to its default value within `resetController`; it's basically an escape hatch before a nicer API comes along. 

I don't think we're accepting new documentation for query params because we'll be shifting that API toward route-driven components very shortly, so I'm going to close this.

**Comment by robclancy** [comment]
This is frustrating sometimes. Not only are you not willing to fix an issue in ember (reset only happens on exit, this is also needed when not leaving the route) but you don't update documentation because at some point in the future it won't matter anymore... that time according to this issue is over 1.5 years as we are still waiting on route-driven components which seem to be more of an excuse to not do things people have needed since 2014 more than anything.
