### ISSUE TITLE
Exception swallowing within willTransition

### ISSUE THREAD

**Issue by jasonmit** [emberjs/ember.js#10311]
When you have an exception thrown from within `willTransition` the exception gets swallowed and the router breaks in a very subtle way.

This took quite awhile to triage, as I originally thought the bug was within queryparams and the LinkView.

## Steps to reproduce:
* http://jsbin.com/kevisujowa
* Type anything in the `foo` input
* Notice the queryParam updates as expected
* Now click on the Bar `link-to` and notice that query param was pushed onto the new route's URL (side effect of the bug)
* Notice that in the console you don't see a stacktrace from the `throw new Error()`

## Excepted:
* `throw new Error()` should emit a stacktrace in the console

**Comment by stefanpenner** [comment]
oh god this one constantly trolls me :+1: .

@machty you promised me he would fix this :broken_heart:

**Comment by stonecalvin** [comment]
Hey, I've been looking into this issue lately, and I believe I have found the cause.

When you throw an error in the willTransition, it gets caught and a Transition is created with the error set on it, along with a Promise.reject(error). At this point error is the thrown error as expected.
```javascript
      if (error) {
        this.promise = Promise.reject(error);
        this.error = error;
        return;
      }
```

The problem is that when the transition is taken, the then() of the transitions promise gets set to
```javascript
    transition.then(null, function(error) {
      if (!error || !error.name) { return; }

      Ember['default'].assert("The URL '" + error.message + "' did not match any routes in your application", error.name !== "UnrecognizedURLError");

      return error;
    }, 'Ember: Process errors from Router');
```

This assert will only recognize the UnrecognizedURLErrors. Unfortunately I have just started looking into ember and do not know enough about the general architecture to make a call on how this should be handled.
