### ISSUE TITLE
Issue when nesting index route inside resource with specified path 

### ISSUE THREAD

**Issue by piotrpalek** [emberjs/ember.js#10371]
I am not sure how to explain what's happening, I stumbled uppon this issue while trying to make a jsbin, here's an example: http://emberjs.jsbin.com/vavujo/8/edit. Afaik that jsbin should print all 3 templates but it fails with `Uncaught #<UnrecognizedURLError>`.

What I did was nest an `this.route('index')` inside an `resource` with `path: '/'`, and that seems to break something.

**Comment by ajadex** [comment]
More details on this error. Resources don't match with URLs, routes do. Ember generates routes for all its resources. In order to access the resource 'posts' in the URL '/' Ember would generate the child route posts.index with path '/'. Something like this:

post  NO PATH APPLICABLE
 | -- index  "/" 

@piotrpalek what you are doing is providing your own index route preventing Ember to generate that default index route. Your route is equivalent to this: route("index", {path: "/index"}) so Ember cannot match "/". It's like this:

post  NO PATH APPLICABLE
 | -- index  "/index"

There are a couple of experiments you can do to test what I'm saying. Navigate to /index and you will see the 3 templates rendered. Or, define the path for index like this: route("index", {path: "/"}).

My opinion is that Ember should log an Error warning you about this attempt to override the path of a nested index route with a value different than "/" .

**Comment by piotrpalek** [comment]
@ajadex makes sense thanks for the explanation :)
