### ISSUE TITLE
Cached computed properties seem to be invalidated too often

### ISSUE THREAD

**Issue by qbolec** [emberjs/ember.js#10433]
Consider this code:
```
var UserController = Ember.ObjectController.extend({
  firstName: "John",
  lastName: "Doe",
  largeFirstLetter:function(){
    console.log("Recomputing");
    return this.get('firstLetter').toUpperCase();
  }.property('firstLetter'),
  firstLetter:function(){
    return this.get('fullName').substr(0,1);
  }.property('fullName'),
  fullName:function(){
    return this.get('fisrtName') + ' ' + this.get('lastName');
  }.property('firstName','lastName')
});
var userController = new UserController();

console.log(userController.get('largeFirstLetter'));
console.log(userController.get('largeFirstLetter'));
userController.set('lastName','Smith');
console.log(userController.get('largeFirstLetter'));
```
http://jsfiddle.net/L95npwyj/

The idea is that we have a dependency tree :
```

largeFirstLetter <- firstLetter <- fullName <-- firstName
                                            <-- lastName
```
And the operations we perform change `lastName`, and `fullName`, but not `firstLetter`.

The output on the console is:
```
Recomputing
U
U
Recomputing
U
```

Ember spec seems to promise to me that `largeFirstLetter` will be recomputed only if it's dependencies are no longer valid. But the experiment reveals that what it actually means is that "deeper" dependencies, such as `lastName` are also taken into account. So even though `firstLetter` (the only direct dependency of `largeFirstLetter`) does not change, the `largeFirstLetter` gets recomputed.

The example above is very simple, but we hit this problem in a more advanced scenario where it was causing a lot of redraws in situations where nothing actually changed.

I've "fixed" it with making `firstLetter` a real (not computed) property, and manually recomputing it using observe('fullName'). 

Am I doing something wrong?

**Comment by stefanpenner** [comment]
CP's are lazy, once invalidated something needs to pull the data out of them.

imagine the following DK chain

```js
foo -> bar -> baz
```

if `foo` becomes dirty, the values for `bar + baz` are also not known, as they are derived from `foo`. Even if `foo` ultimately computes to its original value the current experience is to still recompute `bar + baz`.

For many scenarios this actually works fine, and wont cause re-renders. Because of simple template bindings, we "diff" the previous and new value to decide if a re-render is needed.

the basic `diffing` code actually lives [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/views/simple_bound_view.js#L79-L87)

Where this does fall short currently is when dealing with complex objects as values. And we are aware of this.

@tomdale and @wycats are currently working on the template rendering side of this problem: https://github.com/tildeio/htmlbars/pull/282. Although the goal is for server side rendering, it has the potential to help mitigate the issue.

On the CP side, we currently have paired changeEvent contract of `willChange` followed by a `didChange`. Although it would be a breaking change, we _may_ be able re-imagine this as

* `willChange`
* downstream pulls
* previous and newValue are compared
* didChange is emitted if the newValue is different.

Ultimately, the `cp` side change, as I imagine it, will only work with simple values, not with arrays or objects, so in the pathalogical cases it may not help that much. I do believe the template rendering side has sufficient context to handle the complex object case much better.

Although both solutions could work together, the reactive template approach is likely be the near term solution.

**Comment by qbolec** [comment]
In our scenario the problem was that `largeFirstLetter` was actually something somewhat difficult to compute (comparing message text against search query) and thus reevaluating it on 1k+ messages even though the query didn't change, seemed a bit slow. Probably I attributed the slowdown to re-renders while it was actually the computation itself that was so slow. In other words: consider a scenario in which re-renders are not the issue, but the re-computation of the property is costly.

Or, is it a bad pattern to have CP which are costly to compute?

**Comment by stefanpenner** [comment]
this appears to be work as expected
