### ISSUE TITLE
Add Browser Support List

### ISSUE THREAD

**Issue by anotheredward** [emberjs/ember.js#10566]
After reviewing the project page and the Ember site I don't know what browsers the latest stable version supports.

Can we please have a list of browsers in one or both of these places?

http://stackoverflow.com/questions/9873744/ember-js-browser-support
Says Ember supports IE6 on XP, but soon that won't be true according to this:
https://github.com/emberjs/ember.js/pull/5236

**Comment by stefanpenner** [comment]
IE9+, but yes we should make sure this id documented

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js#emberjs shows a browser listing (those tested by Sauce Labs).

**Comment by anotheredward** [comment]
Thanks!

**Comment by effulgentsia** [comment]
Hi. Thanks for the link to https://github.com/emberjs/ember.js#emberjs, but I think additional documentation somewhere would be helpful. Because the SauceLabs graphic currently only shows IE9,10,11, Edge14, and Safari9. Does that mean Safari10 is not supported? What about Edge13 and Safari8? What about Firefox and Chrome? https://github.com/emberjs/ember.js/blob/master/testem.dist.json has a bit more info, as it shows SL_Chrome_Current and SL_Firefox_Current, but does that mean that (Current - 1) is not supported for each of these? What about Firefox ESR?

A documentation page somewhere like https://jquery.com/browser-support/ would be clearer (though even that is lacking clarity on Firefox ESR).

As an aside, SL_Safari_Current and SL_Safari_Last probably need to be bumped from 9/8 to 10/9, respectively?

**Comment by saiqulhaq** [comment]
I wanted to migrate my JS App to Ember JS
but I am wondering where is the statement of supported and unsupported browser to convincing me 

the statistic reported by Sauce Labs seems clear of mentioned browser
but is that mean Ember JS targeting 5 browsers only?

![screen shot 2017-03-10 at 1 02 13 pm](https://cloud.githubusercontent.com/assets/1275215/23783977/cf6dc668-0591-11e7-8d31-b1dde633277b.png)

**Comment by stefanpenner** [comment]
We should write down our official policy somewhere.

A quick note for now: we support all major browsers. Any evergreen browsers latest version and non ever green browsers the latest few versions. 

But a detailed officially supported matrix would be a good addition to our docs.

Cc @locks

**Comment by locks** [comment]
Moved to https://github.com/emberjs/website/issues/2870, will address soon!

**Comment by drmscpxl** [comment]
is there any other browser support? aside from IE, Edge, Safari. as i can only see three in the README.md file.

Any plans to support major browsers?
