### ISSUE TITLE
Ember 1.10 fails with prototype extensions turn off

### ISSUE THREAD

**Issue by bcardarella** [emberjs/ember.js#10590]
See: http://emberjs.jsbin.com/haqutagihu/1/edit?html,js

The jsbin should be pretty self-explanatory

**Comment by stefanpenner** [comment]
https://github.com/emberjs/ember.js/blob/5fd2d035b30aa9ebfe73de824b3b283ec8e589cc/packages/ember-runtime/lib/system/array_proxy.js#L222

**Comment by rwjblue** [comment]
Random thoughts/findings:

* the model hook returns an array
* we use an ArrayController (which is basically an ArrayProxy with the ControllerMixin mixed in) if the model hook returns an array
* the ArrayController automatically maintains `arrangedContent` (which is an alias of the `content`/`model` property)
* Since ArrayController is an ArrayProxy, it expects that `content` implements `Ember.Array`
* Our model here does not implement `Ember.Array` when prototype extensions are not enabled

This can be fixed by returning an `Ember.Array` in the model hook of the JSBin: http://emberjs.jsbin.com/sasotu/1/edit?html,js,output

I tested the following versions to see what version this stopped working on here are the JSBins:

* 1.6 (same error) - http://emberjs.jsbin.com/yopife/2/edit?html,js
* 1.5 (same error) - http://emberjs.jsbin.com/yopife/3/edit?html,js
* 1.4 (no error logged because async error logging was broken in 1.4, but same error) - http://emberjs.jsbin.com/yopife/4/edit?html,js
* 1.3 (same error) - http://emberjs.jsbin.com/yopife/5/edit?html,js,output
* 1.2 (WORKS!!!) - http://emberjs.jsbin.com/yopife/7/edit

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/10697 should fix this...

**Comment by bcardarella** [comment]
:+1:
