### ISSUE TITLE
Not able to build in my windows 7 64  bit.. copied the debug-log

### ISSUE THREAD

**Issue by myntuser** [emberjs/ember.js#10628]
0 info it worked if it ends with ok
1 verbose cli [ 'F:\\nodejs\\\\node.exe',
1 verbose cli   'F:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink F:\nodejs\\node.exe
5 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
6 info prebuild ember@1.12.0-beta.1
7 info build ember@1.12.0-beta.1
8 verbose unsafe-perm in lifecycle true
9 info ember@1.12.0-beta.1 Failed to exec build script
10 verbose stack Error: ember@1.12.0-beta.1 build: `ember build --environment production`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (F:\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (F:\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1008:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
11 verbose pkgid ember@1.12.0-beta.1
12 verbose cwd C:\Users\user\Desktop\ember-src\ember.js
13 error Windows_NT 6.1.7601
14 error argv "F:\\nodejs\\\\node.exe" "F:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
15 error node v0.12.0
16 error npm  v2.5.1
17 error code ELIFECYCLE
18 error ember@1.12.0-beta.1 build: `ember build --environment production`
18 error Exit status 1
19 error Failed at the ember@1.12.0-beta.1 build script 'ember build --environment production'.
19 error This is most likely a problem with the ember package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     ember build --environment production
19 error You can get their info via:
19 error     npm owner ls ember
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by myntuser** [comment]
I was actually trying to run ember with node.. The window not defined error with RSVP. I read in one forum that It was resolved in the masters but not in production. Any help on this

**Comment by stefanpenner** [comment]
this doesn't seem like an issue in ember.js sounds like you are having issues with ember-cli ?

**Comment by stefanpenner** [comment]
ah, maybe you where trying to build this repo? I don't believe we support windows builds yet on this project.

**Comment by pjmorse** [comment]
I am seeing a similar issue in OX X, trying to build this repo. Here's the `npm-debug.log`:

> 0 info it worked if it ends with ok
1 verbose cli [ '/Users/pmorse/.nvm/v0.10.36/bin/node',
1 verbose cli   '/Users/pmorse/.nvm/v0.10.36/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@1.4.28
3 info using node@v0.10.36
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild ember@1.11.0-beta.1
6 info build ember@1.11.0-beta.1
7 verbose unsafe-perm in lifecycle true
8 info ember@1.11.0-beta.1 Failed to exec build script
9 error ember@1.11.0-beta.1 build: `ember build --environment production`
9 error Exit status 1
10 error Failed at the ember@1.11.0-beta.1 build script.
10 error This is most likely a problem with the ember package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     ember build --environment production
10 error You can get their info via:
10 error     npm owner ls ember
10 error There is likely additional logging output above.
11 error System Darwin 13.4.0
12 error command "/Users/pmorse/.nvm/v0.10.36/bin/node" "/Users/pmorse/.nvm/v0.10.36/bin/npm" "run" "build"
13 error cwd /Users/pmorse/Projects/ember.js
14 error node -v v0.10.36
15 error npm -v 1.4.28
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

N.B. I was building at a586365 because I'm trying to bisect 1.10.0 to 1.11.0, hunting a change which broke a test in our app. But I've encountered this problem at several places in the repo history, including HEAD. Trying to build with node 0.12.x gives the same error.

**Comment by stefanpenner** [comment]
everything should work now

**Comment by myntuser** [comment]
ok will try and update
