### ISSUE TITLE
ember-latest.js is gone breaking every jsfiddle everywhere including the docs

### ISSUE THREAD

**Issue by alexspeller** [emberjs/ember.js#10641]
http://builds.emberjs.com/ember-latest.js is a 404, meaning that every single jsbin or jsfiddle referencing ember anywhere on the interwebs is broken. This includes large swathes of Ember's documentation.

@rwjblue pinging you as I think you know about builds more than anyone

**Comment by rwjblue** [comment]
The canary build to use is located here: http://builds.emberjs.com/canary/ember.debug.js 

The http://builds.emberjs.com/ember-latest.js hadn't been updated in a very very long time (like mid-August of last year) so I removed it.  In theory I could make some sort of redirect that could be used?

All of the JSBin's in the guides will be removed soonish (as we update to use ember-cli formatting in the guides).

**Comment by rwjblue** [comment]
Wrong timeline, it was in early November: https://github.com/emberjs/ember.js/pull/9520

**Comment by alexspeller** [comment]
Hmm redirecting would be good, although it's misleading then to call it latest. Would it be possible to serve that version of ember from `/ember-latest.js` with a prepended `alert("This is an old version of ember, please update your link")` so it still worked but wasn't used accidentally or something?

Regardless of guides, it seems there is a *lot* of content out there that removing this breaks, unfortunately

**Comment by rwjblue** [comment]
> Would it be possible to serve that version of ember from /ember-latest.js with a prepended alert("This is an old version of ember, please update your link") so it still worked but wasn't used accidentally or something?

Yes, it is possible, but then we would have the same problem eventually.  If you feel strongly about it, I'll add this to my list of things to do, but I'm not sure what the right path forward is here...

Also, Canary JSBin's from older than a month ago were already broken due to missing `ember-template-compiler.js`, and we can't really do too much to fix that.  So it is highly likely that these JSBin's/JSFiddle's are already broken and making `builds.emberjs.com/ember-latest.js` point to the right place (with an alert) can't fix that...

**Comment by alexspeller** [comment]
Hmm with the guides rewrite I guess old jsfiddles and bins will be relatively minor, especially if they've been broken for a while and there hasn't been massive complaints
