### ISSUE TITLE
[1.11.0-beta.5] Injected service is not observed after template is renderered

### ISSUE THREAD

**Issue by mihai-scurtu** [emberjs/ember.js#10649]
I'm pretty new to Ember so it's very likely i'm missing something. 

In the project I'm working on I have a notification service that basically wraps around a list. I also have a *notification area* component that has the notification service injected. The problem is that when other routes/components add stuff to the notification service, the binding in the *notification area* doesn't get updated (it's basically an `{{#each}}`).

I made a JS Bin illustrating the issue (clicking _Add green_ doesn't do anything visually, although it updates the list inside the service): http://emberjs.jsbin.com/xezujahigi/4/edit

I can provide actual code samples if they are necessary.

**Comment by mihai-scurtu** [comment]
The issue is apparently broader. There must be something I don't understand about binding arrays.

Here is a different jsbin without the service, but with the same behaviour: http://emberjs.jsbin.com/cifato/1/edit?html,js,console,output

**Comment by rwjblue** [comment]
Because Ember cannot observe when you call `Array.prototype.push` you must use the observable methods (like `pushObject`).

Docs: http://emberjs.com/api/classes/Ember.MutableArray.html

Working JSBins:

* http://emberjs.jsbin.com/royecu/1/edit
* http://emberjs.jsbin.com/pavari/1/edit?html,js,console,output

**Comment by mihai-scurtu** [comment]
My bad. Thank you!
