### ISSUE TITLE
Item controller in ArrayController doesn't work

### ISSUE THREAD

**Issue by Tonkonozhenko** [emberjs/ember.js#10655]
Hello, community!

I have an issue with the item controller 
http://emberjs.com/guides/controllers/representing-multiple-models-with-arraycontroller/#toc_item-controller

It doesn't render attributes from controller or from model in template.

Here is jsbin where you can see it: http://emberjs.jsbin.com/xuqecu/15/edit?html,js,output

Or you can see the code in my project: https://github.com/Tonkonozhenko/embernoise

**Comment by Tonkonozhenko** [comment]
I found such solution at last:
```handlebars
{{#each c in controller}}
  {{#with c.model}}
    <li>title: {{title}}, ownedBy: {{c.ownedBy}}</li>
  {{/with}}
{{/each}}
```
or live http://emberjs.jsbin.com/mocufo/3/edit
Is it ok or not?

**Comment by pdud** [comment]
Hey there!

I think you'll find setting your `PostController` to extend from `Ember.ObjectController` rather than `Ember.Controller` will solve your problem.

To keep the `PostController` as an `Ember.Controller` your template should look something like this.

```handlebars
{{#each post in controller}}
  <li>title: {{post.model.title}}, ownedBy: {{post.ownedBy}}</li>
{{/each}}
```

This is because `Ember.Controller` does not proxy properties to the model like `Ember.ObjectController` does.

Hope this helps :)

http://emberjs.com/api/classes/Ember.ArrayController.html

**Comment by jamesdixon** [comment]
I was having issues with this as well given that `Ember.ObjectController` is being deprecated as of version 1.11. Thanks for the solution, @pdud !

**Comment by stefanpenner** [comment]
both are now deprecated
