### ISSUE TITLE
[Feature Request] dasherized attributes to camelCased on components

### ISSUE THREAD

**Issue by knownasilya** [emberjs/ember.js#10686]
So Polymer is [doing this](https://github.com/Polymer/polymer/blob/0.8-preview/PRIMER.md#annotated-property-binding) (bottom of that section), and it only makes sense, since HTML uses dasherized attributes and we are moving closer to the Web Components spec. I think we should convert to camel cased attributes for internal manipulation.

```hbs
{{my-component change-user='updateUser'}}
```

Within the component would be accessed as `changeUser`, e.g. `this.sendAction('changeUser')`.

**Comment by rwjblue** [comment]
We landed https://github.com/emberjs/ember.js/pull/5398 a while back, then subsequently reverted because of issues with our own helpers needed to support both the dasherized AND camel cased properties with **different** values.  An example is `{{input}}` with its `focus-out` (will be used as an action) and `focusOut` (is the actual function that will be called on blur).

**Comment by rwjblue** [comment]
I am definitely in favor of fixing this, and will flag this issue for conversation with the rest of the team...

**Comment by lightblade** [comment]
:+1:

**Comment by knownasilya** [comment]
Would love this when angle bracket components land.

**Comment by rwjblue** [comment]
We generally track feature requests in emberjs/rfcs, would you please reopen there?
