### ISSUE TITLE
`transitionToRoute` return promise not always giving the route instance to the fulfilled handler

### ISSUE THREAD

**Issue by uberclops** [emberjs/ember.js#10704]
```
-------------------------------
Ember             : 1.11.0-beta.5
Ember Data        : 1.0.0-beta.15
jQuery            : 1.11.2
Ember Simple Auth : 0.7.3
-------------------------------
```

If I use `transitionToRoute` to redirect to the route that I am currently on, instead of passing the route instance into the fulfilled handler it provides a JavaScript object with properties like "queryParams".

**Comment by JaronAndre** [comment]
According to the [documentation for the model hook](http://emberjs.com/api/classes/Ember.Route.html#method_model), your model function should be called everytime:
> Routes without dynamic segments will always execute the model hook.
Looking at the transitionToRoute() call you're making, it looks like your route definitely isn't a dynamic one, so that isn't the problem.

When you navigate away from the "someEntity.new" route, are you navigating to a child route of it and then making the transitionToRoute() call from that child route? If so, that would mean that you never actually left the route and would explain why the model isn't getting called.

**Comment by uberclops** [comment]
Sorry I had accidentally posted the original question in the wrong place... A have moved it to http://discuss.emberjs.com/t/best-practice-for-a-route-which-creates-a-new-instance-of-a-model/7606/1. But to answer your question I am never leaving the route. The transition to `someEntity.new` is happening from its parent `someEntity`. I have a button on `someEntity` which is supposed to transition to `someEntity.new` in the child outlet.

**Comment by acorncom** [comment]
Given the lack of input on this issue (it's been over a year), I'm going to go ahead and close this.  If this is still an issue, please comment and we can re-open and work out how to address your problems.
