### ISSUE TITLE
[1.11 regression] Controller is no longer context of Handlebars helpers

### ISSUE THREAD

**Issue by drogus** [emberjs/ember.js#10714]
I found one regression in Ember 1.11.0-beta5 regarding Handlebars helpers. In previous versions (definitely 1.9, not sure if in 1.10) you could do this:

```javascript
Ember.Handlebars.registerHelper('something', function(options) {
  this.get('model');
});
```

```javascript
Ember.Handlebars.registerHelper('something', function(options) {
  options.data.view.get('controller.model');
});
```

This is not a huge deal as I will be rewriting all of the Handlebars helpers to HTMLBars version anyway, nevertheless it's a regression. I can provide a failing test or a jsbin later today.

**Comment by rwjblue** [comment]
The `this` context inside of helpers has changed in various versions:

* `this` was the controller in 1.0.0 through 1.8.0
* `this` was the view in 1.9.0 and 1.10.0
* `this` is `undefined` in 1.11+

While, the helper context had been consistent for a number of versions (1.0.0 - 1.8.0) it was not considered public API. This was an intentional change in preparation of the HTMLBars (and now Glimmer) work.

**Comment by rwjblue** [comment]
The work around that you listed above `options.data.view` has worked in all of these versions, and is the correct way to go.

I'm sorry if this has caused any troubles...

**Comment by drogus** [comment]
@rwjblue thanks for explanation, I'm going to close this

**Comment by drogus** [comment]
> I'm sorry if this has caused any troubles...

No worries, this isn't a huge deal and it's good to know that it wasn't considered a public API.

**Comment by perlun** [comment]
While trying to update our app to Ember 1.10, I noted that the workaround suggested by @drogus doesn't seem to work for me.

This is the Handlebars:

    {{l _CompanyName}}

And the helper (CoffeeScript):

````
Ember.Handlebars.registerHelper('l', (options) ->
  // options is "_CompanyName" at this point.
  return 'foo'
)
````

How comes?

**Comment by rwjblue** [comment]
@perlun - `options` is always the last argument.  In your case you are providing `_CompanyName` to the helper, so it would need to accept the correct signature in your callback:

```javascript
Ember.Handlebars.registerHelper('l', (compan_name, options) ->
  view = options.data.view
  return 'foo'
);
```

**Comment by perlun** [comment]
Ah, I see. This seems to have changed a bit since 1.8.1 (where we are coming from). Will try your advice and see if I can get it working.

Am I right in assuming that there is no way from the helper to be able to access the view/controller *in which it is being used*? This is done by design, no? (it used to be possible, but one can clearly argue whether it was good or not...)

**Comment by rwjblue** [comment]
Nope, the way to build these helpers has not changed since 1.8.  The `this` context has, but not the signature or structure of them...

**Comment by perlun** [comment]
@rwjblue - thanks! Works fine. :smile:

Could you elaborate a bit more on the "`this` is undefined" in 1.11+ statement. Is there a forum discussion, PR or similar that describes the background a bit more in detail here? For example, if a helper is being used from a component, how would one access the component? `options.data.view.get('something')`?
