### ISSUE TITLE
initializer broken: "ember-application-instance-initializers" feature flag not honored?

### ISSUE THREAD

**Issue by IanVS** [emberjs/ember.js#10744]
It seems that the feature flag is not correctly handling the changes in https://github.com/emberjs/ember.js/pull/10179.

I came to this conclusion after discovering the addon `ember-slide-show` is broken with 1.11.0-beta.5 due to the initializer not working correctly.  It uses the (now deprecated) format:

```
export default function (container, application) {
  container.lookup = function (fullName, options) {
```
If I inspect the container, I find it is actually a registry, not a container.  The initializer then doesn't work as it's supposed to, and the app crashes.

Perhaps this change should be wrapped by the feature flag? https://github.com/emberjs/ember.js/pull/10179/files#diff-72046545a81f2bbfa349461bbcf59035L698

I tried to fork ember.js and make the change to see if it would work, and maybe even submit a PR, but I can't for the life of me figure out how to use a local fork of ember in an app.  `npm link` usually makes it so easy, but I'm lost with bower, and there seems to be no good guide that I can find.  Is there one somewhere that I'm missing?

Using: 

- ember-cli: `0.2.1`
- ember: `1.11.0-beta.5`
- ember data: `1.0.0-beta.16`

Edit: this breaks in `1.11.0-beta.1` as well, but works fine in `1.10.0`

**Comment by IanVS** [comment]
Wait, maybe this has more to do with other recent changes (specifically https://github.com/emberjs/ember.js/pull/10256).  But I don't see any deprecation warnings or URLs or anything, the app just breaks...

**Comment by stefanpenner** [comment]
@IanVS https://gist.github.com/rwjblue/9216101d3d15a9134bdd might be of help to you

**Comment by rwjblue** [comment]
That addon is actually overriding `container.lookup` with its own custom function ([here](https://github.com/tzellman/ember-slide-show/blob/master/app/initializers/slide-lookup.js#L18-L29)). That is generally not a good idea....

The fact that it is not working with 1.11.0-beta.5 is due to a large refactor of the (completely private) container lookup system.  That addon will need to accommodate these changes.

I do not believe that this is an Ember bug, but if you can reproduce without overriding private internal methods (you can use [this JSBin](http://emberjs.jsbin.com/rwjblue/371/edit) as a baseline) we will absolutely get it fixed.

**Comment by IanVS** [comment]
@rwjblue OK thanks.  I'm no expert so I figured I'd report just in case it was indeed a bug.  Appreciate you taking a look.
