### ISSUE TITLE
Unable to call Route action from Controller

### ISSUE THREAD

**Issue by herom** [emberjs/ember.js#10767]
Shouldn't it be possible to call an `action`, declared in a `route` from its connected `controller`?

http://emberjs.jsbin.com/quxiqusonu/1/edit?html,js,output

**Comment by teddyzeenny** [comment]
Hey :) Actions are triggered on the currently active routes, regardless of which controller triggered them. I think the issue here is that you're calling the action during the `setupController` hook, in which case it seems the route is not considered "current" yet to start catching actions.

If you define the action in a parent route (application route), the action will be caught. Or If you delay sending the action to the next run loop, the action is caught by the index route.

See http://emberjs.jsbin.com/sawicu/2/edit?js,console

Not sure if that's a bug or intentional.

**Comment by herom** [comment]
Ah, I see, thanks Teddy :)

I thought that it must be possible to do so as the `model` observer is triggered during `setupController` and therefore I assumed that the `route` is also already set... hmm....

**Comment by trek** [comment]
Regardless of bug/intentional, controllers are going away from 2.0 so it's unlikely this behavior will change in the remaining 1.x releases before June 12.
