### ISSUE TITLE
Binding event attributes `onclick={{exprAsString}}` doesn't work as expected

### ISSUE THREAD

**Issue by jayphelps** [emberjs/ember.js#10774]
Without getting into the security/best practice debate, I'm curious if the current behavior of template bindings to [Event Attributes](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Event_attributes) is correct? Seems counterintuitive.

```hbs
{{!-- Hardcoded, works fine. --}}
<button onclick="alert('such wow');"></button>

{{!-- Via binding, doesn't work. --}}
<button onclick={{exprAsString}}></button>
<button onclick="{{exprAsString}}"></button>
```

This is due to Ember/HTMLBars "property-first" rule; if a the normalized key exists on the DOM object as a property, it is set instead of using `setAttribute`. It would seem this is another exception to the norm, similar to SVG, `style`, `class`, etc.

Here's an example showing the various behaviors:
http://emberjs.jsbin.com/boterobubo/1/edit

**Comment by rwjblue** [comment]
I think we need @mixonic to review, and chime in...

**Comment by jayphelps** [comment]
Low hanging fruit. Just wanted to document as I'm (ab)using HTMLBars.

**Comment by mixonic** [comment]
@jayphelps I'm actually surprised that `<button onclick="alert('such wow');"></button>` works- my assumption was that it would act prop-first and also not create an executable listener.

We plan to implement an `on-` pattern. So you would do this with something like: `<button on-click={{action "alertMe"}}>` to point at an action. In general we expect devs to use actions and not write JavaScript code into HTMLBars templates.

I'm definitely not inclined to add support for `onclick="{{what}}"`, since it would be an XSS vulnerability.

**Comment by jayphelps** [comment]
@mixonic Agreed, it has potential for XSS vulnerability. I'm primarily discussing the consistency and expected behavior, rather than the "best practice". Perhaps this specific case of stuffing a string to them should be assert as unsupported, unless `{{{}}}`/`SafeString` is used. At least for HTMLBars-level to basically comply with expected behavior and then make more restrict assumptions in Ember.

**Comment by mmun** [comment]
Double curlies are too much work. I'm ok with supporting triple curlies.

**Comment by jayphelps** [comment]
@mixonic don't lose cycles over this since it's obviously not a good idea for Ember devs to do this in almost every case, just noting for posterity.

**Comment by stefanpenner** [comment]
this should now work as expected.
