### ISSUE TITLE
API documentation on Promises needs to be fixed

### ISSUE THREAD

**Issue by lmcardle** [emberjs/ember.js#10844]
I looked for changing the content and sending a pull request for this, but I could not find where this file is located in the source code.  The sample code for RSVP.Promise Class, http://emberjs.com/api/classes/RSVP.Promise.html, shows examples of how to return a new promise, here is one:

```
var promise = new Promise(...)
```

With ember-cli, this should instead be:

```
var promise = new Ember.RSVP.Promise(...)
```

**Comment by stefanpenner** [comment]
this is a dupe.

* the docs come from RSVP, which doesn't know anything about Ember.
* shortly this will become `import Promise from 'ember/rsvp'`

**Comment by cbou** [comment]
The link to the definition are also broken: [bower_components/rsvp/lib/rsvp/promise.js:34](https://github.com/emberjs/ember.js/tree/v2.3.0/bower_components/rsvp/lib/rsvp/promise.js#L34)

**Comment by CHIEFnChowCombo** [comment]
:+1:  please fix documentation.

**Comment by jevanlingen** [comment]
@stefanpenner: `import Promise from 'ember/rsvp'` does still not work with Ember 2.4.4. Is there an ETA when this will be possible?

**Comment by stefanpenner** [comment]
@jevanlingen `import RSVP from 'rsvp';`

**Comment by pixelhandler** [comment]
@lmcardle once https://github.com/tildeio/rsvp.js/pull/421 is merged I think that will help.  Since RSVP is a separate library I don't think that the API docs will publish the use of "Ember.RSVP" but rather include the RSVP docs instead. That is why RSVP shows up instead of Ember.RSVP.

I'll close this for now. I think there could be room for more info on using Promises in the guides.

**Comment by pixelhandler** [comment]
Related documentation improvement proposed in the guides… https://github.com/emberjs/guides/issues/1585
