### ISSUE TITLE
Infinite loop for component helper when controller and component have same name

### ISSUE THREAD

**Issue by tsing80** [emberjs/ember.js#10862]
To prepare for Ember 2.0 transition, I try to create the same name for both the component and controller in order to migrate to routable component later. However using the component helper seem to cause an indefinite loop:

Example:
Code:
https://gist.github.com/tsing80/8ada4ca68a9cbe573995

Demo:
http://ember-gist.joostdvrs.com/8ada4ca68a9cbe573995

**Comment by tsing80** [comment]
Ignore the demo link as ember-gist seem isn't upgraded to ember.js 1.11 yet

**Comment by btecu** [comment]
Components must contain a dash in their name.

**Comment by tsing80** [comment]
@btecu Is using the component helpers lift the restriction that component need to be dashized, also the same problem can be reproduced no matter the component have a dash or not  as long as  controller template and component template have the same name (app/any-name/template.hbs and components/any-name/template.hbs )

**Comment by rwjblue** [comment]
This is due to the way the resolver looks for template names.  The route driven template (`app/foo/template.hbs`) is looked for then attempts to render a component named `foo` (which I agree, should trigger an assertion due to lack of dash in the name), then looking up a `component:foo` checks `app/foo/template.hbs` first (because there is no `podModulePrefix`) which is found and used causing the loop.

This isn't how we plan to leverage routable components in future versions (I am unsure if they will be the same type or another type) so I'll close this for now...
