### ISSUE TITLE
{{link-to}} 'active' class is being applied for nested routes

### ISSUE THREAD

**Issue by ryanjm** [emberjs/ember.js#10863]
I expect that only one route's path should be matched when applying the `active` class to a link.

Therefore if you are at `#/school/edit` and have a cancel button which goes back to `#/school` I'd expect it _not_ to have the `active` class on it. 

Here is an example of the output with both links visible and what I would expect:

```html
<a id="ember290" class="ember-view" href="#/school">School</a>
<a id="ember291" class="ember-view active" href="#/school/edit">Edit</a>
```

Here is what I actually get:

```html
<a id="ember290" class="ember-view active" href="#/school">School</a>
<a id="ember291" class="ember-view active" href="#/school/edit">Edit</a>
```

Here is a [JSBin](http://emberjs.jsbin.com/hezaxe/4/edit?html,css,js,output) with the example code reproducing this with `1.11.1`.

I didn't see anyone else's GH issue representing this bug, sorry if this is a duplication.

**Comment by rwjblue** [comment]
Since the `school.edit` route is nested *inside* the `school` route (it is a child), both are technically active.  What you are really trying to do is link to the `school.index` route (not `school` itself).  It is somewhat confusing, but I don't think it is a bug...

Working example: http://emberjs.jsbin.com/suvixa/1/edit?html,js,output

**Comment by ryanjm** [comment]
Ahh, that makes sense. I was wondering how `.index` might play into it. Thanks @rwjblue.

**Comment by manoharank** [comment]
For cancel button, I'm using `window.history.back()` instead of `link-to`.
