### ISSUE TITLE
Visit route helper

### ISSUE THREAD

**Issue by opsb** [emberjs/ember.js#10918]
I'm adding a visitRoute() test helper that will take the same arguments as a {{link-to}}. Here's my implementation so far:

    import Ember from 'ember';

    var testHelpers = function() {
      Ember.Test.registerAsyncHelper('visitRoute',
        function() {
          var args = Array.prototype.slice.call(arguments, 0);
          var app = args.shift();
          var router = app.__container__.lookup('router:main');

          // todo - find a cleaner way to initialize router
          if(!router.router){
            visit("/"); // necessary to setup router
          }

          // extra andThen necessary in case router needs to be initialized with visit()
          andThen(function(){
            var url = router.generate.apply(router, args);
            visit(url);
          });

          return app.testHelpers.wait();
        }
      );
    }();

    export default testHelpers;

As you can see it uses a rather unsightly hack to initialize the router. Is there a cleaner way to do this?

**Comment by stefanpenner** [comment]
actually interesting suggestion.

@teddyzeenny what are your thoughts?

**Comment by teddyzeenny** [comment]
@opsb I don't think it's currently possible to build the URL without the initial visit. You need the Router.js instance to build the URL, and Router.js initialization and the initial visit happen in the same method call. I think you would need to change [how this works](https://github.com/emberjs/ember.js/blob/b80d66f71d75ad0db9022438ed58a41ac84f45f5/packages/ember-routing/lib/system/router.js#L127-L133).

@stefanpenner do you think it's a good idea to have this helper as a core feature? If we want to support this in core, I think it would make sense to add this to the existing `visit` helper which would be consistent with how `tansitionTo` works. We can [detect if it's a URL or a path](https://github.com/emberjs/ember.js/blob/b80d66f71d75ad0db9022438ed58a41ac84f45f5/packages/ember-routing/lib/system/router.js#L976-L978) and act accordingly. My only concern is that it would break existing visit calls without a `/` in them since that would be detected as a path instead of a URL.

**Comment by stefanpenner** [comment]
> @stefanpenner do you think it's a good idea to have this helper as a core feature?

I am unsure, on one hand it will make less brittle tests if URLs change, on the other these are meant for acceptance tests and the public URL's at part of the public "api" humans use to interact with your app. Circumventing that in tests, seems like an anti pattern.

**Comment by teddyzeenny** [comment]
@stefanpenner totally agree with what you're saying. I have the same feeling about the existing `currentPath()` and `currentRouteName()` helpers.

**Comment by stefanpenner** [comment]
ya :(

**Comment by opsb** [comment]
The urls I'm generating are dependent on the ids of the objects that are used to populate the data-store. I wouldn't be able to just use a fixed url as the ids will change on each run.

**Comment by opsb** [comment]
Or perhaps you're suggesting there's value in wiring up the url by hand?

e.g. 

    '/projects/' + project.get('id') + '/tasks'

**Comment by opsb** [comment]
Perhaps a better pattern would be to allow something like:

    visit('planet', planet.get("id"), 'tasks')

**Comment by rwjblue** [comment]
Not really sure how to progress on this.  I'm generally :-1: on suggesting acceptance tests use artificial means to visit specific URL's.

Closing for now, happy to entertain a PR if consensus can be found...
