### ISSUE TITLE
[Regression] Rendering into wrong outlet when hijacking `renderTemplate` and using `this.render()`

### ISSUE THREAD

**Issue by alexdiliberto** [emberjs/ember.js#10916]
This one can be pooled into all of the other recent issues around rendering for v1.11. 

I'm hijacking `renderTemplate` on all the routes and manually rendering into outlets and named outlets with nested children involved. The nested child route for both resources is rendering into the main outlet rather than their respective parent outlets.

Kind of a weird issue to describe...my description probably doesn't do it justice, so just check out the JSBins side by side. 

v1.10 - Working
http://jsbin.com/qupekatuyu/2/edit?html,js,output

v1.11 - Broken
http://emberjs.jsbin.com/pidituqufu/1/edit?html,js,output

/cc @ef4

**Comment by alexdiliberto** [comment]
:facepunch:

**Comment by alexdiliberto** [comment]
:facepunch: 

Noting that this is still an ongoing issue in the latest release of Ember v1.13.4

**Comment by ef4** [comment]
You are probably right that there is a regression here, but this bug has been stuck at low priority because it seems to affect a very tiny slice of actual apps. We are three major releases in, with a single bug report.

There were a lot of underspecified corner cases in the old implementation, and we have tried to fix as many as is practical. I would like to fix this one too, but haven't found the time.

**Comment by jcope2013** [comment]
bumped into issue today in my app also on 1.13.5 as i jumped from 1.9

**Comment by alexdiliberto** [comment]
@jcope2013 Glad I'm not the only one who is having this issue, but I looked at your example workaround and couldn't get it working with my original broken JSin

**Comment by jcope2013** [comment]
@alexdiliberto this seems to fix it? or make it act more like the 1.10 version which has other bugs http://emberjs.jsbin.com/peramivuxu/edit?html,js,output

i removed 

``` this.render('accounts', {
      into: 'application'
    }); ```

**Comment by alexdiliberto** [comment]
@jcope2013 Yea still not the same unfortunately by removing that `render` block...now the transition looks messed up. Hopefully this issue can be fixed

**Comment by locks** [comment]
@ef4 @jcope2013 @alexdiliberto is this still happening?

**Comment by jcope2013** [comment]
@locks yes tried on ember 2.5 and still have to use workaround mentioned in https://github.com/emberjs/ember.js/issues/10916#issuecomment-123816269 or it doesn't work properly

**Comment by Serabe** [comment]
This issue is still happening in [2.6.2](http://emberjs.jsbin.com/pidituqufu/1/edit?html,js,output). In beta still looks like:

![2016-07-22 at 19 01](https://cloud.githubusercontent.com/assets/36221/17064805/be792676-503e-11e6-8286-8e344a747b34.png)

While in 1.10 it looked like:

![2016-07-22 at 19 02](https://cloud.githubusercontent.com/assets/36221/17064829/d716a758-503e-11e6-8f8a-56b9d8e12b98.png)

**Comment by Serabe** [comment]
Still happening in 2.12. Moved it to [this twiddle](https://ember-twiddle.com/86d3d7e7cb5bde232edc42abeac7abb8?openFiles=twiddle.json%2C&route=%2Ftransfers%2Ffoo).
