### ISSUE TITLE
Template support for binding multiple classes to one conditional

### ISSUE THREAD

**Issue by ariroseonline** [emberjs/ember.js#10933]
__To prevent this (without having to make a computed property__):
`<a {{bind-attr class="foo.isActiveButton:btn foo.isActiveButton:btn-xs foo.isActiveButton:btn-capitalize"}}>`

__Suggestion:__
`<a {{bind-attr class="foo.isActiveButton:btn.btn-xs.btn-capitalize"}}>`

__or, in newer Ember versions,__

`<a class={{foo.isActive:btn.btn-xs.btn-capitalize"}}>`

The syntax is fairly intuitive to multiple classes except that the first class doesn't have a period before it. Open to alternative syntax suggestions...

**Comment by rlivsey** [comment]
You can do this in the latest Ember with an inline `{{if}}`:

```hbs
<a class={{if foo.isActive "btn btn-xs btn-capitalize"}}>
```

hth

**Comment by mixonic** [comment]
@ariroseonline I think @rlivsey has the right idea. Micro syntaxes like this are great for experienced devs, but also troll new users just trying to get up to speed on a really rich API. I think Ember will try to move away from them rather than try to make them handle more cases.

But, I encourage you to explore the idea in an addon if it grabs your interest! I think there could be some great htmlbars helpers you could come up with for classes.
