### ISSUE TITLE
ember-source@1.11.3 gem is not actual 1.11.3

### ISSUE THREAD

**Issue by tricknotes** [emberjs/ember.js#10949]
[ember-source@1.11.3](https://rubygems.org/gems/ember-source/versions/1.11.3) has some differences with [actual 1.11.3](http://builds.emberjs.com/tags/v1.11.3/ember.debug.js).
Especially , it has no `Ember.DefaultResolver` :disappointed: 
[[the diff is here](https://gist.github.com/tricknotes/206412c5bbac52bc8890)]

We expect [gem bundled sources](https://rubygems.org/gems/ember-source) are the same as [tagged released versions](http://emberjs.com/builds/#/tagged).
Could you someone republish a new version?

**Comment by tricknotes** [comment]
@fivetanley How about this?

**Comment by bfcoder** [comment]
+1 Any chance a new release could be made for the gem please? I'm stuck monkey patching because the `Ember.DefaultResolver` is undefined.

Can I change line 3198 of ember.debug.js from `Ember['default'].DefaultResolver = resolver.DefaultResolver;` to `Ember['default'].DefaultResolver = resolver['default'];`? Sure, but it would be nice to have the gem reflect the tagged release. :]

Thanks!

**Comment by rwjblue** [comment]
Holy goodness I have been screwing the pooch on these issues.  1.11.3.1 is published

@tricknotes - Please confirm, and close once you have confirmed.

**Comment by tricknotes** [comment]
Thanks @rwjblue 
It works fine for me :green_heart:

**Comment by bfcoder** [comment]
Thanks @rwjblue !
