### ISSUE TITLE
Adding routes at runtime no longer works

### ISSUE THREAD

**Issue by yosoyju** [emberjs/ember.js#10979]
Issue #2892 allowed new routes to be added at runtime. This appears to no longer function in 1.11.3 or 1.12.0 beta 1.

**Comment by rwjblue** [comment]
Can you provide a reproduction? The tests added in that pull request are all passing, so I'm not sure how this is failing without a repro.

**Comment by yosoyju** [comment]
Here is a JSBin running in Ember 1.10.0. Wait two seconds, then click the Foo link.

http://emberjs.jsbin.com/cogofekuho/2/

Here is the same JSBin running 1.11.3. Clicking the link never works because the route is seemingly never registered.

http://emberjs.jsbin.com/kilevi/1/

**Comment by simi** [comment]
You can reproduce it without `setTimeout`  also.

http://jsbin.com/dusogogapa/1/edit?html,js,output

**Comment by honbo** [comment]
Seeing this as well after upgrading to Ember 1.11. Router.map can still be called multiple times, but the actual router instance isn't being remapped when that happens. The tests in the aforementioned commit aren't failing because the second call to Router.map is still happening before app initialization (which IMO doesn't reflect the spirit of the enhancement--in practice the second call to Router.map would happen after initialization).

As a temporary workaround I have resorted to mimicking some of the behavior of _initRouterJs after calling Router.map to at least have my new routes recognized:
```
r = App.registry.lookup('router:main')
cb = r.constructor.dslCallbacks
dsl = new Ember.RouterDSL null,
    enableLoadingSubstates: false
generateDSL = ->
    @resource 'application', { path: "/", overrideNameAssertion: true }, ->
        b.call @ for b in cb
generateDSL.call dsl
r.router.map dsl.generate()
```

**Comment by rwjblue** [comment]
To be honest, I was not aware that we supported lazily defining routes (after app initialization).  I'll try to confirm with the rest of the core team, and see if it was intended as a public API.

**Comment by yosoyju** [comment]
Is there any update to this?

**Comment by rwjblue** [comment]
At this point, I would say that dynamically adding more routes after router initialization is not supported.

Sorry for keeping this issue open so long...

**Comment by sdhull** [comment]
Hah I just [posted in discuss.emberjs.com about this](https://discuss.emberjs.com/t/dynamically-add-routes-at-runtime/13652) ... I guess (for now) I'll try @honbo's hack above and see if that works still (hopefully still works 2 yrs later 😬 )

**Comment by sdhull** [comment]
uhhh trying to reproduce your success @honbo ... in your snippet, it's adding the `'application'` route right?

**Comment by sdhull** [comment]
Ohhhh you run that snippet after calling `Router.map` again at runtime, right?

**Comment by sdhull** [comment]
OK got some deprecation warnings but it works!  🎉 
Thanks @honbo ❤️
