### ISSUE TITLE
transition.sequence is not reset between tests

### ISSUE THREAD

**Issue by blimmer** [emberjs/ember.js#10975]
I have a route that I explicitly block direct access to. Because there are lots of ways to enter this route (I can't always rely on certain properties being set in the model and would prefer to not set a flag just for this case), I check in `beforeModel` if `transition.sequence === 0` and boot the user back to a sane place.

This works swimmingly "IRL", but I'm having trouble testing it because the transition sequence is not reset between subsequent acceptance tests. If I only run that one test, things pass, but when run alongside other `visit`s, I get unexpected behavior because `transition.sequence` does not match what happens during the normal runtime of the application (0 on first visit).

I created this [JSBin](http://emberjs.jsbin.com/wupixe/3) to show the problem. As you can see, the two tests are exactly the same, but one passes and one fails. In my opinion, these two tests should both pass because I'm destroying the app after each test. I understand that ember does some mucking with the Router to allow testing, but I think the `transition.sequence` should be reset between each test.

**Comment by rwjblue** [comment]
The `transition.sequence` is a global integer that tracks a given transition amongst all transitions in the entire system.  The code that manages it just does `this.sequence = Transition.sequence++;` (see [here](https://github.com/tildeio/router.js/blob/ed45bc5c5e055af0ab875ef2c52feda792ee23e4/dist/commonjs/router/transition.js#L51)).

So the reason this fails is because, the second test is actually getting the third transition (first test initial visit, first test redirection, second test initial visit).

I don't think this is a bug per-se (though I definitely understand the confusion that you hit).
