### ISSUE TITLE
Allow {{partial}} accept a content block

### ISSUE THREAD

**Issue by lolmaus** [emberjs/ember.js#11043]
Is there a reason why this is not implemented yet?

**Comment by rwjblue** [comment]
Can you describe what you are after?  If you want `{{partial}}` with a template block it sounds to me like you really should be using a component...

**Comment by lolmaus** [comment]
I'm struggling to DRY out my layouts.

I've got layout Foo which looks like this:

**layouts/foo.hbs**

```html
<foo>
  {{yield}}
</foo>
```

And I want layout Bar to look like this:

**layouts/bar.hbs**

```html
<bar>
  <foo>
    {{yield}}
  </foo>
</bar>
```

The goal is to get rid of code duplication.

Ember Views can't accept more than one layoutName. If they could, I would simply do:

```js
Ember.View.extend({
  layoutNames: ['Foo', 'Bar']
})
```

But that's not possible. :(

So I'm thinking of resolving the issue by writing Bar like this:

**layouts/foo.hbs**

```html
<foo>
  {{yield}}
</foo>
```

**layouts/bar.hbs**

```html
<bar>
  {{#partial 'layouts/foo'}}
    {{yield}}
  {{/partial}}
</bar>
```

This would resolve the issue. But unfortunately Ember Partials don't accept content blocks.

It seems to be a trivial thing to implement for a person familiar with Ember's and HtmlBars' internals.

There are two reasons why I can't use a component instead of a block partial:

1. Component would create an extra DOM element which in turn would interfere with my styles, e. g. `display: table` + `display: table-cell`, the immediate descendant `>` selector and other problems.
2. Components have isolated scope. I often want to split a large `.hbs` file into smaller chunks without going through all the hassle with passing through data and actions (boy, I hate passing through actions! So much boilerplate code!).

These two prevents me from splitting my templates into distinct, DRY partials (one function per partial: menu title, menu item, collapse/expand button; one unique HTML class namespace per partial), like I do in ERB/Haml.

Also, failed to figure out how to dynamically provide a template name to a component. `templateName` seems to be deprecated and doing `{{my-component layoutName="something"}}` won't work for me.

**Comment by rwjblue** [comment]
You should use components for this composition.

Demo: http://emberjs.jsbin.com/rwjblue/443/edit

**Comment by lolmaus** [comment]
Using components is an overkill:

1. I have to create an extra JS file for each template file.
2. Components are a much more heavy machinery than partials, more RAM and CPU usage.
3. Components create an extra DOM element which results in three problems:
  1. Instead of being located in one place, the HTML structure of a partial is split into two places: the top element and the rest of the template. That's so inconvenient.
  2. Extra elements litter the DOM. It becomes deeply nested without any practical benefit.
  3. You can reuse the top element (if you care to customize its HTML via freaking JS), but there can be only one element. You can't have a list of nodes at top level. E. g. you can't provide a list of table cells with a component.
4. Namespacing. When you move a portion of your template into a component, you have to manually pass through every single value and action used in it.

All in all, it's just unreasonable to use components as a way to split a long template file into smaller files.

It's also a misuse of the paradigm. A component is supposed to be a self-contained, reusable element unaware of its context. But when you organize a large template into a number of smaller portions, each portion is meaningless out of its context.

We could use views instead of components for a shared namespace, but it's still an overkill.

Partials are an ideal instrument for the task. The only thing they lack is the ability to accept a content block.

**Comment by rwjblue** [comment]
> I have to create an extra JS file for each template file.

Why?  Components work perfectly without a JS file.  You can even specify the correct `tagName` that works in the calling sites scope (e.g. `{{x-foo tagName="tr"}}` if calling from within a table body or `{{x-foo tagName="li"}}` if calling from a list).

> Components are a much more heavy machinery than partials, more RAM and CPU usage.

Maybe yes, maybe no.  Not sure, but I do know that we are absolutely working very hard to make view/component usage much faster.  Glimmer work was part of this, but more to come.

> Components create an extra DOM element 

As I have described a few times above, this is not true.

> You can reuse the top element (if you care to customize its HTML via freaking JS)

Not required to use a JS file for this (as mentioned above), and future work via the [Element / Fragment RFC](https://github.com/emberjs/rfcs/pull/37) will make it super easy to do this in the components own template.

> Namespacing. When you move a portion of your template into a component, you have to manually pass through every single value and action used in it.

This concern is very important. The fact of the matter is that having a specific API (what things the component/partial require) is *extremely* helpful.  This is not something to be avoided or assumed to be a flaw. It is extremely easy to get into a situation with partials where you have no ability to use multiple places because the partial has assumed that it has access to absolutely everything.  It is a massive refactoring hazard.

> All in all, it's just unreasonable to use components as a way to split a long template file into smaller files.

* I agree to disagree. :smile_cat: 
* Splitting a long file into smaller files serves no purpose without some sort of compartmentalization.
* To make many smaller files that you have to dig through to find where a given thing is just to avoid paging down seems like an odd trade off.

> It's also a misuse of the paradigm. A component is supposed to be a self-contained, reusable element unaware of its context.

I completely disagree. Components are isolated, that isolation allows for very nice re-use (which is a wonderful use-case for them), but re-use is definitely not what their sole purpose is.

> Partials are an ideal instrument for the task.

The benefits of using a component for this use case are many (I have made a few above). Like the `{{template}}` helper, `{{bind-attr}}`, and eventually `{{my-thing}}` (component invocation with curly braces), `{{partial}}` will eventually be deprecated and removed.
