### ISSUE TITLE
Breaking change in {{view}} semantics

### ISSUE THREAD

**Issue by ef4** [emberjs/ember.js#11053]
Passing a class to the {{view}} helper used to be unbound. Now it is bound.

While this may be nice behavior, I'm pretty sure it's an unintentional breaking change.

**Comment by rwjblue** [comment]
Agreed, we should enforce it to be unbound.

**Comment by wycats** [comment]
I'm happy to fix this, but I'm a little surprised that there are cases where people are *relying* on the fact that `{{view foo}}` doesn't update when `foo` changes.

**Comment by rwjblue** [comment]
If we are intentionally changing the semantics here, I think that would be OK.  It seems that this was not intentional (we didn't even know about it until someone reported), and should be treated as a bug.

If we decide to make it dynamic in the future, it will be super simple to reverse whatever the fixing PR does behind a feature flag.

**Comment by ef4** [comment]
> I'm a little surprised that there are cases where people are relying on the fact

liquid-fire was relying on it. More by accident than by design, but here we are. I very much doubt it's the only example.

I don't think there's any behavior so crazy somebody isn't relying on it, if only to mask their own bugs. :smile:

**Comment by rwjblue** [comment]
JSBin Demo here: http://emberjs.jsbin.com/rwjblue/453/edit?html,js,output
