### ISSUE TITLE
Accessing an attribute that holds object in component

### ISSUE THREAD

**Issue by ilkkao** [emberjs/ember.js#11065]
I checked my app against canary and saw many `DEPRECATION: You accessed the 'content' attribute directly. Please use 'attrs.content' instead.` warnings.

In 'The Road to Ember 2.0' RFC it's mentioned that:

`In applications, you should update your component JavaScript and templates to access provided attributes via the component's attrs property.`

I have components that take an Ember object as an attribute, e.g:

`{{my-item content=model}}`

In this case, inside the component

`console.log(this.get('content.foo'));`

Works but generates deprecation warning
    
`console.log(this.get('attrs.content.foo'));`

Doesn't work. Should it?

`console.log(this.get('attrs.content.value.foo'))`
    
Works but starts to be very verbose.    

Full jsbin example: http://jsbin.com/sukatesaha/3/

Is this all intended behavior?

**Comment by ilkkao** [comment]
Correct jsbin: http://jsbin.com/sukatesaha/3/edit?html,js,output

**Comment by rwjblue** [comment]
> I checked my app against canary and saw many DEPRECATION: You accessed the 'content' attribute directly. Please use 'attrs.content' instead. warnings.

The deprecation has been removed for now, until we flesh out the transition plan a bit better.

> `console.log(this.get('attrs.content.foo'));`
> 
> Doesn't work. Should it?
>
> `console.log(this.get('attrs.content.value.foo'))`
>     
> Works but starts to be very verbose.

For mutable values you must use `this.get('attrs.attr-name.value')` in the component JS, but that mutable value is unwrapped for you in the template (so you can use `{{attrs.attr-name}}` in the template.

Since using `this.get('attrs.some-name.value')` is pretty annoying (especially since you may not know or care in your component if you were given a mutable value) we have added a new API (still needs docs) to return the attribute value regardless: `this.getAttr('attr-name')`.

Also, if you do not want a mutable value you can use `(readonly foo)` sub-expression (which will become the default for Ember 2.0) and then you only have to access `attrs.foo.value` if you have a mutable value.

Demo: http://jsbin.com/midasi/1/edit?html,js

**Comment by ilkkao** [comment]
@rwjblue thanks for a thorough answer. getAttr sounds a really nice addition.
