### ISSUE TITLE
CollectionView's itemView and itemViewClass do not support components

### ISSUE THREAD

**Issue by ofbriggs** [emberjs/ember.js#11071]
While the ```itemView``` and ```itemViewClass``` attributes can be used to lookup views in ```CollectionView``` as seen here: 
http://emberjs.jsbin.com/yececapoge/1/edit
They cannot do the same for components:
http://emberjs.jsbin.com/jiyuhamuxe/4/edit

This poses an issue for those who want to want to build a list of components without having to nest a component inside an item view.

**Comment by rwjblue** [comment]
As of a few days ago (when the Glimmer PR landed), a standard `{{each}}` invocation does not create a nested view.  Therefore:

```hbs
{{#each model as |item|}}
  {{my-item-component-name model=item}}
{{/each}}
```

Is the same number of views as when specifying `itemViewClass` / `itemView` *and* will be considerably faster because of the special optimizations that were added with the Glimmer rendering engine.

**Comment by ofbriggs** [comment]
Great news! Does that mean ```itemView``` / ```itemViewClass``` will be deprecated as well in lieu of this approach?

**Comment by rwjblue** [comment]
Yes, specifying any `item*` properties to an `{{each}}` will likely be deprecated.

**Comment by rwjblue** [comment]
I am going to close this now, but am happy to re-open if there are other issues with the direction...
