### ISSUE TITLE
Ember.enumerable lacks ES6's findIndex

### ISSUE THREAD

**Issue by cibernox** [emberjs/ember.js#11108]
I've found that the enumerable mixin does not implement the `#findIndex` method defined in the ES6 specification, although it *does* implement it's cousin `#find`

Should be very easy to implement. Fancy a PR?

**Comment by stefanpenner** [comment]
We would actually like to remove enumerable in favor of something more aligned with es6 iterable.

I think before we add more es6 things. ( that we could get from a different library like core-js) we should do some thorough cleaning of some of our legacy concepts in this area.

Enumerable also introduces enumerable change events, which really nothing uses. It just costs us. Also enumerable doesnt even each correctly ;(

**Comment by cibernox** [comment]
![terrible](http://www.videotapeswapshop.co.uk/wp-content/uploads/2011/09/EverythingIsTerrible.png)

In fact I do use core-js to polyfill ES6 stuff, but doesn't work with hasMany relations and that stuff. What could be the upgrade path for this kind of things?

**Comment by stavarotti** [comment]
@stefanpenner I just recently updated the EnumerableUtils docs and planned on doing more cleanup on ArrayProxy to make more clear methods that are KVO compliant versus those that aren't.  Should I put any effort towards that or wait?

**Comment by buschtoens** [comment]
Just stumbled across this. Still missing `findIndex` and the complementary `findByIndex`.

Would a PR adding these methods be accepted?

**Comment by allthesignals** [comment]
I would just add this in `ember-cli-build.js`:
```
// ember-cli-build.js

var app = new EmberApp(defaults, {
  'ember-cli-babel': {
    includePolyfill: true
  }
});
```

See documentation here: https://github.com/babel/ember-cli-babel#polyfill.

**Comment by buschtoens** [comment]
@allthesignals If I am not mistaken, this has no effect. The core-js polyfill only polyfills natives, not specific Ember implementations and since the Ember.Enumerable or Ember.Array do not extend the native Array, there's no connection between them.

---

To further clarify my original comment, `findIndex` and `findIndexBy` should be added to `Ember.Array`, not `Ember.Enumerable`.

**Comment by buschtoens** [comment]
I published a PR for this: https://github.com/emberjs/rfcs/pull/246

**Comment by allthesignals** [comment]
@buschtoens thanks for the clarification - you're right. Also agree about Ember Array vs Enum.

I guess you'd have to convert back to a "genuine" array to use those: https://www.emberjs.com/api/ember/2.14/classes/Ember.Array/methods/toArray?anchor=toArray - but maybe I'm interpreting that wrong.

**Comment by buschtoens** [comment]
Either that or you use [this trick](https://github.com/buschtoens/ember-rfcs/blob/efad6ae2e0214556f77b99fb0c1e6925a1503dda/text/0000-array-find-index.md#closure--leaky-find-callback-function) described in my RFC. The disadvantage of using `toArray` is that it has to traverse the whole array first in order to construct the native array. That's pretty inefficient.

**Comment by aalimovs** [comment]
@buschtoens FYI, with `toArray()` the order is not guaranteed, see [here](https://www.emberjs.com/api/ember/2.15/classes/Ember.Array/methods/toArray?anchor=toArray).
