### ISSUE TITLE
Reconsider `<angle-brackets />` for components

### ISSUE THREAD

**Issue by sandstrom** [emberjs/ember.js#11100]
It would be better to use a character other than `<` for new components[1]. Ideally just keep the current syntax.

They are confusingly close to HTML syntax, reduce template readability and may break with (future) changes in W3C's web-components.

[1] http://emberjs.com/blog/2015/05/10/run-up-to-two-oh.html

**Comment by wycats** [comment]
Angle-brackets for framework components were a huge selling point of Angular and were since adopted by React.js. More recent frameworks have similarly used angle-brackets for framework components.

It is not only not a controversial syntax, it is effectively the consensus syntax for this feature **at this time**.

In the long-term, `Ember.Component` will likely become a subclass of `HTMLElement`. In the short-term, web components have not landed in many browsers, and are still in active flux. We aren't going to pin our component API to web components until things settle down more, but we have never been shy about saying that once they do, we will likely transition `Ember.Component` to a convenience library written for web components.

What I like about using HTML syntax is that many of the thing you want to do with components actually map directly only things you want to do with tags and attributes.

With angle-bracket components, you can do this, and expect `href` to appear as an attribute on the component in question.

```handlebars
<my-link href="{{url}}/index.html" />
```

To achieve something similar with the Ember 1.x model, you would need to do something like:

```handlebars
{{my-link href=(concat url "/index.html")}}
```

Ember doesn't come with a `concat` helper, so you would need to build one, and you would also need to define an `attributeBindings` on the `my-link` component. A bunch of papercuts when the HTML syntax quite clearly says what it means.

**Comment by sandstrom** [comment]
If there will be a path towards web components (and web components take flight), that'll solve 2/3 of the reasons why I'm sceptic (I certainly trust that you have a pretty good idea of where web components are heading).

I still think they'll be confusing to newcomers (“why does my `<input-field>` component get a `<div>` tag?”) and may decrease template readability (less clear which portions are plain html).

But I'm already converted from *against* to *neutral*. :smile:

**Comment by rwjblue** [comment]
> I still think they'll be confusing to newcomers (“why does my <input-field> component get a <div> tag?”) and may decrease template readability (less clear which portions are plain html).

I don't think it would be a `div`.  I think it would be `<input-field>` (this works today by setting your components `tagName` property, but would likely be automatic when invocation was via angle-brackets).

**Comment by wycats** [comment]
> I don't think it would be a div. I think it would be <input-field> (this works today by setting your components tagName property, but would likely be automatic when invocation was via angle-brackets).

Correct. The default would be derived from the invocation rather than `div`. The fact that that doesn't work yet is part of why the feature isn't on yet :smile:

**Comment by sandstrom** [comment]
Well, you've more or less defused all three then :smile: 

![265963-pic10](https://cloud.githubusercontent.com/assets/122287/7556858/ec770cf2-f782-11e4-8e47-ef64c91e323d.jpg)

**Comment by eccegordo** [comment]
@wycats just because angular and react do it doesn't mean it is best. I agree with the conceptual mapping argument. But there is an important aesthetic consideration. The html angle brackets are ugly like XML is ugly. And the little bit of react code I have seen makes me shudder. But maybe this is one of those bikeshed questions not worth fighting over.

I am not sure I will ever use angle brackets syntax though. But I would have to see more of in action to feel comfortable with it.

I would hope that there is no plan to deprecate mustache curly braces. Because the day I am forced to use angle brackets syntax is the day I quit Ember.

Can you confirm whether or not the long term plan is to actually remove mustache curlies and handlebars long term (3.0 time frame). Because I would prefer to use the handlebars stuff indefinitely even though it means opting out of one way binding. In fact I like that there will be that distinction.

I would assume both angle brackets and mustache templates will be supported for a long time. Any reason they can't be?

**Comment by ef4** [comment]
@eccegordo: 

> Can you confirm whether or not the long term plan is to actually remove mustache curlies

To be clear, we're talking about removing curlies *for invoking components*. Nobody has proposed removing curlies entirely for all the other things they do, like data binding and invoking helpers.

But yes, we intend to eventually drop curly components. Presumably in Ember 3.0. There may be optional builds sooner ("svelte builds") that remove them for people who have already fully migrated.

> I would assume both angle brackets and mustache templates will be supported for a long time. Any reason they can't be?

One problem is that the syntax change is also tied to a behavior change in how you implement components, and maintaining the old behaviors has a performance cost. We can make Ember faster and smaller as soon as we can drop them.

> I would hope that there is no plan to deprecate mustache curly braces. Because the day I am forced to use angle brackets syntax is the day I quit Ember.

It would be far easier to just implement whatever template transpiler you want and continue to benefit from the rest of the Ember community. The actual amount of code involved in supporting the mode you want is tiny -- our reasons for not officially supporting it are not technical, they're social. We need to balance the needs of learners and existing large codebases alike without leaving anyone behind. But you as an app owner are less constrained, and you should feel free to experiment with whatever syntax you like, so long as you can compile it to standard Ember htmlbars templates.

**Comment by eccegordo** [comment]
@ef4 Thanks for the clarifications.

> you should feel free to experiment with whatever syntax you like, so long as you can compile it to standard Ember htmlbars templates.

That was what I was looking for. Coming from the ruby world you have all these great options for templates slim, html, erb, etc. So as long as Ember can remain faithful to that I am satisfied. And the fact that stuff like Emblem is still possible gives me hope.

It seems like in other worlds (angular and react) we have these Java and PHP monolithic corporate cultures behind them imposing hideous code and aesthetics. God help us if JSP tag libraries were still the way to do things. Ugly ugly ugly. And angular suffers from some of the same lack of soul. 

Ember has a certain cool that I hope remains. And just trying to keep up with social trends and popularity becomes a fools errand. Or at least leads to blandness. Anyway, thinking my biases are showing so I will shut up now.

But I can respect the performance argument.

As long as there is a reasonable transpile path I think that is sufficient. Because after all we have to read far more code than write it. We are humans. Make the code for humans. Code is our thoughts expressed in terms that a computer can understand.

Let transpilers and compilers make the code optimal for machines.

**Comment by bevinhex** [comment]
I really love '<' way !!!
Tried angular, react, meteor, ember ... and from point of "Programming enjoyablility" perspective, meteor + react was most enjoyable, followed by ember using ember-cli. UNTILL they released meter1.3 , to me it's like 2.0 version, looks like everything changed, after upgrading, everything used to work doesn't. Then I missed ember again, But this time accidently found out the very feature I've been requesting ember team was realized!
Last time I used ember, everything was perfect, except it's really annoying to use '{{' everywhere, now that it's solved, it's PERFECT. quite ENJOYABLE! 
Now I can use sane stack + cordova to solve most of my problems , effectively.
Personally thanks to the ember community for the feature.
(Yeah, I'm emotional, because I'm excited ;-P)
