### ISSUE TITLE
Ember.Route 'enter' hook missing _super() call will die with unhelpful error

### ISSUE THREAD

**Issue by glennfu** [emberjs/ember.js#11136]
I've been using an "enter" hook on my route to set up some connections to Pusher that my app uses, and  an "exit" hook to remove them. I'm not sure what round of googling suggested me to use this, but I was using it without calling `this._super()`. In Ember 1.10.0, this was totally fine and I wasn't given any warnings or messages. Once I upgraded to Ember 1.11.1, the app just died and FireFox gave the following error:

    Error while processing route: stories.index this.connections is undefined

Chrome was a bit more helpful and said:

    Error while processing route: stories.index Cannot read property 'push' of undefined TypeError: Cannot read property 'push' of undefined

and pointed me to `EmberObject.default.extend.render`. The solution, as @runspired offered, was to call `this.super()`.

Here's a JSBin in case that's necessary: http://emberjs.jsbin.com/kilohiquda/1/

Googling didn't help me out so hopefully people having this problem will find this post. I think the best solution in my mind would be to have Ember more gracefully handle this error and let the user know where they messed up.

Edit: Maybe it would be nice to mention as a 1.10 -> 1.11 transition/migration detail since that's when it changed.

**Comment by selvagsz** [comment]
@glennfu `enter` is a [private api](https://github.com/emberjs/ember.js/blob/8fe0caa26354d8b2198b00fb3a8101d5cd15cd4e/packages/ember-routing/lib/system/route.js#L376-L385). Use `activate` instead. And, I agree some assertions will be helpful though

**Comment by runspired** [comment]
@selvagsz it maybe private now, but there was a time that it was used widely in examples as an easy way to reset scrollTop, which is what I was using it for.  It was maybe the oldest piece of original code left in my app, and so when this happened it took me well over a day to trace down the error.

**Comment by rwjblue** [comment]
It is always a good idea to do `this._super.apply(this, arguments)` (or the much better looking ES2015 version: `this._super(...arguments);`) when implementing framework methods or hooks.

The `enter` method has been [marked as private](https://github.com/emberjs/ember.js/blob/v1.0.0/packages/ember-routing/lib/system/route.js#L32-L39) since prior to 1.0.0.

---

It may be possible to ensure that `_super` is called as I mentioned above from an app linting perspective, but I do not see a way that Ember could determine this at runtime...

**Comment by runspired** [comment]
@rwjblue it's been marked, but that hasn't stopped the examples.  If you google "ember reset scrollTop", the second link (first non ember-docs link) is this: http://stackoverflow.com/questions/13120474/emberjs-scroll-to-top-when-changing-view

**Comment by rwjblue** [comment]
@runspired - Sadly, I do not have the power to make all examples ever use only public API's and give good advice. :smile_cat: 

In the end, it really isn't an issue of public/private, I can not think of a way to do what this issue is requesting (to enforce `this._super` usage by Ember) without also breaking the capability to override things.  It might be able to be done via a build step in Ember CLI though..

**Comment by rwjblue** [comment]
Ok, this is pretty stale, and the solution is to call `this._super` when overriding hooks (in this case a private one).  I'm going to close as I don't really see any other way forward for now.

I'm happy to reopen if others have a better idea...
