### ISSUE TITLE
SVG patterns unreachable while using non hash location with queryParams

### ISSUE THREAD

**Issue by igorrKurr** [emberjs/ember.js#11139]
Hi!

I'm working on integrating charts from DevExpress to my ember app. 
And i faced such issue: when i'm using location 'auto' or 'history' with providing queryParams, svg can't find pattern to use it for filling.
It works with location 'hash' and also without queryParams.
I've created demo repo for this issue - https://github.com/igorrKurr/svg-unreachable-demo( i can't use this combination of queryParams and location: 'auto' in jsbin).
You can find svg in templates/-svg-chart.hbs. 
I made it filling on hover, so it's easy to see what happens.
You can see how it should be displayed visiting http://localhost:4200/ and wrong displaying visiting  http://localhost:4200/?hotelId=123456

Thanks!

**Comment by rwjblue** [comment]
Just submitted https://github.com/igorrKurr/svg-unreachable-demo/pull/1 to update to 1.13, but it seems that there is still an issue. Swapping to `hash` location fixes the issue, which likely means that this is another case of `<base>` tag messing things up again (because it changes the URL that all `url()` functions in CSS are based on).

The solution here is to prevent the `<base>` tag from being used, or use something other than an element id with `url`.  Also, this is more of an ember-cli issue than an Ember one (see https://github.com/ember-cli/ember-cli/issues/2633).

Closing in favor of https://github.com/ember-cli/ember-cli/issues/2633.
