### ISSUE TITLE
[1.13.0-beta.1] `attrs` is null in `init` method on angle-bracket component

### ISSUE THREAD

**Issue by uberclops** [emberjs/ember.js#11200]
Given:
```
<my-component test={{test}} />
```
And:
```
export default Ember.Component.extend({
    init: function() {
        let x = this.get("attrs.test");

        return this._super();
    }
});
```
Then `this.get("attrs.test")` returns `null` as `attrs` is `null`. This is not the case when using:
```
{{my-component test=test}}
```

**Comment by rwjblue** [comment]
This is intentional. Having attributes available on init is a 'legacy' (aka curly bracket) component behavior. If you are using angle bracket invocation for your component you must do your initialization in 'didInitAttrs'. 

There will be a blog post/guide released soon to review some of the new life cycle hooks and when to use them. We are definitely sorry for the confusion here.

**Comment by uberclops** [comment]
Not a problem, busy playing around with everything :P Thanks for everything you guys are doing!
