### ISSUE TITLE
{{input type="phone"}} does not works in Chrome 43 with Ember 1.12

### ISSUE THREAD

**Issue by Serabe** [emberjs/ember.js#11265]
In Chrome 43, the following code returns "text" and not "phone" as expected.

```js
var input = document.createElement('input');
input.type = "phone";
input.type;
```

Therefore, with Ember.js 1.12, the following code shows a text input.

```hbs
{{input type="phone"}}
```

[JSBin](http://emberjs.jsbin.com/leqoyelobo/3/edit)

In Ember 1.11.3, the correct type was shown ([JSBin](http://emberjs.jsbin.com/leqoyelobo/5/edit)).

**Comment by brettburley** [comment]
Here's the commit that caused this change:
https://github.com/emberjs/ember.js/commit/7526d1fbc9c062b4054c2349796f8845499236f9#diff-31b69c26536594b82281abdbb33f9492

The type you're probably looking for is `tel`. It looks like Chrome automatically falls back to a text type when phone is provided:
```
> var e = document.createElement('input');
> e.type = 'phone';
> e.type
"text"
```

So in version 1.12, Ember is doing this fallback itself, rather than relying on the browser to prevent an error in IE10 as according to the commit message.

**Comment by rwjblue** [comment]
Correct. The current behavior is intentional (though I agree it is annoying that we have to deal with the browser inconsistencies like this).

**Comment by stefanpenner** [comment]
should be addressed by https://github.com/tildeio/htmlbars/commit/d63b675a579bade22124d02415da7a996cda4ecb
