### ISSUE TITLE
Query Params not Serializing Properly when Default Value is `null`

### ISSUE THREAD

**Issue by jfelchner** [emberjs/ember.js#11275]
JS Bin: http://jsbin.com/quyoha/1/edit?html,js
Screencast: https://www.dropbox.com/s/7l27llc0ce8s487/ember-query-params-bug.mp4?dl=1

As shown in the screencast, if the value of the QP starts off as an array `[]`, then when the transition happens, the new array value is properly serialized in the URL.

However if the QP starts off as `null` (because we don't want a default value), then the QP is improperly serialized in the URL.

It seems as though the array is being converted into a String and _then_ serialized rather than being serialized as is.  This behavior happens if I set the value of the QP to `'some string'` and then try to transition to it and set it to an Array.

My assumption would be that when I do the transition, the current value of the QP would be wiped away and the new value passed in would take its place.

The only thing I can think of is that it was desired that "query params should not change their type" for whatever reason (and if you know the reason I'd love to understand it).  If that _is_ the case, first off, I'd like to voice my opinion to the contrary, but if there's a good reason, then a default value of `null` should still be allowed to be changed considering that `null` is effectively "no type".

This took me about 3 hours to track down and figure out what the problem was.  If a newbie were to run into this, they would have almost zero recourse as to how to proceed since the solution is so non-obvious.

So even if this is intended behavior, I think some sort of message to the user would be appropriate.

Thanks! :grinning:

**Comment by joshfarrant** [comment]
+1 on this one, I've also noticed that any overrides applied to the `serializeQueryParam` method in the route don't seem to take effect.

For example I could set `someQueryParam` in the controller, then have something like this in the route:

```
serializeQueryParam: function(value, urlKey, defaultValueType) {
     return 20;
},
```

I would expect the resulting param in the request to look something like this: 

_?someQueryParam=20_

However it remains like this

_?someQueryParam=1_

Is this expected?

**Comment by brettburley** [comment]
@jfelchner That is the design of the default serializer:
https://github.com/emberjs/ember.js/blob/v1.12.0/packages/ember-routing/lib/system/route.js#L269

It bases the serialization from the type of the default value. Since the deserializer must work from strings from the browser window location, it doesn't necessarily know the type of that string before deserializing it. Using the default property type is a good guess.

I suppose that if you're redirecting to a route with a `queryParams` property, the type could be known. The technical reason it isn't is because it's passed through the serializer first:
https://github.com/emberjs/ember.js/blob/bfcc15ee3ac2b2b3e4dad6aa0d7a447936302f5a/packages/ember-routing/lib/system/router.js#L532

If this array were to be serialized to `%5B%22a%22%2C%22b%22%2C%22c%22%5D` from the `this.transitionToRoute` call, after a page refresh, how would this be deserialized back into an array, since the only types you know are that the querystring is a string, and the default value is `null`?

I could imagine that the default query param serializer might be smarter about types so that there isn't ambiguity in the type it's deserializing from. In fact, I'm not sure why it doesn't just always use `JSON.stringify` and `JSON.parse` for all data types, and not just arrays.

**Comment by pixelhandler** [comment]
@jfelchner can you provide an updated example (reproduction of the issue) using a current release of Ember.js or the LTS release (2.4.6) ?

**Comment by knownasilya** [comment]
Seeing something similar, but a different situation.

I have an array QP on the ApplicationController, and in certain situations the array comes back serialized, i.e. a string instead of an array.

**Comment by jfelchner** [comment]
@pixelhandler http://jsbin.com/puvovupatu/edit?html,js,output

**Comment by Serabe** [comment]
As explained by @brettburley, that is how the serializer for QPs work: it depends on the value for the default value.

Thank you!

**Comment by mmpestorich** [comment]
This is because a copy of the the default query param value is made:
https://github.com/emberjs/ember.js/blob/3e804aea5bb63ae8a74b923a53aab6b088c7317a/packages/ember-routing/lib/system/route.js#L117

If that default query param value on the controller is an array, later on when finalizing the query params, a referential equality check is done to determine whether the qp value is a default value:

https://github.com/emberjs/ember.js/blob/3e804aea5bb63ae8a74b923a53aab6b088c7317a/packages/ember-routing/lib/system/route.js#L740

Because that will never be the case if the array on the controller is replaced with a new array, the param will be serialized in the url. If you always replace the contents of that array instead of setting the controller value to a new one, the referential check will work as intended and not serialize the value in the url.
