### ISSUE TITLE
Components don't isolate their properties

### ISSUE THREAD

**Issue by igorrKurr** [emberjs/ember.js#11354]
Hi!

While developing addon I faced that problem. I have two components - one that used as container and one as it's item.

So, in item component I have `didInsertElement` hook that just pushes kinda decorated item  to container component's items property. Then in container component also on `didInsertElement` I initialize some jquery logic with received items from item components.

But problem is when i put this container components both on the same page, then in the second container component i placed i get its items property contains items from the first container component too.

I've tried to run it on `1.12.1` from master, `1.13.0-beta.2`, on `canary`, but same result.

I've created jsbin to illustrate, you can see it there - http://emberjs.jsbin.com/retikulayu/1/edit?html,css,js,output

**Comment by rwjblue** [comment]
When you define a non-primitive value in an objects prototype it is shared across all instances of that object.  This isn't really an Ember issue, it is normal Javascript behavior.  Consider the following:


```
function Thing() { }
Thing.prototype.items = [];

var thing1 = new Thing();
var thing2 = new Thing();

thing1.items.push('item from thing1');
thing2.items.push('item from thing2');

// thing1.items and thing2.items both
// point to the same exact Array instance
// with the contents of:

// => ['item from thing1', 'item from thing2']
```

To do what you want, you need to have each instance create its own `items` array (so they are not shared on the prototype).  This would like like the following in plain JS:

```javascript
function Thing() {
  this.items = [];
}
```

Working JSBin: http://emberjs.jsbin.com/xelizib/1/edit?html,js,output

**Comment by igorrKurr** [comment]
:+1: Exactly) Thanks a lot!

**Comment by rhasson** [comment]
Hi, 

I opened a similar issue (#11356) around the same time but closed it fairly quickly after being pointed to this issue.  However, my solution is still broken.

When Iook at the prototype chains I see that the DS.model that I create for each of my components share the same prototype.  Since I'm creating a new instance of the same DS.model for every one of my components that data I enter into one shows up in all the others.  I don't know how to resolve this issue.

JSBin: http://jsbin.com/mavaxomofi/1/edit?html,js,output
To use it, just click the button next to the Hello, then type something in the box and click the button again.  This will create another instance of the model/component but will show the text from the previous input box.  I expect them to not share the data.

Thanks,
Roy
