### ISSUE TITLE
Ember.lookup.location.origin is undefined for old IE versions

### ISSUE THREAD

**Issue by f3ndot** [emberjs/ember.js#11398]
Tested on: `1.12.0`
Minimal example: http://emberjs.jsbin.com/liqezejiwa

## Steps to reproduce:

1. Open minimal example in Chrome, Firefox, Safari, IE11
2. Observe that the origin is displayed
3. Open minimal example in IE10 or older
4. Observe that the origin is blank (below)

![screen shot 2015-06-10 at 12 34 36 pm](https://cloud.githubusercontent.com/assets/740289/8088126/19c1275e-0f6d-11e5-940f-d46f3f9cb1df.png)

## Problem:

Despite having a bunch of polyfills for old browsers/IE defined in `ember-routing/location/util`, the location object used in Ember isn't polyfilled, directly.

## Solution:

I propose that when the `window.location` object is placed into `Ember.lookup.location`, the polyfills (like [`getOrigin()`](https://github.com/emberjs/ember.js/blob/v1.12.0/packages/ember-routing/lib/location/util.js#L50-63)) are run so we can access it directly.

**Comment by mixonic** [comment]
I believe we would prefer to move away from extending native objects (and prototypes) instead of doubling down on them.

Fwiw, in app code, I'm not sure accessing `Ember.lookup` instead of `window` is best. `Ember.lookup` is really just an internal that allows us to retarget the global scope.

IMO the ideal solution here is an addon (or JS lib) that exposes a bunch of cross-browser utilities for reading and writing to the location. In fact we do something similar here:

* https://github.com/aptible/ember-cli-aptible-shared/blob/master/app/utils/location.js#L3

So we can stub out "writes" to the location object in testing:

* https://github.com/aptible/ember-cli-aptible-shared/blob/master/test-support/helpers/mock-location.js#L12

I'm going to close this issue as I don't think we will be polyfilling the native location object ourselves, but please re-open if I have missed something!

**Comment by mixonic** [comment]
Oh yeah, and we use the mocked location history for assertions when testing: https://github.com/aptible/ember-cli-aptible-shared/blob/master/test-support/helpers/aptible-helpers.js#L62
