### ISSUE TITLE
Inconsistent behaviour of {{#with}} helper

### ISSUE THREAD

**Issue by novtor** [emberjs/ember.js#11473]
Ember 1.13.0
If there is a component inside {{#with}} helper, the component is not rerendered on the with condition change.
{{#with colors as |color|}}
  {{my-component data=color}}
{{/with}}
Example:
http://emberjs.jsbin.com/jopulo/9/edit?html,js,output
on 1.12.0 and before, the entire {{#with}} block was rerendered and now it seems that {{#with}} becomes just a synonim of {{#if}}
Is it expected behavior?

**Comment by joeruello** [comment]
This is expected with the new Glimmer rendering engine. It is optimized as to only update changed areas of the DOM, rather than fully renderer everything. Glimmer only works with templates, so if you've added DOM nodes using another method (jQuery), it has no knowledge of them and won't touch them.

Is there a use-case here that you could not implement using templates?

**Comment by novtor** [comment]
Thank you for your answer @joeruello. Yes, my usecase is that within {{#with}} block I render a table with jquery datatables and rendering is done by the datatables itself, I just pass it the data to render. In this manner it avoids rendering the table twice (well perhaps one and a half): first time by the template and the second time by datatables which will need to parse the DOM, make pagination, add classes and so on.
Another usecase can be d3 charts, where the entire chart must be re-rendered on the model change.

**Comment by joeruello** [comment]
Have a look at the [Blog Post](http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html), specifically the part about component life cycle hooks. I haven't tested it myself, but It seems if you move your `didInsertElement` to `didRender` and manually clear out the DOM each time (`this.$().empty()`) you'll get the effect you're looking for. Although it probably isn't best practice...

D3 gives you tools to update charts rather than re rendering them, which also allows you to do some cool animations/transitions when models/data changes.

On the table front, have you looked at [Ember Table](http://addepar.github.io/ember-table/#/overview) at all?

Should probably close this issue, feel free to email me if you want to talk more.

**Comment by novtor** [comment]
Hi again @joeruello, here is my usecase reproducing:
http://emberjs.jsbin.com/celiwo/1/edit?html,js,output
Yes, I saw this blogpost and this what I was thought of to workaround the problem : is to use the hooks to clear and re-render the data.

About d3: I agree with you that there are some cool staff for transition animations but sometimes you just need to re-render the entire area just because the current data in the chart is nothing to do with the new arrived data: let's say there was a chart with potatos cosommation per capita during last 10 years monthly and now the user wants fuel consommation by family since 1940 yearly. 

I'll try to give you yet another example where the number of charts can vary. Let's say that we represent the electric energy production evolution by year and by country and we want to have a chart by the energy type. Imagine that the country X produces nuclear energy and petrol energy so we render 2 charts: for the nuclear and for the petrol, and now the user chooses another country Y which produces only solar energy (scince-fiction but anyway) so we should render only one chart : for the solar. It should be something like:
```
{{#with model as |energies|}}
  {{#each energies as |energy|}}
    <h2>energy.title</h2>
     {{my-d3-chart data=energy.data}}
  {{/each}}
{{/with}}
```
JSBin for this usecase (with table as component, not chart):

http://emberjs.jsbin.com/xofote/edit?html,js,output

Type 2 letters let's say 'ab' then replace them by 'cd' nothing happens. Another case: type 'ab' and then replace it by 'cde'. The 'cd' has no effect so the tables for 'ab' stay displayed and table for 'e' is added.

So IMHO the {{#with}} helper should have its place as it had before 1.13. Otherwise there will be some coding overheads for components to observe if the data has completly changed and to clear the stale data and to render the new one.

**Comment by novtor** [comment]
just tested, the workaround is as you suggested to move the table creation from didInsertElement to didRender. Then should check if datatable exists then destroy it and recreate a new one

**Comment by novtor** [comment]
As no more persons are interested, I think you can close this issue. It is just dammage that everyone will have to implement the same thing on all components to handle model changes that could be handled by with helper.

**Comment by rwjblue** [comment]
If you take a look at [this](http://rwjblue.jsbin.com/romekif/edit?html,js,output) demo, you will see that the `with`'s block param is indeed being updated properly,  but `TableCmpComponent` is expecting that `didInsertElement` to be fired for each update of the `colors` block param.  This was true of Ember 1.12, because every rerender deleted and re-created the element associated with the view/component.  However, in Ember 1.13+ the element itself is only inserted once and is updated for each change.  Using `didRender` as was mentioned earlier can be used for similar behavior as `didInsertElement` (in this case).

Sorry for the delay in responding, seems like you have this sorted out...
