### ISSUE TITLE
Passed in actions on component override methods

### ISSUE THREAD

**Issue by gordonkristan** [emberjs/ember.js#11527]
I recently upgraded to Ember 1.13 and created a component. My component looks something like this:

```js
export default Ember.Component.extend({
    someMethod() {
        this.deleteVertex()
    },
    deleteVertex() {
        // do some stuff
        this.attrs.deleteVertex();
    }
});
```

I use the component like this:

```html
{{tree-graph deleteVertex=(action 'deleteVertex')}}
```

Passing in an action with the same name as a method the component _overwrites the component method_. The `deleteVertex()` method in the component can never be called. Is this desired behavior? It seems like a bad idea that consumers of a component can modify the behavior of the component without the component knowing.

**Comment by rwjblue** [comment]
This has been the behavior for a very long time (well prior to 1.0.0), it is definitely not good and we are actively moving away from this (and towards setting attributes passed in on the '.attrs' hash instead of the root of the object).  

We will be using angle bracket component invocation to opt into the new semantics (and to avoid such a breaking change). You can take a look at the pending RFC discussing angle bracket unification).

**Comment by gordonkristan** [comment]
Wow, you're right. I've been using Ember since before 1.0.0 and apparently this is the first time I've run into a name collision like that (or at least the first time I remember running into one). :confused:

Thanks for clarifying that. I'll just rename my methods until angle bracket components land. :+1:
