### ISSUE TITLE
Possible Glimmer regression in accessing a component's array attribute

### ISSUE THREAD

**Issue by jacobthemyth** [emberjs/ember.js#11538]
# Summary
An array passed as a parameter to a component is being "wrapped" in an object.

![screen shot 2015-06-23 at 1 30 55 pm](https://cloud.githubusercontent.com/assets/1620230/8312800/ceb8b796-19ac-11e5-9d42-1ccd0c713886.png)

It seems to behave differently on 1.12.1 than on 1.13.0, beta, and canary.

# Explanation

Given the following Handlebars:

```html
<script type="text/x-handlebars">    
  {{#each model as |item|}}
    <li>{{item}}</li>
  {{/each}}
    
  {{add-item items=model}}
</script>

<script type="text/x-handlebars" data-template-name="components/add-item">
  <button {{action 'addItem'}}>Add Item</button>
</script>
```

## 1.12.1 behavior

With the following, 'green' is added to the list:

```js
App.ApplicationRoute = Ember.Route.extend({
  model: function() {
    return ['red', 'yellow', 'blue'];
  }
});

App.AddItemComponent = Ember.Component.extend({
  actions: {
    addItem: function(){
      this.items.addObject('green');
    }
  }
});
```

### Example
http://emberjs.jsbin.com/muceheweyu/18/edit?html,js,output

## 1.13.0, beta, and canary behavior
Changing the action function to the following shows that the `items` array is being wrapped by, presumably, Glimmer.

```js
console.log(this.attrs.items);
// => screenshot below
```

![screen shot 2015-06-23 at 1 30 55 pm](https://cloud.githubusercontent.com/assets/1620230/8312800/ceb8b796-19ac-11e5-9d42-1ccd0c713886.png)

```js
addItem: function(){
  this.attrs.items.addObject('green');
  // or `this.get('attrs.items').addObject('green');`
} // => Uncaught TypeError: Cannot read property 'addObject' of undefined
```

### Example
http://emberjs.jsbin.com/muceheweyu/20/edit?html,js,output

**Comment by rwjblue** [comment]
`this.attrs.item` is wrapped as a mutable object (as you have discovered) because bindings are two-way by default for components invoked with curly brackets. In the future, when we have enabled angle bracket invocation for components bindings will be one-way by default and `this.attrs.items` will be the standard value (not a mutable object wrapper).

---

You must use `this.get`  (or `Ember.get`) to access attributes passed to components.  Updating the [example JSBin](http://rwjblue.jsbin.com/daseyo/3/edit?html,js,output) to use `this.get('items').addObject('green')` works as expected in both 1.12 and 1.13.

It is unfortunately that accessing `this.items` directly (without `this.get`) worked in older versions, but we have always documented that folks should use `this.get` to access properties of a component.  I am sorry, but I don't think we are going to consider this a regression.

**Comment by jacobthemyth** [comment]
@rwjblue Thank you. I originally was using `this.get('attrs.items')`, so using `this.get('items')` is not a problem. However, it wasn't clear to me that you could access attributes directly with `.get` ever since `attrs` were separated from the component's own properties.

**Comment by rwjblue** [comment]
Using `this.attrs` is not recommended until we have one-way bindings by default.  It will work, but isn't really great because you will always have `this.attrs.someThing.value` (due to mutable object by default) which kinda sucks.  

^^ is the main reason we have not "advertised" heavily the use of `this.attrs.foo` for things passed in just yet.

**Comment by jacobthemyth** [comment]
:+1: Makes sense, thanks.
