### ISSUE TITLE
How to use multiple action on input helper

### ISSUE THREAD

**Issue by xfanz** [emberjs/ember.js#11551]
{{input name="nm action="oknm" on="focus-out" }}
I also want to define an action on "focus-in"
How to do?

**Comment by sevansio** [comment]
If you use a native input element rather than the `{{input}}` HTMLbars helper and you can do the following: 
`<input name="nm"
  {{action "focusIn" on="focusIn"}}
  {{action "focusOut" on="focusOut"}}
/>`

Then you just need to define the action handlers where applicable on your Component, Controller or Route depending on where you've implemented your `<input>` field :
```
actions: {
  focusIn: function() {
  },
 
  focusOut: function() {
  }
}

**Comment by trek** [comment]
The related PR is https://github.com/emberjs/ember.js/pull/11373. This should be present on 1.13

**Comment by stefanpenner** [comment]
@trek i don't believe that works on the `input` component

that being said, this is better asked on Stackoverflow as it is a much better venue for Q/A. If an issue does arise feel free to open an issue.
