### ISSUE TITLE
Link-to URL serializes inaccurately with nested routes with same param name

### ISSUE THREAD

**Issue by brian-gates** [emberjs/ember.js#11595]
http://emberjs.jsbin.com/runepileyi/1/edit?html,js,output

Expected: "Go to subroute" should link to #/1/2

Actual: The link shows #/2/2 and transitions to #/1/1

Manually specifying the values in the URL seems to work as expected.

**Comment by pixelhandler** [comment]
@brian-gates I took a look at your example jsbin and still am wondering where I could start to look into the issue. Have you tried adding logging, does that help add more clarity to the describing the issue?

```js
App = Ember.Application.create({
  LOG_TRANSITIONS: true,
  LOG_TRANSITIONS_INTERNAL: true
});
```

**Comment by SaladFork** [comment]
I worked with @brian-gates on this a bit via Slack so might be able to provide some background information.

In the posted JSBin we have two routes: `foo` and its child `foo.bar`. Each of these has a dynamic segment with name `brian`.

The application template contains a link to the child route, `foo.bar` with segment values `1` and `2`. Upon clicking the link and transitioning, the `foo/bar` template correctly shows the two values, `1` and `2`.

There seems to be three issues that arise:
* The URL shows an incorrect `#/1/1` rather than the expected `#/1/2`.
* Refreshing the page will actually result in a different app state: both `brian`s being set to `1`.
* Changing the URL manually seems to only update the app when the first `brian` is changed, but not the second:
 * Change URL from `#/1/1` to `#/2/3` updates the values to `2` and `3`, this is correct.
 * Change URL from `#/2/3` to `#/2/4` -- nothing happens
 * Change URL from `#/2/4` to `#/5/4` updates the values to `5` and `4`, this is correct.

I suspect that somewhere along the way something is doing an `Ember.merge` and not considering whether multiple routes can have the same dynamic segment name.

**Comment by rwjblue** [comment]
This is mostly a documentation issue I believe.  Using the same param name for nested routes is going to have these sorts of issues.

It might be possible to detect this, and issue a warning/assertion but I'm unsure if that would take away some legit cases where you would want this behavior...

**Comment by locks** [comment]
@rwjblue could it be a linting rule that's turned on by default?

I suggest we close this issue and open one in the Guides for a clarification in the nested routes section.

**Comment by rwjblue** [comment]
Sure, seems good to me (RE guides info). We may also want to add info to the router.map API docs.

**Comment by pixelhandler** [comment]
@locks can you close this issue once you open an issue in the emberjs/guides repo?

**Comment by jameshoward** [comment]
I've hit this issue with trying to have nested routes that handle showing models from a `hasMany`. For example:

* `people.person` has path `people/:id` and should show the person matching ID. The `model` hook returns a Person.
* `people.person.lectures.lecture` nested route has path `people/:id/lectures/:id`  Show the lecture matching the ID that belongs to the person.

Changing those routes to `people/:personId` and `people:/personId/lectures/:lectureId` is fine until you start using `transitionTo` / `linkTo` and specifying the models rather than IDs. E.g. `this.transitionTo('people.person', person)` shows the right data but the URL is updated to `people/undefined`, presumably because there's no `personId` on the model.

**Comment by christophermlne** [comment]
@jameshoward i got around the lack of `personId` on the model by adding  `personId: computed.alias('id')` to the model. Hopefully this helps someone who finds this thread looking for a solution
