### ISSUE TITLE
Ember Component observes triggered twice

### ISSUE THREAD

**Issue by SeyZ** [emberjs/ember.js#11638]
I have an `Ember.Component` that observes a property passed through the template. The observes function is always called twice instead of just once.

Here's the JSBin to reproduce/understand the problem:
http://emberjs.jsbin.com/jiquki/edit?html,js,console,output

**Comment by locks** [comment]
Just want to add that passing the model and observing model.property instead triggers once as expected: http://emberjs.jsbin.com/tozoro/1/edit?html,js,console,output

**Comment by stefanpenner** [comment]
@SeyZ / @locks can you guys confirm on canary?

**Comment by mixonic** [comment]
Confirmed that this still occurs on canary

**Comment by SeyZ** [comment]
@stefanpenner +1 I confirm.

**Comment by pixelhandler** [comment]
For an additional example, see #11821, may be a duplicate, which has a jsbin link: http://emberjs.jsbin.com/qimagaciqu/edit?html,js,output

**Comment by justin-lau** [comment]
[The `number` computed property](https://github.com/justin-lau/ember-intl-tel-input/blob/v1.1.2/addon/components/intl-tel-input.js#L189-L206) of a component in [an addon of mine](https://github.com/justin-lau/ember-intl-tel-input) no longer works after upgrading to 1.13.0 - 1.13.5.

I'm not sure if the root cause is the same with this issue, but when I tried to add an observer in the dummy app's controller, I found it fired twice every time the input's value has changed. Eventually I found the property's getter is also fired twice on every update. Here is the weird part: the property getter always returns the correct value when it is fired, but `this.get('number')` in the observer only evaluates to that value in every first time it gets fired, and `undefined` every second time.

I have tried adding observers to some other properties of the same component but they only fire once.

To test the behaviour on my addon, use [tag v1.1.1](https://github.com/justin-lau/ember-intl-tel-input/tree/v1.1.2) for ember 1.12, and the [master branch](https://github.com/justin-lau/ember-intl-tel-input) for ember 1.13.5.

**Comment by stefanpenner** [comment]
I believe @ef4 just landed a pr that fixes this

**Comment by rwjblue** [comment]
@stefanpenner - The fix that just landed prevents double observers on initial render, but it does not address this issue.

**Comment by rwjblue** [comment]
Update JSBin: http://rwjblue.jsbin.com/nacaki/edit?html,js,output

**Comment by stefanpenner** [comment]
it appears we trigger from both of the following:

*  legacyAttrDidChange
* legacyDidReceiveAttrs

**Comment by jcope2013** [comment]
seem to be fixed on canary/release now

**Comment by SeyZ** [comment]
I confirm, it's fixed! Thanks!

**Comment by ef4** [comment]
@rwjblue: this is still a problem on 1.13.6 but fixed in canary. Will it hit the next 1.13.x release?

**Comment by rwjblue** [comment]
@ef4 - It is already pulled into the stable branch (you can confirm with `bower install --save ember#release`), and queued up for release once 1.13.7 is released.

**Comment by miguelcobain** [comment]
Any idea when this bug was introduced?

**Comment by rwjblue** [comment]
@miguelcobain - It was introduced as part of the rendering engine rewrite (glimmer), specifically related to the implementation of the attrs proxy for pre-angle-bracket component support.  It has been in every version since 1.13.0-beta.1.
