### ISSUE TITLE
Observable property for .didInsertElement .willInsertElement etc...

### ISSUE THREAD

**Issue by olivierlesnicki** [emberjs/ember.js#11672]
When trying to access a component's `this.$` method, before the `willInsertElement` hook has fired an error is thrown.

What I had to do is create a custom property: `isElementInserted` and make sure I never do a `this.$` call if `isElementInserted` is false.

This seems like a common enough pattern, and would encourage reactive programming.

For example:

```js
height: Ember.computed('isElementInserted', 'some-other-property', function () {
  return this.get('isElementInserted') ? this.$().height() : 0
})
```

**Comment by mixonic** [comment]
@olivierlesnicki I suggest using a hook and schedule:

```
  didRender() {
    Ember.run.schedule('actions', () => {
      this.set('height', this.$().height());
    });
  }
```

This has three advantages:

* It runs after each render instead of just after the initial render of the component (a component may change height based on a change of its contents).
* It schedules the change into actions, so if several components change height properties there is only a single (expensive) re-render.
* By scheduling into actions, you ensure that children and parent components have completed rendering (other components may change the layout of this component).

I don't believe we have an observable property, and we have avoided adding one. There is a performance concern related to firing property change notification during rendering, and additionally we want to avoid re-renders as much as possible and making part of the render process observable would encourage re-rendering code.

**Comment by olivierlesnicki** [comment]
@mixonic  Won't `component.set` (which you've called in the schedule callback) trigger a re-render?

**Comment by mixonic** [comment]
@olivierlesnicki correct, it will still trigger a re-render. However it will finish the current pass first, then cause a single rerender even if multiple components have had values set.
