### ISSUE TITLE
can't overwrite component's template in unit tests

### ISSUE THREAD

**Issue by olivierlesnicki** [emberjs/ember.js#11688]
I get the following error:
 Cannot call `compile` without the template compiler loaded

```
  var component = this.subject({
    layout: Ember.Handlebars.compile(`
      <div class="small-div">
        Small div
      </div>
      <div class="big-div">
        Big div<br />
        Big div<br />
        Big div<br />
        Big div<br />
        Big div<br />
      </div>`),
    viewport: Ember.Object.create({
      width: 0,
      height: 0
    })
  });
```

**Comment by mixonic** [comment]
@olivierlesnicki this is intentional. Template compilation on the client will not result in good performance, and has never been suggested for production mode apps. When you use Ember in a jsbin (for example), the template compiler is included for dev/debug reasons only.

* If you are writing tests, I strongly suggest this excellent addon: [ember-cli-htmlbars-inline-precompile](https://github.com/pangratz/ember-cli-htmlbars-inline-precompile) it will be part of the official testing story as soon as we document that story :-p
* Otherwise, you can find the templates compiler [for download on the builds pages](http://emberjs.com/builds/#/release) or included in the bower package. In ember-cli you could import the template compiler into dev/prod/test if needed, but again I do not suggest that.

**Comment by olivierlesnicki** [comment]
@mixonic quite happy with https://github.com/pangratz/ember-cli-htmlbars-inline-precompile
hopefully this story gets documented soon :)
