### ISSUE TITLE
Tagged builds for v2.x are not displayed on http://emberjs.com/builds/#/tagged.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#11725]
Most likely something wrong with https://github.com/emberjs/website/blob/master/source/javascripts/app/builds/app.js#L55, but I haven't had time to review in detail...

---

Would love help on this (I don't have time to track it down ATM).

**Comment by pdud** [comment]
It looks like v2 entries are not being returned in the response from S3.

http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html

According to the above, this is because there are a max of 1000 alphabetical results.

To get additional keys, we can make an additional request with a `marker` param set to the last entry on the first page. Then v2.0.0-beta tags appear.

`<IsTruncated>true</IsTruncated>` is present when there are additional pages.

Page 1: https://s3.amazonaws.com/builds.emberjs.com?&marker=&max-keys=&prefix=tags/
Page 2: https://s3.amazonaws.com/builds.emberjs.com?&marker=tags/v1.7.1/ember-docs.json&max-keys=&prefix=tags/

If this approach sounds good, I'd be happy to add a PR.

**Comment by rwjblue** [comment]
:+1: -- Sounds like a good plan, thanks for researching so quickly!
