### ISSUE TITLE
ArrayProxy Plays Poorly with an Array Having Undefined Elements

### ISSUE THREAD

**Issue by jherdman** [emberjs/ember.js#11734]
I'm trying to insert an element into an ArrayProxy whose content has been pre-set like this:

```javascript
let myAP = Ember.ArrayProxy.new({ content: new Array(7) });
```

When I attempt to insert an element at a target index, I'm finding the length of the array is increasing, instead of swapping the `undefined` value for the target value. Example:

```javascript
myAP.get('length') => 7
myAP.insertAt(4, 'foo');
myAP.get('length') => 8
myAP.get('content') => [undefined x 4, 'foo', undefined x 3]
```

I'd expect the following:

```javascript
myAP.get('length') => 7
myAP.insertAt(4, 'foo');
myAP.get('length') => 7
myAP.get('content') => [undefined x 3, 'foo', undefined x 3]
```

Here's a JSBin for that illustrates http://emberjs.jsbin.com/banijehoji/edit?html,js,output

**Comment by herom** [comment]
While debugging your jsbin example I'm pretty sure that this is caused by the implementation of `Ember.ArrayProxy._insertAt()` which is passing `0` as the `amt` (referred as "The number of items to remove from the conten" in the `Ember.ArrayProxy.replaceContent()` method) property down the line of methods called until `Array.prototype.slice` is finally reached, which takes it as `deleteCount` param (see https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/splice for further information).

As `deleteCount` is set to `0` none of the existing items are acutally really replaced. I guess a quick fix would be to override `Ember.ArrayProxy._insertAt` to gather the length of inserted objects.

**Comment by stefanpenner** [comment]
I am unsure if we aim to support sparse arrays here, historically our array polyfils have taken the same path as lodash, and ignored the concept of sparse arrays.

**Comment by pixelhandler** [comment]
@jherdman do you think it would be work creating an RFC for the desired behavior you're looking for. Or alternatively get a discussion around the best practices for managing sparse arrays in Ember.

**Comment by jherdman** [comment]
I'm quite interested, but my time is at a premium as of late. Realistically this problem isn't that bad, and it's relatively easy to work around. I'm comfortable closing this ticket unless someone in here feels that it's a valuable placeholder for conversation or work to be done.

**Comment by stefanpenner** [comment]
As many libs. Like lodash treat sparse arrays as exceptional. I suspect it is alright for us to as well.

But yes if this is truly a blocker we can reconsider
