### ISSUE TITLE
Add to check a subscription on action

### ISSUE THREAD

**Issue by AndreyUtka** [emberjs/ember.js#11781]
It would be great to have method that could check - has controller subscription for action or no.
For now, when I try to trigger parent action I can check it by ``` _.has(controller._actions, actionName) ``` if expression  ``` true ```  I trigger action with dependency data or no if I receive ``` false ```.

For example my propose is create new method something like this:

``` this.hasAction('actionName') ```

**Comment by pixelhandler** [comment]
@AndreyUtka to make a feature request the best way is to create an RFC. Would you consider closing this out as an issue and creating an RFC instead?

Also, I've heard this type of request once before it may be nice to get a thread going in the http://discuss.emberjs.com forums or ask around in the embercommunity.slack.com group to see other patterns people use aside from checking if a subscription already exists prior to sending the action.

I think the design around throwing an error was intentional. sounds like more discussion is needed in order to make a case for the 'check subscription of action' feature request.
