### ISSUE TITLE
Input readonly attributes added even when readonly=false

### ISSUE THREAD

**Issue by alltouch** [emberjs/ember.js#11828]
After migration to ember 1.13.4 i found inputs broken on my site. All of them have readonly=false attribute which renders as <input readonly=false> markup.

Here is jsbin for it
http://emberjs.jsbin.com/hazuluvela/edit?html,js,console,output

Could you please fix it?

**Comment by mixonic** [comment]
Regression check says this was introduced in 1.13.3

**Comment by pixelhandler** [comment]
@alltouch just curious is it possible to not use the readonly attribute when the value for the readonly attribute is false?

I'm wondering if you've already found a workaround you can add to the context of this issue.

**Comment by pixelhandler** [comment]
@mixonic @alltouch Are you sure this is a bug? Or, could it be an improper use of the readonly attribute.

**Comment by krisselden** [comment]
@pixelhandler you are correct, it is just the presence of the attribute that makes it readonly in the DOM, it ignores the actually attribute value, though the behavior in this release I think was to check if the property existing on the element, as set it instead, that would make it work, except that the property is 'readOnly' not 'readonly' so the property set doesn't work.

**Comment by stefanpenner** [comment]
@krisselden it seems like we may want to special case readonly like we did maxLength.

**Comment by stefanpenner** [comment]
@mmun suggested we built a map of all the boolean attributes and consult that. Should be doable, and something that will have to be done in HTMLBars

**Comment by mixonic** [comment]
The old check code did not require a map, it built it up by comparing only the lowercase of key names.

**Comment by alltouch** [comment]
@pixelhandler 
Its not a problem for me to build workaround. My point that this is core feature to set readonly attribute programatically and i want to know what is the proper way for it?

**Comment by perlun** [comment]
@stefanpenner - special-casing it seems like a good idea. This is btw broken in 2.0 also (which is where I just noticed it). It is especially awkward if you are making your own components that wrap `{{input}}`; you can't really expose the `readonly` attribute in your component since its mere presence will make the input always be disabled...

**Comment by lazloman** [comment]
Is there a workaround for this issue? I can't use the disabled property as the text needs to be selectable and copyable. Although Chrome allows you to select/copy text from a disabled input field, Firefox does not.

**Comment by selvaa89** [comment]
@lazloman It works if you pass undefined instead of false to readonly.

**Comment by kamilogorek** [comment]
Thanks @selvaa89, it indeed helps to get it working again.

**Comment by kayakyakr** [comment]
We should probably break down which versions of ember this works on and which it does not. Needs to be undefined and not just false on 1.11.3 for me. Sounds like 1.13.3 and 1.13.4 and possibly 2+ also have the issue.

**Comment by manufitoussi** [comment]
I confirm that 2.1.1 has the same issue.

**Comment by Eusebius1920** [comment]
Same in 2.2

**Comment by sweatypitts** [comment]
I would be happy to try to fix this if someone can confirm this is a bug that we want to be fixed and how (i.e. building a map of all the boolean attributes to consult). This behavior persists in 2.4.0-beta.3.

**Comment by pixelhandler** [comment]
@robbiepitts I hate to say it but I really do avoid the `{{input}}` helper, there are more than one work arounds, e.g .using `<input>` and binding the `readonly` attribute. 

@alltouch I'll close this issue for now as it's stale. If you feel it's necessary to reopen feel free to do so.

**Comment by mwagz** [comment]
I don't wanna re-open, but I wanna add to this, since I ran into a similar "issue" and did a lot of digging around this and wanna help anyone else with the issue.

### My Problem
I had some input fields that I needed to be readonly if bound to a specific variable. I was basing this on an `isReadOnly` property that was watching my variable and then did an attribute binding to `isReadOnly` like so:
```javascript
// ...
attributeBindings: ['isReadOnly:readonly']
// ...
```

This was making it so that the readonly attribute was being added regardless of the boolean value being set to false and, as this thread discusses, was setting the `readonly` property to the HTML document as false, which HTML then decided to make the field `readonly`.

### The Solution to My Problem
I started digging around and found [this comment in the docs](https://github.com/emberjs/ember.js/blob/7dd709422e1961dffe65a967fc48b0e5940a0200/packages/ember-glimmer/lib/component.js#L411) which says that if you don't want the attribute to render at all, set `null` or `undefined` as the return value of the monitored property. Doing so removed the readonly property when I didn't want it!

This works for me in Ember 1.13, as well, but looks like it was added in the 2.11 docs.
