### ISSUE TITLE
Route named "select" renders <select> in outlet (1.13.5)

### ISSUE THREAD

**Issue by peec** [emberjs/ember.js#11893]
If you create a route named "select" a `<select>`dom node is rendered in the `{{outlet}}` instead of the template named "select.hbs" in the app folder.

Ember version: 1.13.5
Ember cli: 1.13.1

router.js:

```javascript
Router.map(function() {
    this.route('select');
});
```

select.hbs inside the templates folder:

```handlebars
This will never show, instead a <select> will be rendered.
```

**Comment by peec** [comment]
Markdown was not supported above, again:

If you create a route named "select" a <select> is rendered in the outlet instead of the template named "select.hbs" in the app folder.


Ember version: 1.13.5
Ember cli: 1.13.1


router.js:

```javascript
Router.map(function() {
    this.route('select');
});
```

select.hbs inside the templates folder:

```handlebars
This will never show, instead a <select> will be rendered.
```

**Comment by stefanpenner** [comment]
this is shorta expected but extremely `WAT`.

workaround: 
```
Route.extend({
  viewName:  'something-not-select'
})
```

**Comment by rwjblue** [comment]
Seems pretty weird to me. We definitely need to fix it. 

My guess at what is happening is that we are using Ember.Select because it is registered as 'view:-select'. We have a known issue with the globals resolver that causes the leading dash to be completely ignored/dropped, so when we look for 'view:select' (which is what is happening here) you get Ember.SelectView. 

We need to address this two ways:

* Fix the globals resolver to honor the leading dash. 
* Add a helpful warning for 1.13 that tells you that using a route named 'select' (and defining a App.SelectView) will prevent you from using {{view 'select'}}.

**Comment by peec** [comment]
Initially i thought this had to do with some bug within "routable components". That is why I reported it, I have no problem with switch the route to something else thus it might be a deep problem within glimmer or somthing else.

**Comment by EricSchank** [comment]
@rwjblue can you please take a look at PR #11902 ?
It should tackle the second of your steps to address this by adding the warning.

**Comment by rwjblue** [comment]
FYI - #11902 was merged, adding a helpful warning when you use a route named `select`.

**Comment by jayphelps** [comment]
Sort of obvious to me, but just in case: One could also work around this by just naming the route something different, but keep the path, if that's needed.

```js
this.route('select-something', { path: '/select' });
```

**Comment by rwjblue** [comment]
@jayphelps - Confirm, that is why the warning is the most helpful.  At least now folks will know they may have an issue...
