### ISSUE TITLE
mouseDown blocks focusOut event

### ISSUE THREAD

**Issue by miguelcobain** [emberjs/ember.js#11904]
It looks like when mouseDown is triggered in an element, focusOut isn't triggered in the previously focused element. The element doesn't even lose its focus.
I've setup a twiddle with Ember and a corresponding fiddle with equivalent functionality with jQuery. It's working in jquery but not in Ember.
I'm assuming that mouseDown "blocks" focusOut because it is actually triggered before.

Twidde: http://ember-twiddle.com/956977846bddd6f9814b

Vanilla jQuery equivalent: http://jsfiddle.net/e3L83pL4/2/

**Comment by pixelhandler** [comment]
@miguelcobain this seems to be an issue that is strange the input doesn't loose focus when the button is clicked.

**Comment by rlivsey** [comment]
This is because by default [actions call `preventDefault` on the event](https://github.com/emberjs/ember.js/blob/7a8a46be489871820ca100f536dd03b174788ddb/packages/ember-routing-htmlbars/lib/keywords/element-action.js#L99) which is triggered as a result of invoking the action. You can disable this by setting `preventDefault=false` in the action.

The docs for this are in the templates section now that Views are gone: http://guides.emberjs.com/v1.13.0/templates/actions/#toc_default-event

I can't remember the history around why this is opt out vs opt in, maybe to behave the same as `link-to`? Possibly this is something which should be discussed to be changed in the run-up to v2.0 to make it less surprising, obviously changing that default would be a breaking change in the 1.x series.

**Comment by tsteuwer** [comment]
@rlivsey  is correct. If you change your "some-component.hbs" to:

```
{{input focus-out="focusOut"}}
<button {{action "mouseDown" on="mouseDown" preventDefault=false}}>Click here</button>
```
It fires both. This is documented, however, I feel like an example like this should be included in the Docs so people aren't confused when working with multiple events such as this.

**Comment by pixelhandler** [comment]
@tsteuwer @rlivsey awesome didn't know about the passing `preventDefault=false` I take back my comments about 'breaking the web' but it does seem easy to do with actions + events.

@miguelcobain I updated your twiddle with the solution using `preventDefault=false` see http://ember-twiddle.com/71747389e27e3b72332d

**Comment by miguelcobain** [comment]
Yes, that solved my problem. Thanks everyone.
