### ISSUE TITLE
Component not re-rendering properly in 1.13

### ISSUE THREAD

**Issue by mpedrera** [emberjs/ember.js#11915]
Resizing the output viewport under/over the `1024px` limit in 1.12 updates the template accordingly.

Doing so in the 1.13 version does not update the template, but the `console.log` displays the updated value.

1.13 version:
http://emberjs.jsbin.com/yahujesewo/edit?js,console,output

1.12 version:
http://emberjs.jsbin.com/hipuvujeme/1/edit?js,console,output

**Comment by rwjblue** [comment]
The template is rerendered, but rerendering does not cause the CP to be consumed (because its stream is not dirty).  You can fix it by calling `this.notifyPropertyChange('isTouch')` to force invalidation (you can then remove `.volatile()` because you are notifying to invalidate cache).

Demo: http://rwjblue.jsbin.com/nomiwu/edit?html,js

---

Arguably, a volatile CP should always be considered dirty (which I think would have made your original example work), but setting volatile like this will ultimately cause more work upon each rerender than is needed.

**Comment by mpedrera** [comment]
Thanks @rwjblue, it actually works when using `notifyPropertyChange`. According to the docs it's private API, but it's something.

**Comment by rwjblue** [comment]
Thanks for pointing that out!  It shouldn't be `@private`. Updated in https://github.com/emberjs/ember.js/pull/11919.
