### ISSUE TITLE
Make link-to a pure component

### ISSUE THREAD

**Issue by mmun** [emberjs/ember.js#11962]
- [x] Use the new arbitrary-length positional params feature.
- [x] Expose `hasBlock` on components, privately.
- [x] Use a nested helper to avoid exposing `escaped`.

**Comment by rwjblue** [comment]
:+1:

**Comment by codefox421** [comment]
Hi @mmun. Can you explain what you mean when you say things should be exposed "privately"?

I'm currently trying to build a reusable component, which should only be used in the block form. I run an assertion on init that currently checks `this.get('template')`. I wanted to make the check against `this.get('hasBlock')` since [`template` is deprecated according to the API docs](http://emberjs.com/api/classes/Ember.Component.html#property_template), but `hasBlock` always comes back undefined. Will exposing `hasBlock` "privately" solve this, or would it need to be exposed more than privately?

**Comment by jayphelps** [comment]
@codefox421 `hasBlock`/`hasBlockParams` has been turned into an HTMLBars keyword, instead of a property on the component itself. https://github.com/emberjs/ember.js/pull/11158, https://github.com/emberjs/ember.js/pull/11968

**Comment by mmun** [comment]
We'll probably make it public, but that requires a feature flag and is orthogonal to this issue.

**Comment by mmun** [comment]
`{{{link-to '<b>location</b>' 'location'}}}` is pretty dubious. Specifically, why should the "escaped-ness" apply to the first argument?

We should add an `html-safe` subexpression and write an AST transform that rewrites the above to `{{link-to (html-safe '<b>location</b>') 'location'}}`. This would remove one of the "impurities".

**Comment by rwjblue** [comment]
There is a `-html-safe` subexpression, it is only not public because we needed it internally and didn't have time for RFC and documentation process.

With some docs and a transform (for support for `-html-safe` also) we could likely take care of that...

**Comment by mmun** [comment]
@rwjblue oh sweet :)

**Comment by mmun** [comment]
It should be "html-unsafe", so that `{{html-unsafe userInput}}` feels bad.

**Comment by nathanhammond** [comment]
Questions:
- If we want a pure component, would we want it to live at `component:link-to` or `component:-link-to`?
- Where should we assign `hasBlock`? `ComponentNodeManager` knows everything, but I'm unsure about setting properties in `create` there.

Notes:
- `hasBlock` is required in JS code because you need to identify if you should `shift` all of the passed `params` (first argument is the block content if there is no specified block).

Here's a spike: https://github.com/nathanhammond/ember.js/commit/f7069ed7a36849014f30778cba545f5e2f011e15

**Comment by rwjblue** [comment]
Implemented in https://github.com/emberjs/ember.js/pull/12176.
