### ISSUE TITLE
Ember.Array methods return Array rather than Ember.Array

### ISSUE THREAD

**Issue by indirect** [emberjs/ember.js#12003]
Ember.Array methods that return an array, like `filterBy`, return a bare JS Array rather than an Ember.Array. This makes chaining Ember.Array methods impossible with prototype extensions disabled. Here's an example:

```javascript
// prototype extensions on
Ember.A(someArray).filterBy(‘property’).mapBy('otherProperty') // => [1, 2, 3]

// prototype extensions off
Ember.A(someArray).filterBy('property').mapBy('otherProperty') // => undefined is not a function

Ember.A(Ember.A(someArray).filterBy('property')).mapBy('otherProperty') // => [1, 2, 3]
```

I can't find any discussion of this in the documentation, so I'm opening an issue. It seems like it would make sense for Ember.Array methods that return an array to return an Ember.Array, so that chaining Ember.Array methods becomes possible.

**Comment by stefanpenner** [comment]
Until we can subclass natives, there isn't a reasonable & performant way to do this.

There are two potential ideas:

* use lodash – https://github.com/ember-cli/ember-cli/issues/4211 will unlocks efficient tree-shaking builds of lodash
* transition embers helpers to follow a similar pattern, i suspect the former is more appealing.

**Comment by indirect** [comment]
Okay. So I should be using `Ember.Enumerable.filterBy(array, function(){})` when I want to use `filterBy` with prototype extensions turned off? If that's true, I can see how lodash seems like the better option. :)

Is there a way to get the property-based ease of `filterBy('propName', 'wantedValue')` via lodash? Or am I just out of luck?

**Comment by stefanpenner** [comment]
> Is there a way to get the property-based ease of filterBy('propName', 'wantedValue') via lodash? Or am I just out of luck?

Unsure, i do know some of the mappers support deep properties in lodash.

If there is a missing feature, i think this might make good addon territory for now.

**Comment by sukima** [comment]
`Ember.Enumerable.filterBy` does not exists. `Ember.Enumerable.mixins[0].properties.filterBy` does however. How did this work 20 days ago?

**Comment by sukima** [comment]
@stefanpenner, You said:

> use lodash – ember-cli/ember-cli#4211 will unlock efficient tree-shaking builds of lodash

Does this mean Ember will have a version of lodash included?

I think that perhaps there is a context confusion here. I ran in to the problem of chaining and using `Ember.A()` _everywhere_ because I am maintaining an ember-cli addon which by design has prototype extensions turned off. This means that if an addon does any significant amount of data manipulation then they have to do one of:

1. Perform a large bit of heavy lifting to deep dive into the Enumerable mixin.
2. Or force the inclusion of a third party library like lodash.

The first one seems like a disservice to ember addon authors and the second seems like an insidious expectation on the consumers of such an addon. Advice?

Also here is how I managed to handle array manipulation in my ember addon. The down side is I could not find a way to accomplish this with out `Ember.A()` which as you described is redundent and probubly slated to go away! :cold_sweat: 

```javascript
// Ember Addons need to be coded as if Ember.EXTEND_PROTOTYPES = false
// Because of this we need to make our own proxy functions to apply as one offs
// to native arrays.
const emberArrayFunc = function(method) {
  return function(ctx, ...args) {
    const props = Ember.Enumerable.mixins[0].properties;
    Ember.assert(
      `Ember.Enumerable has no method ${method}`,
      Ember.typeOf(props[method]) === 'function'
    );
    const result = props[method].apply(Ember.A(ctx), args);
    if (Ember.typeOf(result) === 'array') {
      return Ember.A(result);
    } else {
      return result;
    }
  };
};
const _contains = emberArrayFunc('contains');
const _mapBy    = emberArrayFunc('mapBy');
const _filterBy = emberArrayFunc('filterBy');
const _findBy   = emberArrayFunc('findBy');
const _uniq     = emberArrayFunc('uniq');
const _compact  = emberArrayFunc('compact');
```

**Comment by stefanpenner** [comment]
> Does this mean Ember will have a version of lodash included?

no, it means using lodash will be pas as you go as that PR explains.

**Comment by stefanpenner** [comment]
the final solution is two fold. Remove internal dependencies on `Ember.A` https://github.com/emberjs/ember.js/pull/10899

And second, allow people to use something like lodash without each addon having to include it  ember-cli/ember-cli#4211
