### ISSUE TITLE
nearestOfType marked private?

### ISSUE THREAD

**Issue by raycohen** [emberjs/ember.js#12110]
In https://github.com/emberjs/ember.js/commit/6e1ad90712db713fd9b32fab38020dddf65e6114 `nearestOfType` was marked as `private`.

On a quick search I could not find anything internal to ember accessing `nearestOfType` beyond the tests explicitly testing it.

`nearestOfType` seems to go against the desire for components to be encapsulated.  However I have run across a few addons that use it.

It seems like it should either be marked as public or become deprecated.  What is the future for this method?

**Comment by rwjblue** [comment]
I would much prefer the contextual component/helpers RFC's concepts to allow nested components to have access to their relative parents vs traversing up the tree to find the nearest of a given type.

For example, I would prefer something like the following:

```
{{#form-for model as |f|}}
  {{f.input 'firstName'}}
{{/form-for}}
```

Where because it was invoked off of `f`, the `input` can be aware which instance of `form-for` it belongs to.

---

Anyways, that isn't really the point of this issue (or maybe it does show the potential future if we can make it all happen).  I am OK with it being marked `@public`, but my goal is to ultimately make it useless (sometime during the 2.x cycle) so we can then deprecate it.

**Comment by rwjblue** [comment]
The above is referring somewhat to the ideas of https://github.com/emberjs/ember.js/pull/10244 and https://github.com/emberjs/rfcs/pull/64.

**Comment by mmun** [comment]
`nearestOfType` is still useful for some things (it's discussed in that rfc)

**Comment by steffenbrem** [comment]
@mmun Indeed, I use it too and it is very helpful. For composable components it is very neat to have it traverse to the parent component by type instead of manualy recursing on `parentView`. It is very little code, that is quite usefull to me.

**Comment by mmun** [comment]
@steffenbrem I think you'll find that what @rwjblue suggested is _even better_ in almost all cases.

**Comment by raycohen** [comment]
while it isn't as nice as the contextual components rfc, I've been associating parent and child components by emitting `this` from the parent and passing it down, for example:
```
{{#radio-group selected=currentColor name="color" disabled=isDisabled as |group|}}
  {{#radio-button group=group value="red"}} Red {{/radio-button}}
  {{#radio-button group=group value="blue"}} Blue {{/radio-button}}
{{/radio-group}}
```

**Comment by rwjblue** [comment]
@raycohen - Yep, that is a great solution (if a little more verbose) until this lands. 

Still: :+1: on marking as public. Would merge. :)

**Comment by rwjblue** [comment]
Closed by https://github.com/emberjs/ember.js/pull/12111.
