### ISSUE TITLE
[Glimmer Component] Quoted/Unquoted Attributes

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#12133]
It appears that with glimmer components there is an issue with quoted vs unquoted attributes on the top-level elements.

http://emberjs.jsbin.com/qaloyad/

**Comment by pixelhandler** [comment]
@chadhietala I'm not sure what is the proper use of unquoted use of curly braces on an attribute of a component, but it seems to me that the curly braces should be inside quotes. I found it odd to see `src={{src}}`, I would have expected `src=src` instead of unquoted curlies; however this does look proper `src="{{src}}"`.

I recall the blog post announcing the glimmer release had an example of an attribute that used curlies inside of quotes.

>```
Supports angle-bracket components (<my-component />), ergonomic attributes (<my-link href="{{url}}.html">go home</my-link>), that hews closely to HTML syntax with a few small enhancements.
```

**Comment by rwjblue** [comment]
The thinking on this has changed a bit, and the initial angle bracket component implementation has been removed.  When this is reintroduced, there will be an updated RFC with more details on the path forward for this type of thing.

Closing for now, since the feature doesn't exist in the codebase...
