### ISSUE TITLE
tagName on application template

### ISSUE THREAD

**Issue by eibrahim** [emberjs/ember.js#12183]
The application template adds a div... so my page ends up looking like

```
<body>
  <div id="ember441" class="ember-view"> </div>
</body>
```
I want to set the tagName for the application template to nothing because I don't want my content wrapped in a div - it messes up my css. Previously I have done this by creating an views/application.js and setting tagName: '' but views are deprecated - how can I do this without views?

**Comment by quaertym** [comment]
See https://github.com/emberjs/ember.js/issues/11909

This is how you do it. (It is ugly I know.)
```
// app/views/application.js or app/application/view.js
import Ember from 'ember';

export default Ember.Component.extend({
  tagName: ''
});
```

**Comment by eibrahim** [comment]
I know how to do it :).  My question is how do I do it without using views because views are deprecated?

**Comment by quaertym** [comment]
The code above does not use `View`. It extends from Ember.Component. :)

**Comment by rwjblue** [comment]
@quaertym's suggestion (which I have also mentioned in other issues/comments/etc) works just fine, but we generally do not want to encourage folks to have components in `app/views` (it *feels* weird and might be a future refactoring hazard).

I would use the `ember-legacy-views` addon if you need a root level view like this.  That is exactly what it is for...

**Comment by eibrahim** [comment]
@quaertym sorry about that.  Didn't see the `Component` part of your code...  Interesting solution but I agree it's ugly :)  I will take a look at the legacy views add-on...

@rwjblue what is the future for this "feature" without using components in /views or the legacy addon?  Will routable components address this?

**Comment by rwjblue** [comment]
Yes, when routable components land, you will have an actual component and can customize your tag / attributes / classes / etc.

**Comment by gentlefox** [comment]
2 years on and all that has changed is the legacy addon is no longer a solution. Adding an ID to the Application Object just results in 2 wrapping elements instead of one, such as this mess, where the child elements have become grandchild elements breaking styling hierarchy and the element needing to be targeted is generic in the extreme for any Ember App:
```
<div id="core-app" class="ember-application">
  <div id="ember323" class="ember-view">
    <header id="ember353" class="nav-header ember-view">...</header>
    <div class="primary-content">...</div>
    <footer id="ember365" class="nav-footer ember-view">...</footer>
  </div>
</div>
```
This wrap is a redundant just-in-case solution for legacy sites, yet has lead to an in-every-case layout and styling black hole for every Ember site since. This element is the foundation stone for the site, and when a hack or workaround is required to achieve the semantic styling desired it leaves me feeling like I've used Microsoft Frontpage to build the heart of my app. The styling methods I see others employ to achieve a letterbox or "holy grail" layout are reminiscent of a decade ago as even well-established styling options such as flexbox cannot be employed. Targeting via pseudo-element CSS or selector index leaves the site at the mercy of any addon or dynamic element injection (such as ember-wormhole) potentially hijacking the site's styling.

Is there any reason that the *ember-application* class cannot also fulfil the needs for this wrap - perhaps by including the "ember-view" class?
