### ISSUE TITLE
Missing controller keyword deprecation in 1.13

### ISSUE THREAD

**Issue by ef4** [emberjs/ember.js#12189]
A template using the `controller` keyword functions correctly without deprecation warning in 1.13.8:

````hbs
{{some-component currentController=controller}}
````
It causes an assertion at compile time on canary:

```
Using `{{controller}}` or any path based on it has been removed in Ember 2.0
```

**Comment by rwjblue** [comment]
Hmmm. Both view and controller based paths should have triggered a deprecation in 1.13.

**Comment by mixonic** [comment]
@rwjblue we may not have looked for `controller` or `view` usage as the value of a hash argument to a mustache.

**Comment by rwjblue** [comment]
Given:

```handlebars
{{some-thing foo=controller}}
```

Deprecation is properly printed in 1.13.8: http://rwjblue.jsbin.com/dihutu/edit?html,js,output

**Comment by rwjblue** [comment]
The deprecation is done here: https://github.com/emberjs/ember.js/blob/release-1-13/packages/ember-template-compiler/lib/plugins/deprecate-view-and-controller-paths.js#L55-L66

**Comment by rwjblue** [comment]
I am unsure if related, but the [ember-cli-template-lint](https://github.com/rwjblue/ember-cli-template-lint/blob/584f63a39c70232c70b14cc7735fb1d8adaeb4f9/index.js#L25-L31) does not propertly handle `function`'s as `test` (it considers them all as `true` because a function is truthy).  I am working on a fix for that though.

**Comment by ef4** [comment]
Ooh, I am using ember-cli-template-lint, so that is the problem.
