### ISSUE TITLE
can't opt out of properties shadowed by attributes

### ISSUE THREAD

**Issue by shaunc** [emberjs/ember.js#12196]
I undertstand the intention is to move parameters into a separate namespace from internal component state, and that currently this separation is triggered by invoking component with angle brackets.

However, the separation of attrs and properties has much to do with component design; whether shadowing happens shouldn't depend on how a component user invokes the component.

Currently we are trying to take advantage of the split between attrs and properties, but it is proving hard. Can we have a way (like a property or even a mixin) to signal we want attrs separate from properties?

We have code that looks like

    didReceiveAttrs() {
      this._super();
      var columns = this.getAttr('columns');

      ... (check columns, translating if necessary into internal format) ...

      this.set('columns', columns);
     
Unfortunately, after "didReceiveAttrs" is run, the property "columns" is set with the original unprocessed value. I've tried `this.attrs.colums = columns` inside of `didReceiveAttrs` ... and several other attempted hacks... but I can't seem to shake shadowing.

**Comment by rwjblue** [comment]
The current semantics for components and how to access passed attribute values have not changed.  We are internally representing passed attributes in `this.attrs`, but we will continue to mirror those attributes to the component's root (likely for all of the current `Ember.Component`'s lifespan).

In theory, it is possible to prevent this mirroring, but I would strongly suggest that you should not do this.  It would require overriding private internal behavior, and be very brittle to changes throughout versions.

**Comment by shaunc** [comment]
In the 2.0 transition blog, we have:

> As described above, conflating the attributes (values provided by the component's caller) with the  component's own state can cause confusion, especially when combined with mutable attributes.
> Beginning with angle-bracket components in Ember 1.13, a component's attributes will be available in this.attrs rather than on the component itself.

So by that, at least, it seems like you are encouraging developers to transition to separate namespaces, at least when they are writing "angle-bracket components" which are already available.

The question is, how does an addon developer write an "angle-bracket component" when addon user is free to invoke however they want? IMHO you need a flag for a component to say "I'm an angle-bracket component (however I'm invoked)".

**Comment by rwjblue** [comment]
The quoted blog post was written at a time where angle bracket components were enabled by default (1.13.0-beta.1), that feature was subsequently disabled because of numerous issues.

> how does an addon developer write an "angle-bracket component" when addon user is free to invoke however they want?

There will be an assertion if an angle bracket component (these will have to extend from `Ember.GlimmerComponent`) is invoked with curly brackets.

> IMHO you need a flag for a component to say "I'm an angle-bracket component (however I'm invoked)"

Yep, you will `export default Ember.GlimmerComponent.extend()`.

There will likely also be a way to opt-into allowing a `Ember.GlimmerComponent` to be invoked via curly brackets with a deprecation (to allow authors to provide a way forward for existing components).

**Comment by shaunc** [comment]
Awesome! I should have expected you'd have resolved this (in private...).

[ember-grid](https://github.com/shaunc/ember-grid) was targeting 2.0. I see GlimmerComponent pops into view once I enable:

        'ember-htmlbars-attribute-syntax': true,
        'ember-htmlbars-inline-if-helper': true,
        'ember-htmlbars-component-generation': true

Is this slated for release in 2.1?

**Comment by rwjblue** [comment]
No, it will not be in 2.1.0.  There are still a number of issues to be ironed out (see https://github.com/emberjs/ember.js/issues/12129 for a list).

**Comment by shaunc** [comment]
Thanks!

**Comment by locks** [comment]
I am closing this issue as the discussion seems to have reached some sort of resolution. There's also the matter that angle bracket components are under heavy consideration, so the original concern might not be valid anymore.
I'm labelling the issue as `wontfix` merely because classic components maintain the mirroring semantics and it's not feasible to change that behaviour currently.

Feel free to re-open the issue if you think it's still justified, thank you.
