### ISSUE TITLE
Ember.computed.map issues

### ISSUE THREAD

**Issue by jskeate** [emberjs/ember.js#12210]
See this JSBin:

http://emberjs.jsbin.com/pulabawezu/1/edit?html,js,output

Clicking "change color" causes the `Ember.computed.map` version to add duplicate values. If you observe `mappedModel` and `console.log` its value on change, it actually changes four times.

**Comment by stefanpenner** [comment]
@jskeate most of these issues have been resolved in 2.0. As the whole internals of these array computed macros are not totally lazy and simplified.

The world is unlikely to be back-ported, as the change was quite involved [https://github.com/emberjs/ember.js/pull/11513] many apps depend on todays spurious change events.

In theory someone could extract these 2.0 macros and provide them as an addon to older systems. It is unlikely we will have time ourselves to support and provide this due to time constraints.

**Comment by jskeate** [comment]
Ah, ok. Just wasn't sure if this was a known issue or not; I did a quick scan and didn't find anything.

**Comment by rwjblue** [comment]
Demo with 2.0.1 (does not duplicate items): http://emberjs.jsbin.com/goxobi/edit?html,js,output
