### ISSUE TITLE
Alias property returns initial value of source property even after the source property is updated

### ISSUE THREAD

**Issue by ilkkao** [emberjs/ember.js#12234]
This is not a good bug report, but because I unsuccessfully spent many hours to prepare a jsbin I decided to open an issue.

In my private app I have a computed alias that always returns ~~undefined regardless what the value of source property is~~ the initial source property value instead of the current value. The jsbin that I unsuccessfully tried to create to demonstrate the problem:

http://emberjs.jsbin.com/ketuji/edit?html,js,output

In my app, `{{activeDesktop}}` is always null. In the jsbin it works. Could it be a timing issue? I have already a workaround (mentioned in the jsbin) but would really like to avoid committing it.

I bisected my problem to PR #12177, @ef4 any ideas?

**Comment by ilkkao** [comment]
In my app I noticed that the problem is only happening in the template. In the component JS code alias has the correct value.

I still haven't been able to create a jsbin or minimal app to demonstrate it.  I probably close this issue soon if I don't make progress.

**Comment by rwjblue** [comment]
There is at least one other issue related to the changes in #12177 (the length property on an ArrayProxy does not update properly) so it is quite possible that this issue is related. 

It would be extremely helpful to have a reproduction (to help us ensure that we are on the right track), but I definitely understand that repros are sometimes the most difficult part of fixing a bug. 

Thanks for working on it, please keep us updated.

**Comment by rwjblue** [comment]
I am in favor of reverting #12177 until we can put time into fixing this issue and the one described by https://github.com/emberjs/ember.js/pull/12218.
