### ISSUE TITLE
Proxied promise fail handler in PromiseProxyMixin doesn't execute and exception thrown in fail handler isn't caught by application

### ISSUE THREAD

**Issue by acalfo** [emberjs/ember.js#12254]
Relates to issue https://github.com/emberjs/ember.js/issues/9888
"The proxied fail handler isn't called, and the exception that's rethrown in PromiseProxyMixin isn't caught by the application. This is causing our error handling acceptance tests to fail."

PromiseArray is experiencing the same issue as the linked related issue, where rethrown exceptions in the PromiseProxyMixin are not catchable at the application level. Thrown error reads 'Uncaught [Return Type]". 

JSFiddle example: http://jsfiddle.net/pk54m2sx/7/

**Comment by pixelhandler** [comment]
@acalfo I only see one `promise` in your jsfiddle example. You assigned the same promise to two results but `Ember.$.getJSON("/endpoint")` returns only one promise that is referenced by both `result` arrays `DS.PromiseArray` Since the code only creates one promise it seems correct that the function for failure is only executed once.

**Comment by acalfo** [comment]
Thanks for the response! I now realize I did a terrible job of showing the problem I'm having. I've updated the fiddle http://jsfiddle.net/pk54m2sx/10/ to do a better job of that - but the trouble I'm having is that even though I'm handling the error from the promise, I keep getting an error in the console Uncaught undefined. If you open up the console and run the fiddle you'll see what I'm talking about.
