### ISSUE TITLE
Component documentation misses lifecycle-hooks

### ISSUE THREAD

**Issue by fpauser** [emberjs/ember.js#12326]
Ember.Component currently documents the following events (see http://emberjs.com/api/classes/Ember.Component.html):
- didInsertElement
- willClearRender
- willDestroyElement
- willInsertElement

As stated in http://emberjs.com/blog/2015/05/24/another-two-oh-status-update.html#toc_new-lifecycle-hooks these events are currently undocumented:
- didUpdateAttrs
- willUpdate
- didUpdate
- didReceiveAttrs
- didRender

**Comment by rwjblue** [comment]
Documentation is underway for these hooks, as part of the angle bracket component feature.

I believe @chancancode is working on it (though I could be mistaken).

**Comment by chancancode** [comment]
Yes! I will try to submit a pull request for feedback soon. But as I understand, the reason that these hooks and 'attrs' property are not in the docs is intentional as of 2.1 because they are not considered public/finalized yet. (Primarily because they are not very usable without GlimmerComponent/angle bracket components.)

But anyhow, the docs I am writing should be done in time for 2.2, so as glimmer component, and I don't think we expect any major changes to them so it should be resolved soon!

**Comment by tulios** [comment]
:+1:

**Comment by stavarotti** [comment]
>
But as I understand, the reason that these hooks and 'attrs' property are not in the docs is intentional as of 2.1 because they are not considered public/finalized yet. (Primarily because they are not very usable without GlimmerComponent/angle bracket components.)

Should we be using these component life cycle hooks?  I've been doing so since this post, http://emberjs.com/blog/2015/06/12/ember-1-13-0-released.html#toc_component-lifecycle-hooks.

**Comment by adamesque** [comment]
I'd argue that since they were announced in a blog post, they are de facto public as of 1.13. Is it not safe to be using these hooks?

**Comment by efx** [comment]
+1

**Comment by Panman8201** [comment]
FYI, these are now in the [Guides](https://guides.emberjs.com/v2.3.0/components/the-component-lifecycle/) but still missing from the [API](http://emberjs.com/api/classes/Ember.Component.html) docs.

**Comment by locks** [comment]
Both are now landed :) Thanks everyone.
