### ISSUE TITLE
2.1: `<a href={{condition}}>` results in `<a href="null">` after `condition` was dynamically set to null

### ISSUE THREAD

**Issue by lolmaus** [emberjs/ember.js#12358]
So you've got this in your template:

``` html
<a href={{condition}}>
```

`condition` is `null`, and it correctly renders to `<a>`.

But then you change `condition` dynamically.

When `condition` is `null` again, it renders as `<a href="null">`.

Demo (thx to @alexspeller): http://ember-twiddle.com/a0a8088d67b451817902

**Comment by pixelhandler** [comment]
@lolmaus I guess the work around is to use an if/else rather than the condition for this use case.

Seems like the attr is bound by default and the condition determines the value. If you want the `href` attr binding to be present or not based on the condition it seems more reliable to use an if/else or define a component that sets up the attribute binding for `href` based on a property of the component.

**Comment by lolmaus** [comment]
@pixelhandler the `if` helper doesn't help, see the example above.

**Comment by dylanmensaert** [comment]
It seems to work for attributes other than href: http://emberjs.jsbin.com/leyehe/edit?html,js,output

**Comment by pixelhandler** [comment]
@lolmaus I meant using the if / else in your template instead of relying on a conditional in the value assignment to the html attribute `href`.

```js
{{#if hasURL}}
  <a href="{{url}}">GO</a>
{{else}}
  <a>WAT</a>
{{/if}}
```

**Comment by stefanpenner** [comment]
I suspect this may be related to `href` being special cased, and not reflected...

**Comment by lolmaus** [comment]
@pixelhandler That would result in code duplication. It gets really burdensome when your link content is complex.

**Comment by pixelhandler** [comment]
@lolmaus this issue has been inactive for some time, do you still have this issue?

**Comment by lolmaus** [comment]
I don't think so. Will repoen if I run into this again or someone reports it.
