### ISSUE TITLE
Can't extend LinkComponent in 2.0

### ISSUE THREAD

**Issue by zulaica** [emberjs/ember.js#12363]
This issue is similar to #11912 except that the solution provided there results in the same `Uncaught TypeError: Cannot read property 'slice' of undefined` error. I understand that extending `LinkComponent` will be possible in 2.1, but is there a way to make the params available in 2.0?

**Comment by pixelhandler** [comment]
@zulaica perhaps use a beta release and maybe feature flag?

**Comment by stefanpenner** [comment]
I am inclined to believe this is a bug.

cc @rwjblue (not asking you to fix this, but curious if you agree)

@zulaica can you provide a quick jsbin, to make it easy to diagnose? Even better, a failing test as a PR.

**Comment by zulaica** [comment]
@stefanpenner Here's a quick [jsbin](http://jsbin.com/gayebu/edit?html,js,output). I'll try to submit a failing test tomorrow.

**Comment by rwjblue** [comment]
Ya, it was a bug and it is fixed in beta/canary.  

Prior to 2.1 it wasn't really possible (many issues existed) to use your own link to variant so I don't think this is a regression. 

My suggested solution is to use beta/canary to take advantage of the refactoring that was done to make this possible.
