### ISSUE TITLE
Set a Computed Property in Component from outside (Inconsistent behavior)

### ISSUE THREAD

**Issue by denisovlev** [emberjs/ember.js#12385]
The basic idea is that I try to pass in a Component property which is handled inside the Component by a Computed Property.

The jsFiddle example shows a real-world application of this approach:
* we have list of items component: each of items can be selected (`App.ItemListComponent`)
* and we have header component with a checkbox which can select/unselect all the items (`App.HeaderPanelComponent`)
* they communicate through controller's boolean property `allSelected`

It worked in Ember v1.2
In Ember 1.13.10 (and at least in 1.9.1) the behavior has changed: when you select all items and then unselect one of them all of items get unselected

With Ember v1.2:
http://jsfiddle.net/6Evrq/688/

With Ember v1.13.10
http://jsfiddle.net/6Evrq/691/

Is this a correct expected behavior? The previous behavior was more convenient from my point of view, is there any workaround to get the same behavior in newer versions of Ember?

**Comment by xtian** [comment]
@denisovlev I think the proper way to achieve this effect is to define the computed property above the two components that depend on it:
http://jsfiddle.net/6Evrq/692/

I'm not sure exactly why the setter function gets called in your example, but it has something to do with how you're passing in a binding from the parent controller and then overwriting it with a computed property. I think you might have been depending on undefined behavior in older versions which is why this broke. Note that the example also works if you move the `{{header-panel}}` inside `{{item-list}}`:
http://jsfiddle.net/6Evrq/693/

**Comment by denisovlev** [comment]
@xtian thank you for response
I cannot define the computed property above as the idea of this is that each item inside item list gets wrapped in `ObjectProx`y on which `selected` is defined in order to not pollute model with it. Header panel component may be rendered rather far from the list and, generally, can work with different lists and should not know much about them or be inside them (as lists are general too and can be without a header)

From my point of view this is strange behavior as, in fact, change of the computed property calls setter on this property.

Is it certain that pass binding inside a component and then handle it with computed property is undefined behavior? 

Because this is very convenient way to connect components. Otherwise we have: 
* `observes` which works not very reliable and obscures logic of application
* `action` which is not a solution, as you cannot send action to a sibling or child component. And if you sent it to the controller it will not be able to call action on another component
* to pass inside a component a whole context of controller or parent component, or register object of component on the controller - which seems not the best idea as it couples tightly different parts of application
* some kind of event bus which is not ember way at all and which makes logic very complex

This feels like the right way and IMO worth considering.

**Comment by xtian** [comment]
Why can't you wrap your model in a proxy higher up in the application?

Your method doesn't feel like the right way to me since the header has an implicit dependency on a side-effect of the list component being added somewhere else in the application. This seems like a confusing architecture to me since there's very little to indicate the relationship between these two components and nothing preventing another component from clobbering that binding with its own computed property implementation.

**Comment by rwjblue** [comment]
I think a good alternative / pattern was given by @xtian.  Closing this for now...
