### ISSUE TITLE
ERROR: Attempting to register an unknown factory: `model:application`

### ISSUE THREAD

**Issue by rbemis** [emberjs/ember.js#12402]
Using ember-cli, I generated an application adapter and serializer. Edited the adapter and serializer to extend JSONAPIAdapter and JSONAPISerializer respectively. When I run the generated unit test, I get the following error:
```
Uncaught TypeError: Attempting to register an unknown factory: `model:application`
```
Looks like the failure is happening in the moduleForModel() step, even before the first line of code in the actual test is executed.

My environment:
```
[00:20 48] ember -v
version: 1.13.8
node: 0.12.7
npm: 2.13.4
os: darwin x64
```

Here's how to reproduce the problem:
(or, you can just clone the app from https://github.com/rbemis/ember-app1)
```
ember new ember-app1
cd ember-app1
ember g adapter application
ember g serializer application

===> Edit app/adapters/application.js so it extends DS.JSONAPIAdapter, like so:

import DS from 'ember-data';

export default DS.JSONAPIAdapter.extend({
});

===> Edit app/serializers/application.js so it extends DS.JSONAPISerializer, like so:

import DS from 'ember-data';

export default DS.JSONAPISerializer.extend({
});
```
In your browser, navigate to localhost:4200/tests
Here's what I see: http://cl.ly/image/3s2a3B0R2w0o/o

Please advise.

Thanks in advance.

**Comment by Serabe** [comment]
I think the bug is ember-cli not having a special case for the application serializer.

**Comment by pixelhandler** [comment]
@rbemis `moduleForModel` is part of the the ember-qunit repo, https://github.com/rwjblue/ember-qunit if your serializer does not have an associated model to test serialization don't use `moduleForModel`

The ember-cli blueprint for a serializer test expects a factory to exist for the generated test. In this case you generated a serializer test for 'application'. So the default blueprint assumes that there is a related model to serialize, hence the lookup of 'model:application', which doesn't exist there is no app/models/application module.

However your tests for an application serialize won't need to serialize an "Application" model so change `moduleForModel` to `moduleFor`. or import `module` from quit instead of `moduleFor` from ember-quint

My best guess is that you may want a test for the application serializer only to assert it's type, JSONAPI ?

This is NOT a BUG in ember, ember-cli, nor ember-quint.
