### ISSUE TITLE
Transitioning CSS class on multiple links to same route

### ISSUE THREAD

**Issue by topaxi** [emberjs/ember.js#12419]
When linking to the same route, with a different model, all links add the `ember-transitioning-in` class.
On this one, I'm not sure if this is right or wrong.

But this seems definitely like a bug:
When the transition ends, none of links but the one clicked remove the `ember-transitioning-in`.

Small example: http://emberjs.jsbin.com/muwaxavive/edit?html,css,js,output

Click on any color to switch to a subroute, all links go immediately red (`ember-transitioning-in`), after the transition, the clicked color goes blue again but the other links stay red.

This might be related or even a duplicate of #10989 or #10195

**Comment by pixelhandler** [comment]
@topaxi yeah this seems like a bug. The css class `ember-transitioning-in` seems sticky. Below is the HTML after clicking the links in order, red, yellow, blue. The class should be gone after the transition is done right?

```html
<ul>
      <li><a id="ember324" href="#/red" class="ember-view ember-transitioning-in">red</a></li>
      <li><a id="ember338" href="#/yellow" class="ember-view ember-transitioning-in">yellow</a></li>
      <li><a id="ember339" href="#/blue" class="ember-view active">blue</a></li>
</ul>
```

**Comment by topaxi** [comment]
@pixelhandler yes, the `ember-transitioning-in` should definitely be gone after the transition.

**Comment by topaxi** [comment]
I've added a failing test for this issue at [master...topaxi:transitioning-in-dynamic-segment](https://github.com/emberjs/ember.js/compare/master...topaxi:transitioning-in-dynamic-segment#diff-5e749b88e9f0ecb644ce1aebe45d2547R204). After going through some ember routing modules and [tildeio/router.js](https://github.com/tildeio/router.js/) I'm unsure where the issue lies and in which repository this should be reported and fixed.

**Comment by XaserAcheron** [comment]
Welp. I just ran straight into this -- same use case, basically. I've got a route which serves up some data-driven content, along with a navbar that transitions to the same route with a different model. `ember-transitioning-in` gets applied to every `link-to`. :(

I haven't been able to narrow it down properly (running into issues getting Ember's dev environment set up), but I suspect the culprit is somewhere around [here](https://github.com/emberjs/ember.js/blob/aeeddf7c00b42a340494465252481b5414d87009/packages/ember-glimmer/lib/components/link-to.js#L590). I suspect the `willBeActive` computed property is returning `true` for all the "incorrect" `link-to`'s, and `transitioningIn` never gets recomputed once the transition completes since `active` is never set on these extra links, leaving the `ember-transitioning-in` class hanging in limbo.

I'll see if I can pry further. I'd better throw together a test app so I don't have to upgrade my working ember version to canary. :P

**Comment by bgentry** [comment]
This bug is definitely still active, I just encountered it on v2.16.0.

I have a route `items.show` with a dynamic ID segment. I'm using the `link-to` helper with the model ID instead of a whole model because I'm using ember-apollo-client and want a different set of data fetched for the child route. When I click between a list of items, every single one of them gets the `.ember-transitioning-in` class applied. It is only removed from the item that eventually gets transitioned to, while the class remains on every other link that points to the same route but with a different dynamic segment variable.

I traced this all the way down to [`isActiveIntent` in router.js](https://github.com/tildeio/router.js/blob/0235c1de0aeb2c6c44215f7ab3ce56e8f4651227/lib/router/router.js#L301-L320), which returns `true` in the case of these other links. Even more specifically, the problem occurs [in this section](https://github.com/tildeio/router.js/blob/0235c1de0aeb2c6c44215f7ab3ce56e8f4651227/lib/router/router.js#L331-L349).

At this point, `contexts` contains the dynamic segments of the not-actually-transitioning link. However, `newState.handlerInfos`, `testState.handlerInfos` both end up having handlers with identical params, specifically `{ id: "ID_OF_ITEM_ACTUALLY_BEING_VISITED" }`. They are in fact equal here, though it seems that `testState.handlerInfos` is probably intended to have the params of the link being tested rather than the route being transitioned to.

On reading this, I believe the `NamedTransitionIntent` function call `applyToHandlers()` is intended apply the params in `contexts` to the `testState`. This does not happen, however, and the params remain identical to the `newState`'s params. You can see the result in this debugger screenshot:

<img width="1610" alt="screen shot 2017-10-29 at 9 32 50 pm" src="https://user-images.githubusercontent.com/114033/32154859-dce68aac-bcf0-11e7-8795-7675d199b7be.png">

I'm in pretty far over my head here and I'm not able to figure out what the fix is. Also having a hard time grasping router.js code without any documentation. Hopefully this is enough info to help somebody familiar fix it pretty quickly?
