### ISSUE TITLE
Ember.computed.sort doesn't update when live RecordArray updates.

### ISSUE THREAD

**Issue by bravo585** [emberjs/ember.js#12516]
I just upgraded from Ember 1.13 to Ember 2.1. I noticed Ember.computed.sort no longer updates if a live RecordArray updates.

For example, if I have:

```javascript
users: Ember.computed(function() {
  return this.store.filter('user', {filter: {'is-active': true}}, function(record) {
    return record.get('isActive');
  })
}),

sortLastName: ['lastName:asc', 'firstName:asc'],
usersSorted: Ember.computed.sort('users', 'sortLastName'),
```

And I print out:

```
{{#each usersSorted as |user|}}
  {{user.lastName}}, {{user.firstName}}
{{/each}}
```

If I add a new user, the users list will update, but the usersSorted list will not.

**Comment by g-cassie** [comment]
I think this is the same as https://github.com/emberjs/ember.js/issues/12475

**Comment by pixelhandler** [comment]
@bravo585 would you be able to create an example using jsbin, jsfiddle, or ember-twiddle? Perhaps instead of store.filter return a promise with the content as a RecordArray

**Comment by workmanw** [comment]
Actually this might be related to #12212 since it happened after upgrading to 2.x. Is your `Ember.computed.sort` in a component or other control that has multiple active instances at the same time? 

If it is related to #12212 ... you could try using my addon [ember-computed-sortby](https://github.com/workmanw/ember-computed-sortby).
