### ISSUE TITLE
Component template context wrong when wrapped with a layout

### ISSUE THREAD

**Issue by mvuckovic** [emberjs/ember.js#12593]
I'm on 1.13.10. 

Use case: If component uses both layout and template, context inside template will be that of a controller while it should (IMO) remain in components context.

Example: I have a modal component, and a receipt component, receipt component extends modal component and uses it's template as layout. Receipt component then provides its own template that the layout template simply yields.

Since both layout and template are properties of the receipt component, shouldn't they both have components context also?

Have a nice day!

**Comment by rwjblue** [comment]
I don't think I follow you here, can you please provide a runnable demo that shows what you mean?

**Comment by mixonic** [comment]
@mvuckovic we would definitely welcome an example in JSBin or Ember Twiddle, however I believe the behavior you describe (that a component's template has the context of the component's invocation) is correct. The template of a component is equivalent to the part you `yield` from the layout, thus the scope from invocation is restored.

I'm going to close this for now, but please re-open and provide more information if you think there is a regression in 1.13 or I've otherwise mis-understood you. Cheers!

**Comment by mvuckovic** [comment]
I apologise for the bad explanation and lack of demo!

I wanted components to be able to extend modal component, inherit its functionality and UI and then provide their own content inside.

Demo: http://emberjs.jsbin.com/qezimel/2/edit?html,js,output

I understand why this is happening and it works as intended if I use {{partial templateName}} instead of {{yield}}. 

I expected that component would be able to wrap itself with layout and still have access to its own template.
