### ISSUE TITLE
Application Container CSS/Containers in general

### ISSUE THREAD

**Issue by MadMub** [emberjs/ember.js#12656]
I'm new to ember, and trying to use ember 2.0. I discovered that views/controllers are going away in favor of a component based architecture (sounds good to me as I've already enabled a pod based folder layout and am loving it). My problem is I am trying to attach CSS styles to the application container, however I don't see how I can without Ember.View.

Furthermore, I think if it were possible, it would be more flexible if containers weren't javascript responsibility but rather the markup.
so this:
```
<!-- application/template.hbs -->
<p>content inside div.ember-view<p>
```
became:
```
<!-- application/template.hbs -->
<div class="ember-view" ember-view-name="application">
    <p>content in  inside div.ember-view</p>
</div>
```
This might not be possible given ember's long history, but my points for are the details of the container is entirely config, why not just let html/htmlbars handle it instead of js config (which is deprecated now anyways in the case of Views, I know Components have the config to support it).

DISCLAIMER: I come from a background of Angularjs, and my suggestion comes from ui-router's usage

I'm sure there are plenty of architectural reasons why this can't happen (feel free to explain, I'm here to learn). But getting back on topic, could I use jquery in a controller or something, to select a templates parent and add a css class to it? This would be a hack, but I imagine once we can route to a component, I can extend component and customize the container.

Just looking for workarounds for now, without leaving the latest stable release.

UPDATE: I'd like to add I've tried adding the following to my css with no success:
```
body > .ember-view {
    height:100%;
    width:100%;
}
```
UPDATE 2: this works for some reason, I'm not a fan, it meets my needs for this particular use case, but my general questions still stand
```
body > .ember-view {
    height:100vh;
    width:100%;
}
```

**Comment by pichfl** [comment]
The issue tracker is not intended for questions like this. Please see the [extensive list](http://emberjs.com/community/) of other platforms including Stack Overflow, the official forum, IRC and Slack. 

However, here are some starting points:

1. You can [change the apps root element](http://emberjs.com/api/classes/Ember.Application.html#property_rootElement) very easily. Since the default is the document body, you probably don't want to do that.
2.  You can also define a ~~view~~ __a component__ for your application root. Since routable components are not ready yet, you would have to create a new view file and use a component inside. This should be more likely give you the control that you're looking for. Just create `app/views/application.js` and paste this:
  ```
  import Ember from 'ember';

  export default Ember.Component.extend({
    classNames: ['something'], // now your application view has a class named "something"
    tagName: 'div',
  });
  ```
3. The first CSS block you added doesn't work because that's how CSS works. Since neither `<body>` nor `<html>` have a specific height, `height: 100%;` doesn't do anything inside the `.ember-view`. Going with `100vh` **is** the appropriate solution. Also since an application will only have one root view, your selector is correct and the solution you have in the second update is actually perfectly fine.


For further questions close this ticket and create a tagged question at [Stack Overflow](http://stackoverflow.com/questions/tagged/ember.js).

**Comment by MadMub** [comment]
Thanks for the info! Sorry for posting in the wrong place
