### ISSUE TITLE
enter argument of input helper doesn't work

### ISSUE THREAD

**Issue by ruz** [emberjs/ember.js#12665]
Hi,

All that I've read in the docs tell me that action set with enter argument is triggered when user hits enter and before form submission, but tests show different behaviour. I just can not trigger enter action.

demo: https://ember-twiddle.com/42d5e1be42ab56f744d7

**Comment by pixelhandler** [comment]
@ruz i don't think that `enter` is a registered event, see: http://guides.emberjs.com/v2.2.0/components/handling-events/#toc_event-names perhaps use `submit` or ask in the ember-community.slack.com chat rooms about the best practices for handing form submission using the enter key.

**Comment by bekzod** [comment]
@ruz you should be listening to form event `onsubmit` not `enter key` event on input to cancel form from submitting https://ember-twiddle.com/59435e6baaabf3798122

**Comment by ruz** [comment]
what is that then? http://guides.emberjs.com/v2.2.0/templates/input-helpers/#toc_actions

also, if you use action with ```{{input}}``` helper embers tells you that action is deprecated and you should use enter instead.

**Comment by locks** [comment]
@ruz `enter` is an Ember action that the input component emits, not an event. If you open the console you'll see "e.preventDefault is not a function", which is due to that.

You would need to handle the submit event like mentioned.

I am closing this issue as it seems like it was a small misunderstanding.
Feel free to re-open the issue if you think it's still justified, thank you!
