### ISSUE TITLE
key-press action on {{input}} has no access to event

### ISSUE THREAD

**Issue by ruz** [emberjs/ember.js#12667]
key-up and other pass event object as second argument to the action handler, but not key-press.

demo: https://ember-twiddle.com/f06db4499c0c2806c5a3

**Comment by pixelhandler** [comment]
@ruz to handle keyboard events and access the event object using an event handler instead of an action should work, see - http://guides.emberjs.com/v2.2.0/components/handling-events/

I think that actions are not expected to pass any event object.

**Comment by ruz** [comment]
Bug report is not about how, but that it's not consistent :(

**Comment by JennieJi** [comment]
@ruz, no way to acess event object in keypress, also focusin/focusout. You need to use keyUp/keyDown instead. From the source code, keyPress is using a specific sendAction function wrote for {{action 'xxx' on=""}} and call another sendAction function used in keyUp/keyDown with sending input element's value before entering new charactor only. Yep, event object at all... No idea why they did this. I sent a pull request to fix this, but I'm not sure whether it will be proved or not.

**Comment by nightire** [comment]
@JennieJi back you up on this

**Comment by JennieJi** [comment]
@nightire Thank you Albert :)

**Comment by mixonic** [comment]
Thanks all. I expect when we write a glimmer version of the `input` helper we can change the arguments being passed and make them more consistent.

However we're not interested in making this change. It perpetuates inconsistencies about when and where the event object is passed as well as adding more jquery to our API. We're attempting to move away from passing jquery events around, instead of adding more in.

**Comment by ruz** [comment]
Please update documentation. I spent quite a while trying to use ```{{input}}``` helper with event handler via helper arguments. It was so frustrating, annoying and time consuming experience.

**Comment by ironyinabox** [comment]
So, generally speaking, not having access to the event object in actions is annoying, so I built this workaround (warning: coffescript ahead)

```coffescript
click: (e) -> @set('clickEvent', e)
actions:
    clickAction: ->
        Em.run.next =>
            e = @get('clickEvent')
            # do stuff
```

The `Em.run.next` is neccesary because ember fires actions before it delegates events. I'm sure this is why they don't give you the event object in your actions; because firing one before the other is better for some meta reason that I can't be bothered to figure out (until it breaks for some reason, of course). I haven't tested this with non-click events, but I'm assuming it will work.

**Comment by rwjblue** [comment]
In the following snippet, the `someThing` action will be called with the event...

`<input value={{foo}} oninput={{action 'someThing'}}>`

**Comment by mm2ha** [comment]
The same issue exists with focusOut. I just had an instance where I needed to know which element caused focusOut from input and the event was not being passed through.

**Comment by allthesignals** [comment]
Seems related to null-null-null/ember-keyboard#56
