### ISSUE TITLE
Dynamic parameters for dynamic components

### ISSUE THREAD

**Issue by CostaRico** [emberjs/ember.js#12671]
Hi, how can I pass hash of params into a component?
```javascript
import Ember from 'ember';
export default Ember.Controller.extend({
  componentParams:{
    value: '23'
  }
});
```

Im looking for something like this:
```handlebars
{{component 'inputs/number-input' componentParams}}
```
or this
```handlebars
{{component 'inputs/number-input'  properties=componentParams}}
```

**Comment by rwjblue** [comment]
> Dynamic parameters

This isn't really supported at this time.

> `{{component 'inputs/number-input'  properties=componentParams}}`

You can use this, but you will need to update your `inputs/number-input` component to look in `properties` for various things instead of the root of the object.

---

On a side note: we generally agree that this would be a very useful addition and are working on adding syntax in Handlebars for this.  Follow along in https://github.com/wycats/handlebars.js/issues/1050.

Closing this for now, as it isn't really a "bug" but a welcome new feature (that is being worked through).
