### ISSUE TITLE
didReceiveAttrs not picking up changes in arrays and objects

### ISSUE THREAD

**Issue by rmmpaderes** [emberjs/ember.js#12696]
As the title says. Is this expected or is this a bug?

https://ember-twiddle.com/871c9b8d68f9be999e9c?numColumns=1

**Comment by pixelhandler** [comment]
@rmmpaderes I'm curious if the fact that the `test` array has not changed, it's the same array instance, since on only the content of the `test` attr changed not the test attr itself… it appears that the result is that `didReceiveAttrs` is only called once. My assumption is that if the `test` array was swapped with a new array that perhaps the lifecycle hook would be called again. Technically the `test` attr has not changed only it's length has changed.

**Comment by rmmpaderes** [comment]
@pixelhandler - Yes, that's exactly what's happening. I was under the impression that didReceiveAttrs will get fired for any changes in the attribute no matter how deep inside an array/object.

Okay, so I guess didReceiveAttrs would not be the solution for triggering an event whenever a `hasMany` property changed.

**Comment by rwjblue** [comment]
@rmmpaderes - Yes, there is absolutely still a need for computed properties!  @pixelhandler is correct in this example, `didReceiveAttrs` is not being fired because the `test` object is not changing.

**Comment by Panman8201** [comment]
Ran into this same issue, objects are not "fully" observed, therefore the `didReceiveAttrs()` doesn't always fire. :cry: :cry: Leaving this Twiddle here for reference: https://ember-twiddle.com/f1740177799321f88eda?numColumns=1&openFiles=application.controller.js%2C
