### ISSUE TITLE
Positional param 'value' leaks inner data when used in combination with nested component helpers

### ISSUE THREAD

**Issue by martndemus** [emberjs/ember.js#12717]
If I have component with the positional param `value`, and I use it in combination with nested component helpers `{{component (component my-component)}}`, and the following component code:
```js
let MyComponent = Component.extend({
  didReceiveAttrs() {
    let value = this.getAttr('value');
    console.log(value);
  }
});

MyComponent.reopenClass({ positionalParams: ['value'] });
```

Then the logged `value` will be an object with attributes `COMPONENT_CELL`, `COMPONENT_HASH`, `COMPONENT_PATH` and `COMPONENT_POSITIONAL_PARAMS`.

This fails for me using `2.3.0-beta.2` and `components/ember#canary`. I'll try to add a failing test if I get to it. 
I also believe @Serabe will be delighted to hear about this.

**Comment by Serabe** [comment]
I cannot reproduce it:

https://ember-twiddle.com/bc25554d2cbe7c0c5ced
https://ember-twiddle.com/8991cb8cfb659cd6ea60

Can you please provide more info?

If I remove the quotes around `my-component` I get an expected error: component path cannot be null.
`{{component (component (component "my-component"))}}` simulates `my-component` being a closure itself in your code. I get two `undefined`s. Can you try to modify the twiddles to show the failure?

Thank you for reporting this!

**Comment by martndemus** [comment]
@Serabe It seems it's the contextual helper is needed to trigger the bug. https://ember-twiddle.com/1eba14b986610d4dc631

**Comment by Serabe** [comment]
Thank you! I'll be fixing this today "hopefully"

**Comment by martndemus** [comment]
:+1:

**Comment by Serabe** [comment]
I need @mixonic or @rwjblue guidance on this.

The problem is that this is being rendered as `{{c.my-component}}` (the fact that is has no `params` nor `attrs` is actually really important.

When htmlbars finds `{{c.my-component}}` it thinks that it is a `render`, not an `inline` (which would happen if the call was `{{c.my-component 1}}`). The problem arises because `range` sends to `handleRedirect` `[value]` as the parameters (can be seen [here](https://github.com/tildeio/htmlbars/blob/master/packages/htmlbars-runtime/lib/hooks.js#L837). I tried removing the value inside the array and all tests pass.

Should I submit a PR for this or is there any reason for that code being there? How can I test ember with a custom htmlbars?

**Comment by rwjblue** [comment]
Reopening to get the updated version here.

@Serabe - Can you submit a PR updating to HTMLBars v0.14.11?
