### ISSUE TITLE
this.actions on application route is undefined in 1.13.11

### ISSUE THREAD

**Issue by adam-knights** [emberjs/ember.js#12743]
Using Ember 1.13.11 (and data 1.13.5) if I defined actions in my application route, and then try to access `this.actions` then it is undefined.

See this twiddle: https://ember-twiddle.com/547ceb6019bf444f0a7f

If you move that twiddle upto Ember 2.0.2 (and data 2.0.1), then it works correctly.

So this appears to be a resolved in Ember 2 onwards but opening issue incase either a) this could/should be backported to Ember 1.13, or b) This was fixed by accident and isn't tested for and needs a test adding, or c) I couldn't see anything like this anywhere in my search and this may save someone else some time who can upgrade.

**Comment by rwjblue** [comment]
Ya, this is not really a bug. In Ember 1.x `.actions` was moved to `._actions` mostly due to the way the actions hash was added and to allow folks that were using an `actions` property to have a path forward. As we progressed through the 1.x cycle usage of `.actions` for anything other than an actions hash became very very uncommon, but various tooling was stuck using `_actions` for things like you are doing in the twiddle.  

If you are needing to access the actions hash directly **AND** you have to support Ember 1.x and 2.x  you should do something like:

```
var actions = route.actions || route._actions;
```

**Comment by rwjblue** [comment]
Also, this isn't really a breaking change because we have an accessor to allow the older pattern of using `route._actions` with a deprecation ([tested here](https://github.com/emberjs/ember.js/blob/341a325a13fc685a10399de600586b6fb744e99f/packages/ember-routing/tests/system/route_test.js#L197-L211)).

**Comment by adam-knights** [comment]
Perfect, thankyou, agreed not a bug

**Comment by rwjblue** [comment]
FWIW - We changed this because of exactly your scenario. It is mega annoying/confusing to have defined a thing at `.actions` yourself and then it not be there.

**Comment by adam-knights** [comment]
haha yes exactly, at first I thought one of the addons we use had somehow broken it. Anyway, i've updated my answer to my original question at http://stackoverflow.com/questions/34392187/in-an-ember-route-how-can-i-check-if-an-action-exists to help others.
