### ISSUE TITLE
component has some missing documentations

### ISSUE THREAD

**Issue by oriSomething** [emberjs/ember.js#12760]
http://emberjs.com/api/classes/Ember.Component.html

part of them are the `render hooks` and some are functions as `readDOMattr`

**Comment by pixelhandler** [comment]
@oriSomething that api doc page should be generated from https://github.com/emberjs/ember.js/blob/v2.2.0/packages/ember-views/lib/components/component.js#L32 I didn't see `readDOMattr` or `render hooks` there.

I do see docs for `readDOMattr` in the source at https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/mixins/view_support.js#L580-L616 however I have no idea where that would be rendered in the api docs since Ember.View is deprecated.

**Comment by oriSomething** [comment]
hey, `readDOMattr` is used in a component where some of the creators are core contributors (or related to) of Ember.
`Ember.View` might deprecated, but `Ember.Component` still inherit from `Ember.View` and because of this still relevant.

**Comment by runspired** [comment]
@oriSomething Ember.Component does not inherit from Ember.View anymore.

**Comment by oriSomething** [comment]
@runspired 
https://github.com/emberjs/ember.js/blob/2.2/packages/ember-views/lib/components/component.js#L119
???

**Comment by runspired** [comment]
@oriSomething this is not the same View as `Ember.View`.

**Comment by runspired** [comment]
After rereading the source, the `Ember.Component` vs `Ember.View` split from `View` happens just before Ember.View is solidified, so if it's on `View` it will also be on `Ember.Component`, and should be documented as you said.

**Comment by chrisjshull** [comment]
The #element property for ViewSupport/View/Component is literally not in the documentation anywhere (at least the I could find). Ditto many other properties.
Can this be prioritized? Not sure how anyone can use a framework that's missing critical bits of docs.

**Comment by acorncom** [comment]
This was resolved a few weeks ago, closing this issue. If we're still missing something feel free to comment here or open a new issue, we want the docs to be accurate! :+1:
