### ISSUE TITLE
Function.prototype.apply with arguments

### ISSUE THREAD

**Issue by bmeurer** [emberjs/ember.js#12774]
Looking at https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/utils.js#L311-L320 and similar places in EmberJS, you'll likely defeat optimizations wrt. Function.prototype.apply in JS engines. For example, V8 nowadays does apply with unmodified unmapped arguments (i.e. strict mode arguments object or sloppy mode arguments w/o any declared parameters) very fast - even w/o any support from the optimizing compiler(s). Copying the arguments to a temporary array first not only disables the optimization and adds allocation and copying overhead, but also takes the super slow path for Function.prototype.apply, because the array is holey due to the initial new Array(length). I'm working on making this slow path less slow, but it'll still in general require prototype chain and hole checks nevertheless.

So I'm not sure how important this workaround is currently (I guess a lot of Android phones are still running outdated Chromium based browsers), but for the future, you should probably consider not copying arguments before calling into apply.

**Comment by stefanpenner** [comment]
I'm our tests. Modern v8 is ok without this, but our lovely problematic android friends aren't so lucky.

I suspect this branching is ultimately worse if there are some uncommon paths hit after the hit hits some steady state.

**Comment by bmeurer** [comment]
Can you point me to the original V8 issue that caused this work-around? AFAIK there was some weird deopt w/ apply and arguments in Crankshaft?

So from measuring w/ your benchmarks, this case isn't hit that often, because you manually switch over arguments.length and use F.p.call for small lengths, but that's also a rather unfortunate work-around, since the VM cannot properly optimize that either. Running the pathological "Complex List" thing it seems we only see around 150 calls to the super-slow case of F.p.apply with a holey array or some slow arguments object.

Maybe we can find a way to avoid the copying while still not hitting the old Crankshaft issue.

**Comment by stefanpenner** [comment]
@bmeurer yes, the issue was: https://code.google.com/p/v8/issues/detail?id=3709 if I recall.

It's also worth noting, in the past (likely when the more specialized apply variant was implemented) `super` wrappers where much more common, since then on platforms that support `Function.prototype.toString()` I added support to only wrap if `_super` was detected. This dramatically reduced usages.

It might be worth stripping out al this branching in-favor of a pure `fn.apply(this, arguments);`, At my current work, I no longer have a pile of androids on my desk, so testing side-affects isn't quite as easy. But i'll see if i can round up a few.

@bmeurer are you interested in having a google hangout sometime this week, that way we can get on the same page. Maybe compile a hitlist of action items/investigations, and see if our friends over at linkedin (who are really trying to get better android perf) can lend a hand.

**Comment by bmeurer** [comment]
Sure such a list would be very useful to us. I'll try to figure out what the problem with Crankshaft was about.

**Comment by bmeurer** [comment]
Ah yeah, that's interesting. So it was not about Crankshaft running into a weird deopt, but the fact that Crankshaft was disabled because it couldn't deal with the uninitialized CallIC properly.

Now looking into that particular function (https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/system/core_object.js#L176-L184): Isn't it beneficial to disable Crankshaft there anyway? Both Class and makeCtor will likely see highly polymorphic feedback for various (Keyed)Load/StoreICs, so optimized code will likely be deoptimized quite often on this over the runtime of an Ember application, slowing down execution compared to executing makeCtor and Class in fullcodegen only.

@stefanpenner Did you see a real performance improvement after https://bugs.chromium.org/p/v8/issues/detail?id=3709 was fixed? Did you measure the impact of using the temp Array vs. using arguments directly?

**Comment by stefanpenner** [comment]
> @stefanpenner Did you see a real performance improvement after

yes, although this was quite some time ago.

> Did you measure the impact of using the temp Array vs. using arguments directly?

not after the fix landed, for fear of degrading android performance.

> Now looking into that particular function (https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/system/core_object.js#L176-L184): Isn't it beneficial to disable Crankshaft there anyway? Both Class and makeCtor will likely see highly polymorphic feedback for various (Keyed)Load/StoreICs, so optimized code will likely be deoptimized quite often on this over the runtime of an Ember application, slowing down execution compared to executing makeCtor and Class in fullcodegen only.

Very likely.

@krisselden is working currently, to produce a good example app we can use to further this discussion + test our hypothesis.

Due to the many dimensions of composition/code-paths in typical apps, it is often quite tricky to reason about locale/global affect of optimizations. Especially as the code-base evolves overtime, and the patterns shift.

I believe the only sensible path forward, is via a common example app (that is open and not tied to some companies IP) that tries to enumerate common cases. So hopefully @krisselden can land that in the next  little while and we can start testing these hypothesis.

**Comment by pixelhandler** [comment]
@bmeurer @krisselden @locks @pixelhandler @stefanpenner is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by bmeurer** [comment]
What does the code look like nowadays?

**Comment by pixelhandler** [comment]
@bmeurant the comment that @stefanpenner mentioned as the path forward was...

> I believe the only sensible path forward, is via a common example app (that is open and not tied to some companies IP) that tries to enumerate common cases. So hopefully @krisselden can land that in the next little while and we can start testing these hypothesis.

So that seems like something outside of fixing an ember bug but perhaps can be created as an RFC issue, https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature

> Use RFC issues to propose a rough idea, basically a great place to test the waters.

I'll close this for now. @bmeurer @krisselden @locks @pixelhandler @stefanpenner  if you'd like to propose to do the suggestion to make a **common example app** please open an issue on the RFCs repo to track that effort.
