### ISSUE TITLE
Glimmer 2: Promise-aware templates

### ISSUE THREAD

**Issue by fivetanley** [emberjs/ember.js#12825]
Often requested because of ember data: https://github.com/emberjs/data/issues/2418

The basic idea is this: When I give a promise to a helper, curly, or component in Ember, it should re-render when the promise resolves.

Example:

```handlebars
{{#each comments as |comment| }}
  {{comment.name}}
{{/each}}
```

This currently never re-renders, and as there is no API for determining whether the promise is resolved or not, it never will. This leads the user to implement their own book-keeping, by setting properties on the controller and relying on watching arbitrary KVO for the re-render to occur.

Alternatives:

* Promise helpers (`isFulfilled`, `isRejected`, `isPending`)

I don't really have anything flushed out yet, but I think @stefanpenner has some ideas, and this issue belongs here rather than Ember Data as it affects all promises and templating in Ember.

**Comment by pixelhandler** [comment]
@fivetanley I like the idea of using a promise proxy object/array with the promise proxy mixin so that properties like you mentioned `isFullfilled` can be used.

I'm curious why the `comments` never re-render. Is `comments` a promise from a request to the `store`? So are there never any comments rendered? or does `comments` change somehow, like a new comment added to the collection.

I'm not sure how the helpers e.g. `each` would become promise aware. Are they not currently? The guide page for rendering a list is not clear whether or not the value passed to the `each` helper is a promise or not. see: https://guides.emberjs.com/v2.3.0/templates/displaying-a-list-of-items/

```hbs
<ul>
  {{#each people as |person|}}
    <li>Hello, {{person.name}}!</li>
  {{/each}}
</ul>
```

So if `people` is a property that depends on a request to the `store` (that is a promise) would the list items never render?

You mentioned that developers are led to solving this creatively, e.g. own book-keeping. My solution was in a data persistence library rather then in my application code. For the sake of the sharing use cases on how people address this, below is an example…

Here is an example of how I use a computed property for a relation that resolves to the data returned from an API request. Below `model` is the `post.comments` computed property. It's a promise proxy using an array, so it starts as a promise and when resolved the content is set to the array of data. the change to the computed property for `post.comments` does re-render the template.

```hbs
{{#each model key="@identity" as |comment|}}
  <li>
    {{#with comment.commenter as |commenter|}}
      <span>by <strong>{{commenter.name}}</strong>…</span>
    {{/with}}
    on <span>{{comment.date}}</span>
    <p>{{comment.body}}</p>
  </li>
{{/each}}
```

- Post has-many "comments"
- Comment has-one "commenter"
- See the models for post, comment, commenter here: https://github.com/pixelhandler/jr-test/tree/master/app/models

These "relationships" use a related proxy object, `ArrayProxy` (has-many) or `ObjectProxy` (has-one) combined with the `PromiseProxyMixin`, see: https://github.com/pixelhandler/ember-jsonapi-resources/blob/master/addon/utils/related-proxy.js#L90-L92

So, the computed property of the model for has-one and has-many relations use a proxy for the data.

When the comments template (above, used in an outlet of the post template) has a resolved `model` the array of comments are rendered, likewise when the comments' related commenter is resolved the `comment.commenter` renders.

My template's are not "promise aware" instead the model relations are proxy objects, but the template does re-render when the promises resolve.

**Comment by stefanpenner** [comment]
this seems like RFC discussion.

**Comment by fivetanley** [comment]
confirm. can you copy/paste over to the RFC @pixelhandler? https://github.com/emberjs/rfcs/pull/110

**Comment by fivetanley** [comment]
I'm closing in favor of moving discussion to the RFC. I think we've agreed at this point in the RFC discussion that this should exist in userland. Follow the RFC discussion for a link to the in-progress (not implemented) addon.

**Comment by pixelhandler** [comment]
@fivetanley thanks, I added my comment to your RFC.
