### ISSUE TITLE
Consider using get to access templateName on the Ember.Route

### ISSUE THREAD

**Issue by foxnewsnetwork** [emberjs/ember.js#12857]
### The problem
Currently, the internal function `buildRenderOptions` in the ember route at:

https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/route.js#L2095

access `templateName` via just the regular javascript access operator `.`

This makes specifying the `templateName` as a computed property problematic e,g:
```coffeescript
match = (subject, matchers...) -> ...

Ember.Route.reopen
  templateName: computed "routeName", ->
    match @get("routeName"),
      /\.new$/, -> "default-new",
      /\.edit$/, -> "default-edit",
      /./, -> "default-index"
```
won't work

### The fix
Can we possibly consider changing the line at https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/route.js#L2111
from:
```javascript
templateName = route.templateName || name;
```
to:
```javascript
templateName = route.getWithDefault(templateName, name);
```
If this is okay, I can do a PR

**Comment by pixelhandler** [comment]
@foxnewsnetwork my best guess is that here is some history on this subject about using the `templateName`. Perhaps this issue should be moved to the RFC issues. See https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature

> Use RFC issues to propose a rough idea, basically a great place to test the waters.

**Comment by pixelhandler** [comment]
@foxnewsnetwork if you want perhaps make the PR, seems like a simple change, not sure if there are any performance considerations.

**Comment by foxnewsnetwork** [comment]
@pixelhandler I actually did a fork and tried doing it with the `get("templateName")` way... but the problem is, `route.routeName` is accessed with the `.` in a lot more places than I had originally anticipated, and so if one overrides `templateName` with a computed property, it unfortunately breaks a lot stuff. IMO, this might not be the can of worms the good folks working actively on Ember wants to open.

**Comment by rwjblue** [comment]
The vast majority of folks should be using the default template names, I am not really sure that we want to add additional features that make knowing which template goes with a specific route harder.

You may be able to use a normal JS getter function instead of a computed property here to work around this in your specific case...

**Comment by yads** [comment]
My use case is in a mixin that is configured by whatever route extends it. Part of the mixin is to configure the correct rendering, so the `controllerName` and `templateName` should be dynamic. I did solve it with the suggestion that @rwjblue provided, by using `Object.defineProperty` in the init method. However it's unintuitive since almost everywhere else you can use computed properties.

I guess it brings up another question for me: What is the best way to provide configurable mixins. Is it to have a function that creates a new mixin every time based on the options, or is it better to configure the mixin using the `init` method:

i.e.

```
export default function createMyMixin(opts) {
  return Ember.Mixin.create({
    aProp: opts.aProp
  });
};
...
Ember.Object.extend(createMyMixin({aProp: 'foo'}, {});
```

or

```
export default Ember.Mixin.create({
  init() {
    this._super(...arguments);
    let _this = this;
    Object.defineProperty(this, 'aProp', { get() { return _this.get('opts.aProp'); } });
  }
});
... 
Ember.Object.extend(MyMixin, {
  init() {
    this._super(...arguments);
    this.set('opts', {aProp: 'foo'});
  }
});
```

**Comment by pixelhandler** [comment]
@foxnewsnetwork I agree with @rwjblue Ember has conventions that developers can count on changing `templateName` in a way that can become dynamic sounds like a debugging headache in the making. Is there a way you can just define all the routes you need and associated templates?

I'll close this out for now. If you want to continue the discussion please create an RFC issue (not PR) https://github.com/emberjs/rfcs
