### ISSUE TITLE
Component resets all attributes when a dynamic attribute is changed

### ISSUE THREAD

**Issue by SuperCoolFrog** [emberjs/ember.js#12867]
I have a component that I pass some static and dynamic parameters.  The component updates these static values during interaction.  When dynamic parameters are updated by the implementing component, all the static parameters are reset.  I would expect that the component retains the updated value.

[Ember Twiddle](https://ember-twiddle.com/4b348bfbf73af4b53c35?openFiles=outer-component.template.hbs%2Capplication.template.hbs)

**Comment by pixelhandler** [comment]
@SuperCoolFrog the `showYield=false` static value is changed via action after render, then the update time action changes something in the parent node causing it's template to redraw (which seems to have the side effect of resetting the showYield back to false. I don't think you want to mix the stack value and dynamic value. perhaps define the default value as a property and use that property instead of the static value.

**Comment by SuperCoolFrog** [comment]
Thank you for the response.  I have implemented a work around very similar to what you described, but I was curious if this is the intended behavior since the component's init and willDestroy are not called.  I will ask on stack overflow thanks.

**Comment by rwjblue** [comment]
Yes, this is intended behavior. All attributes are passed for each rerender.  If you want this to be the initial value, you may want to change something like: https://ember-twiddle.com/725b98fcd55637dc77b8?openFiles=outer-component.component.js%2Capplication.template.hbs.

**Comment by SuperCoolFrog** [comment]
Thanks
