### ISSUE TITLE
Data not loading in API but is in Cache

### ISSUE THREAD

**Issue by hannahcooperRHUL** [emberjs/ember.js#12870]
Hello,
When trying to load embedded data, I have a problem in that when the model is already cached on my page, this embedded data will not load in the view. If, however, it it is reloaded from scratch and therefore read from the API, it does load. I can see that the data is being loaded into the model from the Ember inspector plugin, however. 
If you could tell me the issue here so that the data will load every time, this would be appreciated. 
Many thanks. 

````
import DS from 'ember-data';
import WebApiSerializer from 'ember-web-api/serializers/web-api';

export default WebApiSerializer.extend(DS.EmbeddedRecordsMixin,{
    attrs: {
        subjects: { embedded: 'always' }
    }
});
```

Models

```
import DS from 'ember-data';

export default DS.Model.extend({
    name: DS.attr('string'),
    graduationDate: DS.attr('string'),
    institutionLevel : DS.attr('string'),
    subjects: DS.hasMany('subject'),
    cv: DS.belongsTo('cv')
});

```

```
import DS from 'ember-data';

export default DS.Model.extend({
    name: DS.attr('string'), 
    grade: DS.attr('string'), 
    education: DS.belongsTo('education')
});
```

**Comment by davidpett** [comment]
This seems like a question and not an issue with the ember.js codebase, for help like this, please ask on Stack Overflow, or join the ember community slack (https://ember-community-slackin.herokuapp.com/). Please look at this page for other options, http://emberjs.com/community/. Thanks!

**Comment by fivetanley** [comment]
You can override `http://emberjs.com/api/data/classes/DS.RESTAdapter.html#method_shouldReloadRecord` to return `true` so that the data is always fetched. If you prefer to have the data be refetched in the background but return the record immediately you can instead override `shouldBackgroundRefreshRecord`.

Also for future reference, this would have been more appropriate to file on the Ember Data issue tracker or StackOverflow as @davidpett pointed out.
