### ISSUE TITLE
TypeError when passing models to route with `intermediateTransitionTo`

### ISSUE THREAD

**Issue by brendan-rius** [emberjs/ember.js#12886]
[Click here for Twiddle](https://ember-twiddle.com/67430930263c65915d02?openFiles=application.route.js%2Capplication.template.hbs)

According to the doc, I should be able to pass models as parameters when calling `intermediateTransitionTo`, but when I do, it raises an exception:

```Uncaught TypeError: Cannot read property 'length' of null```

If I do not pass models, it works. The exception is raised here [in this file](https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/router.js) line 1042:

```javascript
for (var i = 1, l = handlerInfos.length; i < l; i++) 
```

P.S.: I use Ember 2.2.0

**Comment by GavinJoyce** [comment]
An exception is thrown when we're doing an intermediate transition:

`Error: More context objects were passed than there are dynamic segments for the route: loading(…)`

![image](https://cloud.githubusercontent.com/assets/2526/12732878/83b01a22-c92f-11e5-9bee-68cb88a02be2.png)

I think this is because the loading route doesn't have a dynamic segment.

I've replicated this same exception in [this twiddle](https://ember-twiddle.com/0da5e43d515c4f872359?openFiles=application.route.js%2Capplication.template.hbs). It works for the `dynamic` route, but it doesn't for `non_dynamic` route:

![image](https://cloud.githubusercontent.com/assets/2526/12733069/8f2e8db0-c930-11e5-9998-571786b48b52.png)

**Comment by brendan-rius** [comment]
It makes sense now.

I tried passing a model to display a custom message depending on the current route while loading. I could have used the route "myroute-loading", but then I am forced to create a new template for each route, while I wanted something generic and use it like

```javascript
import Ember from 'ember';

export default Ember.Route.extend({
  loadingMessage: "Custom loading message"
});
```

**Comment by GavinJoyce** [comment]
@brendan-rius great, perhaps close this issue?

**Comment by rwjblue** [comment]
Thanks @GavinJoyce!
