### ISSUE TITLE
Rendering the default template instead of the given `templateName` when using `renderTemplate`

### ISSUE THREAD

**Issue by MatrixZ** [emberjs/ember.js#12967]
In order to render the template in the given outlet, `renderTemplate` hook is implemented and `templateName` is given to render the required template.
But default  [routeName](https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/route.js#L1956) template is rendered instead of the given `templateName`.

https://ember-twiddle.com/e58f8466fad4994deb3e

In the twiddle, I have two routes `new-route` and `edit-route`. I want to reuse the same template for both routes. The `edit-route` renders the `edit-route/template` instead of `new-route/template`, though `templateName` is given.

**Comment by pixelhandler** [comment]
@MatrixZ I typically make a form component that I can use for both editing and creating resources. I think that would be a good work-around. Also considering that routable components are in the roadmap it may be a good idea.

**Comment by stefanpenner** [comment]
something seems fishy, likely needs some more investigation.

**Comment by dguettler** [comment]
The reason this is happening is due to the interaction of `render` and `buildRenderOptions`.
In case `_name` is an object and no options are passed `name` is set to `this.routeName` which is then passed on to `buildRenderOptions`.

`buildRenderOptions` receives `name` as `_name` argument and uses it (if present) as the `templateName`
```
  let name, templateName;
  if (_name) {
    name = _name.replace(/\//g, '.');
    templateName = name;
  } else {
    name = route.routeName;
    templateName = route.templateName || name;
  }
```
https://github.com/emberjs/ember.js/blob/v2.7.0/packages/ember-routing/lib/system/route.js#L2122

Possible fix would be to check in the `if` clause if a `templateName` is given
```
  if (_name) {
    name = (route.templateName || _name).replace(/\//g, '.');
    templateName = name;
  } else {
```

Or to change the upstream `render` method to not set the passed `name` to the `routeName` but the `templateName` if present
```
    if (typeof _name === 'object' && !options) {
      name = this.templateName || this.routeName;
      options = _name;
    } else {
      name = _name;
    }
```
https://github.com/emberjs/ember.js/blob/v2.7.0/packages/ember-routing/lib/system/route.js#L1969

**Comment by andrewmp1** [comment]
@dguettler Amazing I just decided to work on some bugs today and was looking at this and came to the same conclusion.  Created a PR for the fix w/ a failing test: https://github.com/emberjs/ember.js/pull/13969

**Comment by dguettler** [comment]
Should this get a different label? Fix has been merged to master
