### ISSUE TITLE
Reopen in initializer is not working immediatly

### ISSUE THREAD

**Issue by GCorbel** [emberjs/ember.js#12977]
Hi,

I have an addon initializer like this : 

```
import Subscription from 'tiny/models/subscription';
import DS from 'ember-data';

export function initialize(applicationInstance) {
  Subscription.reopen({
    customData: Ember.computed(function() {
      return {}
    })
  });
  console.log("value");
}

export default {
  name: 'modify-models',
  initialize
};
```

And this route : 

```
import Ember from 'ember';

export default Ember.Route.extend({
  model(params) {
    var record = this.store.findRecord('subscription', params.id);
    console.log(record.customData);
    console.log(record.get('customData'));
    return record;
  },

  actions: {
    submit: function() {
      console.log(this.controller.model.customData);
      console.log(this.controller.model.get('customData'));
    },
  },
});
```

The initializer is triggered before all, so the `reopen` method is executed. In the model function, `record.customData` returns `undefined`. In the `submit` action, it's correct.

Is there something wrong ?

**Comment by stefanpenner** [comment]
Reopens after something has been instantiated, is largely an anti-pattern (it causes performance issues, tricky to solve (without more performance issues)). 

The way it works, is reopens are lazy, and only do "work" when something is instantiated, then the work is applied. This has been deemed ok, because we would actually love to move to a more static world, where after the first installation reopening is disabled. The later is still in early stages, and before anything happens (it may not) it will go through the RFC process.

Another approach, is as the es6 and es7 class syntax (+decorators) mature, we will be able defer all our extra model stuff to that system, allowing more native support for these sorts of features. Likely without some of the same downsides and caveats.

Sorry you encountered this strange quirk.

**Comment by GCorbel** [comment]
Thanks for answer! If I understand, there is no solution yet. Right?

**Comment by stefanpenner** [comment]
> there is no solution yet. Right?

Correct.

**Comment by GCorbel** [comment]
Sorry but I was wrong and it works.

I had to this : 

```
  model(params) {
    var record = this.store.findRecord('subscription', params.id).then((subscription) => {
      console.log(subscription.customData);
      console.log(subscription.get('customData'));
    });
    return record;
  },
```

It's obvious. The function is not on the promise !

Thanks again. I understand that's not a perfect solution but it works for now.
