### ISSUE TITLE
Accessing an array by index variable in a template

### ISSUE THREAD

**Issue by ctusch** [emberjs/ember.js#12980]
In a template I can access an array element with `{{array.[0]}}`. This works but somehow I can't use a variable as the index (e.g. `{{array.[index]}}`). There are other ways to solve my specific problem but I'm just not sure whether this is a bug or just a missing feature.

[Here is an Ember Twiddle.](https://ember-twiddle.com/675d3250a2ba9ab35e0b)

**Comment by rwjblue** [comment]
We prefer to keep this issue tracker for bugs in the framework, and use things like StackOverflow, Slack channels, etc for general questions.  This doesn't really seem like a bug to me, so I'm goign to close this for now.  Please link back to your question on SO so that others that find this issue can see your final resolution...

**Comment by ctusch** [comment]
It wasn't really a question. As I've stated I'm able to work around this issue. I just wasn't sure if this behavior was by design or actually a bug. Didn't find much about it in the docs either. Thanks for clarifying!
