### ISSUE TITLE
input cursor jumps to right and decimal sets value to zero when using property as query param

### ISSUE THREAD

**Issue by kybishop** [emberjs/ember.js#13023]
Ember twiddle showing the bug: https://ember-twiddle.com/2ea65490cb17b85366d6

**Comment by pixelhandler** [comment]
@kybishop the input with number type and step set to decimal does behavior strange. I cloned your example using a native number input here -> https://ember-twiddle.com/2ea65490cb17b85366d6

Maybe as work around you can use a native input[type=number] element and on focus out or change set the the property from the value of the input.

**Comment by mmun** [comment]
There are several things going on here that are interacting poorly:

- `typeof myValue` starts off as `number` which instruct the router to try to coerce the query param into a number whenever it can
- Internally, the `{{input}}` relies on `event.target.value` to read the current value of the number field. This is a problem because value is always a string! There is a separate property `event.target.valueAsNumber` that should be used in this case.
- Internally, `{{input}}` does a `===` check to see if the new value is different than the old value to avoid having the cursor jumping around. The check is failing because the value's type keeps switching between `string` and `number`.

**Comment by yohanmishkin** [comment]
Hey @kybishop ! We took a look at this issue on the latest Ember release and the kinks appear to be ironed out. 

[Here's a twiddle](https://ember-twiddle.com/f5e7d7f426a8e451aac60eba0b88a180?openFiles=application.template.hbs%2C) with the updated ember version (and also an idea of what an implementation might look like without the `{{input}}` helper two way binding approach).

Maybe we can consider closing this one out if you think it may no longer be an issue?

**Comment by pixelhandler** [comment]
@kybishop glad the newer version of Ember works :) - Closing
