### ISSUE TITLE
How do I access a service in an acceptance test?

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember.js#13046]
So, in my test, I'm testing if the user has successfully logged in.

[my whole test file](https://github.com/NullVoxPopuli/aeonvera-ui/blob/914dd9a1f6dae5b0d5ecc81373f5c8a5445b885b/tests/acceptance/login-test.js#L42)

Currently, I'm looking up the service via:
```
    let session = application.__container__.lookup('service:session');
```

but that's not an ideal way to get the session as `_` methods are private, and may be removed. 

My assert goes like this in my test, and I'm wondering if there is a better way to get the session?

```
  andThen(() => {
    let session = application.__container__.lookup('service:session');
    let auth = session.get('isAuthenticated');
    assert.equal(auth, true);
  });
```

**Comment by rwjblue** [comment]
In general, questions like this are better suited for Stack Overflow or the community slack channels.  The issue here is that there is no good way to do what you want, I have proposed an RFC to unify the various testing concepts and specifically address accessing services.  See https://github.com/emberjs/rfcs/pull/119 for more information.
