### ISSUE TITLE
Strip feature flagged docs from API docs.

### ISSUE THREAD

**Issue by toddjordan** [emberjs/ember.js#13101]
Features behind a feature flag still show up in official documentation, which can be confusing since they are not actually there for folks that don't enable them.

---

Support was added in #13105 to filter items with an `@category` tag when the given feature is not enabled by default. We need to extend that support for the following scenarios:
- [x] Remove class items
- [ ] Remove methods
- [ ] Remove properties

**Comment by cibernox** [comment]
My two cents here is that I was also bitten by this once. Is there any way in yuidoc to tag certain APIs with the version number (like the `@since 2.4.0`) and use that to 
a) Not show them unless you are in a version of the docs for that version or greater
b) Show them anyway but with a visual indicator of the version in which this became public.

**Comment by rwjblue** [comment]
Yep, I chatted with @toddjordan about this in slack, and I think we can have a YUIDoc preprocessor that is aware of the features.json, and "does the right thing".

**Comment by rwjblue** [comment]
Where the "right thing", is to not include the docs for features that are not enabled.

**Comment by HeroicEric** [comment]
Related to https://github.com/emberjs/ember.js/issues/12739

**Comment by rwjblue** [comment]
Some of this was addressed in #13105, but a few additional items are still needed. Updated description to include checklist.

@toddjordan - Do you think you might want to try and pick off adding support for those additional cases to the YUIDoc preprocessor?

**Comment by toddjordan** [comment]
Will do
