### ISSUE TITLE
Computed option selected attribute in IE is unreliable if option text content is modified at the same time

### ISSUE THREAD

**Issue by robbytx** [emberjs/ember.js#13172]
http://emberjs.jsbin.com/xobedisofi/edit?output
1. Open in IE 11 (reproduced in 11.0.9600.16428 on Windows 7 - from http://aka.ms/vagrant-win7-ie11)
2. Click "Reproduce"
3. First select box should show "A !== B"
4. Second select box (which uses option label attribute instead) should show "B === B"

I believe there is some problem related to updating the text node in the <option> element, which causes it to lose its selected state.

**Comment by robbytx** [comment]
Unfortunately, due to https://bugzilla.mozilla.org/show_bug.cgi?id=option-label, Firefox requires that we put the label in the option's text content, not in the label attribute.

**Comment by rwjblue** [comment]
I don't have a IE11 VM handy, but a **huge** amount of the underlying rendering engine has changed since this was reported.  I'm very sorry that we didn't get back to this in a timely manner, but at this point I _believe_ that it is addressed.

I'm happy to re-open and dig in if this is still an issue...
