### ISSUE TITLE
Deprecate usage of `{{render` helper with a model param.

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#13183]
This is always better written today as a component invocation, we should deprecate this.

Bad:

```hbs
{{render 'foo-bar' someModelThingy}}
```

```hbs
{{foo-bar model=someModelThingy}}
```

---

- [ ] AST transform to deprecate while compiling templates (to provide line number information)
- [ ] Add deprecation guide entry in emberjs/website

**Comment by cesardariogarcia** [comment]
@rwjblue I tried to solve this issue but I'm new to ember so I'm not pretty sure that i did it well,
could you check this changes to see if they are good to make a PR.
Or in defect I am open to any suggestion to achieve this, thanks :). 

https://github.com/cesardariogarcia/ember.js/commit/1f987180a7d4b8f16fa67ab6489b104f7ea28d40

p.s. I located the deprecated call in the validation because there is where the `{{render + model` comes in i think.
```
if (params.length > 1)
+      deprecate('Usage of `{{render` with a model param is deprecated, use `{{render "foo"} ` instead.', false, { id: 'ember-metal-views.renderer', until: '3.0.0' });
```

**Comment by sweatypitts** [comment]
I'll take a stab at this.

**Comment by rwjblue** [comment]
Awesome, thanks!

**Comment by sweatypitts** [comment]
@rwjblue  How's this look for a failing test? https://github.com/emberjs/ember.js/compare/master...sweatypitts:render-model-param-deprecation?expand=1
