### ISSUE TITLE
Ember core components should support other WAI-ARIA attributes

### ISSUE THREAD

**Issue by kboucher** [emberjs/ember.js#13224]
Currently only the `role` (`ariaRole`) attribute is supported in Ember core components. Various WAI-ARIA attributes are essential to providing a usable experience for impaired users.

For example using `link-to`:
```
    {{#link-to 'my-route' aria-label="This link will take you to some other route." title="Go to other route name"}}
        My Link Text
    {{/link-to}}
```
renders:
```
    <a id="ember1012" href="#/my-route" title="Go to other route name" class="ember-view">
        My Link Text
    </a>
```
Due to the number of WAI-ARIA attributes and their validity in various tags makes it difficult to suggest an exhaustive list. Perhaps any attributes with the `aria-` prefix added to a helper could just be rendered?

**Comment by pixelhandler** [comment]
@kboucher Nice work forming a solution #13265. I did see some discussion on Aria- use in this RFC, https://github.com/emberjs/rfcs/blob/angle-bracket-components/active/0000-component-unification.md Perhaps comment on that RFC as well. 

Since this ia a feature/enhancement request. See [CONTRIBUTING.md#requesting-a-feature](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature) which recommends creating an RFC Issue to request a feature/enhancement (no need for a PR with RFC, only an issue in the repo)

It may be a good idea to get the discussion going and address the concerns raised regarding performance too.

**Comment by sundered** [comment]
Because of the performance concern, I suggested a new API for this in the PR. It would be great if you guys could take a look and give your 2 cents.

**Comment by rwjblue** [comment]
Features are generally discussed in the https://github.com/emberjs/rfcs/ repository. You can create an issue there for feature requests or a pull request to propose a new feature.  I'm closing this issue (this isn't really a bug in the framework), but please follow up with an RFC issue/PR if you are interested in taking this further.

As mentioned in the PR, the RFC will need to wrestle with adding additional API surface here in the short-term (that likely has a negative performance impact) when we have a much better long term plan (with angle bracket components the invocation site can supply any attributes that it wants, and things will "just work").

I'm going to close this (and the PR) for now, please do open that RFC to flesh out further discussion....
