### ISSUE TITLE
didReceiveAttrs and friends from 1.13 not documented in API

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/ember.js#13244]
I would be willing to write and PR this but I am not sure which file the documentation belongs. It may be Ember.ViewTargetActionSupport?

**Comment by rwjblue** [comment]
I would add the documentation directly to `packages/ember-views/lib/components/component.js` for now.  When `Ember.GlimmerComponent` lands, we would potentially have to tweak that but it seems like a good starting point.

One thing to keep in mind, is that we do not want to document the arguments to these hooks (because we feel that the arguments are somewhat wrong/bad) so we just want to document the hooks themselves and their run order.
