### ISSUE TITLE
Enumberable reject does not behave as expected.

### ISSUE THREAD

**Issue by tyre** [emberjs/ember.js#13269]
I've made a [Twiddle](https://ember-twiddle.com/e0a991b56552b3b4712812c4260baa6b?fileTreeShown=false&openFiles=controllers.application.js%2C) to demonstrate the behaviour of `reject`.

**What is expected**: `reject` returns an array of all the items for which the provided callback did not return a truthy value

**What happens**: `reject` returns an array of all of the items for which the provided callback returned a falsey value

This is inconsistent with every implementation of `reject` I can think of (e.g. Ruby, Underscore.js). While that itself is not a reason to change its behaviour, the behaviour explicitly does the opposite of what it says it does. Rather than rejecting items which pass a test, it keeps ones which fail.

**Comment by rob-e-pitts** [comment]
`reject` is supposed to filter from the array all values for which the callback is true. It should give you the inverse result of `filter`. This is both the [specified](https://github.com/emberjs/ember.js/blob/v2.4.4/packages/ember-runtime/tests/suites/enumerable/reject.js#L12) and [actual](https://github.com/emberjs/ember.js/blob/v2.4.4/packages/ember-runtime/lib/mixins/enumerable.js#L437) behavior. I've made a [Twiddle](https://ember-twiddle.com/e0a991b56552b3b4712812c4260baa6b?fileTreeShown=false&openFiles=controllers.application.js%2C) which mirrors the example given in the Ruby docs to demonstrate the consistency.

Frankly, I don't like `reject` because it can be confusing; much in the same way that using Ruby's `unless` can be confusing. With `reject` you don't get the values that are "rejected", you get the values that remain after the rejected values are filtered out. I always recommend, for myself included, using `filter` and simply inverting the predicate. Much easier to reason about in my opinion.

**Comment by pixelhandler** [comment]
@tyre the docs do explain that `reject` returns the items where a falsey value is the result of the callback function. http://emberjs.com/api/classes/Ember.Array.html#method_reject

It appears the behavior is doing what the docs describe as well as the implementation and test as linked above by @robbiepitts 

Are you suggesting a feature change for reject?

> What is expected: reject returns an array of all the items for which the provided callback did not return a truthy value
>
> What happens: reject returns an array of all of the items for which the provided callback returned a falsey value

**Expected** "callback did not return a truthy value" and **Actual** "callback returned a falsey value" are the same thing, no?

**Comment by ndemonner** [comment]
This came out of a RecordArray problem where reject was returning totally unexpected results, but we can't seem to reproduce it, which means it was probably a predicate mistake on our end. This can be closed.
