### ISSUE TITLE
Observers don't fire when observing properties of injected objects

### ISSUE THREAD

**Issue by jakedetels** [emberjs/ember.js#13330]
When injecting an Ember object onto a class, any of the class' observers for properties of that injected object are not getting triggered when that observed property changes.  This seems to occur whether the injected object is injected via `application.inject()` or simply via importing that object via a regular `import` statement (followed by loading that imported object onto the class).

Here is a simple Twiddle that demonstrates the behavior: https://ember-twiddle.com/93316c9f541f5ad007e4a55eb4d5fbeb?fileTreeShown=false&numColumns=2&openFiles=controllers.application.js%2Ctemplates.application.hbs

Click the "Increment Counter" button and observe how the `counter` computed alias fails to update when the observed property is updated.

**Edit:**
Using Ember Twiddle's nice feature of changing the Ember dependencies, I notice that this issue occurs in Ember 2.4.4 (Twiddle's current default Ember dependency), but not in the release/beta/canary versions.  So it seems the simple fix is to upgrade to Ember 2.5.

**Comment by rwjblue** [comment]
Ugh. The issue here is left over cruft from when a property with an initial capital letter meant "global".  

[Working version of the twiddle](https://ember-twiddle.com/05202899e75f011baf12cefcbf8c3060?fileTreeShown=false&numColumns=2&openFiles=controllers.application.js%2Ctemplates.application.hbs).

Also, good news that @mmun fixed that issue in 2.5 (see https://ember-twiddle.com/65ecc4eddbe686be18480d6b5d2b491f?fileTreeShown=false&numColumns=2&openFiles=controllers.application.js%2Ctemplates.application.hbs)

**Comment by jakedetels** [comment]
Thanks @rwjblue.  Nice to know there's a simple fix that will work in older Ember versions.
