### ISSUE TITLE
event.relatedTarget aways null in focusOut

### ISSUE THREAD

**Issue by villander** [emberjs/ember.js#13428]
focusOut handle events to components aways return null in `event.relatedTarget`

```
focusOut(event) {
  console.log(event.relatedTarget); // awayas null.
}

```

My jsbin just with jquery the `relatedTarget` works

https://jsbin.com/ruqahezaxa/edit?html,js,output

**Comment by locks** [comment]
Do you have a reproduction of the non-working Ember.js code?

**Comment by pixelhandler** [comment]
@villander Here is an example reproduction with Ember: https://ember-twiddle.com/42872f96a56b79bb71e2230fb21ab0ed?openFiles=components.x-input.js%2Ctemplates.components.x-input.hbs

Note that the relatedTarget can be null. The jQuery docs mention using mouse events rather than focus events, see http://api.jquery.com/event.relatedTarget/

In the example above you'll need to open the console to see what is logged. The `mouseLeave` event does have the `relatedTarget` and the `focusOut` does not.

For the list of Ember Events see: https://guides.emberjs.com/v2.5.0/components/handling-events/

I will close this issue out for now, it does not appear to be any bug in Ember.js.

If you would like to discuss more perhaps ask in the http://embercommunity.slack.com group in the #-help channel. Typically the community can be very helpful and you'd get quicker feedback in the chatroom than on the issue tracker.

**Comment by villander** [comment]
@pixelhandler  you are very wrong. look my example where `focusout` has `relatedTarget`

https://jsbin.com/ruqahezaxa/edit?html,js,output
