### ISSUE TITLE
Observer not working when using component Helper after one time

### ISSUE THREAD

**Issue by fahian** [emberjs/ember.js#13469]
When we use component helper instead of directly using component name then the observer is not working after 1st usage.

Here is a JSBin link for a demo of the issue. http://jsbin.com/sefubazika/edit?html,js,output

Here is a JSBin link for a demo of the same code without component helper (directly using component name) where the observer works http://jsbin.com/cemavoqifo/edit?html,js,output

**Comment by Serabe** [comment]
I cannot reproduce it in 2.5 (see this [twiddle](https://ember-twiddle.com/3a82e7d6f539a21435d63b10228be3de?numColumns=2&openFiles=templates.application.hbs%2Ctwiddle.json)). Your example is in 1.13 which is not currently supported. Can you please try to reproduce your problem in 2.5 or LTS?

Thank you!

**Comment by jordpo** [comment]
The issue seems to be more related to the view Ember.Select vs the component helper. I am rendering `facility.firstObject.id` in the below JSBin and you can see that it updates correctly when you toggle the `selectedMarket`.

http://jsbin.com/qawopolimu/edit?html,js,output

Since Ember.Select is now [deprecated](http://emberjs.com/api/classes/Ember.Select.html), I suggest using one of the add-ons out there.

http://discuss.emberjs.com/t/ember-select-is-deprecated-what-should-we-use-now-instead/8613

**Comment by MiguelMadero** [comment]
The issue seems to be that the `selection` and `value` properties aren't raising propery change notifications since they are setup a bit earlier in the view's lifecycle than what they did in previous versions like 1.12. We worked around it using the following code from an initializer: 

```

Ember.Select.reopen({
		didRender() {
			this.notifyPropertyChange('value');
			this.notifyPropertyChange('selection');
		}
	});
```

Hope this helps.

**Comment by pixelhandler** [comment]
@MiguelMadero thanks for posting the `didRender` method to use `notifyPropertyChange` This seems like a viable way to work around.

As @Serabe mentioned v1.13 no longer has any planned patch releases, so it's unsupported at this point.
