### ISSUE TITLE
Actions do not fire on elements that are not inside `App.rootElement`

### ISSUE THREAD

**Issue by fivetanley** [emberjs/ember.js#13513]
There are a few use cases for this that I could think of:
- Your app has a `rootElement` that is not `body` and your modal implementation/popover implementation uses `body` as its parent element.
- Your app has a `rootElement` that is body, but your modal implementation/popover implementation must be rendered in the body to work correctly for styling/accessibility/etc. This means that when you have a `rootElement` of `#ember-testing` in testing, you can't test the integration with your ember app (via `{{action}}`/etc) because those events are only handled if the element is a child of the `rootElement`.

The reason for only listening on `rootElement` passed to `Ember.EventDispatcher` was to account for multiple apps.

Talking with @krisselden and @rwjblue, it sounds like we should only ever have one instance of the `EventDispatcher`, even in the multiple app scenario. This singleton `EventDispatcher` should always be listening on the document.

**Comment by krisselden** [comment]
@fivetanley correction, one per document, if we should support visit() being passed a different document or iframe.

The view registry is also something that belongs on the dispatcher, since ids are supposed to be unique per document and it is to support the dispatcher that it exists.

**Comment by RobIsHere** [comment]
I have an app that is included in unknown customer's sites. Integration should "just work". 
So i don't know if i can use ember-wormhole or others, docs say no because of this issue.

When i built it, i faced 3 things:
* the issue here. actions on wormholed stuff will not work according to docs.
* namespacing of the applications code and url (works great!)
* namespacing of the css (works for application using sass and css class, but not in "content-for")

Two thoughts about the single event dispatcher:
* it must work with all old and future ember versions. E.g. my app is integrated on the same page with some other 3rd party ember app, that uses a different Version.
* it does not solve the css namespacing problem. imagine both applications using ember wormhole. i didn't try it. last included css wins? so css should be namespaced to. At the moment i use sass where it is easy to wrap everything in a css class, even dependencies. But that would be a good ember-cli feature.



So i would prefer solving all issues at once and wrap content-for in a separate div by default:
```
<div id="ember-body-app1" class="namespace-class-of-app1 content-for-body">
    content-for goes here
</div>
<div id="ember-body-footer-app1" class="namespace-class-of-app1 content-for-body-footer">
    content-for goes here
</div>
```
This way not only dispatchers can be attached properly there at the "local parent div" but it is also possible that your own wormhole modal component does not take styles of the other unknown app by chance.

I'm at the moment not using wormhole-like things at all. But it would be a big win for my application architecture because the workarounds are ugly in terms of separation-of-concern and that gets messier the bigger the app grows.



Let me seize the opportunity to say: you are doing a great job with ember! It is so well-structured and thought-out! A joy to use it!

**Comment by pixelhandler** [comment]
@fivetanley @krisselden is this still an issue, perhaps we should close, what do you think?

**Comment by pixelhandler** [comment]
Per our triage policy I'll close this out for now, feel free to reopen if the issue persists on the current release.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
