### ISSUE TITLE
Best Practice: Components, Templates or Partials

### ISSUE THREAD

**Issue by adhamhf** [emberjs/ember.js#13559]
Hello,

I don't understand when I should use a component, a template or a partial.  Is there any guidance on this from the ember core team?

Thanks!

**Comment by Serabe** [comment]
Hello, @adhamhf. I am closing this since it is not an Emberjs bug. Please, go to #-help channel on Slack. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

Furthermore, the official guides can be found in [guides.emberjs.com](https://guides.emberjs.com/v2.5.0/). In the sidebar you will notice there are one section for [Templates](https://guides.emberjs.com/v2.5.0/templates/handlebars-basics/) and another for [Components](https://guides.emberjs.com/v2.5.0/components/defining-a-component/). If you find any information incorrect or lacking, please, report it in the [guides repo](https://github.com/emberjs/guides).

Thank you!

**Comment by adhamhf** [comment]
@serabe. Slack is pretty bad at this type of question.  It's great for some use cases like "how do I do foo". But for complex explainations it leaves a lot to be desired.

The guides explain "how to" but not "when to". And then they don't explain partials at all.

**Comment by Serabe** [comment]
You can try http://discuss.emberjs.com/ if you want a forum to ask an open question.
