### ISSUE TITLE
Loading substate and aborting transition

### ISSUE THREAD

**Issue by yonjah** [emberjs/ember.js#13586]
When a lazy route request is rejected and the transition is aborted (wither explicitly by the user or automatically) the loading substate is not removed.
demo - 
https://ember-twiddle.com/af5acf8f27cc56fee7216e588126a8d0

Since the UI has changed without changing any of the browsing history using `history.back` is irrelevant so it is extremely hard to navigate the user back to the original route he came from.

**Comment by pixelhandler** [comment]
@yonjah If I have to cancel a transition I typically store the page the user is on in local/session storage. then use [intermediateTransitionTo](http://emberjs.com/api/classes/Ember.Route.html#method_intermediateTransitionTo) to re-route the user to where they left off.

I don't this is a bug in Ember it's just the nature of what an app should do when a transition is aborted. If the app does nothing to recover then that makes sense that a substate template remains on screen for the user.

Have you ask about problem in the Ember community slack channels, on the forums or Stack Overflow?

What is the expected behavior you were anticipating from the aborted transition?

**Comment by yonjah** [comment]
@pixelhandler  please notice I don't try to cancel the transition. the transition fails.
I think there are actually two bugs in the way the transition is handled -

1. when loading fails the loading substate should be terminated (stop displaying the loading indicator)

2. changing route should change the URL and history state of the browser, I can understand why Ember doesn't want the loading substate to be stored in history but when the loading substate is entered the URL should indicate the final route of the transition and not the previous one. 

the first issue is not to critical and can be solved now by having an empty error template, but I think that Ember should be smart enough to know the loading substate has ended and should be removed from DOM

The second issue is much more critical since it breaks the use of the browser history. If it's too hard to solve properly then the minimum fix should be changing the url when loading fails and moving from the loading substate to the  error substate (and not only when loading succeeds and your moving to the controller).

Think about the user that is seeing the error page and now want to click his back button and go to the previous page that wont work with the current behavior. Think about a regular web page (not a SPA) you click a link the url changes and the page starts to load if loading fails or if you decide you don't want to wait you click the back button and you go back to the page you came from.

**Comment by pixelhandler** [comment]
@yonjah Ember does have a mechanism for handling failure already, also its up to the developer to use it.

> 1. when loading fails the loading substate should be terminated (stop displaying the loading indicator)

If loading fails there is the error-substate, the app needs to define the template for that error-substate. At the top level there is template/application-error.hbs which needs to be generated. In addition to the [guide page](https://guides.emberjs.com/v2.6.0/routing/loading-and-error-substates/#toc_code-error-code-substates), here is an article on the topic of [using error substates](https://pixelhandler.com/posts/emberjs-handling-failure-using-route-error-substates).

> 2. changing route should change the URL and history state of the browser, I can understand why Ember doesn't want the loading substate to be stored in history but when the loading substate is entered the URL should indicate the final route of the transition and not the previous one.

To propose a change in the router, again this is not a bug, there is a process involving RFC issues or proposals. This issue tracker is specifically used to track bugs in Ember.js

**Comment by yonjah** [comment]
@pixelhandler maybe I haven't made the issue clear .

If user goes from page A to B but B loading is failed and the user gets an error page, clicking the back button will actually take the user to the page he was before A (since from history perspective he is still on page A).

**Comment by pixelhandler** [comment]
@yonjah it may be worth raising some discussion in the embercommunity.slack.com chat regarding:

> If user goes from page A to B but B loading is failed and the user gets an error page, clicking the back button will actually take the user to the page he was before A (since from history perspective he is still on page A).

I'm curious if someone has a workaround or a solution for utilizing the history in an error substate.

My thoughts are that the error.substate route could use [intermediateTransitionTo](http://emberjs.com/api/classes/Ember.Route.html#method_intermediateTransitionTo) via [activate](http://emberjs.com/api/classes/Ember.Route.html#method_activate) event or alternatively no error substate an using the `error` event with `intermediateTransitionTo` ensure that the user is taken to page A instead of the page before A
