### ISSUE TITLE
inline `if`s shouldn't eagerly eval their inverse arg

### ISSUE THREAD

**Issue by machty** [emberjs/ember.js#13589]
`{{if falsy (some-helper)}}` should not eval `some-helper`, but it does, which can be annoying when you want to check the presence of some property before passing it to a helper that'll barf if the prop is falsy.

https://ember-twiddle.com/b06224282690fe6e61c4d16f6fb05aa1?openFiles=controllers.application.js%2C

**Comment by machty** [comment]
Updated the twiddle to also include an example of a CP that also shouldn't be eagerly read.

**Comment by chancancode** [comment]
I believe the glimmer version does not have this problem, I can write a
test to verify

**Comment by pixelhandler** [comment]
@chancancode should this issue be labelled "Glimmer 2" if the resolution is for that to land?

**Comment by chancancode** [comment]
Hmm, this probably needs to have the opposite of that tag (htmlbars/glimmer
1).

There is no reason why this cannot be fixed on the current implementation -
if this is urgent and someone has the cycles and know-how to fix it, I
think we would accept that patch. On the other hand, if this is still open
by the time we land glimmer 2, we can just close it since that issue
doesn't exist there.

**Comment by rwjblue** [comment]
> There is no reason why this cannot be fixed on the current implementation - if this is urgent and someone has the cycles and know-how to fix it, I think we would accept that patch.

Agreed.  Definitely welcome a patch, but that seems unlike at this point (though I'm happy to be wrong here).

> if this is still open by the time we land glimmer 2, we can just close it since that issue doesn't exist there.

I'm inclined to close now....
