### ISSUE TITLE
controller action returning a promise does not bubble up

### ISSUE THREAD

**Issue by sergproua** [emberjs/ember.js#13654]
I have a basic controller and a route both have action submit, I'm trying to keep validation of the model inside component/controller and transitions in route action. 
```
export default Ember.Controller.extend({
  actions: {
    submit() {
      return new Ember.RSVP.Promise(function(resolve) {
        // ... perform validation and bubble up if succeeds
        // ...this.validate().then(() => {resolve(true)});
        resolve(true);
      });
    }
  }
});

export default Ember.Route.extend({
  actions: {
    submit() {
        console.log('we are here, bubbling works!'); 
        return this.currentModel.save();
    }
  }
});
```
I've solved this by calling ```this.send('submitRoute');``` from a controller, note that using the same action name causes infinite loop. Is there a better pattern to accomplish this?

Thanks,
Serge

**Comment by Serabe** [comment]
Hello, Serge. I am closing this since it is not an Emberjs bug. Please, go to #-help channel on Slack. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

For this, I would use a mix of [closure actions](http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_action) and the [ember-route-action-helper](https://github.com/DockYard/ember-route-action-helper). You can find [here an article](https://dockyard.com/blog/2015/10/29/ember-best-practice-stop-bubbling-and-use-closure-actions) on substituting bubbling for closure actions.

Thank you!
