### ISSUE TITLE
this.render and this.disconnectOutlet stopped working in 2.6.0

### ISSUE THREAD

**Issue by KrisOlszewski** [emberjs/ember.js#13670]
Hi there!

First of all thank you for an amazing work with Ember and its ecosystem, you guys are awesome!

Today I've updated my application to `2.6.0` ( together with Ember-CLI, as well as, Ember Data). However, after some testing, I've noticed my dialogs (modals) stopped working on consecutive action.

**Example:**

- user clicks on button to show modal via `this.render`
- user selects yes or no and component sends action with user's decision
- modal is closed via `this.disconnectOutlet`
- user attempts to open modal again and... **nothing happens** 

Here is a Twiddle with replicated issue: https://ember-twiddle.com/ff0aa621c1fde10858b4cc4f1fb62072 As you can see you cannot render dialog component multiple times.

Any help would be much appreciated, thanks!

**Comment by krisselden** [comment]
After the initial render, there is no outlet state for dialog, when you open the dialog, it initializes it, at this point we take the isEmpty() path for the outlet.  The disconnectOutlet() method does not set it back to empty, but sets it to a state that has only "into", "outlet", "name" with no template key.  When you try to open the dialog again, "template" is the only key that is different, but since isStable(old, new) only loops over the old keys, it will never check the template key.

I'm not sure which part of this was changed to regress this.

**Comment by KrisOlszewski** [comment]
@krisselden thank you for looking into it and fixing!
