### ISSUE TITLE
Action Bubbling documentation is missing in Getting started guide

### ISSUE THREAD

**Issue by lokeshkumar** [emberjs/ember.js#13687]
Documentation for preventing Action bubbling is not available in the current ember Getting started guide.

Please refer the below old documentation link
https://guides.emberjs.com/v1.10.0/templates/actions/

And the new documentation link
https://guides.emberjs.com/v2.6.0/templates/actions/

Please have a look and update the same in the new documentation.

Thanks in advance.

Regards,
Lokesh

**Comment by locks** [comment]
Hi @lokeshkumar, issues related to the Guides should be filed at their specific repository: https://github.com/emberjs/guides.

However, this behaviour is on purpose. We moved the Guides to use closure actions (as opposed to classic actions) because they provide better semantics, more functionality, and they cover all the use cases of classic actions. Closure actions don't bubble, so that documentation is unnecessary. On top of that, classic actions are documented in previous versions of the Guides as you point out.

We are not changing this soon, but we have improvements for actions guides planned. It's tricky documenting both styles of actions in the guides without making them confusing, so we're still elaborating a plan.

Thank you for the feedback :)
