### ISSUE TITLE
undefined behavior for nested brace expansion

### ISSUE THREAD

**Issue by kellyselden** [emberjs/ember.js#13693]
I've come across some code that _could_ use nested brace expansion. I tried it out manually first and got this:

```
Ember.expandProperties('first.{second1,second2.{third1,third2}}', echo);
first.second1third1
first.second1third2
first.second2.third1
first.second2.third2
```

I've read [this](https://github.com/emberjs/ember.js/pull/13231#issuecomment-204632269) which hints that it was discussed or decided to not support. If it is unsupported, perhaps it should error, like when you put a space in. Or maybe it just needs a regex update to fully support it? It could make computeds further collapsable.

**Comment by pixelhandler** [comment]
@kellyselden do you know if there are any tests for "nested" brace expansion in the project?

I only found this one: https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/tests/computed_test.js#L461-L482

Also are there any docs on nested brace expansion? I found https://guides.emberjs.com/v2.6.0/object-model/computed-properties/#toc_computed-properties-in-action

My thoughts are that to support "nested brace expansion" we'd need some tests and docs. Maybe the way is to answer the question "Is it supported?" is to start with adding a test that clearly makes it **unsupported**, since there are no tests or docs nesting.

However, that does seem like an edge case. If there are no docs or tests that indicated you could use "nested brace expansion". Even simpler - update in the guides to indicate that nesting braces in a computed property is not supported.

Alternatively - like using spaces is not supported with brace expansion, https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/tests/computed_test.js#L484-L491 It may be a good idea to have a test and assertion that a computed property cannot use "nested brace expansion".

**Comment by pixelhandler** [comment]
@rwjblue @locks is there any undocumented consensus on supporting nesting in brace expansion?
