### ISSUE TITLE
Fix links to Ember Inflector source code in API docs

### ISSUE THREAD

**Issue by locks** [emberjs/ember.js#13767]
Original issue: https://github.com/emberjs/guides/issues/1538#issue-162357683
Submitter: @thomascchen

**Comment by lucasqiu** [comment]
I'd like to submit a PR for this if appropriate. 

@locks  Should the fix be made here or https://github.com/emberjs/website/ ?

**Comment by locks** [comment]
@lucasqiu here, the documentation is in the source code :) Thanks for the interest!

**Comment by Serabe** [comment]
@lucasqiu: are you still interested on submitting a PR for this? If you need some help, you can ping me in Slack (same nick).

**Comment by etseidler** [comment]
@Serabe it looks like the existing link is pointing to a node_modules folder in ember data that doesn't exist in the source code. also, the ember-inflector class is now a dependency. are you sure the change needs to be made in the ember.js repo? it looks like it might be the data repo which needs the update, even though I haven't figured out exactly where the change needs to happen. also, what's the best way to make the source code links point to another repo, since the ember-inflector source is in a separate repo. i'm a real n00b, so let me know if i'm way off here. i'll try to join the slack channel sometime today.

**Comment by pixelhandler** [comment]
@locks @lucasqiu @etseidler is this still an issue, perhaps we should close; what do you think?

**Comment by etseidler** [comment]
from some quick testing, it seems like the issue still does exist. however, it also seems pretty low-priority and this particular thread has been dormant for almost two years. my take is that it should be closed.

**Comment by pixelhandler** [comment]
thanks @etseidler :)
