### ISSUE TITLE
Ember.Test.wait() documentation example outdated

### ISSUE THREAD

**Issue by Turbo87** [emberjs/ember.js#13793]
Currently the API docs of `Ember.Test.wait()` suggest to return it from an async test helper, but according to @rwjblue and the guides this shouldn't be necessary anymore.

**Comment by Turbo87** [comment]
https://github.com/emberjs/website/commit/c5a577a162ad8e221420f4efe4a24626071cd59e removed the `wait()` call from the guides.

**Comment by pixelhandler** [comment]
@Turbo87 so yeah the guides suggest the use of `andThen` see https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/helpers/and_then.js 

I am curious about creating custom async helpers, It seems that this syntax in the `wait` example is still useful https://github.com/emberjs/ember.js/blob/v2.8.2/packages/ember-testing/lib/helpers.js#L150-L156 - especially since that is how the `andThen` helper is implemented.

**Comment by pixelhandler** [comment]
@rwjblue can you confirm that this line should be removed `return app.testHelpers.wait();`:

https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/helpers/wait.js#L26

```js
  ```javascript
  Ember.Test.registerAsyncHelper('loginUser', function(app, username, password) {
    visit('secured/path/here')
    .fillIn('#username', username)
    .fillIn('#password', password)
    .click('.submit')
-    return app.testHelpers.wait();
  });
```
