### ISSUE TITLE
$.trigger does not trigger component actions.

### ISSUE THREAD

**Issue by martndemus** [emberjs/ember.js#13888]
The test suites of `ember-one-way-controls` and `ember-form-for` will not pass on `canary` and `2.8.0-beta`.

An example of what is failing: https://github.com/martndemus/ember-form-for/blob/master/tests/integration/components/form-field-test.js#L156-L164

Specifically this does not seem to trigger actions on components anymore:
```js
this.$('input').trigger('change');
```

Using `git bisect` I found that https://github.com/components/ember/commit/9cff2f835ded50346359ee5aaa3fbfadf8479843 is the commit that introduces the bug, which I think corresponds to this commit: https://github.com/emberjs/ember.js/commit/2a233df8c6aa387898299d79dd4b2965b4266015

**Comment by pixelhandler** [comment]
@martndemus I'm curious, in `this.$('input').trigger('change');` an action named `change` should be triggered? Or, an event handler named `change` (not an action)? I thought `trigger` is a jQuery method that fires events.

**Comment by rwjblue** [comment]
The issue would likely be (based on the bisect result) that the event dispatched cannot find the component that is created, so it doesn't delegate the event to it. I'll try to dig in more this morning.

**Comment by mike-north** [comment]
worth mentioning that it seems this only occurs during testing. When apps are run normally, everything seems to work as one would expect

**Comment by martndemus** [comment]
It is very probable that this is a bug with test tooling working on old View API, that the found commit has broken.

**Comment by pixelhandler** [comment]
@martndemus Just curious is this post https://dockyard.com/blog/2016/07/26/how-to-bisect-ember about this issue?

**Comment by martndemus** [comment]
Yes, the blogpost describes how I found the commit that causes the bug.

**Comment by acorncom** [comment]
@martndemus Would it be possible to get a Twiddle showing a reproduction?

**Comment by alexlafroscia** [comment]
I tried making a Twiddle [here](https://ember-twiddle.com/f03083ff45820e6439dfe2a74ece920c?openFiles=components.my-component.js%2Ctemplates.components.my-component.hbs) but for some reason the whole test thing shows up blank  ¯\_(ツ)_/¯

**Comment by alexlafroscia** [comment]
Seems to be a [bug in Twiddle](https://github.com/ember-cli/ember-twiddle/issues/468)

**Comment by martndemus** [comment]
@acorncom Reproduction is: clone https://github.com/martndemus/ember-form-for/commit/206cc307740bfa07de6eee48cebbca14839651eb and run `ember test`

**Comment by alexlafroscia** [comment]
You can see the same problem on the `master` branch of Ember AJAX right now too.

**Comment by rwjblue** [comment]
This is definitely an issue with an interaction between the change that @martndemus pointed out and the way ember-test-helpers sets up the event dispatcher. Ultimately, this causes the event dispatcher gets the event but can't identify which view it should be triggering. 

I'll try to get a fix together in time for the next beta.

**Comment by rwjblue** [comment]
I did a bit more digging and believe that we have this fixed with https://github.com/switchfly/ember-test-helpers/pull/167 (released in ember-test-helpers@0.5.28) and https://github.com/emberjs/ember.js/pull/13970/commits/ffc29cd237613507e915c7cf9972ef8dd3b16453 (which is cherry-picked into beta branch).

The basic issue is that since the `Ember.Aplication` and `Ember.ApplicationInstance` split there was no good way to execute the registry setup steps that existed in `Em.ApplicationInstance`.  `ember-test-helpers` uses `Ember.Application.buildRegistry` to create the registry/container/owner setup that is used in unit and integration tests, but since there was no way to perform the `Em.ApplicationInstance` registry setup steps we were missing some key injections.

Submitted https://github.com/martndemus/ember-form-for/pull/79.

**Comment by martndemus** [comment]
Can confirm this is fixed now. Closing the issue!
