### ISSUE TITLE
[Glimmer2] isVisible not implemented

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#13901]
__Failing Tests__: [should toggle visibility with isVisible](https://github.com/emberjs/ember.js/blob/f4bf04d75a898232aadff82ec79c8682ecdc2eea/packages/ember-glimmer/tests/integration/components/curly-components-test.js#L2622-L2652), [isVisible does not overwrite component style](https://github.com/emberjs/ember.js/blob/f4bf04d75a898232aadff82ec79c8682ecdc2eea/packages/ember-glimmer/tests/integration/components/curly-components-test.js#L2654-L2687)
__Knowledge__: Understanding of ComponentManager

Current the style attribute is not being merged with a property on the component object.

**Comment by sandstrom** [comment]
cc @chancancode 

I think this will cause issues with [CSP](https://www.w3.org/TR/CSP2/) (unless `unsafe-inline` is set).

I've always wondered by the `isVisible` stuff is needed on views/components? Perhaps it can be skipped or deprecated.

If it need to remain I'd suggest setting the property directly on the DOM node instead of [using an attribute](https://github.com/emberjs/ember.js/commit/a9f5d3915449f199f490485e4373a356d5fea1cb#diff-400da4a3c429c9e5a3a1cea5b9cf1131R97), since it won't trip up CSP.

```js
myElement.style.display = 'none';
```

*Just saw this and thought I'd drop a note. Feel free to ignore this (or correct me) if I'm wrong!*

**Comment by chancancode** [comment]
This is done in #13914

@sandstrom if you never set it to `false`, nothing will be added. We can come back to the rest later!
