### ISSUE TITLE
Array Parameters issues

### ISSUE THREAD

**Issue by git-neelesh** [emberjs/ember.js#13916]
Hi Team,

I come across through a issue for url which having prams as an array. eg: 

> http://url/page?params[test][]=10&params[test][]=20&params[demo][]=ABC etc...

Any idea or support in future?

**Comment by Serabe** [comment]
Hello, @git-neelesh!

Can you please provide us with a [ember-twiddle](ember-twiddle.com) of what is your expected usage? That way we can check if it is a bug or should go through an RFC process.

Thank you!

**Comment by git-neelesh** [comment]
Hi @Serabe,

I'm not getting  ember-twiddle means. I was expecting if I print prams it should parse like this.
Req: params[test][]=10&params[test][]=20&params[demo][]=ABC
```

Output: 
params : { 
   test: {
      [0] : 10,
      [1] : 20
  },
  demo:{
      [0] : "ABC"
   }
}
```

**Comment by pixelhandler** [comment]
@git-neelesh see https://ember-twiddle.com it's a great way to create an example of an issue you find in an ember app. Alternative you could just create a repo and share that as well. having a code reproduction of our issue helps others to debug it.

**Comment by git-neelesh** [comment]
Thanks @pixelhandler, I did not ask in ember community, I'll do it.

**Comment by pixelhandler** [comment]
@git-neelesh I don't see any example in the guides for using an array as the query param value, see https://guides.emberjs.com/v2.7.0/routing/query-params/ 

I'll close this issue for now since it's not an Ember Bug, but more of a question for the community. See http://emberjs.com/community/ perhaps followup on Stack Overflow, the Discus forums or the ember slack channels.
