### ISSUE TITLE
2.7.0: Change in namespace from ember-metal/streams to ember-htmlbars/streams break compatibility

### ISSUE THREAD

**Issue by ffaubry** [emberjs/ember.js#13917]
At 2.6.x, streams/stream and streams/utils were defined under ember-metal.
At 2.7.0, these modules have been moved under ember-htmlbars.
This is breaking backward compatibility for some addons such as:
- https://github.com/jamesarosen/ember-i18n
- https://github.com/DavyJonesLocker/ember-cli-i18n (apparently marked as dying...)

These addons should have never used these private modules. However, they did it and now existing apps using these addons are broken when migrating from 2.6 to 2.7.

Even if using private modules is NOT recommended, can we release the ember lib with also deprecation/migration path for private modules?

I will log issues in the addons above. However, it will take time for all these addons to fix this issue. I'm not even sure how they will fix it without breaking their own backward compatibility (I may be naive here).

**Comment by Serabe** [comment]
Hello @ffaubry:

`ember-cli-i18n` was deprecated one year ago. Regarding `ember-i18n`, latest commit in master is already loading the streams from htmlbars if they are not found under `ember-metal` (you can see it [here](https://github.com/jamesarosen/ember-i18n/blob/a0d053b478d333441b099020a1220b3ad118b9e1/addon/stream.js)).

Can you please open an issue in those addons that are not working in ember 2.7 because of this internal change? The previous link shows how the addon can load one or the other depending on which module is available.

Please, understand that using private APIs is not only not recommended but not maintained and subject to change at any moment.

Since this is not an Ember.js bug, I am closing it.

Thank you for your report!

**Comment by ffaubry** [comment]
Thx @Serabe.
I logged an issue under ember-i18n (see reference above).
