### ISSUE TITLE
Loading states behaviour doesn't match documentation

### ISSUE THREAD

**Issue by urbany** [emberjs/ember.js#13922]
Hi, If I understand correctly, according to [the documentation](https://guides.emberjs.com/v2.7.0/routing/loading-and-error-substates/), if I have a `templates/loading.hbs` file all slow models will default to that template if no better match is found.
This does not seem to be happening, please check this example, where `templates/loading.hbs` is used for the first route `my-account` but in the next route `my-account/services` it is not used anymore (and I think the docs say it should be used)

https://ember-twiddle.com/2e8848e5a2fa3e912fcbfbbf211fe5bd

**Comment by teddyzeenny** [comment]
I think it's because `my-account.hbs` has already rendered when you try to access `my-account/services` so it probably won't remove the already rendered parent (`my-account`) to show `loading.hbs`.

Notice you can see the `loading.hbs` template when you try to access `my-account/services` directly from the homepage. Try adding a link directly to `my-account/services` in `index.hbs`.

**Comment by urbany** [comment]
@teddyzeenny thanks for the quick response. I tested with a direct link like you are suggesting and surely it worked. But shouldn't the desired outcome be to display `templates/loading.hbs` in all scenarios?
Also it seems to me the way it works right now, the `before route` determines the loading page for the route being transitioned to, which seems weird, because each route should know how to display it's loading page independently of the route before.

**Comment by pixelhandler** [comment]
@urbany these is not really a default `loading` template for any route, it depends on your routing structure in your app and where you place your `loading` templates and whether or not you handle a `loading` event

>  But shouldn't the desired outcome be to display templates/loading.hbs in all scenarios?

No, the leaf routes are children (of a parent route) and would not use a 'loading' template above their parent but instead would use a loading route that is a sibling. 

> I think it's because my-account.hbs has already rendered when you try to access my-account/services so it probably won't remove the already rendered parent (my-account) to show loading.hbs.

@teddyzeenny is correct once the parent is rendered there is no need to replace it with a loading templates since its already loaded.

> Also it seems to me the way it works right now, the `before route` determines the loading page for the route being transitioned to, which seems weird, because each route should know how to display it's loading page independently of the route before.

Each route does know how to display a "loading" template if there is one available. It seems that to utilize more loading states more loading templates are needed through the route hierarchy.

The structure and resolution to render a loading template depends an your app needs. The framework just has a simple pattern so you can utilize a loading template. 

Perhaps your example could use a my-account-loading.hbs and/or my-account/services-loading.hbs too. See https://ember-twiddle.com/531313d370d8327298b45cef3c7bd94b

I'll close this out for now since it's not an Ember Bug. Please reach out in the https://embercommunity.slack.com #-help channel if you have more questions on the loading template behaviors.
