### ISSUE TITLE
[Glimmer 2] Component Integration Tests

### ISSUE THREAD

**Issue by dfreeman** [emberjs/ember.js#13963]
In a freshly-minted app using the Ember alpha released today, integration tests fail.

Here's a [repo reproducing the issue](https://github.com/dfreeman/glimmer-integration-failure), which just followed these steps:

```bash
ember new test-app
cd test-app
bower install -S ember#alpha
ember g component-test fails
ember test
```

**Comment by rwjblue** [comment]
I fixed the direct issue reported here in #13970 and https://github.com/switchfly/ember-test-helpers/pull/167, but the reproduction steps are still an issue due to the way top level outlets are being used by ember-test-helpers.

**Comment by rwjblue** [comment]
More work being done in:

* https://github.com/emberjs/ember.js/pull/13980
* switchfly/ember-test-helpers#168

**Comment by rwjblue** [comment]
With the changes from ember-test-helpers@0.5.29 a basic `this.render` should be working (submitted https://github.com/dfreeman/glimmer-integration-failure/pull/1 to the test repo).

A generic `ember g component x-foo` will still fail due to the lack of support for `this.clearRender()` in ember-test-helpers at the moment (still working on that).

**Comment by rwjblue** [comment]
As of ember-test-helpers@0.5.30 `ember g component it-works` passes without change.  

I'm going to consider this finished (though please chime in if there are issues and I'll reopen).
