### ISSUE TITLE
[Templating] UndefinedLiteral Coerced To Null

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#14016]
Currently in both rendering engines UndefinedLiterals are coerced to `null`. This seems incorrect, however there may be application code that is dependent on this incorrectness, which may lead to non-obvious breakages.

__Example:__

```
{{foo-helper undefined}}
```

```
function fooHelper(params, hash) {
  assert(params[0] === null);
}
```

This issue is a placeholder to see if anybody is surprised by this or has code that coerces `null` back into `undefined`.

**Comment by mitchlloyd** [comment]
I was surprised by this recently when writing a helper test to handle `undefined` values. I had to use `{{my-helper nothing}}` instead of `{{my-helper undefined}}`. Now I know why :)

My vote would be to change the behavior to pass the expected `undefined` value. Although it _could_ be breaking, relying on `{{foo-helper undefined}}` being coerced to null would most likely be an accident.

**Comment by chadhietala** [comment]
@mitchlloyd This is my predicament as well.

**Comment by pixelhandler** [comment]
@chadhietala does https://github.com/tildeio/glimmer/issues/252 resolve this issue?

**Comment by chadhietala** [comment]
No waiting on https://github.com/tildeio/glimmer/pull/255

**Comment by chadhietala** [comment]
tildeio/glimmer#255 has landed but I want to keep this open until we bump the version on glimmer.

**Comment by rwjblue** [comment]
Closed by https://github.com/emberjs/ember.js/pull/14060
