### ISSUE TITLE
mut helper does not bind in action parameter

### ISSUE THREAD

**Issue by Asherlc** [emberjs/ember.js#14057]
When a `mut` helper is passed as a parameter to an action, the action receives the original value, not the mutable getter/setter.

https://ember-twiddle.com/88a012a865086742ab2d2601565f6f57?openFiles=controllers.application.js%2C

From my understanding, it should log a `{ update, value}` object.

**Comment by Serabe** [comment]
That object is never passed to user land. That is a implementation specific detail. `mut` does two things:

1. If use in a component's parameter, it indicates that changing the property in the component will update the value in the parent context.
2. If use as the first parameter of an action, firing the action will update the value of the property.

Is there any part of the documentation where the implementation of `mut` is leaked?

**Comment by Asherlc** [comment]
Yes, it's used in the examples here explicitly and repeatedly:
http://emberjs.com/api/classes/Ember.Templates.helpers.html#method_mut
http://emberjs.com/blog/2015/05/10/run-up-to-two-oh.html

Chatted about it with @mixonic on Slack and he agreed it was a bug and should be passed.

**Comment by Serabe** [comment]
I'll try to talk to him on Slack. That behaviour was not there in htmlbars and I think it is not there in Glimmer 2. And I would say that this behaviour is now a breaking change in most places.

**Comment by mixonic** [comment]
As I mentioned on Slack `mut` is half-baked. The solution, if there is anything to be done here, is probably going to be less than ideal. @Serabe is correct that mutable objects are not "leaked" into JavaScript space on any public APIs. The only JS API that currently has access is `this.attrs`, however we should be discouraging that usage since it is likely to be supplanted by something else when Glimmer components land.

With that in mind I think the fix is mostly going to be documentation:

* Fix the `mut` documentation to re-focus on the public API usages that are more common. For example mutable actions. Make the `this.attrs` behavior (if documented) something underneath a "Legacy Behaviors" heading.
* Update the blog post section on `mut` to accurately reflects current API, such that it uses `attrs` when it reaches for a mutable instead of reading the property off `this`.

**Comment by Asherlc** [comment]
I think it would be pretty helpful to expose the mutable object, so one could modify properties inside of actions at runtime.

If the mutable isn't exposed, what makes `foo=bar` different from `foo=(mut bar)`? At that point, it's the same thing, no?

**Comment by Serabe** [comment]
They are. There is a [plugin](https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars-template-compiler/lib/plugins/transform-component-attrs-into-mut.js) that transforms `foo=bar` into `foo=(mut bar)`.

**Comment by Serabe** [comment]
Sorry, I forgot to comment on the helper modifying a property.

I see a helper as a function that gets _called_ whenever one of its parameters changes (yes, I know of class-based helpers, but let's keep it simple). If calling the function changes one of its arguments, how would it stop?

Anyway, if you have some examples of such helpers and think is a feature worth discussing, please, open an issue in [emberjs/rfcs](https://github.com/emberjs/rfcs). You can take a look at the RFC process in the [README](https://github.com/emberjs/rfcs#ember-rfcs). New ideas are always welcomed!

Thank you!

**Comment by Asherlc** [comment]
Mm, I think actually in my use case the _helper_ doesn't actually modify anything -- it just returns a little wrapper for the property. Any actual modifying is done inside an action, etc.

Wrt an RFC, would this be an appropriate place for one, given technically according to current document it _should_ work like this? Or is it for sure that the documentation was effectively in error?
