### ISSUE TITLE
Prevent caching in the head

### ISSUE THREAD

**Issue by ericrange** [emberjs/ember.js#14067]
I use polymer and dynamically generate a vulcanized.html.
This vulcanized.html is available in the head and cause me a lot of trouble because of caching.
`<link rel="import" href="assets/vulcanized.html">`
Is it somehow possible to use a revision number or something like this:
`<script src="assets/vendor-!!!!cab0903f3172a281aa547b98f81c4201!!!!.js"></script>`
for the vulcanized.html file? so that i get something like this:
`<script src="assets/vulcanized-cab0903f3172a281aa547b98f81c4201.html"></script>`

**Comment by Serabe** [comment]
Hello, @ericrange. I am closing this since it is not an Emberjs bug. Please, go to #-help channel on Slack. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

You might be interested on reading about [broccoli-asset-rev](https://emberobserver.com/addons/broccoli-asset-rev)

Thank you!
