### ISSUE TITLE
link-to component no longer accepts special chars

### ISSUE THREAD

**Issue by t4t5** [emberjs/ember.js#14094]
Previously, it was possible to include the "@"-symbol in your URLs.

My router looks like this:

```javascript
  this.route('user', { path: '/:userHandle' });
```

... and I could redirect to the path this way:

```handlebars
{{#link-to "user" "@tristan"}}
  Go to profile!
{{/link-to}}
```

This worked in 2.5 (it transitioned to `/@tristan`), but in the recent versions it instead changes the URL to `/%40tristan`.

What's the reason for this change, and is there a way to turn it off?

**Comment by Serabe** [comment]
I think this is related to the fix of #4794. Not sure if we should consider this a bug or not.

**Comment by rwjblue** [comment]
I think @bantic and/or @nathanhammond would have the best understanding of this. Would love for them to review/reply.

**Comment by rwjblue** [comment]
The changes in question landed in Ember 2.7.0 (and have been reverted in current release branch, to be released as 2.7.2).  They are still included (with bug fixes for the regressions identified) in the current beta (which will become 2.8.0).

The changes regarding encoding/decoding of links (including dynamic segments) were made in https://github.com/tildeio/route-recognizer/pull/91. There is specific discussion there about `@` (in the context of a URL reserved character).

**Comment by bantic** [comment]
One of the changes in https://github.com/tildeio/route-recognizer/pull/91 was to help make it so that route generation and recognition are symmetric (that is, generating a route with a dynamic segment would always create a string that would then be recognized by the route-recognizer). Before that change it was possible to generate routes that would not be recognized, for example, if you had the route `/:userHandle` and you did `{{#link-to "user" "abc/def"}}` the url that is generated would be "/abc/def", which route-recognizer would no longer recognize (it doesn't match `/:userHandle`).

After that PR the part of a dynamic segment is always encoded via `encodeURIComponent` so that, e.g. "abc/def" becomes "abc%2Fdef". This happens in the `generate` method for a dynamic segment [here](https://github.com/tildeio/route-recognizer/blob/master/lib/route-recognizer.js#L69).

I believe if you opt out of the improved encode/decode by setting `RouteRecognizer.ENCODE_AND_DECODE_PATH_SEGMENTS = false;` in your app, you'll see the behavior you're looking for (the "@" will appear in the URL as-is).

**Comment by bantic** [comment]
For context, `encodeURIComponent` will percent-encode any character in the uri reserved set (these: `; / ? : @ & = + $ ,`) as well as non-ascii characters (like emoji). (The JavaScript spec for `encodeURIComponent` is [here](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-uri-syntax-and-semantics).)
And the URI spec for what makes up a path is [here](https://tools.ietf.org/html/rfc3986#section-3.3).
RFC 3986 implies that the following characters should be allowed (non-percent-encoded) in paths:
`! $ & ' ( ) * + , ; = : @`.
I will take a stab at updating route-recognizer to explicitly allow those characters (un-encoded) when generating dynamic segments.

**Comment by t4t5** [comment]
Thanks for the clarification @bantic! Seem overall like it's a good fix, but that some apps could get some nasty side-effects from it. 👍 

Just one question: how can people set `RouteRecognizer.ENCODE_AND_DECODE_PATH_SEGMENTS` to `false` in their Ember CLI apps without forking the Ember library's route?

I naively tried setting:
```javascript
var ENV = {
    RouteRecognizer: {
      ENCODE_AND_DECODE_PATH_SEGMENTS: false,
    },
}
```

... in the `/config/environment.js`-file, but that does not seem to work.

**Comment by bantic** [comment]
@t4t5 Hmm, looking now I'm not sure `RouteRecognizer` is explicitly exposed for you to set the flag on. I'll check on that.

I have a fix for RR (here: https://github.com/bantic/route-recognizer/commit/23455b688c87e6d3536b86d3ac3296cc7145e3ed) that I will PR in a little bit after I have a chance to clean it up.

**Comment by bantic** [comment]
@rwjblue Here's a PR that should fix the problem in RR: https://github.com/tildeio/route-recognizer/pull/109

**Comment by nathanhammond** [comment]
@bantic `RouteRecognizer` isn't exposed to be able to set that flag from Ember land, but that's something I would prefer to keep. As of 0.3.0 I'd prefer to remove the "legacy" encoding behavior (and that flag) and stick with the behavior from RFC 3896 as "correct".

**Comment by nathanhammond** [comment]
Addressed upstream, can be closed.
