### ISSUE TITLE
Template compiler replaces html entities with some weirdness

### ISSUE THREAD

**Issue by sevarubbo** [emberjs/ember.js#14131]
Hi, I'm using Ember 2.7.0, ember-template-compiler 2.2.2. After compilation html entities, like `&hellip;` are replaced with characters like `â€¦`. I think it has something to do with `simple-html-tokenizer`, built in to compiler, but why this stuff is being actually rendered?

**Comment by rwjblue** [comment]
Can you please provide a reproduction that we can review?  Without a way to reproduce, it is very unlikely that we can help...

**Comment by Serabe** [comment]
I cannot reproduce it in a [twiddle](https://ember-twiddle.com/620de551401b11c2d50b0952937c8a5c?openFiles=twiddle.json%2C).

OTOH, any reason not to use `ember-template-compiler` `2.7.0`?

**Comment by sevarubbo** [comment]
@Serabe, thank you for your example. I looked at the code and it turns out, that `https://cdnjs.cloudflare.com/ajax/libs/ember.js/2.2.2/ember-template-compiler.js` is different from `http://builds.emberjs.com/tags/v2.2.2/ember-template-compiler.js`, the one I was using. If you open these files and search for `hellip` you will see the difference.

**Comment by Serabe** [comment]
@rwjblue seems like files in builds.emberjs.com are 7-bit ASCII

**Comment by Serabe** [comment]
Hello, @sevarubbo:

This is being closed because hotlinking is not considered a good practice and there are probably other options you can be using now. If you use Ember CLI, you will get all the files your application needs and even open it to a new ecosystem of addons. You can take a look at all those addons out there in [Ember Observer](https://emberobserver.com/).

I submitted emberjs/website#2671 to remove the _Script Tag_ button present in the builds page too.

Thank you!
