### ISSUE TITLE
Deprecate `renderToElement`

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#14158]

**Comment by runspired** [comment]
@chancancode so long as there is still a way to manually instantiate a component and render it :D

**Comment by miguelcobain** [comment]
@runspired there is still `appendTo` as I understand it.

**Comment by Gaurav0** [comment]
appendTo is private. Please do not deprecate this unless there is another public way to render a component programmatically.

**Comment by miguelcobain** [comment]
`renderToElement` is public? I'd be surprised if it was.

**Comment by rwjblue** [comment]
@Gaurav0 - As mentioned in https://github.com/emberjs/ember.js/pull/14482#issuecomment-254623792, neither is public today.  Would love an RFC to make a public mechanism for programmatic creation of components.

Also, lets centralize conversation on the topic instead of spreading it all over the place (making it hard for others to follow)?

**Comment by rwjblue** [comment]
Closed by #14482
