### ISSUE TITLE
Why this benchmark make Ember the worst framework?

### ISSUE THREAD

**Issue by johnunclesam** [emberjs/ember.js#14151]
Why this benchmark make Ember the worst framework?

They may not know to use it?

http://www.stefankrause.net/wp/?p=301

**Comment by ef4** [comment]
I got a 2.6x speedup on their 1000 rows insert benchmark by factoring out the my-row component (which doesn't do anything you can't do directly in the my-table component).

But it's true that component-heavy composition patterns in current stable Ember don't perform as well as we'd want. Which is why we wrote Glimmer2, which is [already in alpha testing](https://github.com/emberjs/ember.js/issues/13949). 

That said, "Ember" encompasses a lot more functionality than the alternatives it's being compared to. A more meaningful comparison would be to benchmark [Glimmer](https://github.com/tildeio/glimmer) directly (because Glimmer is Ember's view layer, comparable in functionality to most of the others).

**Comment by Adriaaaaan** [comment]
Its especially unfair when you consider the react test case doesn't use a component for the row.  Regardless it would be interesting to see if glimmer 2 improves the worst case scenario like this

**Comment by johnunclesam** [comment]
It will be great to see the Glimmer 2 tests on this.

Any volunteers?
