### ISSUE TITLE
Prevent PromiseProxyMixin from calling set on destroyed objects

### ISSUE THREAD

**Issue by amiel** [emberjs/ember.js#14250]
I am submitting this issue just to get feedback on if this issue is worth fixing. I already have a solution working in my production application and am happy to submit a pull-request.

Here's an ember-twiddle showing the error I get: https://ember-twiddle.com/cdc0cff705e96ca7d136b55e50ee9f95?openFiles=routes.application.js%2C

The example in ember-twiddle is pretty contrived. I generally get this error in my tests.

My solution involves simply checking `proxy.isDestroyed`, as that [seems](http://discuss.emberjs.com/t/how-to-do-you-check-for-isdestroyed/9621) to be the [recommended](http://stackoverflow.com/questions/25141822/uncaught-error-assertion-failed-calling-set-on-destroyed-object) [solution](https://github.com/emberjs/ember.js/issues/3780#issuecomment-63470006).

Is there a reason I should not approach this direction?

**Comment by pixelhandler** [comment]
@amiel I've had to check for `isDestroying` and `isDestroyed` in some cases when working with promise proxy objects. The example does show the result of trying to set something when the object is destroyed, but doesn't show the root cause. My best guess is that its likely it's an async issue. 

It does seem reasonable that when using a promise proxy object that the application code doing the setting in some cases may need to check if that object is destroyed or being destroyed. Just depends on the lifecycle of the object.
