### ISSUE TITLE
ES5 getters on an Ember.Object only ever return first computed value

### ISSUE THREAD

**Issue by chrisjshull** [emberjs/ember.js#14282]
``` js
var i = 0;
var obj = Ember.Object.extend({
    get index() {
        return i++;
    }
}).create();
console.log(obj.index); // 0
console.log(obj.index); // 0 -> should be 1
```

Compare to not extending Ember.Object:

``` js
var i = 0;
var obj = {
    get index() {
        return i++;
    }
};
console.log(obj.index); // 0
console.log(obj.index); // 1
```

Ember 2.8.0

**Comment by chrisjshull** [comment]
Reopen of https://github.com/emberjs/ember.js/issues/12940 as I'm seeing this in Ember 2.8.0.

**Comment by rwjblue** [comment]
Well, the thing is, you aren't adding a getter to that object actually.  You are adding a getter to the POJO you are passing to `.extend`. Until we can reliably suggest that folks use `class` syntax, I don't think we can use the sugary `get index() { }` syntax.

Right now you have to use `Object.defineProperty` to get a real JS getter.  

Demo: https://jsbin.com/gufegu/edit?html,js


**Note:** There is an internal mechanism in Ember to allow this to be as easy as defining a CP (still not perfect), but we don't expose it to userland at this point. We should look into making this easier, but I'd prefer to focus most of our energy behind making real classes work. 

Small teaser demo to show what I mean: https://jsbin.com/vecora/edit?html,js

**Comment by stefanpenner** [comment]
> I don't think we can use the sugary get index() { } syntax.

we can, but at a hefty perf cost (that is my intuition, may need to be tested 4real though)

**Comment by rwjblue** [comment]
@stefanpenner - Yes, we would have to do `lookupDescriptor` for every property passed to `.extend`.  I do not know how costly that is, but we can test.  The other issue is that it is technically a breaking change if you think about it a certain way (using getter passed to `.extend` to lazily update the value of a given property that then is supposed to be static after extend).

**Comment by stefanpenner** [comment]
@rwjblue true, if someone has time. Checking the perf would be interested, if its negligible. I suspect we would be open to the breaking you pointed out (although proper investigation would be required).

But if perf is bad, and it breaks stuff, then its truly DOA until class's

**Comment by rwjblue** [comment]
Ya, I can probably spike it

**Comment by oriSomething** [comment]
I don't know enough the code base of Ember to really comment about this. But what about using `Object.create` ?

**Comment by krisselden** [comment]
@oriSomething we do use `Object.create()` to setup the prototype chain, but as for defining properties on the inheriting object, `Object.create` requires an array of descriptors, does not take a pojo

**Comment by locks** [comment]
I'm closing this as we continue experimenting with `class` support, specifically through Glimmerjs.

**Comment by joefraley** [comment]
this is really counter-intuitive behavior, and `class` syntax doesn't help at all in 2019

```js
import { Component } from '@ember/component'
class MyComponent extends Component {
  get random() { Math.random() }
}
```
```hbs
<div>
 {{ this.random }} // some number
 {{ this.random }} // same #
 {{ this.random }} // same #
</div>
```

**Comment by pzuraq** [comment]
This has actually been solved on master, and should be available in the next release I believe! Native getters will work with classic class syntax, and will not replace themselves with the original value.

As for the second issue, in your most recent example, the issue there is that Ember will not rerender a value unless it is notified that the value (or one of its dependencies) has changed. This is generally more efficient, and it's really rather rare that you have a value that should update on every render, even if it wasn't directly mutated. Generally, you want to mutate the value with an action of some sort. On modern Ember, once Tracked Properties are merged, both of these examples would work:

```js
// component.js
import { Component } from '@ember/component';

class MyComponent extends Component {
  @tracked _random = Math.random();

  get random() {
    return this._random;
  }

  @action
  updateTracked() {
    this._random = Math.random();
  }
}
```

```js
// component.js
import { Component } from '@ember/component';

export default Component.extend({
  _random: tracked({ value: Math.random() }),

  get random() {
    return this._random;
  },

  actions: {
    updateTracked() {
      this._random = Math.random();
    }
  }
});
```

There _is_ a way we can make a value update every time the component renders, which would be to mark it as a volatile value. However, we've kept this as private API for tracked properties since we found that it was actually pretty confusing behavior, which people often misused with computed properties. If you have some motivating use cases for when you would need a value to be volatile, that would be really helpful, we could open up an RFC in the future!
