### ISSUE TITLE
Problems with 2.8.0 binding code

### ISSUE THREAD

**Issue by rwwagner90** [emberjs/ember.js#14280]
I just updated to 2.8.0 and I now have an issue:

```
TypeError: Cannot read property 'substr' of undefined
    at /Users/wagner5/sa-ui/recon/bower_components/ember/ember-template-compiler.js:11004:16
```

It is related to this line in ember-template-compiler:

`if (key.substr(-7) === 'Binding') {`

I think the only binding I am using is:

`classNameBindings: [':recon-event-header'],`

What could be causing this issue?

**Comment by rwwagner90** [comment]
This was due to an incompatibility with flexi, not a bug with Ember itself.

**Comment by runspired** [comment]
For stragglers that hit this that use Flexi, this was fixed in Flexi master.

For stragglers that hit this that do not use Flexi, the underlying root cause was that Flexi uses an AST tranform to rewrite portions of templates. In versions prior to 2.8 it was conveniently not necessary to accurately update the line and column positions of the node being operated on if you (for instance) changed it's name.  It is now necessary to do so.
