### ISSUE TITLE
Ember 2.8: hoisted components no longer cleaned up on route change

### ISSUE THREAD

**Issue by chrisjshull** [emberjs/ember.js#14294]
2.8: https://ember-twiddle.com/6077c950051a93e2dc66981c42ad32ba?openFiles=twiddle.json%2C&route=%2Fbar

2.7: https://ember-twiddle.com/d27d5141538876e05f675633b18c0e6e?openFiles=twiddle.json%2C&route=%2Fbar
1. click the 'foo' link (component added to DOM, and then hoisted to the `<body>`)
2. click the 'bar' link

Observed 2.8:
component **is not** removed from the DOM

Observed 2.7:
component **is** removed from the DOM

**Comment by rwjblue** [comment]
Hmm, this seems a bit odd to me. I would not expect the 2.7 behavior at all, and the 2.8 behavior seems correct to me.

The example is basically taking the return value of `this.$().append('new stuff')` and appending that to the body, it seems pretty odd to me to expect that something manually appended to the body would be cleared.

In general, if you do manual jQuery manipulations in `didInsertElement` you should be cleaning that up with `willDestroyElement`.

**Comment by chrisjshull** [comment]
At a high level I'm inclined to agree with you, but this does seem like a breaking change in a minor version update. (Plus, the issue comes from an addon, which makes it harder to swiftly remedy.)

**Comment by locks** [comment]
Hi @chrisjshull, sorry this change bit you and you seem correct that a breaking change sneaked through. However, due to the [seemingly] lack of activity it doesn't seem to affect many people. That coupled with @rwjblue's feedback that the 2.8+ behaviour is the expected one, I'm closing this issue.
Thank you for reporting, and hope you managed to address the problem in the addon!
