### ISSUE TITLE
On EmberJS webpage there are listed companies that are not using Ember

### ISSUE THREAD

**Issue by mxrguspxrt** [emberjs/ember.js#14308]
On EmberJS page there are listed companies that do not seem to be using Ember on the referred sites. 

* http://www.timbuk2.com/ (Angular)
* https://www.groupon.com (Backbone)
* https://www.livingsocial.co.uk/ (Angular)
* https://www.addepar.com/ (jQuery and its addons)
* and the list goes on

Would it be possible to get updated information who are using Ember and perhaps even comments why someone moved away from Ember? :)

**Comment by stefanpenner** [comment]
@mxrguspxrt some of these companies do use ember, but not for there public websites. For example, addepar's entire client offering is a series of very impressive ember apps. The others may or may no longer use ember, or may use ember for parts of there system but not others.

It is a bit tricky to know this without a representative from that company providing the clarification.

@wifelette maybe we should send out annual "refresher" emails to our contacts at these companies?

**Comment by pixelhandler** [comment]
Also, this issue could be moved to the website repo too.

**Comment by wifelette** [comment]
Will think about it! The truth is we don't have a large workforce for a task like this :p People who completely move away from Ember _do_ tend to remove themselves, and it's pretty well self-policed. We've also, since the starting of the page, had people get more specific about what they're using Ember for in the "use" field on the Yaml file, so this is less of a problem these days.

And finally, confirm, future issues about this indeed belong in https://github.com/emberjs/website/ :)

Thanks!
