### ISSUE TITLE
Ember.get with leading . in key no longer works

### ISSUE THREAD

**Issue by Dhaulagiri** [emberjs/ember.js#14386]
[This commit](https://github.com/emberjs/ember.js/pull/14345/commits/b959046d4f7d0ccc98b7c147b412bbb75afe5eb0) from #14345 breaks `Ember.get()` usage like the [one happening in the ember-inline-svg addon](https://github.com/minutebase/ember-inline-svg/blob/015ad0e4684048e3876b99c4c1843a20a5f4dcfa/app/helpers/inline-svg.js#L10) which sometimes looks up keys in a format of `'.path.filename'`.

[This twiddle](https://ember-twiddle.com/b3273acce03f07d2d0deff79abc01447?openFiles=controllers.application.js%2C) reproduces the scenario.

It's likely this could be fixed upstream in the addon to avoid this situation, but it seemed worth opening an issue here first.

**Comment by rwjblue** [comment]
Honestly, the fact that this worked before is pretty weird:

```js
let obj = { 'foo': 'bar' };

Ember.get(obj, '.foo');
```

I think the change is actually a bug fix, but I understand that this may have broken some things in the wild relying on the bug.  In general, this is a pretty fine line since every bug fixed could theoretically break _something_ relying on the bug.  

I'm happy to get feedback from other core team folks suggesting that this is indeed a breaking change, but at this point I'd like to try to keep the change.  `Ember.get` is one of our hottest pathways in general and reducing overall code complexity and random branches often helps us quite a bit performance wise...

---

To add a small amount of levity here, I always think of this XKCD when thinking about all bug fixes breaking something:

![workflow](https://imgs.xkcd.com/comics/workflow.png)

**Comment by Dhaulagiri** [comment]
I'm inclined to make a PR to the addon which would have it avoid this scenario entirely.  It ended up being relatively easy to update our app to avoid this as well, but it may bit others who relied on this strange behavior.

**Comment by rwjblue** [comment]
Yeah, I agree.  Maybe we can add a helpful assertion to at least point folks in the right direction...

**Comment by Dhaulagiri** [comment]
I think we can close this unless others find more compelling places where this causes them problems
