### ISSUE TITLE
Block params named `component` are unusable in 2.9 beta

### ISSUE THREAD

**Issue by Panman8201** [emberjs/ember.js#14413]
Starting this per @rwjblue request. While I can understand why this wouldn't necessarily work.

When naming a block param `component`, it's not really usable within the block scope. This _did_ work for me <= 2.7. I've just refactored away from the name but just reporting it here... Couple issues I noticed; 
- Nothing is output when using it as text `<li>{{component}}</li>`
- An error is produced when used as an attribute. `<li data-value="{{component}}">Foobar</li>`
  - Uncaught Error: Assertion Failed: You cannot create a component from undefined using the {{component}} helper

``` hbs
<h4>each as |abc|</h4>
<ul>
  {{#each components as |abc|}}
    <li>{{abc}}</li>
  {{/each}}
</ul>
<h4>each as |component|</h4>
<ul>
  {{#each components as |component|}}
    <li>{{component}}</li>
  {{/each}}
</ul>
<h4>each as |component| <em>in attribute</em></h4>
<ul>
  {{#each components as |component index|}}
    <li data-value="{{component}}">{{index}}</li>
  {{/each}}
</ul>
```

Reproduced the issue in ember-twiddle: https://ember-twiddle.com/24f1983de422ed7039c5b21af68cc032?fileTreeShown=false&numColumns=2&openFiles=controllers.application.js%2Ctemplates.application.hbs

**Comment by Serabe** [comment]
I would not consider this a bug but the previous behaviour. `{{component}}` and `(component)` are keywords in 2.8 (not sure there is a different term for them in >2.9) and that meant they were low-level helpers.

Helpers in 2.7 took precedence over properties with the same name (see [this twiddle](https://ember-twiddle.com/8e47d9fd491b4e4894bd83c15c9839d4?openFiles=twiddle.json%2C)), so I guess that this change of behaviour just make it standard.

I think I have seen a test regarding helper precedence, but cannot find it now.

**Comment by rwjblue** [comment]
Yeah, helpers and keywords will win over properties, but they shouldn't win over block params.  Block params should *always* win...

**Comment by Serabe** [comment]
@rwjblue: I updated [the twiddle](https://ember-twiddle.com/8e47d9fd491b4e4894bd83c15c9839d4?numColumns=2&openFiles=twiddle.json%2Ctwiddle.json) to show that the behaviour is consistent with block params as well: helpers win (the twiddle is using 2.7).

I think this is consistent behaviour non making a difference between a block param and a property. Otherwise, refactoring a block to a component would be harder than one would expect.

**Comment by chancancode** [comment]
It seems like #14520 didn't fix this particular scenario – what I did was to make block params always win over helpers on the Glimmer side. However, since `{{component ...}}` is handled by Ember in [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/environment.js#L190), we need another fix/test for this case.
