### ISSUE TITLE
has_many relationship with foreign key in children table only

### ISSUE THREAD

**Issue by eraleis** [emberjs/ember.js#14515]
I have some trouble with has_many relationship in ember, lets say i want to retrieve the comments attached to a post, i can easily do it if my postgres schema look like this:

**posts:**
    
    {
      id: 1,
      comments: [1, 2, 3]
    }
**comments:**

    {
      id: 3,
      post_id: 1
    }

But what I want is to get rid of the "comments" in posts table, like:

**posts:**

    {
      id: 1
    }
**comments**

    {
      id: 3,
      post_id: 1
    }

So far I haven't found anything that can help me even if it doesn't seem hard, and i don't understand why i need an array of id in the parent table

**Comment by Serabe** [comment]
Hello, @eraleis.

I am closing this since it is not an Emberjs bug. Please, go to #-help channel on Slack. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

In any case, the data you send does not need to be in the table as is: you can just query your db for the values. It would be like doing a `SELECT id FROM comments WHERE post_id=1`.

Thank you!
