### ISSUE TITLE
Possible documentation error for action helper

### ISSUE THREAD

**Issue by MarkMT** [emberjs/ember.js#14510]
The API documentation for the `action` helper ([source](https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/helpers/action.js)) contains the following example under the heading "Invoking an Action":
```js
export default Ember.Component.extend({
  actions: {
    // Usage {{input on-input=(action (action 'setName' model) value="target.value")}}
    setName(model, name) {
      model.set('name', name);
    }
  }
});
```
The nested use of `action` in the usage comment seems to be incorrect. My understanding is that the correct usage would simply be:
```
{{input on-input=(action 'setName' model value="target.value")}}
```
Can someone confirm?

**Comment by Serabe** [comment]
I can confirm it would not work. `value`, as specified by the doc, is:

> considered a property path that will be read off of the first parameter of the action.

_Nesting_ the action makes it work since it curries the first argument and the outer action would consider the second argument to `setName` its first argument. This can be checked with Ember Twiddle:

* [Nested actions](https://ember-twiddle.com/78741dce24ac0ed4d2e7618e2ac4f1ac?numColumns=2&openFiles=controllers.application.js%2Ctemplates.application.hbs)
* [Without nested actions](https://ember-twiddle.com/9743a313641e5b28886a2952214cc1ff?numColumns=2&openFiles=controllers.application.js%2Ctemplates.application.hbs) (take a look at the difference in the action implementation!)

Thank you for the report!

**Comment by MarkMT** [comment]
Wow, that's interesting. I obviously didn't understand the paragraph following the example! Thanks.
