### ISSUE TITLE
[request] Deprecate the usage of Ember.on for Component's lifecycle events.

### ISSUE THREAD

**Issue by givanse** [emberjs/ember.js#14511]
### Request

Deprecate this:

```
Ember.Component.extend({
  someRandomName: Ember.on('didInsertElement', function() {
  })
});
```

In favor of:

```
Ember.Component.extend({
  didInsertElement: function() {
    this._super(...arguments);
  }
});
```

### Reasoning

```
Ember.Component.extend({
  doA: Ember.on('willInsertElement', function() { },
  doB: Ember.on('willInsertElement', function() { }
})
```

The order in which `doA` and `doB` happens is unknown. This code might be the result of a bug refactoring. Or, a developer new to the code base not noticing that the event is being observed already. Subtle bugs can be easily introduced.

It is also easier to read and understand the behavior of a component if there is a single place where all the event dependent code is executed. Tracking down all the different pieces of code that are executed at different moments in the lifecycle is cumbersome and can be easily avoided by using overrides.

One argument that might come up against overrides is:

> what if people forgets to call super? that can introduce bugs too!

It is easier to know that you **always** have to have that call inside the hook, there is determinism. Whereas keeping track of all the `Ember.on`s that might be cohabiting an object is not straightforward. When reading the code, you have to keep a mental map of all the pieces that might be executed by hook; the cognitive load is high.

**Comment by pixelhandler** [comment]
@givanse I think a request is something that should be made as an RFC issue, since it's not a bug; the issue tracker is for Ember.js bugs.

See [CONTRIBUTING.md#requesting-a-feature](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature) which recommends creating an RFC Issue to request a feature/enhancement (no need for a PR with RFC, only an issue in the repo)

> if you have an idea that would be nice to have, create an issue on the emberjs/rfcs repo.

**Comment by rwjblue** [comment]
I'm happy to keep exploring this (the suggestion that Ember.on often makes code harder to reason about matches perfectly my own experiences), but @pixelhandler is absolutely right. We should take this to the RFCs repo since it isn't an actual bug (it's more of a feature request).

@givanse - Would you mind opening an issue over there?

**Comment by givanse** [comment]
Opened a new issue in the RFCs repo, thanks!
https://github.com/emberjs/rfcs/issues/174
