### ISSUE TITLE
`didTransition` event of Ember Router is fired incorrectly in Ember 2.10.0-beta.1

### ISSUE THREAD

**Issue by kratiahuja** [emberjs/ember.js#14516]
In Ember 2.10.0-beta.1 which has Glimmer2 enabled, the firing of component lifecycle hooks and `didTransition` is fired in a different order than in Ember 2.8.1. 

For a [simple app](https://github.com/kratiahuja/transition-regression) which does console.log from a component's [lifecycle hooks](https://github.com/kratiahuja/transition-regression/blob/master/app/components/dummy-comp.js#L9) and adds an [instance initializer](https://github.com/kratiahuja/transition-regression/blob/master/app/instance-initializers/route-events.js) that subscribes to the router's `didTransition` event the ordering of events is different.

In Ember 2.8.1 the ordering of events is:
1. willTransition of router is fired
2. didTransition of router is fired
3. init of component is fired
4. didInsertElement of component is fired
5. didRender of component is fired

In Ember 2.10.0-beta.1 the ordering of events is:
1. willTransition of router is fired
2.  init of component is fired
3. didInsertElement of component is fired
4. didRender of component is fired
5. didTransition of router is fired

A repro app is [here](https://github.com/kratiahuja/transition-regression). You can toggle the ember version in that app to see the difference of the ordering of events.

cc: @stefanpenner @chadhietala @krisselden

**Comment by stefanpenner** [comment]
https://github.com/emberjs/ember.js/blob/master/packages/ember-application/lib/system/application-instance.js#L152 used to call https://github.com/emberjs/ember.js/blob/v2.9.0/packages/ember-htmlbars/lib/renderer.js#L137 which scheduled on the `render` queue

Now we call into: https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/views/outlet.js#L115-L124 which ultimately does not schedule. The fix is most likely schedule the `appendOutletView`. Working on a PR now.

**Comment by stefanpenner** [comment]
at first it seemed like 'appendOutletView' return value was used, but it does not appear to be. Which suggests:

* https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/views/outlet.js#L128
* https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/views/outlet.js#L153

may not be working correctly

**Comment by stefanpenner** [comment]
proposed fix https://github.com/emberjs/ember.js/pull/14517

**Comment by kratiahuja** [comment]
Thanks @stefanpenner !

**Comment by rwjblue** [comment]
@kratiahuja - Can you confirm/check if this issue is present for subsequent transitions, or only initial transition?  The fix proposed in #14517 will likely only correct initial render (since we only `appendOutletView` once at the very top of the hierarchy.  I just would like to see if we also need to figure out and fix a similar issue for rerenders...

**Comment by stefanpenner** [comment]
initial render of `foo`:
```
transition-app.js:248 In willTransition
transition-app.js:252 In didTransition
transition-app.js:29 In init of component
transition-app.js:34 In didInsertElement
transition-app.js:43 in didRender
transition-app.js:254 In afterRender of didTransition
transition-app.js:37 Calling afterRender from didInsertElement
transition-app.js:46 Calling afterRender from didRender
```

transition to `index`

```
transition-app.js:248 In willTransition
transition-app.js:252 In didTransition
transition-app.js:254 In afterRender of didTransition
```

transition to `foo`

```
transition-app.js:248 In willTransition
transition-app.js:252 In didTransition
transition-app.js:29 In init of component
transition-app.js:34 In didInsertElement
transition-app.js:43 in didRender
transition-app.js:254 In afterRender of didTransition
transition-app.js:37 Calling afterRender from didInsertElement
transition-app.js:46 Calling afterRender from didRender
```

**Comment by rwjblue** [comment]
Thank you for confirming @stefanpenner!

**Comment by stefanpenner** [comment]
@rwjblue also, as you mentioned. The above ordering issue appears to only have been for initial render, subsequent re-renders did work correctly).
