### ISSUE TITLE
[beta] TypeError: Invalid value used as weak map key, in RootPropertyReference.compute() with canary

### ISSUE THREAD

**Issue by backspace** [emberjs/ember.js#14573]
Hello again! This is a continuation from #14557, which fixed one error but has another on the latest canary (`3c9c494a`):

```
WeakMap_setMeta (ember.debug.js:19145)
meta (ember.debug.js:19246)
didRender (ember.debug.js:22282)
didCompute (ember.debug.js:14227)
compute (ember.debug.js:14287)
value (ember.debug.js:14157)
compute (ember.debug.js:14330)
value (ember.debug.js:14157)
value (ember.debug.js:50776)
initialize (ember.debug.js:44545)
evaluate (ember.debug.js:49091)
execute (ember.debug.js:53295)
RootState.render (ember.debug.js:11301)
runInTransaction (ember.debug.js:22272)
_renderRoots (ember.debug.js:11566)
_renderRootsTransaction (ember.debug.js:11604)
_renderRoot (ember.debug.js:11525)
_appendDefinition (ember.debug.js:11438)
appendOutletView (ember.debug.js:11421)
invoke (ember.debug.js:337)
flush (ember.debug.js:407)
flush (ember.debug.js:531)
end (ember.debug.js:601)
run (ember.debug.js:724)
fire (jquery.js:3187)
fireWith (jquery.js:3317)
ready (jquery.js:3536)
completed (jquery.js:3552)
```

As in the previous issue, some form of this error happens in Chrome, Firefox, and Safari.

A few levels down in the stacktrace, I see references to `config` and `enterprise`, which makes me think it’s connected to what [@rjwblue noted here](https://github.com/emberjs/ember.js/issues/14557#issuecomment-257476968):

![image](https://cloud.githubusercontent.com/assets/43280/19923121/30fcc322-a0e6-11e6-84f9-680516aa2d11.png)

I’m sorry to keep bringing these issues here, I just don’t know at all how to help with them. Let me know if there’s any way I can contribute!

**Comment by pixelhandler** [comment]
@backspace would you mind adding the specific steps to reproduce the bug in your description?

**Comment by backspace** [comment]
Sure. The bug happens when you run [`travis-web`](https://github.com/travis-ci/travis-web) and visit `/`.

**Comment by rwjblue** [comment]
Repro: https://jsbin.com/loseje/1/edit?html,js,output

This comes down to two bugs:

* `{{render 'foo'}}` from a template without a controller defined makes the `{{render`'ed template have no `{{this}}` (since it attempts to inherit from the host location's `controller`, but that is not generated if none was found).
* `didRender` assumes it receives an object and calls `meta` unconditionally on the object passed into it, and if there is no `{{this}}` context it triggers `Invalid value used as weak map key` (because it is calling on `undefined`).
