### ISSUE TITLE
Component block isn't getting values from component, scoping issue?

### ISSUE THREAD

**Issue by bcardarella** [emberjs/ember.js#14580]
See: https://ember-twiddle.com/1c3cec4a039a5a7fcebb109462c3fcb4?openFiles=templates.components.my-component.hbs%2Ctemplates.components.my-component.hbs

Perhaps I am just assuming too much with the scoping rules around component blocks but shouldn't the block template for the component be able to access values in the component and actually prefer them if the outer scope has a similarly defined property?

**Comment by nightire** [comment]
https://ember-twiddle.com/4c07345e8fba266a92d1514ac3b5fecd

**Comment by bcardarella** [comment]
@nightire right, I'm aware I can address this on a case-by-case basis with `yield` but what about the situations where there is a non-deterministic number of properties to yield?

**Comment by nightire** [comment]
@bcardarella The simple answer is: you can yield `this` to represent the whole component

But this is not recommended, because it is not what component should be. In reality, component's author should provide fixed amount of properties or actions to the outside world. Otherwise, how users know what properties or actions they can use? how users know which of them is currently "valid"? (has value or not, for example)

Think about it.

**Comment by Serabe** [comment]
@nightire is right here, this is not an issue. If you need to pass a non-deterministic number of properties, you can pass an object (just as if you were using the `hash` helper).

This let you control and curate the public API of your component.

Thank you!
