### ISSUE TITLE
Ember GraphQL

### ISSUE THREAD

**Issue by kennetpostigo** [emberjs/ember.js#14691]
Hello,

I'm working on a GraphQL client called greed that I haven't open sourced yet. Its framework/library agnostic and wanted to create some ember bindings for it. I want to base the bindings off the same signature that I got working with react and vue which is:

```js
container(
  greed, 
  defaults, 
  queries, 
  mutations
)(component);

// Using a decorator
@container(
  greed, 
  defaults, 
  queries, 
  mutations
)
someComponent
```
**greed: greedInstance-** is the greed instance you want to use
**defaults: ?function -** are the default data for the component to render
**queries: ?function -** are the queries you can run when some user input occurs
**mutations: ?function -** are the mutations you can run when some user input occurs
**component: Component -** the component to enhance

The container essentially enhances whatever component it receives with data needed to render and methods that can be executed to run queries and mutations when some user input occurs in the application.

I'm not familiar with ember myself, so before I get knee deep in ember I wanted some tips and feedback for the best way to go about implementing this in ember.

**Comment by pixelhandler** [comment]
@kennetpostigo I think you'll get the best feedback in the https://embercommunity.slack.com/ chatrooms. Also, since this is not an Ember issue (this is Ember's bug tracker for bugs / issues). Perhaps post on the forums, http://discuss.emberjs.com/ 

There are a few ember addons on a similar topic, using GraphQL, see https://www.emberaddons.com/?query=graphql It may be a good idea to reach out to those authors, maybe even team up.
