### ISSUE TITLE
Ember.run API documentation examples

### ISSUE THREAD

**Issue by anijap** [emberjs/ember.js#14706]
The examples in the [API documentation for Ember.run](http://emberjs.com/api/classes/Ember.run.html#method_scheduleOnce) seem to be a little off.

`run.scheduleOnce('afterRender', myContext, sayHi);`

**sayHi** should be enclosed in quotes.
https://ember-twiddle.com/e441f8a8e5d6051fd313c41fd0d7c9fc

And why is the **run** method invoked directly, should it not be `Ember.run.scheduleOnce`?

**Comment by runspired** [comment]
@anijap we usually talk about "namespaces" without the Ember prefix, because soon you won't need to use or rely on globals for the pieces of Ember, and even today many devs choose to use destructuring to access the parts of Ember they need.

Destructuring looks like this:

```js
const {
  run
} = Ember;

// `run` can now be used
```

For `sayHi`, no, it doesn't need to be in quotes.  The method signature for `run.ScheduleOnce()` is `run.scheduleOnce(<queue>, <target>, <method>, <args*>)` where `target` is the context in which to invoke the function provided as `method`.  In this case, the method `sayHi` was defined immediately above in the docs:

```js
function sayHi() {
  console.log('hi');
}
```

There is, however, a convenience method that some use that let's you pass the name of a method available on the `target` to invoke.

Given the following class:

```js
class Foo {
  constructor() {
    this.name = 'I am a foo';
  }

  sayHello() {
    console.log(this.name);
  }
}
```

You could invoke the `sayHello` method either of the following two ways.

```js
let foo = new Foo();

run.scheduleOnce('afterRender', foo, foo.sayHello); // preferred way to invoke
run.scheduleOnce('afterRender', foo, 'sayHello'); // alternate way to invoke
```

And lastly, you can also invoke without a context or with a pre-bound context.

```js
let foo = new Foo();
let sayHi = () => { foo.sayHello(); };

run.scheduleOnce('afterRender', sayHi);
```

Hope this clears things up!

**Comment by anijap** [comment]
@runspired thank you!
I tripped up when this wasn't working
```
  sayHi() {
  	alert('Hi!');
  },
  
  init() {
    this._super(...arguments);
    Ember.run.scheduleOnce('afterRender', this, sayHi);
  }
```

but with your explanation I figured that it should be
`Ember.run.scheduleOnce('afterRender', this, this.sayHi)`

**Comment by nightire** [comment]
This kind of comment really should be put in the formal API document, even as an external reference link would be great.

**Comment by locks** [comment]
@nightire what part? Can you open a PR?
