### ISSUE TITLE
Ember 2.10.0 - failing route lookup on the container

### ISSUE THREAD

**Issue by thnima** [emberjs/ember.js#14716]
Doing a route lookup on the container like this: `App.__container__.lookup('route:application')` in a test leads to the following error: `Attempting to inject an unknown injection: 'service:-document'`.

This worked on Ember 2.9 - at least on the stable releases. On the beta releases where glimmer 2 was enabled, and now on Ember 2.10.0 it throws the above mentioned error.
Lookups on controllers are still working.

I reproduced it in a twiddle here:
https://ember-twiddle.com/d10633232ab699d57653801107c62448?openFiles=tests.acceptance.my-acceptance-test.js%2C

**Comment by matthiasleitner** [comment]
Seeing the same issue since upgrading to 2.10. Seems to be related to Glimmer 2.0 as the same issue was present in 2.9 beta but disappeared again for 2.9 stable.

**Comment by DavidPhilip** [comment]
Same for me.

**Comment by locks** [comment]
I assume you're aware that `__container__` is double private? ;P What are your use cases for using this API?

**Comment by rwjblue** [comment]
The issue is with instantiating something that gets injections provided by the `ApplicationInstance` instance before the `ApplicationInstance` instance is created (it usually lives at `__deprecatedInstance__` and is generally better to use than `__container__` anyways, since it mirros the "owner" API which is a public API).

Some breadcrumbs for whomever works on a fix for this:

* all `route` types get `template:-outlet` injected
* `template:-outlet` gets `service:-glimmer-environment` injected
* `service:-glimmer-environment` gets `service:-dom-tree-construction` injected
* `service:-dom-tree-construction` gets `service:-document` injected
* `service:-document` is not setup until the application instance is fully booted ([here](https://github.com/emberjs/ember.js/blob/ef8f46e15d920dfbe008594a0177a9a2103f90ed/packages/ember-application/lib/system/application-instance.js#L314))
* In testing, the `ApplicationInstance` does not get created until after the first call to `visit`
* Therefore doing a lookup of any route before the first visit will give this error.

At the moment, I am unsure of the right way to deal with this...

**Comment by pixelhandler** [comment]
@thnima @matthiasleitner @DavidPhilip @locks @rwjblue is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by pixelhandler** [comment]
Per our triage policy I'll close this out for now, feel free to reopen if the issue persists on the current release.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
