### ISSUE TITLE
Custom toString needs to work on Ember.Object subclasses with computed properties

### ISSUE THREAD

**Issue by joelpresence** [emberjs/ember.js#14724]
Hi,

I am creating a custom object that extends `Ember.Object`.  I need to override `toString()` because `Ember.inspect()` just barfs on my object and spews out `unknown mixin`.  However, I want to add some computed properties and set an array property in `init` and according to https://github.com/emberjs/ember.js/issues/14641 , @stefanpenner explained that the custom toString seems to break Ember and the computed properties won't notify of changes properly.

So either we need to fix `Ember.inspect` so that it can properly stringify custom objects or we need to support custom `toString` without breaking computed properties.

Any advice?

Thanks!

**Comment by pixelhandler** [comment]
@joelpresence I like the idea of supporting a custom .toString() property. 

I've been able to use a custom .toString  property on an Ember.Object, https://github.com/pixelhandler/ember-jsonapi-resources/blob/master/addon/models/resource.js#L123-L132

Not sure the any custom toString will break Ember. The comment here https://github.com/emberjs/ember.js/issues/14641#issuecomment-263107520 seems to indicate the problem was using both init to set properties and using those properties in the custom `toString` method.

One thing I did differently was to reopenClass on for the prototype I created extending Ember.Object and redefined `create` so I set some default properties when calling `super` instead of using `init`, here is an example, https://github.com/pixelhandler/ember-jsonapi-resources/blob/master/addon/models/resource.js#L582

Just providing some links as they may provide a workaround too.

**Comment by joelpresence** [comment]
Thanks @pixelhandler!  But I frequently create custom objects that use `init` to set properties because I often have array properties, and if I just do `someProperty: []` in the class then all instances of that class will share the same copy of `someProperty` and that will be a huge aliasing bug.  So how would I override `toString` in these cases?  I'm a newbie Ember user so I'm reluctant to start using `reopenClass` and so forth ... I really just want to be able to make a custom `toString` for classes where I set properties in `init` or (preferably) `Ember.inspect` should **not** just emit text like `<(unknown mixin):ember577>` for a custom object.  Why can't `Ember.inspect` just look at the properties on my custom class?  What is unknown about it?  It's just a straightforward extension of `Ember.Object` and I don't get why it keeps thinking its an unknown mixin ... What is unknown and where is the mixin and how do I get `Ember.inspect` to just work on custom objects that extend `Ember.Object`?

Thanks!

**Comment by stefanpenner** [comment]
I think the underlying issue is that our assertion code, eagerly invokes `toString` during strange periods (such as mid get of a CP during initialization, which may break that CP)

**Comment by pixelhandler** [comment]
@joelpresence @stefanpenner is this still an issue, perhaps we should close; what do you think?

**Comment by pixelhandler** [comment]
Per our triage policy I'll close this out for now, feel free to reopen if the issue persists on the current release.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
