### ISSUE TITLE
2.10 Regression: Setter throws error if object is undefined

### ISSUE THREAD

**Issue by medokin** [emberjs/ember.js#14747]
Worked fine before 2.10

https://ember-twiddle.com/8a4512ca59e24a2d8e77c8fc62849371

The weird thing, in my main project, i'm getting this error only in productions build.

**Comment by rwjblue** [comment]
Is this still an issue?

**Comment by medokin** [comment]
It's still reproducible in twiddle with v3.4.2

The question is if this counts as a bug.

**Comment by rwjblue** [comment]
Specifically, the issue here (at least in 3.4, haven't tested recent versions) is that setting a non-existent property using two way binding throws an error because it attempts to do something akin to `undefined.foo = newValue`.

I _personally_ don't think its a bug, but the poor error message definitely sucks and I'd like to address that...

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? Since setters/getters are gradually being replaced by native ES6 classes anyway, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by medokin** [comment]
Since it not a bug, it can be closed.
