### ISSUE TITLE
Deprecate `canDispatchToEventManager`?

### ISSUE THREAD

**Issue by GavinJoyce** [emberjs/ember.js#14754]
From https://github.com/emberjs/ember.js/blob/e24e403656b9de62d55b1a3111e4eb309276d4b8/packages/ember-views/lib/system/event_dispatcher.js#L105-L133:

```
Note that most Ember applications do not use this feature. If your app also
does not use it, consider setting this property to false to gain some performance
improvement by allowing the EventDispatcher to skip the search for the
`eventManager` on the view tree.
```

<img width="985" alt="screen shot 2016-12-24 at 22 11 05" src="https://cloud.githubusercontent.com/assets/2526/21468909/e3031ed2-ca25-11e6-934c-2e11ffeddf36.png">

Some questions:

 * Do many apps use this? If not, perhaps we can deprecate (with a RFC)
 * If we can't deprecate, can we disable it by default and make it opt-in?
 * What are the use cases for custom `eventManager`s? Can we suggest alternative solutions?

**Comment by rwjblue** [comment]
> Do many apps use this?

I checked with @tomdale and apparently this was originally added to allow views to differentiate between certain types of touch input, however the addon that originally used this ([ember-touch](https://github.com/emberjs-addons/ember-touch/)) has been deprecated in favor of [Hammer.js](http://hammerjs.github.io/).

> If not, perhaps we can deprecate (with a RFC)

Yes, we should absolutely deprecate it.

> If we can't deprecate, can we disable it by default and make it opt-in?

I think we can make it more "pay-go" either way, so that most apps don't have to pay the cost of the feature they never use...

**Comment by GavinJoyce** [comment]
TODOs:

 * [x] Make it pay-as-you-go : https://github.com/emberjs/ember.js/pull/14756 🍻 @rwjblue 
 * [ ] Create RFC to deprecate `canDispatchToCustomEventManager` @gavinjoyce
 * [ ] Deprecate `canDispatchToEventManager`
