### ISSUE TITLE
Ember 2.10 helper errors with 'can't add property _super, object not extensible'

### ISSUE THREAD

**Issue by Kilowhisky** [emberjs/ember.js#14769]
I have a roadblock in my upgrade to ember 2.10 and glimmer 2.  

I keep getting this error in a helper as its attempting to get the length of an array. It doesn't mater if its an ember array or not. As soon as i attempt to get the length it goes kaboom. 
```
Uncaught TypeError: Can't add property _super, object is not extensible
    at Array.superWrapper [as get] (index.ts:8)
    at Class.hasPermission (about:srcdoc:63)
    at Class.compute (about:srcdoc:42)
    at ClassBasedHelperReference.compute (index.ts:8)
    at ClassBasedHelperReference.value (index.ts:8)
    at ConditionalReference.value (index.ts:8)
    at ReferenceCache.initialize (index.ts:8)
    at ReferenceCache.peek (index.ts:8)
    at JumpUnlessOpcode.evaluate (index.ts:8)
    at VM.execute (index.ts:8)
```
At this line of code.

```
for (let i = 0; i < permissions.get('length'); i++) {
```

Here is a twiddle showing the issue. To view the issue open the JS error window. 
https://ember-twiddle.com/1eba1236f9d5c78a30589eb4dfb0663c?openFiles=helpers.has-permission.js%2C

Here's what the twiddle is running off of. 
DEBUG: -------------------------------
DEBUG: Ember      : 2.12.0-alpha.1-canary+2cb8e503
DEBUG: Ember Data : 2.10.0
DEBUG: jQuery     : 1.11.3
DEBUG: -------------------------------

I thought it might be related to 
https://github.com/emberjs/ember.js/issues/14264 and https://github.com/emberjs/ember.js/pull/14649 but even with the canary build it still shows up.

**Comment by btecu** [comment]
What about `permissions.length`?

**Comment by rwjblue** [comment]
A few things going on here:

* array prototype extensions are enabled (meaning that `NativeArray` methods are added to the main `Array` prototype)
* `params` (the first arg passed to `Helper.prototype.compute`) is a frozen array
* the twiddle calls `params.get('length')`
* since `NativeArray#get` calls `._super` [here](https://github.com/emberjs/ember.js/blob/59ff63b342c8a3c4843cced009d75c2d7aab18da/packages/ember-runtime/lib/system/native_array.js#L47) it is wrapped in a [standard super wrapper](https://github.com/emberjs/ember.js/blob/59ff63b342c8a3c4843cced009d75c2d7aab18da/packages/ember-utils/lib/super.js#L54-L60) function
* As you can see [here](https://github.com/emberjs/ember.js/blob/59ff63b342c8a3c4843cced009d75c2d7aab18da/packages/ember-utils/lib/super.js#L56) the super wrapper function sets `this._super` to the next super function (this is just how `_super` works)
* Since `params` is a frozen object, calling `this._super = anything` results in the error shown here

I do not think that `.get` or `.objectAt` are needed in this case (the argument passed to `.compute` will always be a native `Array` instance).  

Removing those method calls fix the twiddle: [see here](https://ember-twiddle.com/47c2609ea02fa4f190ef42607dda3200?openFiles=helpers.has-permission.js%2C)

```js
        hasPermission(userPermissions, permissions, allRequired) {
           for (let i = 0; i < permissions.length; i++) {
               if (userPermissions.includes(permissions[i])) {
                   return true;
               }
           }
           return false;
         }
```

**Comment by Kilowhisky** [comment]
Cool. This solves my current problem. Thanks for that!

Is it not an issue though that the NativeArray methods cause this error when the passed in array is of that type? Am I correct in assuming that if I had called .get('length') before passing it to the helper then it wouldn't have error'd on the method inside the helper? I understand that it technically is mutating it but that's not what it seems like as the end developer.

**Comment by Serabe** [comment]
Yes, the frozen array is the params, not your object.

Closing this then :)

Thank you all!
