### ISSUE TITLE
Explore if routerjs creation can be done on Ember Application rather than Ember Application Instance

### ISSUE THREAD

**Issue by kratiahuja** [emberjs/ember.js#14790]
@krisselden suggested this after looking at some heap snapshots for a server side rendered app. We are creating the route recognizer every `visit` request after the app instance is created. We could extract that out into Ember Application creation if it is static and not containing request specific information and have the router being created for every instance since that might be holding request specific info. This will help reduce memory load per visit. 

This is *not* a bug but something worth exploring though it will touch very critical parts of the framework.

**Comment by pixelhandler** [comment]
@kratiahuja Great suggestion :)

This seems like a feature/enhancement. See [CONTRIBUTING.md#requesting-a-feature](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#requesting-a-feature) which recommends creating an RFC Issue to request a feature/enhancement (no need for a PR with RFC, only an issue in the repo)

Typically the Ember.js issue tracker is mainly for bugs and since the RFC process (PRs or issues) most new feature/refactor issues are tracked on the RFC repo, https://github.com/emberjs/rfcs/issues

Would you mind moving this issue over to that one ^ ?

**Comment by kratiahuja** [comment]
@pixelhandler sure porting it there now!

**Comment by kratiahuja** [comment]
Opened: https://github.com/emberjs/rfcs/issues/197

**Comment by Serabe** [comment]
Closing this in favor of emberjs/rfcs#197.

Thank you @kratiahuja
