### ISSUE TITLE
HTTPS-only for emberjs.com?

### ISSUE THREAD

**Issue by bgentry** [emberjs/ember.js#14838]
Hi there,

I was surprised to notice that emberjs.com is still not even available over HTTPS, let alone HTTPS-only. What can be done to make that happen? Is there anything I can do to help?

Free certs are available from Let's Encrypt or AWS ACM, or you could get free TLS termination from CloudFlare.

Note that this does not apply to guides.emberjs.com, which is HTTPS-only.

Cheers :v:

**Comment by ef4** [comment]
The site is currently hosted on GitHub pages, which [does not yet support custom TLS certs](https://github.com/isaacs/github/issues/156).

I don't think it's possible to get free TLS on Cloudflare using your own domain name unless you pay for a Business plan ($200/month).

**Comment by bgentry** [comment]
> I don't think it's possible to get free TLS on Cloudflare using your own domain name unless you pay for a Business plan ($200/month).

That is incorrect. You can get a free TLS with a shared cert on CloudFlare, just not using your own personal cert.

**Comment by ef4** [comment]
I see you are correct. When I read "shared certs" I assumed they meant on a cloudflare domain, but they really mean SNI-based certs with your own domain as a subjectAltName. That would work.

**Comment by workmanw** [comment]
I realize this is probably a different issue, but since we're talking about TLS for `*.emberjs.com` ... `discuss.emberjs.com` still does not have a cert. Even when sending auth credentials, it's in the clear. See: http://discuss.emberjs.com/t/possible-to-configure-ssl-tls-for-discuss-emberjs-com/9781 

Just thought I'd bring it up if someone was going to spend the cycles to cover the `*.emberjs.com` domains and it turned out to be easy to also cover discuss.

**Comment by rwjblue** [comment]
@workmanw - Hmm, https://discuss.emberjs.com/t/possible-to-configure-ssl-tls-for-discuss-emberjs-com/9781 works for me?

**Comment by workmanw** [comment]
@rwjblue Oh hey look at that! I just doesn't force it if you go to `discuss.emberjs.com`. Sweet!

**Comment by locks** [comment]
Thank you for the discussion everyone, we're already tracking this in the [website repository](https://github.com/emberjs/website/issues/2155)!
