### ISSUE TITLE
Add shorthand for Ember.Object.create() to Ember namespace

### ISSUE THREAD

**Issue by Senthe** [emberjs/ember.js#14844]
We have Ember.A() for NativeArray. Is there a reason to not add for example Ember.O() to Ember namespace?

**Comment by locks** [comment]
@Senthe the bar for adding new APIs to Ember has been raised since the introduction of Ember CLI and its addon ecosystem, and an effort to keep the the Ember codebase more focused. This is because addons allow developers to provide and experiment with new functionality easily and quickly (`ember-get-helper`, `ember-cli-fastboot`, `ember-engines`).
Could you move this issue to the [RFCs](https://github.com/emberjs/rfcs/issues) repository to carry out the conversation there? Thanks for the feedback.
