### ISSUE TITLE
`computed.union()` doesn't do what people would naturally expect it to do

### ISSUE THREAD

**Issue by Herriau** [emberjs/ember.js#14891]

**Comment by locks** [comment]
@Herriau can you please provide a description of what the behaviour you expect is, and what the current behaviour is?

**Comment by Herriau** [comment]
I'd expect it to work similarly to `computed.intersect()` (http://emberjs.com/api/classes/Ember.computed.html#method_intersect), except obviously it'd be computing a union instead of an intersection, e.g.

```javascript
let obj = Ember.Object.extend({
  allFriends: Ember.computed.union('adaFriends', 'charlesFriends')
}).create({
  adaFriends: ['Charles Babbage', 'John Hobhouse', 'William King', 'Mary Somerville'],
  charlesFriends: ['William King', 'Mary Somerville', 'Ada Lovelace', 'George Peacock']
});

obj.get('allFriends'); // ['Charles Babbage', 'John Hobhouse', 'William King', 'Mary Somerville', 'Ada Lovelace', 'George Peacock']
```

The current behavior is to:

> computes a new array with all the unique elements from the dependent array

**Comment by locks** [comment]
Your code snippet seems to be how it currently works? https://ember-twiddle.com/fb5f3d17bb84526b37b762b7472eee16

Are you saying that the output should have 'Mary Somerville' twice?

**Comment by bwbuchanan** [comment]
Perhaps the problem is that the docs don't make it clear that `computed.union()` accepts multiple dependent keys, because it's an alias for `computed.uniq()`?

From a code clarity point of view, it makes sense for an app to use `uniq` if it wants the set of unique elements from a single array, and `union` if it wants the set union of several arrays, even though they're the same function. The docs could be updated to reflect this and to indicate that `union` accepts multiple dependent keys.

**Comment by locks** [comment]
I want to note that `computed.intersect` also doesn't reflect you can pass multiple property keys and should be updated with the other macros.

**Comment by Herriau** [comment]
@bwbuchanan Correct this seems to be a documentation issue rather than an implementation issue.

@locks The doc for `computed.intersect` is actually pretty clear about that:

> A computed property which returns a new array with all the duplicated elements from two or more dependent arrays.
