### ISSUE TITLE
Template compilation output of tabs in optcodes

### ISSUE THREAD

**Issue by tsteuwer** [emberjs/ember.js#14899]
I'm not entirely sure if this is the correct place to put this, but I feel like tabs shouldn't be included in the output if we are using tabs (not spaces) while building out the templates. For some reason when I look at the output from the template compilation there's tons of "\t" characters, for example:

```
nt"],["text","\\n"]],"locals":[]},{"statements":[["text","\\t\\t\\t\\t\\t\\t\\t\\t"],["append",["unknown",["memberDropdownCms"]]....
```

It's kind of a waste of bandwidth even if gzipped.

**Comment by rwjblue** [comment]
We cannot strip whitespace because at a framework level we cannot guarantee that stripping whitespace doesn't break the application.

If you would like to utilize an optimization like this, you should take a look at including the [ember-hbs-minifier](https://github.com/simplabs/ember-hbs-minifier) addon.

Closing as this isn't really a bug in the framework (more of a feature request IMHO).
