### ISSUE TITLE
Make Location A Public API

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#14909]
It's a mistake that the interface to the location is a private API. Creating an issue so we don't forget. /cc @rwjblue.

**Comment by rwjblue** [comment]
Confirm, the interface [discussed here](https://github.com/emberjs/ember.js/blob/3bd80eef4182a8d5eddbc24eb93382fdc41bd338/packages/ember-routing/lib/location/api.js#L105-L120) is definitely intended to be public.

I suspect what we need to do is rework those guides a bit though:

* make it so that we can document the API and the `Custom implementation` section as public
* move the documentation of `AutoLocation`, `HistoryLocation`, and `NoneLocation` into their own actual implementation files
* list the various implementations and cross link them in the API docs
