### ISSUE TITLE
Automatically generated div that wraps all routes breaks some css

### ISSUE THREAD

**Issue by gregattra** [emberjs/ember.js#14918]
The wrapper div that is automatically generated around every ember route prevents me from being able to do things like `height:100%`. 

```
    <div class="parent-route-wrapper">
         <div class="ember-view">
             <div class="child-route-wrapper">
```

I want the child route to have the full height of the parent route wrapper, but the auto-generated ember view prevents this.

**Comment by gregattra** [comment]
a hack that gets me around this is to do this:

```
.parent-route-wrapper > div.ember-view {
  height: 100%;
}
```

**Comment by locks** [comment]
@gregattra what version are you on? For quite some time only the application template is wrapped in a `div`.

**Comment by gregattra** [comment]
v. 2.11.0

it's not just the application template, it's every route gets wrapped in a div

**Comment by rwjblue** [comment]
Please provide a reproduction so that we can determine if there is a bug here.

See [this demo ember-twiddle](https://ember-twiddle.com/a64873c1356dc1e4e8590a6346906f31?openFiles=templates.foo.bar.baz.hbs%2C&route=%2Ffoo%2Fbar%2Fbaz) showing that a wrapping `<div>` is not automatically put around each route template in recent Ember versions.

**Comment by rwjblue** [comment]
Closing for now, happy to reopen with more details (basically a response to https://github.com/emberjs/ember.js/issues/14918#issuecomment-278770932).
