### ISSUE TITLE
event.preventDefault inside component touch events no longer works correctly on Chrome 56

### ISSUE THREAD

**Issue by acburdine** [emberjs/ember.js#14927]
_For reference, see https://github.com/jgwhite/ember-sortable/issues/130_

Came across this issue with ember-sortable, and it can be reproduced if you view the demo in responsive mode using Chrome's DevTools. Try to drag an element, and Chrome throws a warning that you're calling `event.preventDefault()` on a passive event listener, and it also has very odd behavior (try dragging an element up the screen). After research, the only `preventDefault` call we have in ember-sortable is in a component touchStart event handler, which is provided by Ember.

The warning is caused by this: https://www.chromestatus.com/features/5093566007214080 -> apparently all Chrome events (as of Chrome 56) are registered as "passive" now by default, so preventDefault doesn't work.

As the error came through Ember's provided component hooks, I wanted to see if there's a way to manually specify `{passive: false}` to an ember event handler, or if I'd need to try registering the events manually on the component to work around it.

**Comment by acburdine** [comment]
Note: I originally was using the demo that was on Ember 2.2 -> after updating my local copy to Ember 2.11 the same issue occurs.

**Comment by RByers** [comment]
Sorry for the trouble, this is a breaking change in Chrome 56 to [improve scroll performance](https://developers.google.com/web/updates/2017/01/scrolling-intervention).  This can probably be fixed by adding an appropriate `touch-action` [CSS rule](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) to disable scrolling/zooming where appropriate (which is necessary to work correctly with touch on IE/Edge anyway).

**Comment by mixonic** [comment]
We've discussed if Ember should be setting `passive: false` on the `touchstart` and `touchmove` event listeners it installs, basically treating the breaking Chrome change as a bug. It will be a topic of discussion tomorrow at the core team meeting.

**Comment by RobIsHere** [comment]
Would it be possible to let the developer decide on this at least on ember level, maybe by setting a config flag?

I have projects where this is ok and faster scrolling is good. Although because of going against spect it is a bug ;)

And I have web-app projects / cordova projects where I think this could cause trouble with libraries like ember-gestures, hammer.js, hammertime, fast-click. As they have complicated logic regarding scrolling prevention on touch. That's just an assumption. But I don't think google did test that in advance?

I'm a little bit worried about this. I don't know any real alternative for hammer.js as a gesture recognizer e.g. So if I can't disable the chrome bug, could it break my app really seriously?

**Comment by RByers** [comment]
> Although because of going against spect it is a bug ;)

I'm not going to argue that you shouldn't consider this a bug.  But _technically_ it's permitted by the [TouchEvents spec](https://w3c.github.io/touch-events/#cancelability) which says:

> Canceling a touch event can prevent or otherwise interrupt scrolling (which could be happening in parallel with script execution). For maximum scroll performance, a user agent may not wait for each touch event associated with the scroll to be processed to see if it will be canceled. In such cases the user agent should generate touch events whose cancelable property is false, indicating that preventDefault cannot be used to prevent or interrupt scrolling. Otherwise cancelable will be true.

But this isn't really fair because I wrote that part, and have been talking with the other browsers about solving this problem for years.  Browsers have a variety of different hacks to try to address this problem, but this is probably the one that has caused the most developer pain :frowning_face: 

> But I don't think google did test that in advance?

No, we have not tested libraries like this exhaustively.  But we did have moths of trials and dev/beta channel releases where we dug into each report of site breakage and provided solutions.

>  I don't know any real alternative for hammer.js as a gesture recognizer

hammer.js supports pointer events, right?  At least I helped them adopt touch-action correctly years ago.  I would have thought hammer.js would just work via it's pointer events / touch-action support (which requires this).  @dtapuska, have you looked into hammer.js behavior at all?

**Comment by dtapuska** [comment]
hammer.js has supported pointer events for some time now. I've tried several examples and they are registering only pointer events and no mouse or touch handlers.  Looking at the code it seems to be correct since Nov 2015ish.

**Comment by RobIsHere** [comment]
Very well. Thank you for the clarification!

**Comment by pixelhandler** [comment]
@mixonic any update you can add here re followup on Chrome change?

@acburdine have you found a workaround, e.g. did Hammer.js help?

**Comment by acburdine** [comment]
@pixelhandler in ember-sortable we just added the `touch-action: none;` css class to the right place and that solved the issue.

**Comment by mixonic** [comment]
@pixelhandler afaict the Chrome team is not interested in reverting this change. We're inclined to treat it as a bug, however since jQuery does not offer a way to pass arguments to an event listener (yes, seriously, you can't opt-out of this with only JS when using jQuery) the mechanism we have for a fix is rather convoluted. I need to sync back up with @rwjblue to check our direction again.

**Comment by pixelhandler** [comment]
@mixonic any update here regarding direction for Ember? can this be closed?

**Comment by pixelhandler** [comment]
@mixonic I'll close for now, please reopen if this issue persists on a current release.
