### ISSUE TITLE
[Project Svelte] Deprecation Introduction Hitlist

### ISSUE THREAD

**Issue by chadhietala** [emberjs/ember.js#15062]
## Wanted
We need to know in which versions of Ember these deprecations were introduced. Please simply report the version a specific id was introduced. To ensure that we don't have overlapping efforts, please state what deprecation you are investigating before you do the work.

## Why

With the eventual introduction of Svelte builds, there will be a mechanism to say "strip out any code for deprecated features from 2.0 to 2.8". However, to enable this range-based decision, we need both the start of the range.

## How

Ways to find deprecations:

* `deprecate()` method in the codebase
* `[DEPRECATE]` and `[DEPRECATION]` tags in the [CHANGELOG](https://github.com/emberjs/ember.js/blob/master/CHANGELOG.md).

## Deprecation IDs

- container-lookup-factory 
- ember-application.injected-container
- ember-application.app-instance-registry
- ember-application.registry-resolver-as-function
- ember-application.app-instance-container
- ember-application.app-initializer-initialize-arguments
- ember-application.validate-type
- ember-debug.deprecate-options-missing
- ember-debug.deprecate-id-missing
- ember-debug.deprecate-until-missing
- ember-debug.warn-options-missing
- ember-debug.warn-id-missing
- ember-views.component.defaultLayout
- ember-routing-views.controller-wrapped-param
- ember-htmlbars.make-bound-helper
- ember-htmlbars.ember-handlebars-safestring
- ember-metal.binding
- ember-views.did-init-attrs
- ember-metal.required
- ember-metal.observer-argument-order
- ember-metal.immediate-observer
- ember-views.render-double-modify
- ember-routing.router-resource
- ember-routing.top-level-render-helper
- ember-runtime.controller-proxy
- ember-runtime.action-handler-_actions
- ember-runtime.enumerable-contains
- ember-runtime.will-merge-mixin
- ember-runtime.frozen-copy
- ember-runtime.enumerable-contains
- ember-runtime.freezable-init
- ember-string-utils.fmt
- ember-template-compiler.deprecate-render-model
- ember-template-compiler.deprecate-render
- ember-template-compiler.transform-input-on-to-onEvent.dynamic-value
- ember-template-compiler.transform-input-on-to-onEvent.no-action
- ember-template-compiler.transform-input-on-to-onEvent.normalized-on
- ember-template-compiler.transform-old-binding-syntax
- ember-testing.test-waiters
- ember-views.lifecycle-hook-arguments
- ember-views.render-to-element
- ember-views.did-init-attrs
- ember-metal.ember-k
- ember-metal.ember-backburner

**Comment by Serabe** [comment]
Is the property still `since`?

**Comment by Serabe** [comment]
I'm working on this, I've gone through most of the changelog and still I have a few to solve.

I'll be uploading a PR soon with the part I get done by then.

**Comment by chadhietala** [comment]
@Serabe We basically just need the mapping from deprecation ID to version. We are basically going to have deprecation flags that take a semver version. This semver version will get turned into a bool based on what the consuming app says it supports.

**Comment by Serabe** [comment]
If you just need the mapping, this is the list:

- container-lookup-factory not found in code
- ember-application.injected-container 2.3.0
- ember-application.app-instance-registry 2.1
- ember-application.registry-resolver-as-function 2.3.0
- ember-application.app-instance-container 2.1
- ember-application.app-initializer-initialize-arguments 2.1.0
- ember-application.validate-type 2.0.0
- ember-debug.deprecate-options-missing 2.1
- ember-debug.deprecate-id-missing 2.1
- ember-debug.deprecate-until-missing 2.1
- ember-debug.warn-options-missing 2.1
- ember-debug.warn-id-missing 2.1
- ember-views.component.defaultLayout 2.1
- ember-routing-views.controller-wrapped-param 2.0
- ember-htmlbars.make-bound-helper 2.0
- ember-htmlbars.ember-handlebars-safestring 2.8.0 (included before but reverted).
- ember-metal.binding 2.7
- 
- ember-views.did-init-attrs 2.6
- 
- ember-metal.required 2.0
- 
- 
- 
- ember-metal.observer-argument-order 2.0
- ember-metal.immediate-observer 2.0
- ember-views.render-double-modify 2.0
- ember-routing.router-resource 2.0
- ember-routing.top-level-render-helper 2.11
- ember-runtime.controller-proxy 2.0


- ember-runtime.action-handler-_actions 2.0
- 
- ember-runtime.enumerable-contains 2.7
- ember-runtime.will-merge-mixin 2.0.
- ember-runtime.frozen-copy 2.0
- ember-runtime.freezable-init 2.0
- ember-string-utils.fmt 2.0
- ember-template-compiler.deprecate-render-model 2.6
- ember-template-compiler.deprecate-render 2.11
- ember-template-compiler.transform-input-on-to-onEvent.dynamic-value 2.1
- ember-template-compiler.transform-input-on-to-onEvent.no-action 2.1
- ember-template-compiler.transform-input-on-to-onEvent.normalized-on 2.1
- ember-template-compiler.transform-old-binding-syntax 2.1
- ember-testing.test-waiters 2.7
- ember-views.lifecycle-hook-arguments 2.12
- ember-views.render-to-element 2.11
- ember-metal.ember-k 2.12.0
- ember-metal.ember-backburner 2.7.0

If you don't need the actual `since` option, shall I close #15064 ?

**Comment by andyhot** [comment]
From the work (https://gist.github.com/andyhot/0c574101afc3ff25f95469453447930f) i had done for https://github.com/emberjs/ember.js/issues/14811, here's my (partial) findings:

- ember-application.registry-resolver-as-function 2.3.0
- container-lookupFactory 2.12.0
- ember-application.injected-container 2.3.0
- ember-metal.ember-k 2.12.0
- ember-metal.ember-backburner 2.7.0
- ember-metal.ember-create 1.13.3
- ember-metal.ember.keys 1.13.3
- ember-application.app-instance-container 2.1.0
- ember-application.app-initializer-initialize-arguments 2.1.0
- ember-application.validate-type 1.13.0
- ember-views.component.defaultLayout 2.7.0
- ember-routing-views.controller-wrapped-param 2.2.0
- ember-htmlbars.make-bound-helper 1.13.6
- ember-htmlbars.ember-handlebars-safestring 2.8.0
- ember-routing.router-resource 2.0.0
- ember-routing.top-level-render-helper 2.11.0

The differences I see with @Serabe 's findings:

- I had tracked ember-metal.ember-create and ember-metal.ember.keys though those do not appear in this issue
- I had tracked container-lookupFactory and also included ember-application.app-instance-container, ember-routing.router-resource, ember-routing.top-level-render-helper in more details (though it's basically the same versions, i.e. 2.11.0 instead of 2.11)
- I have different versions for ember-application.validate-type, ember-views.component.defaultLayout, ember-routing-views.controller-wrapped-param, ember-htmlbars.make-bound-helper so someone should take another look at those

fyi, all of the versions i had got where from tracking down the tagged commits hence the more detailed versions (though i can just be plain wrong in same cases where code was moved to different files)

**Comment by chadhietala** [comment]
@andyhot and @Serabe awesome! @Serabe I think we should keep your PR open still, I'm not sure if @rwjblue wants to do the `since` field in the deprecation. I don't know if it's needed with the thing I wrote.

**Comment by chadhietala** [comment]
So I think I need verification on these @rwjblue and if we should just go cleanup all the 1.13.0 flags. There is also some `untils` that have expired.

- 2.3.0 [views.component.defaultLayout ](https://github.com/emberjs/ember.js/tree/bceed2f103b2b79513ecf6a3b0f5d294bf16c35b)
- 2.3.0 [ember-application.validate-type](https://github.com/emberjs/ember.js/tree/28504216e0cd9b8de8ee4bbb67da6f749addec44) was an assertion first 
- 2.2.0 [ember-routing-views.controller-wrapped-param](https://github.com/emberjs/ember.js/tree/f75b2e11955e0eb84af08039d90cdf12)
- 2.3.0 [ember-htmlbars.make-bound-helper](https://github.com/emberjs/ember.js/tree/7e3b4109ee1c228daeed9b3c4b31da1bea2b5de9)

**Comment by rwjblue** [comment]
yep, all of those can can be cleaned up

**Comment by Serabe** [comment]
Can this be closed?

**Comment by pixelhandler** [comment]
@andyhot @chadhietala @locks @rwjblue closing for now, perhaps reopen or create a new issue to continue this effort if there is anything remaining.
