### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by amk221** [emberjs/ember.js#15095]
I'm using the register pattern to register a child component with its parent. I am throwing an error if more than one child is constructed.

```handlebars
{{#my-parent as |p|}}
  {{p.child}}
  {{p.child}}  {{! <--- not allowed }}
{{/my-parent}}
```

When the parent receives some attributes I want to wait for some async work to complete and then re-render manually.

In Ember 2.11.2 this works fine, but switching to Ember 2.12.0 I get an infinite loop

⚠️  The Twiddle will work with 2.11.2, but crash your tab when switching to 2.12.0

https://ember-twiddle.com/49dc9d656cda4adfc6bf21a0d4d904d0?openFiles=templates.application.hbs%2Ctemplates.components.my-parent.hbs

**Comment by Serabe** [comment]
Removing the exception from [register makes it work](https://ember-twiddle.com/54d747af091ab352fe3378f446aa37be?openFiles=components.my-parent.js%2Ctemplates.components.my-parent.hbs).  [Catching the exception works too](https://ember-twiddle.com/54d747af091ab352fe3378f446aa37be?openFiles=twiddle.json%2Ctemplates.components.my-parent.hbs).

**Comment by amk221** [comment]
Thanks, yes, I understand that. It just means I can't have the use-case I desire (i.e. something that used to be possible with Ember, no longer is).

The whole point is that it throws

**Comment by Serabe** [comment]
If your point is to inform the developer without breaking anything, then better use `console.error` than throw an Error. Does that sound right?

**Comment by amk221** [comment]
Potentially.. still, thought it worth highlighting this behaviour changed.

**Comment by Serabe** [comment]
Is the exploding behaviour defined somehow?

**Comment by amk221** [comment]
I doubt there would be an existing test case for it.

**Comment by abrinckm** [comment]
This occurs for accidental uncaught errors which you didn't mean to make. For example, let's take a look at a common programming mistake: "I forgot to define that variable before using it!" 

But, I haven't yet figured that out, I don't know that I'm getting a reference error because unfortunately for me, the tab is locked up (frozen) because of this infinite loop. I cannot open the console to read the error or do anything further and I am forced to close the tab through the task manager and reload the page, only to experience the same problem. I have to wonder what is happening, force quit the browser, open a new tab entirely, open the console first, then try to reload my page. And only then will I see two things, and infinite rendering loop, and my original error at the very top of this endless cycle of "id already registered for this view" errors. I don't think this should be expected by your consumers and is a very annoying iteration. 

With any other frontend frameworks, the page doesn't freeze or consume the entire heap of memory due to a simple reference error. Instead, I can open the console and see "ReferenceError: not defined" (a reasonable expectation) and go to the problem and fix it. 

I'm requesting that this issue be re-opened please, and the issue is dealt with.
