### ISSUE TITLE
2.13 beta breaks ember-simple-auth

### ISSUE THREAD

**Issue by ef4** [emberjs/ember.js#15116]
See https://github.com/simplabs/ember-simple-auth/issues/1284

I have not debugged it far enough to know whether the addon is doing something with private API that would justify breakage, or whether this is an unintentional break in Ember 2.13 beta.

**Comment by Serabe** [comment]
The [fix in ember-simple-auth is this](https://github.com/simplabs/ember-simple-auth/commit/ec761c4f15bb62d97e7d62eadc1a93ce376141aa).

Adding as documentation to the issue.

**Comment by pixelhandler** [comment]
Seems the issue in Simple Auth is being fixed, today, https://github.com/simplabs/ember-simple-auth/issues/1284#issuecomment-292506080

**Comment by ef4** [comment]
I understand the addon changed to address this, but I filed this issue to make sure we don't have semantic breakage in 2.13. It's still not clear to me that the addon was doing anything wrong. Why did the behavior in 2.13 change? Was this particular change intentional?

**Comment by rwjblue** [comment]
@ef4 - FWIW, we tracked this down to the issue that was fixed in https://github.com/emberjs/ember.js/pull/15177.  Essentially, in the 2.13 betas the DI itself was creating enumerable properties for things like the `OWNER` symbol, `NAME_KEY`, `_debugContainerKey`, etc.  In prior versions we used an extra `.extend` to provide injections, so these sorts of issues were avoided (because these were on the prototype chain, not on the individual instance).

Just figured I'd mention what the root cause was...
