### ISSUE TITLE
undefined error 

### ISSUE THREAD

**Issue by niksa88** [emberjs/ember.js#15159]
I am not sure is this a error or I am doing something wrong,

The ember-twiddle [link](https://ember-twiddle.com/aaf4e6bd35ea8855cd67a13f35ac2a60?openFiles=components.promise-test.js%2Ctemplates.components.promise-test.hbs)

After check the inspect shows some undefined error. Number of undefined errors are number of reject promise - 1

**Comment by kennethdavidbuck** [comment]
I believe this expected behaviour. Ember.RSVP.all will reject at the for the very first rejected promise in the array of promises. In this case because your promises aren't really async, the #all is failing on the first #reject in the array (The error that you are currently logging to console). Now, the second failed promise happens after the #all has failed, so I believe it is handled differently (i.e. is thrown and handled by the global onerror handler). If you want to wait for all promises to resolve or reject, then you can use [#allSettled](https://www.emberjs.com/api/classes/RSVP.html#method_allSettled), however you are then responsible for sorting out which was which on your own.

Lastly, undefined is logged to console because there is no stack property on the rejected value (because you are providing a string). If you use an Ember.Error object, for example, then you should see a stack logged to console paired with any message you may have provided.

I have updated your fiddle to demonstrate some of the things I have talked about:

[Updated Twiddle](https://ember-twiddle.com/aa1dd48ab6ab8f688d38de68ec00e686?openFiles=components.promise-test.js%2Ctemplates.components.promise-test.hbs)

**Comment by niksa88** [comment]
thanks @kennethdavidbuck for detailed answer.  I was confused with global error. I was not sure why is activated.
I will close this.
