### ISSUE TITLE
Accessing environment properties inside index.html

### ISSUE THREAD

**Issue by dfgkzhang** [emberjs/ember.js#15155]
I've built a sample project using ember-cli and I'm trying to access the current environment property set by environment.js in index.html, but the only property that seems to be accessible is rootURL.  I've tried adding the value to app.js, but index.html still can't find it.  The reason is I need to know whether or not I am running in production or not.  Can anyone provide some insight as to what I need to do?

**Comment by pixelhandler** [comment]
@dfgkzhang perhaps reach out in the #-help channel of the https://embercommunity.slack.com chat. I'm sure someone can provide some support for checking the environment, prod or not. I don't think you can know the `EmberApp.env()` result, or the EMBER_ENV variable within the index.html itself. There are addons the let you use `config/environment.js` to write key/value within the index.html one addon I think is called `content_for`. The results of the ENV variables created from the config/environment.js file Is written in a meta element within the index.html so it's possible. 

But I think what you can discuss on the slack chat is your specific use case, so other can share what solutions they've found for that use case. 

I'll close this out for now since it's not an Ember.js bug (we use the issue tracker here for reporting bugs).
