### ISSUE TITLE
jQuery'less ember has issues on 2.14.beta.1

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#15187]
ember-native-dom-event-dispatcher seems to be loosing, and the regular dispatcher wins.

**Comment by rwjblue** [comment]
This is the root cause of the test failures in https://github.com/emberjs/ember-test-helpers/pull/205.

/cc @cibernox

**Comment by rwjblue** [comment]
@stefanpenner - I updated ember-native-dom-event-dispatcher to use ember-source@2.14.0-beta.1 and it does seem to be passing its own test suite.  Do you recall which repo/test app you were using so I can pull that down and track down where this issue was coming from?

See:

* https://github.com/rwjblue/ember-native-dom-event-dispatcher/pull/8
* https://travis-ci.org/rwjblue/ember-native-dom-event-dispatcher/jobs/228074211

**Comment by stefanpenner** [comment]
I believe I ran into the issue here: github.com/stefanpenner/ember-strict-resolver

**Comment by Serabe** [comment]
Any follow-up in this issue? Is it fixed?

**Comment by rwjblue** [comment]
I believe things are working properly. A number of addons are now running their test suites without issue.
