### ISSUE TITLE
Error message precompile@0.3 requires the host to use ember-cli-babel@5 despite @0.4 installed

### ISSUE THREAD

**Issue by RobIsHere** [emberjs/ember.js#15211]
Hi! I tried to upgrade a large project and get this error:

ember-cli-htmlbars-inline-precompile@0.3 requires the host to use ember-cli-babel@5. To use ember-cli-babel@6 please upgrade ember-cli-htmlbars-inline-precompile to 0.4.

General question (DOC issue): If you get some broccoli error like this, how do you find out where it's caused? Core or some Add-On Name?

Specific question: I have ember-cli-htmlbars-inline-precompile to 0.4.2 installed. (with 0.4.0 it didn't work, too). Is this a bug? What can I do?

**Comment by rwjblue** [comment]
The issue here (most likely) is that one of your dependencies is using ember-cli-htmlbars-inline-precomplile@0.3, and that assertion message that I added (trying to be helpful to folks :( ) is actually checking the babel version of the _project_ not the babel version of the thing including the inline precompiler. I am working on fixing that though. 

Also, please note, this issue tracker is for bugs in Ember itself but this seems like an bug in ember-cli-htmlbars-inline-precompile. Can you open an issue there and cross link back here?

**Comment by RobIsHere** [comment]
+1000 on assertions ;)
