### ISSUE TITLE
Passing components through properties only works with hash helper 

### ISSUE THREAD

**Issue by alexlafroscia** [emberjs/ember.js#15225]
I've been trying to use the `component` helper to pass components and out of other components (in as a property, or yielding it out to the block) and have noticed that it only seems to work when using the `hash` helper.  Instead of providing example code here, I made a reproduction on Twiddle:

[Twiddle: Passing Components as Data](https://ember-twiddle.com/d3132a66f64aa36b66a8a409b649beb1?openFiles=templates.application.hbs%2C)

As a quick summary, the twiddle above proposes 4 cases where a component is passed into or out of another.

1. Yielding a component as a property of the `hash` helper
2. Yielding a component directly
3. Passing a component as a property of the `hash` helper
4. Passing a component directly

I would expect that all four cases would render exactly the same, meaning all four would have the `This is the child component!` text.  However, the two cases where the component is passed "directly" both render `[object Object]` instead.

I did my best to debug myself, using the `{{debugger}}` in Handlebars to try to get an idea of what the different between the hash and no-hash instances are.  From what I can tell, the component's value is the same both times... I can't figure out why it works through the `hash` and not without it.

**Comment by rwjblue** [comment]
I don't really think this is a bug actually, but let me explain then we can see if we agree 😉.

I believe this is the crux of the issue is what we have generally called the "dot rule", a standard curly invocation can only be a dynamic component if it includes a period in the invocation.

For example, in Ember (all versions that have supported closure components) this syntax works because there is a `.` in the invocation of the yielded component (it really has nothing to do with `hash` helper though):

```hbs
{{#with-hash/yield-to-block as |data|}}
  {{data.child}}
{{/with-hash/yield-to-block}}
```

However, this does _not_ work (and is not intended to):

```hbs
{{#without-hash/yield-to-block as |child|}}
  {{child}}
{{/without-hash/yield-to-block}}
```

The reason for that is: if we made _every_ `{{foo}}` invocation to be:

* a possible component invocation
* a possible helper invocation
* a local property in the backing JS object
* a block param

To make your `without-hash` example work, you would need to use the `{{component` helper:

```hbs
{{#without-hash/yield-to-block as |child|}}
  {{component child}}
{{/without-hash/yield-to-block}}
```

**Comment by Serabe** [comment]
As @rwjblue, this is not an issue.

The reason it works with the hash helper and not without it is by design. Please, look at [this section in the RFC that introduced them](https://github.com/emberjs/rfcs/blob/master/text/0064-contextual-component-lookup.md#hash-helper) and the following one to understand more about it.

Thank you!

**Comment by alexlafroscia** [comment]
Gotcha! Makes sense to me, I appreciate the explanation @rwjblue @Serabe

**Comment by alexlafroscia** [comment]
FWIW I updated that Twiddle to show it "working", but using the `component` helper in the `without-hash` scenarios.
