### ISSUE TITLE
Unexpected observer running on init.

### ISSUE THREAD

**Issue by kellyselden** [emberjs/ember.js#15246]
```js
import Ember from 'ember';

function func1() {
  alert('func1');
}
function func2() {
  alert('func2');
}

export default Ember.Controller.extend({
  onInit1: Ember.on('init', func1),
  onObserve1: Ember.observer(func1),
  onObserve2: Ember.observer(func2)
});
```

`func1` runs twice but `func2` doesn’t run. Is that expected? I would expect `func1` to only run once.

Without `onObserve1`, `func1` runs once, but adding it to an observer causes it to run twice on init.

(observer keys left out because they didn't affect the test)

Also, if I change it to 

```js
  onInit1: Ember.on('init', function() { return func1.apply(this, arguments); }),
  onObserve1: Ember.observer(function() { return func1.apply(this, arguments); }),
```

it works as expected.

**Comment by stefanpenner** [comment]
> onObserve1: Ember.observer(function() { return func1.apply(this, arguments); }),

what is this observing? It seems to be missing the path?

**Comment by kellyselden** [comment]
> what is this observing? It seems to be missing the path?

@stefanpenner I could put in a random key, but it didn't affect the test case so I left it out for conciseness. See "(observer keys left out because they didn't affect the test)"

**Comment by stefanpenner** [comment]
mind adding failing test? or a twiddle

**Comment by kellyselden** [comment]
https://ember-twiddle.com/f8fe3fc5cf5bbd8820f045d8c640c9bb

**Comment by bekzod** [comment]
since `observer`s and `on` (listeners), store dependent keys on passed function itself,
like `observer('foo', func)`  =>  func.__ember_observes__ = 'foo' hence subsequent usage of same function would overwrite `observer('bar', func)`  =>  func.__ember_observes__ = 'bar'
hence I have two solution: 
1. assert for using same function for different `observer`, `listener`,
2. create wrapping function (and use it as listener/observer) each time when `func.__ember_observes__` ( or `func.__ember_observes__`, `func.__ember_listens__`) already populated
there might other complex solutions probably not worth doing for such narrow usecase thing :P 
I am happy to implement either of them
@stefanpenner

**Comment by pixelhandler** [comment]
@bekzod @kellyselden @stefanpenner is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by kellyselden** [comment]
I updated the test https://ember-twiddle.com/f8fe3fc5cf5bbd8820f045d8c640c9bb

I couldn't use any of the dist-tags because I got a CORS error, but the latest stable on there 3.2.2 still has the issue.

**Comment by locks** [comment]
Killing this because of the `.on('init'` 😅
