### ISSUE TITLE
Events are delegated to components during DOM teardown >= 2.8

### ISSUE THREAD

**Issue by mixonic** [emberjs/ember.js#15250]
Preamble:

Chrome triggers synchronous `focusout` events when a focused DOM node is being removed from the DOM. A fiddle to illustrate:

* https://jsfiddle.net/5hs6239L/6/ - What this is: Create a page with `<div><input></div>`. Attach an event listener to the `<div>` for `focusout` (`focusout`, unlike `blur`, bubbles). 
Programmatically focus on the `<input>` element. Remove the `<input>`. The `focusout` event is synchronously triggered.

This behavior is present in Chrome. Neither Firefox nor Safari trigger the `focusout` event during DOM teardown. Firefox has an [open issue](https://bugzilla.mozilla.org/show_bug.cgi?id=559561) to add this behavior, however.

---

In Ember 2.8, `focusOut` handlers on a component will fire during that component's element teardown (I have not tested layout teardown). This seems incorrect, and until 2.7 `focusOut` handlers on a component being torn down were not dispatched.

* [Reproduction in a twiddle](https://ember-twiddle.com/cfaa68c575d83a784469c8f061cb7d1a?openFiles=templates.application.hbs%2C)
  * **Expected behavior:** Given a component with an `<input>` tag for an element and focus on that `<input>`, when the component is removed from rendering the `willDestroyElement` hook is called.
  * **Actual behavior:** The `willDestroyElement` hook is called and *after* that and during the render phase the `focusOut` handler is called.

I suspect that the component handling the event is not removed from the event dispatcher or property disregarded during its DOM teardown phase. There may be other events impacted by this regression, though `focusout` is admittedly pretty weird.

In the wild, this can manifest as `{{input}}` components with focus firing a final change notification for `value` (triggered by the `focusout`) during their DOM teardown. Parts of an app may no longer be expecting changes at that point. For example, an Ember-Data record created for a `/new` route should have `rollbackAttributes` called on it during `willTransition` to remove it from the store (presuming the work was aborted). Given that the record had a property bound to an `{{input}}` value, when user causes a transition the final change notification to `value` occurs during rendering (*after* `willTransition`). The record throws an exception that a deleted record should no longer have properties set.

**Comment by stefanpenner** [comment]
Fun fun, I see two options:

1. ensure the view is removed sooner from the registry
2. guard https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/system/event_dispatcher.js#L220 based on the view being in state where events can be received.

My vote would be 2.

**Comment by RobIsHere** [comment]
It would be quite cool to keep the components around for a short time and schedule destroying for later.

Benefit 1: No hassle with async
Benefit 2: No guarded event behavior, events can work as you expect in your browser of choice
Benefit 3: Simplify Fade-Out and Cross-Fade native animations

Immediate teardown and gc is a problem: see https://github.com/peec/ember-css-transitions/blob/master/addon/mixins/transition-mixin.js#L175

We had to rework our whole application at vinubis.com to native animations (before we used LF), because Chrome has major bugs since more than 5yrs in their issue tracker (Video Fullscreen is broken, Position Fixed doesn't work) and Chrome is not going to change it. They have an issue about translate/will-change creating a new coordinate system because some guy misunderstood the spec back then (two times the same word in different contexts).

So to narrow it down: for Applications dealing with video and/or position fixed top menus css native animation support at the end would be a big secondary effect.

**Comment by stefanpenner** [comment]
> It would be quite cool to keep the components around for a short time and schedule destroying for later.

i think that is orthogonal to this issue. Be sure to look at how liquid-fire addresses this, that solution seems to handle your case nicely.

**Comment by RobIsHere** [comment]
I don't have a case at the moment :) Framework support for keeping components longer would be great for future applications. And just that is a possible solution to the problem here ;)

Liquid fire doesn't work well for sophisticated apps. It just works when the programmer does the UX :( That's my experience from the past.

**Comment by pixelhandler** [comment]
@RobIsHere @mixonic @stefanpenner is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by pixelhandler** [comment]
Per our triage policy I'll close this out for now, feel free to reopen if the issue persists on the current release.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy
