### ISSUE TITLE
How to utilize `ember-router-scroll` sans add-on?

### ISSUE THREAD

**Issue by maxwerr** [emberjs/ember.js#15324]
[Symmetrical question in ember-router-scroll](https://github.com/dollarshaveclub/ember-router-scroll/issues/54)

It appears this addon got folded into ember core, but I can't find any documentation on how to use it within ember. The instructions per the addon don't work.

fwiw: this was on emberjs 2.13.3

**Comment by rwjblue** [comment]
Yes, the addon is still needed. The RFC to Ember simply made the addons job a tad bit easier (and allowed it to rely on only public APIs). Specifically, I believe that step 3 in the [usage instructions on the README](https://github.com/dollarshaveclub/ember-router-scroll#usage) is no longer needed with Ember 2.13.

Since this isn't really a bug in Ember, I'm going to close this issue.  Lets continue the discussion in https://github.com/dollarshaveclub/ember-router-scroll/issues/54.

**Comment by maxwerr** [comment]
Awesome. Thank you!
