### ISSUE TITLE
Testing: initializer not injecting service

### ISSUE THREAD

**Issue by ryanrishi** [emberjs/ember.js#15335]
I'm writing a unit test for a controller that expects to have a service that is injected by an initializer on every controller. The controller test is failing because the service is _not_ there in the controller's `init` method.

[Here](https://ember-twiddle.com/a4901ada49c7efaf7f3d21feca087564?openFiles=controllers.application.js%2C) is a twiddle that demonstrates this behavior.

This ay duplicate #4280, but that's from 2014 and Ember has changed a lot since then :)

**Comment by rwjblue** [comment]
`ember-test-helpers` based unit and integration tests do not run initializers. If you need to unit test something like this, using `Ember.inject.service()` explicitly is generally better (and leads to more understandable code).

**Comment by Serabe** [comment]
Shall we close this issue as it is marked as wontfix?

**Comment by c-emil** [comment]
It would be nice to provide a way to inject the service from the test so that I don't have to explicitly inject the service to each component in which I want to use the service. By injecting it manually everywhere the service initialiser is useless because it's main point is to inject a service to each component/controller/route.
