### ISSUE TITLE
DEBUG: For more advanced debugging, install the Ember Inspector from 

### ISSUE THREAD

**Issue by vladucu** [emberjs/ember.js#15354]
Upgraded this morning to `ember` `2.13.3` and in `production` environment seeing these errors

`DEBUG: For more advanced debugging, install the Ember Inspector from ....`

This seems like a small regression, not happening on `ember` `2.12.2`

**Comment by rwjblue** [comment]
Just to confirm, you are not seeing errors but rather console log messages, right?

**Comment by vladucu** [comment]
ah, yes, sorry for not being clear.

Not anything critical, it just causes these to be logged in Rollbar on every page load... and filling the quota pretty quickly

**Comment by pedrokost** [comment]
I can confirm I seem the same error in my app, in Rollbar

**Comment by Serabe** [comment]
I've been looking into this for a couple of days now with simple projects.

I do something like:

```shell
npm install -g ember-cli@2.13.3
ember new project
# Add a route and a couple of links
```

Both `ember server --environment production` and `ember build --environment production && cd dist && python3 -m http.server` did not reproduce it.

Can you please @vladucu and @pedrokost share more information about your projects?

Thank you!

**Comment by Serabe** [comment]
Just to comment, I did my checks in Incognito mode where the ember extension is not enabled in my machine.

Thanks!

**Comment by pedrokost** [comment]
Thanks for trying to replicate the issue @Serabe 
Today I am unable to duplicate the issue, and it hasn't appeared in production in the past 3 days.
The only change from the time the issue was last present is an unrelated commit. 

I am unable to invest much time for this until the end of the week, in the meantime I am attaching a photo of Rollbar showing when the errors occurred. Also, you can also find the source [code of the app (specifically the package.json file) here](https://github.com/pedrokost/klubi/blob/master/package.json). 

![screenshot from 2017-06-29 00-51-40](https://user-images.githubusercontent.com/725286/27663939-29a660fc-5c65-11e7-9eb1-2f2a547c0e54.png)

**Comment by Serabe** [comment]
Was there a new build? Did the ember version changed between them? Do you have access to a diff between both prod versions?

Thanks!

**Comment by pedrokost** [comment]
The ember version never didn't change.

It seems to me that the issue started after [this commit](https://github.com/pedrokost/klubi/commit/08661961093c792a315b9381a57ec1bfd947de85) or [this commit](https://github.com/pedrokost/klubi/commit/a084a8855f863652005b4e12b62dffba94a1a525) which enabled sourcemaps and upgraded `ember-cli-rollbar`, and I changed `Ember.LinkComponent.reopen`.

I just now realized that I had another report in Rollbar showing that the issue is much more frequent that previously thought.
![screenshot from 2017-06-29 21-06-46](https://user-images.githubusercontent.com/725286/27705736-1fd222fa-5d0f-11e7-94d8-5dc1efb09b51.png)

Unfortunately I don't tag production deploys as I tend to deploy very regularly (almost each commit), so I cannot pinpoint the exact commit.

**Comment by pedrokost** [comment]
I seem to be able to replicate the issue on my production app by opening the page [https://www.klubi.si/fitnes](https://www.klubi.si/fitnes) in Incognito mode.

![image](https://user-images.githubusercontent.com/725286/27706095-7c82bdec-5d10-11e7-9ffe-806845979c4f.png)

It seems to come from a file body-class.js from the [`ember-body-class` library](https://github.com/AddJam/ember-body-class)

**Comment by Serabe** [comment]
@vladucu do you use rollbar as well? It seems that ember-debug `isTesting` returns `true` for some reason.

**Comment by vladucu** [comment]
@Serabe yes, we use rollbar....we've manually ignored these errors for now

> Was there a new build? Did the ember version changed between them? Do you have access to a diff between both prod versions?

not really, we just upgrade from `2.12.2 -> 2.13.3` when noticed this

**Comment by pixelhandler** [comment]
@pedrokost @rwjblue @vladucu is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by vladucu** [comment]
not an issue for us anymore, thx!

**Comment by pixelhandler** [comment]
Thanks for the reply :) @vladucu
