### ISSUE TITLE
ember server does not start

### ISSUE THREAD

**Issue by alper** [emberjs/ember.js#15388]
I ran the Quick Start and then `ember server` hangs on:

`WARNING: Node v8.1.2 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js.`

How is this a warning if this prevents the thing from running?

Also it would be nice to either tell me what version of node actually needs to be installed and/or include a recipe in the Quick Start that makes sure I have the right node version.

**Comment by locks** [comment]
Hi, thanks for letting us know of your problem. For future reference, this should likely go in the [Guides](https://github.com/emberjs/guides) issue tracker, or asked in one of our support channels since it's more of a support question.

> How is this a warning if this prevents the thing from running?

I would say the warning is appropriate. It might work, but you might also have problems, which you did!

> Also it would be nice to either tell me what version of node actually needs to be installed and/or include a recipe in the Quick Start that makes sure I have the right node version.

The error message does say which version you should install, most-recent Active LTS (6.x at the moment). We also have an [Install Ember](https://guides.emberjs.com/v2.13.0/getting-started/quick-start/#toc_install-ember) section that links to a full [Installing Ember](https://guides.emberjs.com/v2.13.0/getting-started/) guide with more details.

Hope you give Ember another try. If you can't switch to Node 6.x at the moment, Ember CLI v2.14 should be released in the upcoming days and will support Node 8.x.
