### ISSUE TITLE
deactivate called on parent route when going to a child route with a promise model and there is a loading template

### ISSUE THREAD

**Issue by laynegt** [emberjs/ember.js#15466]
[twiddle](https://ember-twiddle.com/cf72b5ab9d92653303ce590a3c36186b?openFiles=routes.parent.js%2C&route=%2Fparent%2Fchild)

Given the following:
* `parent` route
* `parent/child` route with async model
* `parent-loading.hbs` template

if you navigate from `/parent` to `/parent/child`, the parent route's `#deactivate` gets called.

Appears to have been introduced in 2.10.  I stepped through router changes introduced in 7e1afe71c.  From what I could gather, there is now an extra transition called on `parent` due to the presence of the loading route.

**Comment by laynegt** [comment]
Just want to add that this was pretty easy to work around by using a `willTransition` action instead.

**Comment by kumkanillam** [comment]
Simply If you add `parent/child-loading.hbs` then `deactivate` is not called. !. the reason might be the intermediate transition for showing loading causing the bug.

**Comment by pixelhandler** [comment]
@laynegt given the description of `deactivate`  https://emberjs.com/api/ember/2.14/classes/Ember.Route/methods/deactivate?anchor=deactivate

> This hook is executed when the router completely exits this route. It is not executed when the model for the route changes.

My expectation is that the parent route is not deactivated when transitioning to a child route, but instead only deactivated when leaving from a child route of from itself to another route (aside from it's own leafs).

However I'm not sure that this is a bug, would need confirmation. cc\ @machty 

Do you know the last version that the deactivate behavior worked as expected?

**Comment by pixelhandler** [comment]
@Serabe @locks this seems like a regression, would you agree?

**Comment by laynegt** [comment]
@pixelhandler yeah 2.9 did not have the issue.  Seems to have been introduced in 7e1afe7.

**Comment by bgentry** [comment]
I'm encountering an issue that might be related. My app is transitioning from `/post/1` to `/post/2`, same route but with a different param. The `deactivate` hook is normally not called here. However, if I add a `post-loading.hbs` template and make this same transition, `deactivate` does get called.

Based on the Router documentation (linked above) this certainly doesn't sound correct, so it sounds like either a bug or a doc that needs fixing.

**Comment by pixelhandler** [comment]
@laynegt any luck with 2.16.x ?

**Comment by bgentry** [comment]
@pixelhandler I ran into this on 2.16.x when I tried it the other day. The bug is still active.

**Comment by rwjblue** [comment]
>  My app is transitioning from /post/1 to /post/2, same route but with a different param. The deactivate hook is normally not called here. However, if I add a post-loading.hbs template and make this same transition, deactivate does get called.

In this case you are definitely exiting `/post/`, why would you expect `deactivate` to not be called?

I'm not certain that this is super well understood, so I'll try to explain what I _think_ the disconnect here is.  From @bgentry's example, the following route structure exists:

* `post`
* `post-loading`

In this case, to move _from_ `post` to `post-loading` you absolutely have to exit `post` which is why deactivate is called.

**Comment by bgentry** [comment]
@rwjblue your explanation makes sense and upon closer look I think my issue was not related to this one anyway. Sorry for causing extra confusion here

This issue was describing a bug where the *parent* route calls `deactivate` when a child route transitions to loading, though I haven't verified if it still exists.

**Comment by rwjblue** [comment]
Gotcha, thanks for clarifying that @bgentry. 

I do believe my explanation above also applies to the original posters comment as well. 

In other words, I believe this is intentional (and desired) behavior. If the docs need to be updated to make it more clear, let’s do it. But I don’t think this is a bug...

**Comment by pixelhandler** [comment]
@bgentry @kumkanillam @laynegt @rwjblue closing for now
