### ISSUE TITLE
Form component with bound id and submit input with form attribute doesn't handle submit event

### ISSUE THREAD

**Issue by makepanic** [emberjs/ember.js#15461]
If one uses a component with tagName `form` in combination with the form `id` attribute and an input that uses the `form` attribute, it won't handle the forms submit event.

It gets rendered correctly: 
![20170706-100717](https://user-images.githubusercontent.com/1205444/27902730-02b44cca-6237-11e7-912f-908453f5164f.png)

If one clicks on the `<input type="submit" form={{name}}>`, the `submit` method on the form component won't get called.
The `form` attribute on an `input` element does the following [according to MDN](https://developer.mozilla.org/en/docs/Web/HTML/Element/input#attr-form):

> The form element that the input element is associated with (its form owner). The value of the attribute must be an id of a <form> element in the same document. If this attribute is not specified, this <input> element must be a descendant of a <form> element. This attribute enables you to place <input> elements anywhere within a document, not just as descendants of their form elements. An input can only be associated with one form.

Example [twiddle](https://ember-twiddle.com/b6e35bd02de13aeee6ae0dada1c7760a?openFiles=components.my-form.js%2Ctemplates.components.my-non-id-binding-form.hbs) shows two forms. The first one uses an named input and the second one doesn't.

If one clicks on the second input, the text changes.
If one clicks on the first input, the whole page changes because the form action gets triggered without calling the components submit method.

I'm not sure if i misunderstood the `form` input attribute or if this is a bug in ember.

**Comment by pixelhandler** [comment]
@makepanic I agree this behavior seems like a bug. Thanks for providing the twiddle example :)

However there is a difference between what MDN and general form handling works and using an Ember component with a submit event. Typical HTML form element w/o ember would need  `action` (or input with `formaction` attr) and a `method` (or input with `formmethod` attr) attributes for the default HTML form submit behavior to work.

We assume that a `form[id="myform"]` should be submitted using the `input[type="submit"][form="myform"]` element but we want the submit behavior to work with the Ember.Component#submit event handler instead of using the `form[action="serverAction"][method="POST"]` attributes.

I think that given the difference in implementation using  the Ember framework, we'll need to use an action hander on the form. e.g. `<form on-submit={{(action submit)}}>` or something like that.

I don't think this is a bug but just a scenario that as developer's we need to be more explicit regarding how the Ember component with the `form` `tagName` should behave. Ember gives us a lot of options, including not using default form method/action attributes to submit a form.
