### ISSUE TITLE
ember 2.14.0 debug: classCallCheck issue

### ISSUE THREAD

**Issue by stefanpenner** [emberjs/ember.js#15533]
ember.debug.js in 2.14.0 contains two ember-babel AMD modules, one with `classCallCheck` and one without `classCallCheck` this causes:

```js
Uncaught TypeError: (0 , _emberBabel.classCallCheck) is not a function
    at new ValueReference (vendor.js:28729)
    at vendor.js:28736
    at internalRequire (vendor.js:9308)
    at internalRequire (vendor.js:9304)
    at internalRequire (vendor.js:9304)
    at internalRequire (vendor.js:9304)
    at internalRequire (vendor.js:9304)
    at requireModule (vendor.js:9255)
    at vendor.js:82657
    at vendor.js:82659
```

**Comment by stefanpenner** [comment]
Actually: http://builds.emberjs.com/release/ember.debug.js seems correct, but the file in bower seems to be the offender.

**Comment by stefanpenner** [comment]
hmm bower seems fine too: https://raw.githubusercontent.com/components/ember/2.14.1/ember.debug.js

wtf

**Comment by stefanpenner** [comment]
Ya, I can't actually figure out where this file is coming from for me....

**Comment by rwjblue** [comment]
@stefanpenner the issue is what I was trying to fix here: https://github.com/emberjs/ember.js/pull/15199.  Basically, `ember-template-compiler.js` uses prod but `ember.debug.js` does not.  Since the `ember-babel` module has not already been required at the time `ember-template-compiler.js` is loaded, the subsequent definition of a prod version `ember-babel` clobbers the proper debug build version.

**Comment by ctcpip** [comment]
Is this issue related?  https://github.com/ember-cli/ember-cli/issues/7329

**Comment by rwjblue** [comment]
Ultimately the same issue as https://github.com/emberjs/ember.js/issues/15533.

**Comment by ctcpip** [comment]
this as well? emberjs/ember.js#15671

**Comment by rwjblue** [comment]
This should be resolved now.
