### ISSUE TITLE
input helper's value not working in IE 11/Edge

### ISSUE THREAD

**Issue by jeffrey008** [emberjs/ember.js#15598]
DEBUG: -------------------------------
Ember      : 2.13.4
Ember Data : 2.14.9
jQuery     : 3.2.1
DEBUG: -------------------------------

Do this in template:
`{{input class="btn btn-lg btn-lg-block btn-success" type="submit"  value="Sign in"}}`

The button shows annoying "Submit Query" instead of "Sign in"

**Comment by lifeart** [comment]
@jeffrey008 why you use `input` instead of `button`?

**Comment by pixelhandler** [comment]
@jeffrey008 I typically avoid the input helpers and just use an HTML input, since we can bind attributes directly in the template. I created an ember-twiddle.com example using the code you provided, but unfortunately ember-twiddle.com doesn't with with Edge or IE 11.

So instead used `ember new` to create an app then put `{{input class="btn btn-lg btn-lg-block btn-success" type="submit" value="Sign in"}}` into the application.hbs file.

I can confirm that the input display is not as expected.

![issues-15598-edge](https://user-images.githubusercontent.com/17178/29723259-bf127082-8978-11e7-8933-be735597c922.png)

**Comment by pixelhandler** [comment]
Closing for now, feel free to re-open if you can reproduce in the current release of Ember.

- https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#triaging-policy

**Comment by keanedawg** [comment]
I would like to re-open this. We are experiencing this bug in IE11 on our Ember 3.4 site. One of our engineers was able to recreate this error in a beta version of Ember 3.10.
