### ISSUE TITLE
currentPath does not respect resetNamespace dsl option

### ISSUE THREAD

**Issue by janmisek** [emberjs/ember.js#15728]
Even when `resetNamespace` is used `currentPath` returns path including segments from parent routes above resetNamespace.

Same behaviour observed for:
- `Ember.getOwner(this).lookup('controller:application').get('currentPath')`
- `Ember.getOwner(this).lookup('service:-routing').get('currentPath')`
- `currentPath()` testing helper

**Comment by janmisek** [comment]
```
    this.route('root', {path: '/root'}, function () {
      this.route('reset', {path: '/reset'});
    });
```

link to works properly, following works
```
{{link-to 'reset' 'href title'}}
```
But 
- `Ember.getOwner(this).lookup('controller:application').get('currentPath')`
- `Ember.getOwner(this).lookup('service:-routing').get('currentPath')`
- `currentPath()` testing helper

Returns `root.reset` instead of `reset`

**Comment by Serabe** [comment]
Hello, @janmisek,

this is the expected behaviour of `currentPath`. You are looking for `currentRouteName`.

See [this twiddle showing the difference between currentPath and currentRouteName](https://ember-twiddle.com/f20d82ba73968ed3b81becea9001cf63?fileTreeShown=false&numColumns=0&route=%2Froot%2Freset).

Thanks!
