### ISSUE TITLE
Fix visit() promise resolution

### ISSUE THREAD

**Issue by krisselden** [emberjs/ember.js#16059]
The fix in this PR makes the issue worse, it is now less likely render is fully resolved when the visit promise is resolved.

https://github.com/emberjs/ember.js/pull/14591

This issue causes a lot of tests to force flush the run loop to ensure visit is done rendering.

To clarify, this issue isn't about error handling, it is about actually resolving the promise only when rendering is actually settled.

**Comment by tomdale** [comment]
@krisselden Can you provide some more context about this bug?

> The fix in this PR makes the issue worse, it is now less likely render is fully resolved when the visit promise is resolved.

What does "it" refer to here?

What are the specific behaviors that we need to change about the current implementation for us to consider promise resolution fixed and close this bug?

**Comment by krisselden** [comment]
that the promise resolves here https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/renderer.ts#L194

**Comment by krisselden** [comment]
Also, I think it would be nice to have an API for a promise when rendering has settled.

**Comment by rwjblue** [comment]
As a mechanism to flush out tests that artificially forced visit to behave synchronously, I swapped `Ember.ApplicationInstance.prototype.visit` out to use `run.next` instead of `run.schedule('afterRender', ....)` (temporarily) and then fixed all the test failures. That work is progressing in https://github.com/emberjs/ember.js/pull/16086.
