### ISSUE TITLE
check change in binded values

### ISSUE THREAD

**Issue by mehrajpasha** [emberjs/ember.js#16064]
We can check change in input with "onchange", how to check the change in already binded values. I need to check the change in binded values and call a action. How to do that ?

**Comment by Serabe** [comment]
Hello, @mehrajpasha .

I am closing this since it is not an Emberjs bug. Please, go to #-help channel on Slack. If you are not registered, use the [Slackin app](https://ember-community-slackin.herokuapp.com/).

This is the fourth time we invite you to join the channel and ask for help there. Please, use the Slack for this. Our triaging time is limited and we would be very grateful if we could just go through bugs.

Thank you!
