### ISSUE TITLE
Input helper passed type does not work in Ember 3.1 beta

### ISSUE THREAD

**Issue by rwwagner90** [emberjs/ember.js#16256]
I was working on updating my apps and addons to 3.1 beta and noticed some strange behavior. I have components that wrap the `{{input}}` helper and only the first one was rendering an input. I created a reproduction here https://github.com/rwwagner90/inputs and I played around with it some. It appears the issue is passing `type` down as an argument. It chokes on:

```hbs
{{input type=type}}
```

I also tested this against https://s3.amazonaws.com/builds.emberjs.com/canary/shas/9300d1b7d3aa70987986b1997ecf02a542ea49be.tgz and there did not seem to be any difference.

**Comment by rwjblue** [comment]
Awesome, thank you for the reproduction!

**Comment by Serabe** [comment]
Forked repo. Investigating since I did two changes related to input type, one in Ember and one in Glimmer.

**Comment by rwjblue** [comment]
Seems very bizarre indeed...

**Comment by Serabe** [comment]
Let me write my findings so far, because this is quite strange.

## Background

`input` is neither a component nor a helper. It is referred as a macro, and the closer explanation is that they work like a low-level helper. In any case, this is only important to understand why the code for input does not look like anything familiar for the users of Ember.

`input` requires a [template compiler plugin](https://github.com/emberjs/ember.js/blob/2845af24edc36679fef82b38834e58b8bdfc9428/packages/ember-template-compiler/lib/plugins/transform-input-type-syntax.js) that transforms `{{input type=boundType}}` into `{{input (-input-type boundType) type=boundType}}`.

[`-input-type` is an internal helpers](https://github.com/emberjs/ember.js/blob/2845af24edc36679fef82b38834e58b8bdfc9428/packages/ember-glimmer/lib/helpers/-input-type.ts) that basically checks if the given parameters is `"checkbox"` and returns the name of a component based on that.

## Checking the bug

First thing I noticed is that there was no error in the console and the rendering was working past the first breaking input. Looking more deeply, changing the order of the types, would keep the same result: only the first input would be rendered.

Also, the input being inside a component is required. If we are to add three inputs directly into `application.hbs`, they would just work, which invalidates the theory that the problem is `type` not being handled. Moreover, [if we are to add more `{{input}}`s after the failing component, these just work!](https://github.com/ember-triage/ember.js-16256/commit/6767c142679ceceb2f3882ea9024e67ab6e6e443)

## What is happening?

While checking in the DevTools the execution of the input macro, I saw that [`params`](https://github.com/emberjs/ember.js/blob/2845af24edc36679fef82b38834e58b8bdfc9428/packages/ember-glimmer/lib/syntax/input.ts#L154) had different length from the first execution, to the rest. The rest are missing the first param, the one added by the compiler plugin.

## Summary

* It is not a problem in the input macro handling type.
* It is a problem with the params being passed to the input macro.
* It does not fails if `{{input}}` is directly in `application.hbs`.

**Comment by rwwagner90** [comment]
👏 thanks for the fix!
