### ISSUE TITLE
Unhelpful syntax error message

### ISSUE THREAD

**Issue by GuillaumeGomez** [emberjs/ember.js#16322]
I just updated to ember 3 and got the following error (everything else is working fine):

```
Uncaught Error: SYNTAX ERROR: #if requires a single argument
```

Considering the size of the codebase, I can't figure out where this error comes from (already looked at all `#if` so I suppose I missed one...) and didn't find out how or where it was generated in this repository so I can't send a PR either.

Could you add the full `#if` syntax please? It'd be really helpful...

**Comment by rwjblue** [comment]
Thanks for reporting!  We definitely consider bad error messages like this to be bugs.

The error is being thrown [here](https://github.com/glimmerjs/glimmer-vm/blob/6c107df5859fdcabc192988007f196fe6730c798/packages/%40glimmer/opcode-compiler/lib/syntax.ts#L441). Sadly, by that point in the process we have lost the original syntax and source locations.

I'd propose making an "invalid-syntax-detection" AST transform that we can use to move this specific error (and perhaps any other statically detectable errors that are being thrown in the opcode compiler) so that it can include the template path, line number, and column.

**Comment by rwjblue** [comment]
For anyone looking to pick this up, we need to do something like:

* Add a new AST transform ([this is a good base](https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/plugins/assert-reserved-named-arguments.js))
* Add that AST transform to [this array](https://github.com/emberjs/ember.js/blob/fca8c30837fa36db62aaf4418769ecf486dcb629/packages/ember-template-compiler/lib/plugins/index.js#L19-L37)
* Add a test confirming that the assertion is thrown, given the bad input (something like [this one](https://github.com/emberjs/ember.js/blob/fca8c30837fa36db62aaf4418769ecf486dcb629/packages/ember-template-compiler/tests/plugins/assert-reserved-named-arguments-test.js#L7-L25))

**Comment by GuillaumeGomez** [comment]
What I had in mind was way simpler but this new solution might be more helpful (I just wanted to print the arguments...). I don't have enough time to implement this myself for the moment but if it's still not fixed next time I pass by, I'll give it a look.
