### ISSUE TITLE
Unexpected behavior change of ariaRole with v3.1.0-beta.1 glimmer-vm upgrade

### ISSUE THREAD

**Issue by nbibler** [emberjs/ember.js#16379]
PR #15828 seemed to introduce a (unexpected?) change to the behavior of `ariaRole` on Components.

In previous versions of Ember, the `ariaRole` is allowed to be dynamic and the `role` attribute on the generated element would update as expected. If it were initially falsy, there would be no `role` attribute. If it later became truthy, a `role` attribute would be appended.

Once the PR was merged into v3.1.0-beta.1 (at 36ac96a), there is now a [conditional check](https://github.com/emberjs/ember.js/commit/bedbc2132010cab64f7063c3d1692f5e1a950044#diff-1d6263d5fa618e89a735e9df0fe95f81R418) which _optionally_ binds the attribute. Only if `ariaRole` is truthy at instantiation will it be monitored for future changes. If it's initially falsy, no binding will be setup and any future changes to `ariaRole` will not add a `role` attribute to the element.

The change is highlighted below:

```diff
--- a/packages/ember-glimmer/lib/component-managers/curly.ts
+++ b/packages/ember-glimmer/lib/component-managers/curly.ts
@@ -414,6 +413,12 @@ export default class CurlyComponentManager extends AbstractManager<ComponentStat
         ClassNameBinding.install(element, component, binding, operations);
       });
     }
+    operations.setAttribute('class', PrimitiveReference.create('ember-view'), false, null);
+
+    const ariaRole = get(component, 'ariaRole');
+    if (ariaRole) {
+      operations.setAttribute('role', PrimitiveReference.create(ariaRole), false, null);
+    }
 
     component._transitionTo('hasElement');
```

Was this an intended behavior change? If so, I don't see it called out in the CHANGELOG.

**Comment by rwjblue** [comment]
Oh no! I'm sorry I missed this issue!  The basic change needed here is to do `ariaRole in component` instead of `if (get(component, ariaRole)) {}` like was done above. It will still do less work than before (most components do not have or use `ariaRole` at all), but it will allow a component to _not_ set an `ariaRole` by returning a falsey value.

**Comment by rwjblue** [comment]
Should be addressed by https://github.com/emberjs/ember.js/pull/16563.

**Comment by rwjblue** [comment]
FYI - The fix for this has been pulled into release (for 3.1.x release) and beta (for 3.2.0-beta.x release).  The latest builds (in 10-15 minutes) to the release, beta, and canary channels should include the fix (you can get the latest tarball URL via [ember-source-channel-url](https://github.com/ember-cli/ember-source-channel-url/#command-line-api)).
