### ISSUE TITLE
[ember 3.1.0-beta.1] viewBox attribute on SVG component has incorrect capitalization 

### ISSUE THREAD

**Issue by mlwilkerson** [emberjs/ember.js#16477]
**Summary**

When rendering a component with `tagName` of `svg` and a bound `viewBox` attribute, the resulting DOM element has attribute `viewbox` (without the capital B).

**Impact:** the SVG will have the wrong size. (Observed in Chrome).

[Here is a reproduction of the issue.](https://github.com/mlwilkerson/ember-svg-viewbox-bug)
(I couldn't figure out how to JSBin or Ember-Twiddle it).

This problem does not exist in ember 3.0.0.

Similar past issue: https://github.com/emberjs/ember.js/issues/10303

**Comment by st-h** [comment]
looks like this unfortunately persists with the 3.1.0 release

**Comment by st-h** [comment]
Copied over from #16311 as it seems this applies to this issue only

> st-h:
I tried to create a test first, however my efforts to write something that matches the current implementations only showed that the current test setup happily accepts any diffs in case sensitive bindings (both in glimmer.vm and ember.js). Probably the test helpers should be refined... However, there are too many internals involved and I don't know the codebase well enough to make a substantial decision here.
So, I continued to find out what is actually going wrong and I believe to have found the offending [commit](https://github.com/emberjs/ember.js/commit/30bb21fa907f16a736599277911ecf41cc30a1ad) / [code](https://github.com/emberjs/ember.js/blame/master/packages/ember-glimmer/lib/utils/bindings.ts#L66). This essentially changed using the lower case name of the attribute when setting it within the [install method](https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/lib/utils/bindings.ts#L113)
Yet again, being very new to the ember/glimmer internals, I don't feel comfortable deciding what is the best way to fix this. I am happy to help getting this done with a little support though.

> rwjblue:
> Hmm. That change definitely does odd. Do Ember's own tests pass if you remove that .toLowerCase()? I'm unsure how this could be the cause of <button onClick=(action 'foo')></button)> not working because it seems like it would only be related to component's attribute bindings right?

> st-h:
@rwjblue maybe I should have posted that to the [svg related issue](https://github.com/emberjs/ember.js/issues/16477), as I am not totally sure if both issues really do have the same cause. However, I was specifically looking why an attributeBinding like `viewBox` would end up as `viewbox`.
If I do make requested change there is one test which fails, which specifically [tests for case insensitivity](https://github.com/emberjs/ember.js/blob/master/packages/ember-glimmer/tests/integration/components/attribute-bindings-test.js#L238). Honestly this seems a little odd to me, since I am not used to js being case insensitive.

**Comment by rwjblue** [comment]
Thank you for all that sleuthing @st-h, it is very helpful!

**Comment by st-h** [comment]
@rwjblue happy that this was helpful. I tried to fix that issue yesterday, but came along way too many questions regarding which direction things should actually go and what has been intended and what not. Tried to get some help on slack, but I guess everybody was busy. Happy to see that this is fixed now.
