### ISSUE TITLE
Special kind of Ember object (a proxy) error thrown in ember 3.1

### ISSUE THREAD

**Issue by toranb** [emberjs/ember.js#16521]
I recently upgraded an ember addon from ember 3.0 => 3.1 and found a model class that is created via [Proxy](https://github.com/toranb/ember-cli-simple-store/blob/master/addon/models/record-proxy.js) like so ... (note: RecordProxy is using `ObjectProxy from '@ember/object/proxy'`)

```js
return RecordProxy.create({
  _store: this,
  _type: type,
  _filter_value: actualId,
  _source: this._findAll(type),
  compute() {
    let filter_value = this.get("_filter_value");
    return this.get("_source").findBy(primaryKey, filter_value);
  }
});
```

And constructed it using a model object with a non computed property (ie: vanilla `function`)

```js
import { Model } from 'ember-cli-simple-store/model';

export default Model.extend({
  change_role() {
  }
});
```

Is now throwing an error like so ...

```You attempted to access the `change_role` property (of <(unknown mixin):ember244>).
Since Ember 3.1, this is usually fine as you no longer need to use `.get()`
to access computed properties. However, in this case, the object in question
is a special kind of Ember object (a proxy). Therefore, it is still necessary
to use `.get('change_role')` in this case.```

I'm curious if this is a regression or future deprecation just waiting to happen ;)

If I understand the error  ... as of ember 3.1 I would need to access this `change_role` function with a `Ember.get` ... but prior I could invoke it like a normal function (without `get`) but because it's a function (and not a computed/ or ES5 GETTER) I wouldn't anticipate having to use an explicit `Ember.get` to invoke it.

I had trouble creating this w/ ember twiddle but I was able to `ember new` using 3.1 to prove it's broken. Note: this app works fine if you were to flip the source dependency back to ember 3.0

https://github.com/toranb/simple-store-busted-ember-three-one/commit/427e8057588c1c971474084c48f7b767ff44eb44

Any helpful pointers on how to move forward here? Thank you in advance!

**Comment by rwjblue** [comment]
The issue in this case with ember-cli-simple-store (which doesn't seem terribly simple to me 😉 ) is [here](https://github.com/toranb/ember-cli-simple-store/blob/493398261f9f11eace838b5a9959aeb9079a3fff/addon/models/record-proxy.js#L23). In Ember 3.1 doing that check will trigger the reported assertion because the `unknownProperty` of the proxy assertion will find `change_role` in the underlying model. 

The quick fix workaround is to implement your own `unknownProperty` that always returns undefined during this "copy forward the methods on my underlying model" setup. Something like:

```js
init() {
     // ...snip...
      this.isCopyingMethods = true;
      for(let method in model) {
            if(typeof model[method] === "function") {
                if(!this[method]) {
                    this.proxyMethod(method);
                }
            }
        }
        this.isCopyingMethods = false;
},

unknownProperty() {
  if (this.isCopyingMethods) { return; }

  return this._super(...arguments);
}
```

To fix this issue generically means either:

1. Make [the proxy assertion](https://github.com/emberjs/ember.js/blob/541b9aca02c2062d49e20e79e78bf0a8304ba0cf/packages/ember-runtime/lib/system/core_object.js#L121) ignore when the type of the result is `'function'`. This feels _somewhat_ like "whack-a-mole" but may actually be a nice heuristic for the sorts of "check if this method exists before calling it" types of things (see [list of exclusions which are nearly all functions](https://github.com/emberjs/ember.js/blob/541b9aca02c2062d49e20e79e78bf0a8304ba0cf/packages/ember-runtime/lib/system/core_object.js#L105-L112)).
2. Change the assertion into a warning...

**Comment by toranb** [comment]
@rwjblue thanks for the deep dive into `ObjectProxy` ! I'm not ignoring you - just working on a PR to prevent this strict assertion from throwing when the result is `typeof` function

**Comment by toranb** [comment]
@rwjblue any pointers on this test case? I cannot seem to get it to blow up w/ that assertion error 

```js
        let proxy = ObjectProxy.extend({
          init() {
            this.foobar = function() {
              let content = get(this, 'content');
              return content.foobar.apply(content, []);
            }
          },
        }).create({
          content: {
            foobar() {
              return 'xoxo';
            },
          },
        });

        assert.equal(proxy.foobar(), 'xoxo', 'should be able to use a function from a proxy');
```

**Comment by toranb** [comment]
@rwjblue closing this out in favor of #16560 

Thanks again for all the help Robert !!!

**Comment by rwjblue** [comment]
No problem! Happy to help!
