### ISSUE TITLE
Router service: Failing with query parameters on application controller

### ISSUE THREAD

**Issue by jnfingerle** [emberjs/ember.js#16594]
Hello,

I'm not really sure what's really the problem here. Anyway, when trying to migrate to the router service I got a strange error message. I've distilled it down to the following minimal test case:

* The application controller has a query parameter
* I've got two routes, route A uses the router service to transition to route B in afterModel
* I've got an acceptance test that loads route A with the query parameter set

This leads to "Assertion Failed: You passed the `application:testParam` query parameter during a transition into application, please update to testParam".

The checkin leading to this behaviour can be found here: https://github.com/jnfingerle/emberjs-issue-16594/commit/5b86444f1a5e68604be14542e36dc22c0128dcff

I believe this to be a bug. If the problem should be in my code, a hint would be helpful.

Cheers, 
Jan Niklas

**Comment by btecu** [comment]
You don't need to inject the router in routes.

You can just do:
`this.transitionTo(...)` inside your `afterModel`.

**Comment by jnfingerle** [comment]
What @btecu writes is obviously correct, but this is only due to this beeing an oversimplified test case. 

I have unsimplified my test case a bit: https://github.com/jnfingerle/emberjs-issue-16594/commit/adaf7a45f4617c2f878a17c8c300473afa752451

I don't use the 'router' service in the route, but my own 'foo' service that in return uses the 'router' service. The assertion still fails, but I don't have the easy way out of using `this.transitionTo(...)`.

**Comment by Serabe** [comment]
Forked repo at https://github.com/ember-triage/emberjs-issue-16594

**Comment by panthony** [comment]
I have the same error on ember 3.0.

The `transitionTo` is called from a component (routeA) to redirect into a siblings route.

It's really weird because if I access the routeA directly, then get redirected, it works.

If I access the application for the root, then navigate all the way to routeA, THEN the error will occurs.

The offending query param is on the siblings's parent route not the application route.

**Comment by Gaurav0** [comment]
Seeing this in Ember 3.3

**Comment by raphaelns-developer** [comment]
Same here! In my case the error is printed on the console, however the `replaceWith` work as expected, but only if is not a test because in the test the error is printed and nothing happen.

**Comment by gibso** [comment]
i got the same problem, seems like updating query-params in the application route is a bad idea.

**Comment by snewcomer** [comment]
Got the same problem (different route) here. Mind has a query param of `id`.  Seems there is a slight different where the router service does some cleansing of the query params before calling the router microlib transitionTo method.  I think this could be tracked down.

**Comment by st-h** [comment]
This issue broke ember-simple-auth @1.9.2 where they cleanup up the code related to routing. Previous versions would use the internal ember router due to an overridden computed property. So, older versions still work fine, however show the `computed-property.override` deprecation.

**Comment by st-h** [comment]
@snewcomer I took some time to look into this, and I don't think cleansing is the reason here:

in `@ember/-internals/routing/lib/system/router.js`:`_hydrateUnsuppliedQueryParams()` has a property `_fromRouterService`. This property essentially makes the assertion we see fail, as it is the only thing that differs when using the router service.

This value is previously called `_keepDefaultQueryParamValues` in `@ember/-internals/routing/lib/system/routerjs`:`doTransition()` when not using the router service.

When using the router Service it is always set to true.

I still have troubles understanding the actual meaning of what the assertion is trying to tell me. And I can't really figure out the reasoning behind the variable called `_fromRouterService` - unfortunately this also is the only undocumented param. I'll try and see if I can find someone who can shed some light into how things are supposed or intended to be.

**Comment by st-h** [comment]
@rwjblue I was going through the history of `@ember/-internals/routing/lib/system/router.js` as I was unable to find anyone who would be able to help me with details about the router, and it seems that your name shows up next to the assertion, I can not make any sense of. Would you have some time to help fix this issue?
