### ISSUE TITLE
Feture Request: Add component name into glimmer error

### ISSUE THREAD

**Issue by lifeart** [emberjs/ember.js#16618]
We have error like this - `Uncaught Error: a glimmer transaction was begun, but one already exists. You may have a nested transaction`;

![image](https://user-images.githubusercontent.com/1360552/39693180-d4743276-51eb-11e8-9060-874cdc7848ee.png)

And this is defenetly an component issue, but, if I have 20+ components on page - it's hard to figure out error location.

**Comment by rwjblue** [comment]
We have worked hard to ensure that these transaction out of sync issues are not constantly thrown once we end up down a bad path. If there are specific circumstances where they still happen and are not being recovered from please report them (or submit a failing test PR [around here](https://github.com/emberjs/ember.js/blob/4a98e1610b795edb544513f10a8870af1375141d/packages/%40ember/-internals/glimmer/tests/integration/components/error-handling-test.js#L8)).

Generally speaking, the specific error mentioned above doesn't _have_ any particular component relationship so it isn't obvious how we could do more to associate them.

I'm going to go ahead and close this since we've worked to improve this experience since this was originally reported (very sorry it took so long to get back to you on it though 😢 ), and I hope that you do file new issues or failing test PR's for scenarios that you still happen to be hitting.
