### ISSUE TITLE
Memory leak in IE11

### ISSUE THREAD

**Issue by dwickern** [emberjs/ember.js#16634]
I'm seeing memory leaks in IE11 after upgrading ember 2.18.2 to 3.1.2. Specifically between versions 3.0.0 and 3.1.0-beta.1.

On ember 3.1.0-beta.1, after ~350 acceptance tests, IE11 memory usage climbs to 2 GB then tests start failing with
```
Error: Out of memory
   at startRouting (assets/vendor.js:57541:11)
   at startRouting (assets/vendor.js:36654:7)
   at didBecomeReady (assets/vendor.js:37395:11)
   at invoke (assets/vendor.js:34638:17)
   at flush (assets/vendor.js:34558:25)
   at flush (assets/vendor.js:34711:21)
   at end (assets/vendor.js:34844:17)
   at _run (assets/vendor.js:35215:21)
   at run (assets/vendor.js:34902:13)
   at run (assets/vendor.js:51927:5)
```

On ember 3.0.0, all 450 acceptance tests run and IE11 memory usage is around 1 GB (which is high but not unusual for IE). For comparison, Chrome uses about 450 MB then drops to 200 MB after the tests finish.

My [attempt to bisect](https://gist.github.com/dwickern/486fd13b235d1132cfdfd92980e8c140) seems to point to #15828 but there's a big range of commits in there that I can't build and/or run.

**Comment by rwjblue** [comment]
Haven't had a chance to dig in much yet, but I did capture some memory profiles of the reproduction app. Attaching here (in the hopes that someone has the time to dig in before me :wink: )...

[ie11-leak-repro-dump.zip](https://github.com/emberjs/ember.js/files/2002757/ie11-leak-repro-dump.zip)

**Comment by MelSumner** [comment]
@dwickern what version of Windows & IE11?

**Comment by rwjblue** [comment]
My .zip above was from Windows 8.1 with IE 11.0.9600.16384 (from the http://modern.ie VM's).

**Comment by rwjblue** [comment]
I re-ran the same tests with `ember test --server --environment=production` and was able to run through the full test suite without memory growth (took heap snapshots approximately every 100 tests).

This seems to indicate to me that the leak must be related to a debug build specific feature...

**Comment by rwjblue** [comment]
As I started digging into what the differences were in debug builds vs prod builds, I noticed that in prod we are not rendering anything (whereas in debug we render the `{{welcome-page}}` component). Removing that component invocation enables debug builds to pass without memory growth.

This made me attempt to add a very simple component with the same DOM as the `welcome-page` template which resulted in no memory growth (and all tests completed). The primary difference between this test run and the way the `welcome-page` addon is setup is that this tested with a normally resolved template whereas the addon imports its layout and reexports it. 

After updating `ember-welcome-page` (locally) to make its template resolved (instead of imported and set as the `layout` property on the component's JS file), I was able to re-run the test suite without any memory growth.

**Comment by rwjblue** [comment]
I just confirmed that the latest beta still demonstrates the memory leak, however latest canary builds do not.

**Comment by dwickern** [comment]
I was testing on Windows 7 with IE 11.0.9600.18860

**Comment by rwjblue** [comment]
I have cherry-picked the following commits into the beta branch:

* 2c61d70fcb9d83f1d38158a3694e0e4935c59479
* 5b8c5318058269cff64437419876f160dd9ae56a
* b0ad54e8ea56184d2b29d97fa96eba0d82f72beb
* 83d65e7868415204d85b0e6c1b74de4eefbe739a

Prior to these changes the `beta` branch exhibited the leak with the provided reproduction (in IE11), after these commits there is no leak and the reproduction runs to completion.

**Comment by rwjblue** [comment]
Once CI is completed and publishes the beta builds, you should be able to test via:


* `npm i -g ember-source-channel-url`
* `ember-source-channel-url beta`
* Update your `package.json` to specify the URL printed above for `ember-source`

**Comment by dwickern** [comment]
I can confirm that it's fixed now. Thanks!
