### ISSUE TITLE
Ember don't update component attr binding or array sort

### ISSUE THREAD

**Issue by lifeart** [emberjs/ember.js#16630]
Demo: https://ember-twiddle.com/c39ee86b312ecb9a009aa2994df5e492?openFiles=templates.components.item-list.hbs%2C

Given: 
* an array of Ember objects
* computed from objects array, and it just sort given array
* route template (render sorted list)
* component (render sorted list)

After array sort, list in route template rerendered, but, component has old sorting state

**Comment by lifeart** [comment]
I know I can do `get('items').slice()` or `A().concat(this.get('items'))`, but, why filtered array render list successfully updated inside route template but not inside components? If this is a "feature", it must be documented, to avoid user confusion.

**Comment by lifeart** [comment]
looks related to https://github.com/emberjs/ember.js/issues/10405

**Comment by lifeart** [comment]
Answer is: `because the route template is in the same context as the originating computed property
so the property is updated there, but it's not accross the object boundary`

**Comment by lifeart** [comment]
But, It looks strange and may confuse anyone. How we can teach this?

**Comment by rwjblue** [comment]
The issue here is that the actual identity of the `sortedItems` array is actually the same, so when the `item-list` component internally does `this.set('sortedItems', passedInValue)` the internals of `Ember.set` dictate that the `this.sortedItems` in the `item-list` is the same exact value as it was before and it there does **not** notify that the property has changed (and ultimately does not rerender).

The right fix (IMHO) is to avoid this completely, changing the `item-list` to directly use the array passed in (swap to `{{#each @sortedItems as |item|}}`). This resolves the issue, and makes it much clearer in the template that the `item-list` component itself is not doing _anything_ "special". Demo here: https://ember-twiddle.com/2ee87cc87d2cd28d38d27afd3db523aa?openFiles=templates.components.item-list.hbs%2C

I'm going to close this issue though, as the main focus of the octane edition is to make this entire mental model simpler (things like glimmer components, named arguments, tracked properties, etc).
