### ISSUE TITLE
Ember Website is not working on IE. 

### ISSUE THREAD

**Issue by sukumarvangala** [emberjs/ember.js#16717]
Hi, 

Our website is not working on IE but it is fully functional on Microsoft Edge, Google Chrome, Firefox and Safari. 
We are using Windows 10 OS version and IE 11 browser version. 
Console doesn't show any errors either. 
Am attaching the console image. 
We officially don't support IE, so for our last 5 releases we did not test on IE before releasing our new versions. Now we decided to just show a huge warning header on all the pages. We are not able to make it work and warnings/erros doesn't point anywhere. 

Following is our technology stack:

Ember-cli : 2.12.2
node: 7.9.0 
Server OS: CentOS 7 

These are our dependencies in bower.json: 

    "ember": "2.4.6",
    "ember-cli-shims": "0.1.1",
    "ember-cli-test-loader": "0.2.2",
    "foundation": "~5.5.0",
    "sinon": "1.17.1",
    "lodash": "~3.10.1",
    "pretender": "0.10.1",
    "moment": ">= 2.8.0 < 2.11.0",
    "moment-timezone": ">= 0.1.0 <= 0.5.0",
    "chartist": "0.10.1",
    "pickadate": "amsul/pickadate.js",
    "d3": "~3.5.14",
    "pace": "^1.0.2",
    "hammerjs": "^2.0.6",
    "matchMedia": "0.2.0",
    "FileSaver.js": "eligrey/FileSaver.js#1.3.3",
    "hammer.js": "^2.0.8",
    "pikaday": "^1.4.0"

Can anyone help me to fix this error. 
<img width="774" alt="embererror1" src="https://user-images.githubusercontent.com/36825830/40933655-c03c422c-67f7-11e8-9176-cc8302be030b.PNG">
<img width="782" alt="embererror2" src="https://user-images.githubusercontent.com/36825830/40933656-c05432c4-67f7-11e8-925e-dd12be56d05f.PNG">

Thanks in advance. 

Regards,
Sukumar

**Comment by herom** [comment]
We are working with Ember 2.16 in our Apps and they all work on IE11 - I don't think that's something which is Ember-specific.

**Comment by jenweber** [comment]
Hi @sukumarvangala! I want to share some additional resources to help you figure out what is going on. There is a list of [community forums and chat](https://www.emberjs.com/community/) where you can ask questions and get help debugging whatever is causing the issue. In those forums, please share these same details plus any custom configuration in the build, whether you are using fastboot, etc (no console errors makes me suspect fastboot problems).

Through version 2.18, IE10 was supported in Ember.js. You can read more [here](https://www.emberjs.com/blog/2018/02/14/ember-3-0-released.html). 

This issue should be closed since this is not an ember.js main codebase bug. Good luck!
