### ISSUE TITLE
My PR wasn't cherry picked to the last 3 releases. 3.1.2, 3.2.0, and 3.2.1

### ISSUE THREAD

**Issue by Gaurav0** [emberjs/ember.js#16762]
Apologies for my tone, but this is very frustrating. I cannot seem to get the Transition class into the docs.

https://github.com/emberjs/ember.js/pull/16474

@kategengler What should I do next time?

**Comment by acorncom** [comment]
@Gaurav0 I think it's possible that the scripts used for automating cherry-picking to LTSes doesn't work that well with docs. I believe @toddjordan has run into snags with that as well. Maybe we could work on improving those so that we can get docs fixes into releases more quickly?

**Comment by Gaurav0** [comment]
There is a script? Is it on github? I was told by @rwjblue and others that this process was manual. Can I get a link to the script?

**Comment by rwjblue** [comment]
The process is roughly that we review the commit history since the last beta or release, and cherry-pick things that are labeled for another branch. The fact is that we missed these commits (and didn't correct it when the issue was brought up in slack). We do our best, but these sorts of things do happen. I'm sorry.

If you _for sure_ want to get something into a specific branch, and we missed the cherry-pick, you can definitely submit pull requests directly to that target branch. In this case, it would mean doing the cherry-pick of the commits in https://github.com/emberjs/ember.js/pull/16474 locally and then submitting a PR targeting the `release` branch.

**Comment by Gaurav0** [comment]
It appears that the commits are already in the `release` branch?

**Comment by rwjblue** [comment]
Yep, it was done yesterday. We are working on another patch release so we just went ahead and took care of it with the other cherry-picks that we needed.

**Comment by Gaurav0** [comment]
@rwjblue Thank you!
