### ISSUE TITLE
DS.PromiseManyArray map with unexpected behavior

### ISSUE THREAD

**Issue by phsantiago** [emberjs/ember.js#16918]
**What is happening?**
When I use the map to change the content inside of my data structure it returns me a plain array.

**What is the expected behavior?**
I was expecting the map return the same data type.

**Example:**
![image](https://user-images.githubusercontent.com/10498833/44746760-a1941480-aae1-11e8-8570-a8657ff8958e.png)

I think this behavior occurs when we use the Ember.A to generate the map response at this line:
https://github.com/emberjs/ember.js/blob/v3.2.0/packages/ember-runtime/lib/mixins/array.js#L617

**Comment by locks** [comment]
Hi @phsantiago, do you remember what the situation was that the type of the returned array mattered?

**Comment by pzuraq** [comment]
@phsantiago I don't think this is really a bug, at least not for `DS.PromiseManyArray`. It doesn't really make sense for Ember Data's array data-structures to return new instances of themselves from methods like `map`, since the arrays tend to represent some specific canonical state, so them not relying on `map` to return a standard array is likely intentional.

With that in mind, I don't think we could change the behavior here even if we wanted to 😕 it would be a pretty major breaking change. Going to close this for now.
