### ISSUE TITLE
Deactivate hooks called based on where error is handled in tests

### ISSUE THREAD

**Issue by dexturr** [emberjs/ember.js#16939]
I have found recently, when testing error states, that which routes have their `deactivate` hook called at the end of a test is dependent on where error is handled.

For example if an error is handled on a global `error.js` file then only the application route's `deactivate` hook will be called, regardless of deeply nested the route that caused the error was. If the the error is handled next to the route that causes the error in `{routename}-error.js` then all routes above this one will have their `deactivate` hook will be called.

I would expect at the end of a test that the `deactivate` hook of each route is called regardless of where the error is handled. 

I have produced a repo which demonstrates the issue [here](https://github.com/dexturr/ember-deactivate-issue).

This is my first Ember issue, so I am happy to provide any extra information that may have missed.

**Comment by pixelhandler** [comment]
@dexturr thanks for posting this issue and providing a example reproduction :)

Yeah i agree fault tolerance is important, and in the case of an error on a route that event bubbles up to be handled as the application determines by either using an `error` handler defined with the route's `actions` hash, or as an error sub-state when an error template exists. You can use both but in order to also use the error template and the error event handler (on actions) the error action must return `true`. At least that is what I have observed on the application route.

What I've experience is that the application must be very intentional about fault tolerance. So if you want to utilize the `deactivate` hook I believe you must also handle the error on that route. 

I think it would be ideal if any leaf (child) routes did call their deactivate hook when an error state is entered. But as you have discovered that may not be the case. I think the work around may involve using an error handler on the route that you expect to also use the deactivate hook with and return true from that error handler. That error handler may have to perform the same work as the deactivate hook does in the cast of an error.

I think this is a bug in the framework but I'm not sure how easily it can be solve.

Have you found a work around?

**Comment by pixelhandler** [comment]
@dexturr any update ? did you find a work around ?
