### ISSUE TITLE
release.json not updating

### ISSUE THREAD

**Issue by kategengler** [emberjs/ember.js#17297]
https://s3.amazonaws.com/builds.emberjs.com/release.json references 3.4.4 and is not updating. This is used by ember-try and `getChannelURL`

**Comment by rwjblue** [comment]
I was thinking this might be because we don't publish any builds when we are publishing a tag itself:

https://github.com/emberjs/ember.js/blob/60a538c01e141569531c63673a6f9bbdad780a49/bin/publish_to_s3.js#L20-L31

I pushed a few commits to `release` just now (changelog entry for 3.4.7), lets see what https://travis-ci.org/emberjs/ember.js/builds/465130878 does...

**Comment by kategengler** [comment]
Yep. I self assigned because I want to finish this up today.
