### ISSUE TITLE
Computed property recomputes two times for a single set

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#17393]
[Here is a reproduction](https://github.com/boris-petrov/ember-recompute-bug).

`ember server`

Then open http://localhost:4200/ and type in the console `x.set('a', Ember.A([{ a: 2, b: 4 }]))` - you will see `computing y` twice in the console. If you remove any of the two dependencies of `y` (i.e. make it either `x.@each.a` or `x.@each.b`) - then it computes only once.

I think this is a bug.

**Comment by jacobq** [comment]
I looked at your repro just for fun, and that behavior does surprise me, but at the same time it seems to be caused by returning the computed property from the observer. I don't understand why one would ever want to return a value from an observer. Could you explain this more?

I also tried tweaking your example a bit in https://github.com/boris-petrov/ember-recompute-bug/pull/1 in case it helps someone identify why this happens.

**Comment by boris-petrov** [comment]
@jacobq - thanks for the answer. Actually the return from the observer is just a leftover as I translated this code from CoffeeScript. Getting the value is what is important, returning it does nothing. Our use case is of course much more involved, I don't want to even begin explaining it, but it boils down to essentially this code.

Thanks for the expansion of the example! We've workarounded (not sure if there is such a word) the issue for now but it would be nice if there is a fix at some point. :)

**Comment by boris-petrov** [comment]
Yes, the observer does access the computed property - in a transitive way, but in the end it does. And yes, as you've noticed - if the observer is removed, then the bug goes away.

I'm not sure whether this needs any kind of "synchronization". I wouldn't think it does - it's simple getters and setters (and there is no asynchrony anywhere). And generally I'm against putting randomly stuff like `scheduleOnce` especially when I don't understand why it needs to be there.

**Comment by jacobq** [comment]
Out of curiosity, does the recomputation of the computed property cause a problem (it should should be a pure function of the values it depends on so should produce the same result if re-evaluated) or are you just concerned about the performance?

**Comment by boris-petrov** [comment]
It is a "pure" function, yes, however it causes a search to the BE to be repeated with the same query - we have our own computed properties that do searches and they do a new query when the computed property is recomputed. In this case it recomputes twice with the same value and causes two searches for the same thing. Not the end of the world, just a performance bug. :)

**Comment by zeroe454** [comment]
`index.html > <!-- -->`

**Comment by pixelhandler** [comment]
@boris-petrov I notice `computed('x.@each.{a,b}'` has two dependencies `'x.@each.a'` and `'x.@each.b'` and setting a single object `x.set('a', Ember.A([{ a: 2, b: 4 }]))` with both `a` and `b` meets that criteria. I think that a computed has to be invoked for each dependent key, resulting to two calls to the function, so logging twice.

- https://github.com/boris-petrov/ember-recompute-bug/blob/master/app/controllers/application.js

I don't think this is a bug.

**Comment by jacobq** [comment]
Additionally, if the observer is modified so that it does not access the computed property then it works OK. Perhaps it might be related to how CPs are lazily-evaluated / cached.

**Comment by bekzod** [comment]
this is definitely bug

**Comment by urbany** [comment]
I'm also being hit hard by this, is this a bug?

**Comment by richard-viney** [comment]
If it helps, the advice I generally give is:

1. Don't use observers
2. If you must, do almost nothing in the body of them. They should probably `scheduleOnce` something for later in the runloop as was mentioned above, or maybe set a simple boolean flag. Nothing more than that, including computed property evaluation, use of `set()`, etc.

This will certainly be overly cautious in some instances, but it also eliminates a lot of problems due to how observers (currently) run synchronously.

_Disclaimer: Haven't looked in detail at the precise repro case described here._

**Comment by boris-petrov** [comment]
This seems fixed in 3.25.1. Not sure when but the original issue no longer happens. Thanks!
