### ISSUE TITLE
Changes between ember 3.5 and 3.6 for es2015 class create

### ISSUE THREAD

**Issue by toranb** [emberjs/ember.js#17416]
Today I upgraded from ember 3.5 to 3.6 and found a failing test case in which es2015 class create was failing to pass along the attrs for a component. The test case for this is fairly straight forward

```js
  test('should render attrs', async function(assert) {
    assert.expect(1);

    this.set('myName', 'Dustin');
    await render(hbs`{{count-list name=myName}}`);

    assert.equal(find('.greeting').textContent, 'Welcome back, Dustin!', 'should render attrs provided to component');
  });
```

The component looks something like this

```js
import Component from '@ember/component';
import hbs from 'htmlbars-inline-precompile';
import { connect } from 'ember-redux';

const stateToComputed = function(state, attrs) {
  return {
    greeting: `Welcome back, ${attrs.name}!`
  };
};

const CountListComponent = Component.extend({
  layout: hbs`
    <span class="greeting">{{greeting}}</span>
  `
});

export default connect(stateToComputed)(CountListComponent);
```

I take this^ and pipe it into a HOC to return my wrapped es2015 ember component like so

```js
import { defineProperty } from '@ember/object';
import { core, update, destroy } from './core';
import { inject } from '@ember/service';

export default function wrapEs2015Class(stateToComputed, dispatchToActions, WrappedComponent) {

  defineProperty(WrappedComponent.prototype, 'redux', inject('redux'));

  return class Connect extends WrappedComponent {

    constructor() {
      super(...arguments);
      core.call(this, stateToComputed, dispatchToActions);
    }

    didUpdateAttrs() {
      super.didUpdateAttrs && super.didUpdateAttrs(...arguments);
      update.call(this);
    }

    willDestroy() {
      super.willDestroy(...arguments);
      destroy.call(this);
    }

  }
}
```

When running with ember 3.6 the name attribute (shown in the test case above) isn't available in the constructor. The screenshot below is from my ember 3.6 test case and you will notice it's missing the name attribute.

![busted](https://user-images.githubusercontent.com/147411/50501623-18ed9c80-0a1f-11e9-84e7-dc20de63c54e.png)

To contrast this with ember 3.5 look at the screenshot below. You will note that name is populated and the template renders the attrs as designed.

![working](https://user-images.githubusercontent.com/147411/50501619-1428e880-0a1f-11e9-8ef3-06376d498f0b.png)

I'm writing in to ask for help as an addon author because this was working in ember 3.5 and it feels like a regression given the changes recently in ember 3.6 but I'm unsure where to start as I'm not deeply connected with core about how this should work. Any help validating this as a true defect would be greatly appreciated.

You can see the failing test in action if you clone this branch, yarn up and run `ember test -f toran`

https://github.com/ember-redux/ember-redux/commits/branches/bustedEmber

**Comment by pzuraq** [comment]
The change in behavior here is a result of the change of the constructor that was proposed in the [native class constructor update](https://github.com/emberjs/rfcs/pull/337), and that shipped in 3.6. 

Before the change, arguments passed to components were available by the time the `constructor` ran, which meant that they would be overridden by class field defaults and was a very bad DX. After the change, arguments are assigned _after_ the constructor has run, but _before_ `init` is run. This results in a better DX overall, but was a minor breaking change. 

In the RFC the fact that this was a breaking change was discussed, and we decided that because native classes had never actually shipped, this was not a breaking change to a _public_ API. However, I understand this is definitely a bit painful, and am happy to help figure out a path forward!

**Comment by lifeart** [comment]
```
init() {
  super.init(...arguments);
}
```


``` constructor -> init ```

**Comment by pzuraq** [comment]
For sure, so calling super in all class methods should use [standard class syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Super_class_calls_with_super) for calling `super`, including in `init`:

```js
class MyComponent extends Component {
  init() {
    super.init(...arguments);
  }
}
```

Most users should be able to switch from `constructor` to `init` and things _should_ just work. Class field behavior may change, since they won't have access to the values passed into `create`, but otherwise things should generally be the same.

As for supporting multiple behaviors in your addon, you can probably use [ember-compatibility-helpers](https://github.com/pzuraq/ember-compatibility-helpers). This addon gives you some importable functions and constants that allow you to run code based on what version of Ember the host app is using - and best of all, any unused code gets completely removed from the build.

Unfortunately, users who are using native class syntax will still have to update, there isn't really a way around that 😕 we could write a codemod that helps them do this if you think it would be helpful though!

**Comment by toranb** [comment]
@pixelhandler happy to close it out - seems I need to keep up more w/ the RFC process. For now I'll see if I can get familiar w/ the compatibility helpers @pzuraq  mentioned to keep my v4.X release of ember-redux rolling w/out issue.

Thanks all for the help today!

**Comment by toranb** [comment]
@pzuraq  I was able to get this supported in my addon by including a special shim for ember 3.6+ 

The interesting part is that this^ shim mostly fixed EmberObject based components because my [es2015 class components](https://github.com/toranb/example-ember-three-six-app/blob/master/app/components/baz-baz.js#L32) work with either `init` OR `constructor` in 3.6 - fun times! Likely `init` is the preferred path going forward so I've made a comment to use `init` w/ a reference to your RFC
