### ISSUE TITLE
Replace `valueForCapturedArguments` with CapturedAruments#value

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#17492]
https://github.com/emberjs/ember.js/blob/726c4e2a22dc9eb9e92e749ba754a2d2fde4f2cd/packages/%40ember/-internals/glimmer/lib/utils/managers.ts#L29-L34

should be replaced with usage of the new `CapturedArguments.prototype.value` method added in https://github.com/glimmerjs/glimmer-vm/pull/832. This will require updating to a glimmer-vm version _after_ 0.38.0.

**Comment by eplata31** [comment]
Hello, do you still need help with this?

**Comment by eplata31** [comment]
I think this issue is solved by commit [[FEATURE ember-glimmer-angle-bracket-built-ins]](https://github.com/emberjs/ember.js/commit/0cffa18e02a682ea413946685a5acc6e3d04101d#diff-9e1df4468cde84ba798631cefe8a0930) and refactor [#17788](https://github.com/emberjs/ember.js/pull/17788). If so please let me know and it might be good to close the issue.

**Comment by rwjblue** [comment]
Awesome, thank you for tracking that down!

**Comment by eplata31** [comment]
Glad to help :smiley:
