### ISSUE TITLE
Calling super inside the init raises an invalid error message

### ISSUE THREAD

**Issue by CodingDive** [emberjs/ember.js#17490]
Hey there, thank you for all the effort you put into this framework.

I just upgraded a bunch of dependencies and realized that I now have to change my code from the `constructor` to `init` when inheriting a framework object. This was described in detail in the [rfc](https://github.com/emberjs/rfcs/blob/master/text/0337-native-class-constructor-update.md). I then got following error
```
Error: Assertion Failed: You must call `this._super(...arguments);` when overriding `init` on a framework object. Please update <component> to call `this._super(...arguments);` from `init`.
```

I was already calling `this._super(...arguments)` inside the init and found this [comment](https://github.com/ember-decorators/ember-decorators/issues/329#issuecomment-443769531) saying that one should actually call `super.init(...arguments)`.

**Comment by pixelhandler** [comment]
This article suggests we don't currently have a proper assertion. https://www.pzuraq.com/emberjs-native-class-update-2019-edition/

Also mentions this lint rule is helpful, https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-ember-super-in-es-classes.md#rule-name-no-ember-super-in-es-classes

> super vs. _super()
> When using native classes, you should never use this._super(). Unfortunately, there is not currently an assertion that prevents this (although we would like to add one), but there is a linting rule included with eslint-plugin-ember.

**Comment by cah-briangantzler** [comment]
Just spent a couple hours trying to figure out the problem due to this incorrect message. Was definitely stuck in a rut attempting to follow the instructions in the error message which  just wasnt working.

I did notice the lint rule, but didnt read it as it seemed to contradict the error message. Following the lint rule would have given me what I needed.

To that end, would it be better to remove the incorrect message but leave the lint link?
