### ISSUE TITLE
old style class binding syntax does not work in angle bracket invocations

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#17771]
We don't currently support...

```hbs
<SomeOldSchoolComponent @classNameBindings='foo:foo-is-true:foo-is-false' />
```

...while...

```hbs
{{some-old-school-component classNameBindings='foo:foo-is-true:foo-is-false'}}
```

...works. Is this ok?

See https://github.com/emberjs/ember.js/blob/master/packages/ember-template-compiler/lib/plugins/transform-old-class-binding-syntax.ts

**Comment by rwjblue** [comment]
Ya, we should fix, though clearly it isn't a giant issue.

**Comment by selvaa89** [comment]
We are using this syntax and current blocked from using angle brackets because of this issue. Can this issue be fixed?

**Comment by btecu** [comment]
@selvaa89 You can modernize the syntax since that `classNameBindings` will be going away:
`<SomeOldSchoolComponent class={{if foo "foo-is-true" "foo-is-false"}} />`

**Comment by pzuraq** [comment]
Since the old `classNameBindings` syntax is [now deprecated](https://github.com/emberjs/rfcs/blob/master/text/0691-deprecate-class-binding-and-class-name-bindings.md), I don't think it makes sense to try to resolve this feature gap any more. I'm going to close this issue, but feel free to reopen if you still feel like this hasn't been resolved.
