### ISSUE TITLE
Acceptance Test - `this` is undefined

### ISSUE THREAD

**Issue by HEYGUL** [emberjs/ember.js#17796]
Hi 👋!
I am very new to ember (but not JS).

I am following the official tutorial and everything was fine.
I am stuck with a strange error.
I am trying to do the exact same test as here: [https://guides.emberjs.com/release/tutorial/model-hook/](https://guides.emberjs.com/release/tutorial/model-hook/)

```
test('should list available rentals', async (assert) => {
    await visit('/')
    assert.equal(this.element.querySelectorAll('.listing').length, 3, 'should display 3 listings')
  })
```

The test always fails with this message:
```
Promise rejected during "should list available rentals": Cannot read property 'element' of undefined
```

That leads me to think `this` is undefined but In cannot figure why.
Any clue ?

**Comment by pzuraq** [comment]
Hey there! The issue is that you are passing an _arrow_ function to the test helper. Arrow functions don't have a `this` context, so they default to the parent context. When you do `this.element`, it should be referencing the _test_ itself, not the test module.

You can fix this by passing the `function` keyword here. I generally recommend always using `function` instead of `() =>` because of this:

```
test('should list available rentals', async function(assert) {
```

**Comment by HEYGUL** [comment]
Indeed! Shame on me.

Thank you for the quick reply
