### ISSUE TITLE
LTS 3.4 each yield inner contextual component invocation not working

### ISSUE THREAD

**Issue by Samsinite** [emberjs/ember.js#17883]
I have an example twiddle at https://ember-twiddle.com/a49bf7882f7779577a63543904ce8d1a?openFiles=twiddle.json%2Ctemplates.components.x-list-item.hbs

This seems to work on the latest, so the fix may easily be back-portable? Sorry if this is a duplicate.

**Comment by locks** [comment]
Hey @Samsinite, thanks for reporting.
Unfortunately, if I remember the situation correctly, the fix is a bit in the weeds of the rendering engine code and the backporting the fix to 3.4 might have unintented side-effects. Did you check in 3.8, the nexct LTS release?

I'll close as wontfix due to the mentioned above 🙇
