### ISSUE TITLE
application/vnd.api+json forced on JSONAPI Adapter

### ISSUE THREAD

**Issue by Benjy1979** [emberjs/ember.js#18112]
I've updated to 3.10 and it seems now my content-type set in the model adapter is being ignored. 
No matter what I set it to the request uses:
application/vnd.api+json

If I throw other headers in there, like access_token, it works. So the headers() property is being noted, it's just the content-type is being ignored or overwritten.

`headers: computed('webusers.access_token', function() {
        return {
            'Content-Type': 'application/json',
            'x-access-token': this.get('webusers.access_token')
        };
    }),`

The x-access-token will be in the request but he content-type still goes through as application/vnd.api+json.

**Comment by rwjblue** [comment]
This is Ember's own issue tracker, but this seems like an issue (that has already been fixed) in ember-data. 

I believe that you are hitting https://github.com/emberjs/data/issues/6058 (affected both `Accept` and `Content-Type`) which was fixed in https://github.com/emberjs/data/pull/6062 and is included in ember-data@3.9.2 and higher.

Can you double check your ember-data version (making sure its at least 3.9.2), and if it's 3.9.2 or higher file an issue over in ember-data (cross linking to this one)?
