### ISSUE TITLE
Input docs show curly braces and not Angle Brackets

### ISSUE THREAD

**Issue by jenweber** [emberjs/ember.js#18125]
If you visit [the input page in the API docs](https://api.emberjs.com/ember/3.10/classes/Ember.Templates.helpers/methods/input?anchor=input), it displays docs from [here](https://github.com/emberjs/ember.js/blob/v3.10.2/packages/%40ember/-internals/glimmer/lib/syntax/input.ts#L29)

However we want [this](https://github.com/emberjs/ember.js/blob/v3.10.2/packages/@ember/-internals/glimmer/lib/components/input.ts) to be showing.

Something isn't working quite right. Maybe these two sections are colliding in a race-condition-like way, maybe the newer angle brackets file isn't included in the yuidoc build, maybe the docs feature flag isn't working. This needs some research

How to debug:
- run `yuidoc .` on ember.js and search the output to see if both writeups end up in the json
- Try deleting the curly brackets code comments and run it again to see if the input shows up
- Inspect the JSON payloads on api.emberjs.com to see if we are running an outdated version

**Comment by toddjordan** [comment]
Feature flags don't affect yuidoc processing, therefore both input helper docs get created.  Seems that the curly version of the docs is taking precedent probably having to do with the order of processing.  Since angle brackets are shipped and documented, we should probably just delete the curly braces docs.

**Comment by chancancode** [comment]
Can we not run the built ember.prod.js through yuidoc instead?

**Comment by toddjordan** [comment]
Interesting idea.  Its worth a try.

**Comment by toddjordan** [comment]
so just an update.  I don't think we can run docs of the prod js because we'd lose the line number refs we link in documentation. 

We may be able to use another strategy here.  A couple of years ago we started using the yuidoc category field to filter out docs that were still behind feature flags.  we may be able to use a category for dead docs too.  Will investigate.  

Also, I'm a little confused as to why we would want to still include curly braces in the doc, if we are not going to publicly document them.

**Comment by toddjordan** [comment]
Discussed in the last learn team meeting, and we decided to remove docs for the old way, but since curly braces are still supported, we will move a mention of the approach into the angle bracket-based docs.

**Comment by toddjordan** [comment]
ok.  In looking to fix this I noticed a different behavior from what we first thought.

The angle bracket built-in component documentation _does_ exist in the current api docs documentation.  Its [here](https://api.emberjs.com/ember/3.11/classes/Ember.Templates.components) . problem is that its not linked to from anywhere.  It should be in `@ember/routing`, and on the api docs home page, and possibly in the classes list.  My work will be to do this as opposed to removing the old stuff for now.
