### ISSUE TITLE
Support native classes in app/router.js

### ISSUE THREAD

**Issue by tomdale** [emberjs/ember.js#18166]
Currently, `ember g route foo` will fail with an error if `app/router.js` uses newer JavaScript syntax like class fields or decorators. We should update this generator to ensure that this works correctly if people migrate this file to use native JavaScript syntax.

The bulk of the functionality of this generator lives in https://github.com/ember-cli/ember-router-generator, so this is largely a tracking issue for changes in that repo.

- [x] Support parsing class fields and decorators ([PR](https://github.com/ember-cli/ember-router-generator/pull/61))
- [x] Release ember-router-generator@2.0.0 
- [x] Update ember-router-generator version included with ember-source
- [ ] Update Octane blueprint to generate `app/router.js` file with native class syntax

**Comment by rwjblue** [comment]
Just released ember-router-generator@2.0.0, should get a dependabot PR soon...

**Comment by gabrielgrant** [comment]
not seeing [a dependabot PR for this](https://github.com/emberjs/ember.js/pulls?utf8=%E2%9C%93&q=is%3Apr++ember-router-generator+is%3Aopen+)...is that because it's configured to limit the number of PRs it will have open on a repo and it's already at it's max ([which appears to be 10?](https://github.com/emberjs/ember.js/pulls?utf8=✓&q=is%3Apr+is%3Aopen+dependabot)). Or is there something actually blocking this?

**Comment by rwjblue** [comment]
Nothing blocking to my knowledge, definitely welcome a PR.

**Comment by xg-wang** [comment]
This seems easy, should I do the following:
1. land https://github.com/emberjs/ember.js/pull/18278
2. wait a canary release
3. update ember-cli/ember-octane-blueprint

**Comment by rwjblue** [comment]
@xg-wang thank you! I submitted https://github.com/ember-cli/ember-octane-blueprint/pull/149 to close this out...
