### ISSUE TITLE
this.args is undefined inside component after enabling proxy

### ISSUE THREAD

**Issue by gokatz** [emberjs/ember.js#18202]
In glimmer components, the named arguments are supposed to be accessible via `this.args` property. But after enabling [proxy access](https://github.com/emberjs/ember.js/commit/b6a3ecdb6883401f0aea91a8a290acf937f91f6c), I can't access the arguments and it is coming something like `Symbol(magic-prop)`. With the previous SHA, I can able to get the args without any issue.

Reproduction: https://codesandbox.io/s/my-app-tdwwx 
In this sandbox, `name` argument has been accessed inside `formattedName` getter.

Is there any other way I can access the arguments? Thanks for any help.

**Comment by MalayaliRobz** [comment]
yes facing the same issue in glimmer components when using commit b6a3ecdb6883401f0aea91a8a290acf937f91f6c in ember-source
this.args.`prop-name` gives `undefined` in its component.js

**Comment by CvX** [comment]
Looks like something went wrong in #17835. @pzuraq

**Comment by pzuraq** [comment]
It’s more likely that the way that GlimmerComponent assigns args to the instance of the class is not compatible with the new autotracking strategy, since we test args out with a “Glimmerish” component that implements the same API. I’m currently working on fixing the transpilation bugs that keep popping up, but then this will be my next priority.

**Comment by pzuraq** [comment]
This should be fixed by https://github.com/glimmerjs/glimmer.js/pull/201

**Comment by kennethlarsen** [comment]
We're facing this as well. Thank you for your swift work, @pzuraq
