### ISSUE TITLE
string.htmlSafe uses private type SafeString

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/ember.js#18216]
```
import { SafeString } from "./-private/handlebars";
export function htmlSafe(str: string): SafeString;
```

SafeString should be public

**Comment by rwjblue** [comment]
Sorry, I'm not super clear what you are saying / asking for. Are you talking about typings? Can you help me understand what you mean?

**Comment by runspired** [comment]
@BryanCrotaz you could use `ReturnType` for these sorts of private typings

**Comment by mariowilde** [comment]
He's saying that the public function `htmlSafe(str: string): SafeString` returns a value, whose type `SafeString` is not published and thus unavailable as an import.

We use the function like this `get safeName(): SafeString { return htmlSafe(this.name); }`
and Typescript spits out `TS2304: Cannot find name 'SafeString'.` because we can't find the proper import for `SafeString`.

**Comment by rwjblue** [comment]
Ember (this repo) does not export types at all. I think you'll need to file these sorts of bugs over on definitely typed.

**Comment by mariowilde** [comment]
I didn't think of that, thanks.

**Comment by rwjblue** [comment]
No problem! I'm going to go ahead and close this one for now.
