### ISSUE TITLE
Glimmer components in generator

### ISSUE THREAD

**Issue by chancancode** [emberjs/ember.js#18224]
`ember generate component` should only support `--component-class="@glimmer/component"` (`-gc`) when the package is installed

**Comment by rwjblue** [comment]
Alternatively, we could install the `@glimmer/component` package for them...

**Comment by pzuraq** [comment]
Yeah, I was discussing this with @wycats yesterday. I believe the plan was to have the new generators be installed with the package itself, so that people are explicitly opting into changing their blueprints. I also believe we were going to change the default blueprint, and add a way to access the old defaults (e.g. `ember g classic-component`)

**Comment by chancancode** [comment]
@pzuraq thats not _quite_ right, the details can be found in the merged [co-location RFC](https://emberjs.github.io/rfcs/0481-component-templates-co-location.html).

1. The default is template-only (no class)
2. There is only one component generator (which is what we implemented). While the RFC does leave space for moving the blueprints to the packages (which is why the argument to `--component-class` is a module), currently it only support a few enumerated variants and all the blueprints live in this repo.

@rwjblue I _think_ that seems fine, if it's easy to implement? But imo, the MVP should be either we hide the option in `--help` completely, or at least give you an error (that you need to install the package) when you run it.

**Comment by pzuraq** [comment]
Ah, my mistake, I wasn’t aware that this behavior had been spec’d out in that RFC 👍
