### ISSUE TITLE
Input helper: adding `change` action breaks two-way binding with `checked` property

### ISSUE THREAD

**Issue by aghassemi** [emberjs/ember.js#18249]
See https://ember-twiddle.com/546a8ff1fbafd9651ab5131ed0aa41af

It seems adding an action to `change` event stopes two-way binding with `checked` to work.
`click` does not suffer from the same issue.

**Comment by rwjblue** [comment]
The checkbox component uses the standard `Ember.Component` `change` method in order to update the underly value when the `change` DOM event is fired, passing a `change` function in clobbers that internal method and therefore breaks the component fundamentally.

https://github.com/emberjs/ember.js/blob/fb60c41d1aab65be3a249b6c9ea9627c80d8e9c7/packages/%40ember/-internals/glimmer/lib/components/checkbox.ts#L136

**Comment by aghassemi** [comment]
Is there a good workaround for this that does not involve creating a wrapper component or sending the checked state as a param to actions? I tried using `click` instead of `change` but that value of `isChecked` from two-way binding is the old value and not updated when `click` is used.

**Comment by locks** [comment]
Closing as no longer relevant. Thanks for providing a reproduction!
