### ISSUE TITLE
Quest - update API docs to show Octane and Native Classes

### ISSUE THREAD

**Issue by jenweber** [emberjs/ember.js#18250]
It's almost time to show Octane-style code samples in the API docs! Right now, our examples use Ember Objects, and we want them to use native classes and Component file co-location instead. Can you help? Here's how! If you have any questions, drop by the `#dev-ember-learning` channel on [Ember Discord](https://api.emberjs.com/ember/release). Keep reading for step by step instructions, a styleguide, and some examples of the kinds of changes we need help with.

## Step by step instructions

1. Comment on this issue to say which item you are volunteering for. The checklist of things we need help with is in the comment below. Only volunteer for items that you think you can open a PR for in a week or less.
2. Before you start working, double check to make sure it's not already been PR'd or claimed by someone else.
3. Fork this repo and check out the existing branch `octane-docs`. This branch has some of the work done already, and you will be adding to it.  If it's your first open source PR ever, check out [these instructions](https://medium.com/@jenweber/your-first-open-source-contribution-a-step-by-step-technical-guide-d3aca55cc5a6) to learn how to fork, branch, etc. or make changes via the GitHub website instead.
4. Locate the file that has the API doc. Our docs are written in YUIdoc and they live right next to the JavaScript for the API, here in this repository.
5. Make your changes! EmberObject is still supported, so we need to show both styles. [Here's an example](https://api.emberjs.com/ember/3.12/functions/@ember%2Fservice/inject). In general, you should give Octane examples first, and EmberObject second. In cases where multiple examples are needed, make all of them Octane, and then add just 1 for EmberObject.
If you don't know Octane syntax yet, don't worry. There's a [Cheatsheet](https://ember-learn.github.io/ember-octane-vs-classic-cheat-sheet/) and [guide to what is different](https://octane-guides-preview.emberjs.com/release/upgrading/editions/)
6. When you make a commit, it should start with `[DOC beta]`. For example `[DOC beta] update component example for Octane`.
7. Open a pull request, and target merging into the `octane-docs` branch. Please check the box that says "allow maintainers to make edits."
8. Celebrate and brag about it to all your friends

## Styleguide

All inline documentation is written using YUIDoc. Follow these rules when updating or writing new documentation. This is copied & pasted from [CONTRIBUTING.md](https://github.com/emberjs/ember.js/blob/master/CONTRIBUTING.md#pull-requests)

- All code blocks must be fenced
- All code blocks must have a language declared
- All code blocks must be valid code for syntax highlighting
- All code blocks should have an empty line before and after
- All examples in code blocks must be aligned
- All references to code words must be enclosed in backticks
- Prefer a single space between sentences
- Reference Ember.js as Ember.
- Wrap long markdown blocks > 80 characters
- Don't include blank lines after @param definitions

## Example

_Since this example is trying to show Templates and not teaching Component APIs, it's ok to show just Octane. We'll update the Component to use the native class syntax of `@glimmer/component`_ and change the filepaths to reflect co-location (where a component's hbs and js files are both side-by-side in the `components` folder. We also add `this` for component properties that belong to the component. `@` is used in templates when it is assumed that a property is passed in from the parent._

### Before:

  Templates manage the flow of an application's UI, and display state (through
  the DOM) to a user. For example, given a component with the property "name",
  that component's template can use the name in several ways:

```app/components/person-profile.js
  import Component from '@ember/component';

  export default Component.extend({
    name: 'Jill'
  });
```

```app/templates/components/person-profile.hbs
  {{name}}
  <div>{{name}}</div>
  <span data-name={{name}}></span>
```

### After

  Templates manage the flow of an application's UI, and display state (through
  the DOM) to a user. For example, given a component with the property "name",
  that component's template can use the name in several ways:

```app/components/person-profile.js
import Component from '@glimmer/component';

export default class PersonProfile extends Component {
   name = 'Jill';
}
```

```app/components/person-profile.hbs
  {{this.name}}
  <div>{{this.name}}</div>
  <span data-name={{this.name}}></span>
```

**Comment by jenweber** [comment]
We will try to keep this list up to date, but please double check comments below, plus open & merged PRs before beginning work.

# Needs volunteer
- [ ] [`@ember/component`](https://api.emberjs.com/ember/release/modules/@ember%2Fcomponent) should have nearly all content removed except the link to [the other component api page](https://api.emberjs.com/ember/release/classes/Component)
- [ ] This [Component](https://api.emberjs.com/ember/release/classes/Component) page needs a note about how `@ember/components` are referred to as "classic components."
- [ ] Some examples on [Controller](https://api.emberjs.com/ember/3.12/classes/Controller/methods) need to be updated to use native classes. Others use classic component behavior.
- [ ] show native class controller in [this templates example](https://api.emberjs.com/ember/3.12/classes/Ember.Templates.helpers/methods?anchor=component)
- [ ] [jquery $](https://api.emberjs.com/ember/3.12/classes/LinkComponent/methods?anchor=%24) maybe needs a note about how jquery is not included by default, and links to <https://guides.emberjs.com/release/configuring-ember/optional-features/>
- [ ] the [RouterService](https://api.emberjs.com/ember/release/classes/RouterService) example should use `@glimmer/component` syntax
- [ ] [urlFor](https://api.emberjs.com/ember/3.12/classes/RouterService/methods?anchor=urlFor) should use a native class example.


# WIP


# Done

**Comment by locks** [comment]
- Should we suggest an alternative to named outlets?
- `Some examples on Controller need to be updated to use native classes. Others use classic component behavior.` Does this mean that we keep the classic behavior examples as they are?
- Does it make sense not to use EmberObject in `isEqual` examples? Should we instead using a third-party library for equality?
- `Application … and that many apps never` need to touch it? Should we not generate it by default?
- `Controller actions need to use native class syntax and also show classic` is from the `action_handler` mixin. We might need a deeper approach here since it impacts a couple of different classes.
- `the examples of … need this or @ in front` might not be specific enough. should there be a preference for one or the other? should we purposefully mix them?
- `Maybe partial should just state the alternative of deleting the js file.` It might be a better approach to document how to migrate from partials to template-only components and link to that. Linking to a mention of template-only components in the guides would also be useful, but not mentioning that you have to explicitly pass all arguments and update the partial template with the `@` prefix might lead the dev to headaches.
- ` almost every example in Route needs to be native class'ed. Should show native and classic both at the very top.` Do you mean one single example so readers have a sense how things map?

**Comment by MelSumner** [comment]
@rwjblue could you take a peek at this issue? Can you provide any clarity for @locks question?

**Comment by locks** [comment]
## Missing
- [x] classify `Route` in `RouterService`
- [ ] what to do with `mut` in `get` documentation
- [ ] bring back classic component example for `component` helper
- [ ] normalize `set` and `tracked` in `computed_macros` file
- [ ] grep for `class extends` and add the name for the class
- [ ] review `each-in` for correctness/coesion (key is used before it's introduced)
- [ ] confirm `get` + `mut` example updates properly
- [ ] (?) `action_handler` remove mixins (?)
- [ ] (?) `action_handler` switch examples to `EmberComponent` so that we can still use the classic `.extend` API. (

## Missing code samples
- [ ] `RouterService#isActive`
- [ ] `RouterService#recognizeAndLoad`

## Open questions

- [x] classes, named or anonymous? (`class extends Route` vs `class Menu extends Route`) -> named


### RouterService
- [ ] constructor seems ok in code samples? (cc @pzuraq)
- [ ] `currentRoute` example is using `notEmpty` CP decorator. should we replace with native getter? (cc @pzuraq)

### unless
- Consider introducing `not` to the framework, and deprecating `unless` for `{{if (not)}}`

**Comment by locks** [comment]
## Missing
- [ ] what to do with `mut` in `get` documentation
- [ ] bring back classic component example for `component` helper
- [ ] normalize `set` and `tracked` in `computed_macros` file
- [ ] review `each-in` for correctness/coesion (key is used before it's introduced)
- [ ] confirm `get` + `mut` example updates properly
- [ ] `action_handler` switch examples to `EmberComponent` so that we can still use the classic `.extend` API.
- [ ] investigate syntax highlighting mishaps - [hasBlock](https://api.emberjs.com/ember/3.12/classes/Ember.Templates.helpers/methods?anchor=hasBlock), [hasBlockParams](https://api.emberjs.com/ember/3.12/classes/Ember.Templates.helpers/methods?anchor=hasBlockParams)
- [ ] `observer` is `Helper` class example
- [ ] `RouterService#recognize` uses a strange ember component

## Missing code samples
- [ ] `RouterService#isActive`
- [ ] `RouterService#recognizeAndLoad`

## Open questions

- [x] classes, named or anonymous? (`class extends Route` vs `class Menu extends Route`) -> named

### Router Service
- [ ] constructor seems ok in code samples? (cc @pzuraq)
- [ ] `currentRoute` example is using `notEmpty` CP decorator. should we replace with native getter? (cc @pzuraq)

### unless
- Consider introducing `not` to the framework, and deprecating `unless` for `{{if (not)}}`

### Action Handler
- [ ] (?) `action_handler` remove mixins (?)

### Controller
- [ ] figure out what to do with `Controller#addObserver` - it's currently using an EmberComponent, which seems strange

### action helper
- [ ] figure out how we want to address classic EmberComponent in [action helper](https://api.emberjs.com/ember/3.12/classes/Ember.Templates.helpers/methods?anchor=action)

### partial

While the partial deprecation is not [currently implemented](https://github.com/emberjs/rfc-tracking/issues/38), it is possible that Octane will ship with it.
Regardless, we should definitely suggest GlimmerComponents instead.

### Helper (class)

- `@observer`?

### Route

- `on('activate', function(){` + native class?
- `willTransition`, `didTransition`, `loading`, `error` actions + native class?

**Comment by jenweber** [comment]
@locks regarding:

> figure out what to do with Controller#addObserver - it's currently using an EmberComponent, which seems strange

This came up in the octane meeting. We should change the example to not use a component, and we should add some boilerplate that "addObserver is a low-level feature that is not performant" or something similar.

**Comment by LuisMBarrera** [comment]
Hello everybody, this is my first time trying to contribute on an open-source project, and I wanted to know if I can still help with this quest.

**Comment by jenweber** [comment]
Hi @LuisMBarrera! I’d be happy to help you find something for your first contribution to the project. I think this list is a bit out of date though, and most of these tasks are now complete. I will have a look tomorrow to see if any are still available, or maybe @locks can chime in. If they are all finished, we can suggest something else.

**Comment by LuisMBarrera** [comment]
Thank you very much, I'll be pending for any suggestion or recommendation.

**Comment by ryanolsonx** [comment]
Is this work still needed? If so, I'd like to pick up something.

**Comment by jenweber** [comment]
Hi @ryanolsonx  this is a very old issue, and it should have been closed. Sorry about that! If you would like to help with the release of Ember 4, we could definitely use your help! The general tasks are in #19702

**Comment by jenweber** [comment]
P.S. thanks in advance and please get in touch if you have questions! There is a lot of Q&A about this kind of work that happens in the Ember community Discord’s dev-ember-learning channel. https://emberjs.com/community
