### ISSUE TITLE
`tracked` no longer works with non-decorator style use

### ISSUE THREAD

**Issue by trek** [emberjs/ember.js#18362]
This may possibly be better living at at https://github.com/glimmerjs/glimmer.js but I encountered this issue using `tracked` with latest Octane.

My current use case is tracking the `permission` property of `window.Notification`, which after some chatter with @mmun and @machty in the [alumni lounge](https://twitter.com/trek/status/1169695496933449731) seems like it should be possible either directly or with some handwaving.

[This comment](https://github.com/glimmerjs/glimmer.js/issues/22#issuecomment-336441371) (h/t @mmun) also makes it seem like this is possible:

```
import { tracked } from '@glimmer/tracking';
tracked(Notification.prototype, 'name'); 
```

But this errors with `The options object passed to tracked() may only contain a 'value' or 'initializer' property, not both` coming form [here](https://github.com/emberjs/ember.js/blob/949daaa74213c8569b239a79cffcae690df5f79e/packages/%40ember/-internals/metal/lib/tracked.ts#L127).

We tried doing some of the descriptor setting ourselves 

```
import { tracked } from '@glimmer/tracking';

function track(object, key) {
  let originalDescriptor = Object.getOwnPropertyDescriptor(object, key);
  let trackedDescriptor = tracked(object, key, originalDescriptor);
  Object.defineProperty(object, key, trackedDescriptor);
}

track(window.Notification, "permission");
```

But this also errors with `You attempted to use @tracked on permission, but that element is not a class field.` from [here](https://github.com/emberjs/ember.js/blob/e9714186c4954d10fac64c28e4dfd7ba15685410/packages/%40ember/-internals/metal/lib/tracked.ts#L180)

**Comment by pzuraq** [comment]
That is not a supported method for using `tracked()`. It _can_ be used with `Ember.defineProperty` however, similar to `computed()`, which means that it works with classic class definitions:

```js
const MyClass = EmberObject.extend({
  foo: tracked()
});

Ember.defineProperty(window.Notification, 'permission', tracked());
```

I'm not sure I would recommend this method, but if you're trying to avoid using a service it may make sense. We are trying to figure out the correct shape of public APIs for autotracking in general, and `Ember.defineProperty` will probably eventually be removed from the framework (I'd imagine around the same time as `EmberObject`), so you'd likely have to migrate to something else in the future.

**Comment by trek** [comment]
@pzuraq gotcha. Is this a reversal of earlier behaviors? https://github.com/glimmerjs/glimmer.js/issues/22#issuecomment-336441371

**Comment by mmun** [comment]
And the relevant code that allows it: https://github.com/glimmerjs/glimmer.js/blob/master/packages/@glimmer/tracking/src/tracked.ts#L116.

**Comment by pzuraq** [comment]
Ah, Rob's point there is essentially you can call it like a decorator directly, you would probably be able to do something like:

```js
let oldDesc = Object.getOwnPropertyDescriptor(window.Notification, 'permission');
let newDesc = tracked(window.Notification, 'permission', oldDesc);
Object.defineProperty(window.Notification, 'permission', newDesc);
```

I would definitely caution against this, since decorators _will_ be changing in the future, I think that discussion happened before some of the changes upstream in decorators.

@mmun the implementation for Ember's version currently lives here: https://github.com/emberjs/ember.js/blob/master/packages/@ember/-internals/metal/lib/tracked.ts

That functionality in Glimmer seems odd, unsure why it was added (doesn't seem to be like TS decorators at all), but that was not part of the RFC'd API which is why it wasn't transitioned over to Ember.js. Eventually, the Glimmer.js API will be updated to match the Ember.js one. Definitely think something like this could be added for dynamically defining tracked props, but that'll have to go through RFC too

**Comment by locks** [comment]
This should be resolved as per the discussion, closing. Thanks for your time everyone!
