### ISSUE TITLE
[BUG] Binding does not work when `id` attribute is set after render

### ISSUE THREAD

**Issue by mukilane** [emberjs/ember.js#18368]
Initially, the input is rendered without any ID attribute, and two-way-binding works perfectly. 
Now, when I set ID using `Element.setAttribute` method, the two-way-binding stops working.

Twiddle: https://ember-twiddle.com/e8359f6bb8ee41d342207a53fa15809c
Ember Version: 3.8.3

**Comment by pzuraq** [comment]
Hi @mukilane, thanks for reporting! So, I don't believe this is actually a bug. `{{input}}` is a classic Ember component, and these components manage the state of their element directly, including the `id`. This means that you cannot use standard browser APIs to update the `id` or other attributes directly, you must set the `elementId` property on the component instead:

```hbs
{{input elementId=this.myElementId}}
```

This is the recommended approach in general, even for the new upcoming Glimmer components, you would want to use `...attributes` and pass `id` in via the template rather than use `Element.setAttribute`:

```hbs
{{!-- components/custom-input.hbs --}}
<input ...attributes>
```
```hbs
<CustomInput id={{this.myElementId}} />
```

If you're having difficulty converting your use case to this, feel free to post a more detailed example here, or to join the [community Discord server](https://discord.gg/emberjs) and ping me in #help, happy to work through the details 😄 I'm going to close this issue for now, let me know if you have additional concerns
