### ISSUE TITLE
Refactor render tree testing in prod

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember.js#18409]
https://github.com/emberjs/ember.js/pull/18372/commits/d7d942e4b17e2dfb654175b2b91c8e9ad9f549bc added another CI run specifically to ensure that you can enable the render tree debugging in production. We can _probably_ remove the extra CI job here and instead test this during our other production build tests.

**Comment by sandstrom** [comment]
Couldn't find this in the repo.

https://github.com/search?q=repo%3Aemberjs%2Fember.js+DEBUG_RENDER_TREE%3Dtrue&type=code

So I'm guessing it's no longer in use since we moved away from Travis.

I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue.

By closing some old issues we reduce the list of open issues to a more manageable set. Let me know if you think this is a mistake and that the issue should stay open.
