### ISSUE TITLE
[3.13] @tracked doesn't invalidate @computed cache

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/ember.js#18437]
My understanding is that `@tracked` means that Ember deals with working out the dependencies of calculations. That doesn't appear to work for `@computed`
* tracked -> getter -> template
```
\\template.hbs
{{greeting}}

\\controller.js
@tracked name;

get greeting() {
  return "hello "+this.name;
}

// when name changes, greeting updates
```
* tracked -> computed getter (cached for speed if lots of things are changing) -> template
```
\\template.hbs
{{greeting}}

\\controller.js
@tracked name;

@computed
get greeting() {
  return "hello "+this.name;
}

// when name changes, greeting does not update
```

* tracked -> computed getter with dependencies -> template

```
\\template.hbs
{{greeting}}

\\controller.js
@tracked name;

@computed('name') // isn't the point of tracked to get rid of this?
get greeting() {
  return "hello "+this.name;
}

// when name changes, greeting updates
```

**Comment by pzuraq** [comment]
This was the originally proposed behavior, but we found during development and early testing that this would have been a breaking change for most user's applications. It turns out that the exact caching semantics of computed properties _are_ important, and many applications become deeply connected to them in many ways. The [Tracked Properties Updates RFC](https://github.com/emberjs/rfcs/blob/master/text/0478-tracked-properties-updates.md) goes over these changes in more detail.

However, it was always the intention that any autotracking `@computed` does would be a temporary, interop-only behavior, and that eventually `@computed` would be deprecated due to the (significant) amount of legacy code it requires to implement. 

We definitely plan on having a very minimal `@memoize` type decorator sometime in the future which utilizes autotracking, we just wanted to ship `@tracked`, and potentially even the lower level tracking APIs. In the meantime, you can either continue to use `@computed` with explicit dependencies, or you can do your own memoization in getters that _need_ to be cached for performance:

```js
get reallyExpensiveCalculation() {
  if (this.var = this._lastVar) {
    this._cachedValue = calculate(this.var);
  }

  return this._cachedValue;
}
```

My recommendation here is to base any caching you do, either via decorator or manually, on actual perf benchmarking. Part of the reason we removed caching by default is that it can actually be much _less_ performant as a whole, since caching every getter puts quite a bit of memory pressure on an app. The DOM itself should be the cache in most cases, unless you're doing some very intense or expensive types of operations.

**Comment by BryanCrotaz** [comment]
Thanks!

Something approaching this should be added to the @computed and @tracked docs as they conflict in intent.

@memoize would essentially do the same as your example cache code?

**Comment by pzuraq** [comment]
I'll make sure to add some notes to the edition guide/state management section in the new docs, definitely think this should be clarified.

`@memoize` would use autotracking, and given the behavior of tracked properties this would mean one important difference from the example cache I gave:

```js
class Foo {
  @tracked prop = 123;

  @memo get computedProp() {
    console.log('ran');
    return this.prop + 1;
  }
}

let foo = new Foo();

foo.computedProp; // returns 124, logs 'ran'
foo.computedProp; // returns 124, does not log because memoized
foo.prop = 123;
foo.computedProp; // returns 124, logs 'ran'
```

The reason here is tracked properties _always_ emit a change event when updated, regardless of whether or not the value has changed. Since the memoized getter has no idea which tracked properties are accessed, it can't cache them to compare either. This also affects computed properties too, see https://github.com/emberjs/ember.js/issues/18427 for more details on that.

**Comment by BryanCrotaz** [comment]
That’s the same as setters so that makes sense in the ember world
