### ISSUE TITLE
Tracked properties in Ember 3.13+: No incremental path forward

### ISSUE THREAD

**Issue by mschorsch** [emberjs/ember.js#18614]
We are currently using Ember 3.12 and would like to upgrade to Ember 3.14+. Due to breacking changes with the introduction of tracked properties in 3.13+ we currently see no incremental way to upgrade our applications.

As of Ember 3.13, the model in controller has been a tracked property. This has a significant impact on the behavior of the computed properties in the controller. Computed properties are no longer executed when dependent objects change.

The following simple example shows such a case. The template is no longer updated because the computed property `value` is no longer executed.

```ts
// routes/application.ts
export class Example {
  constructor(public value: string) {}
}

export class ApplicationModel {
  constructor(public example: Example) {}
}

export default class Application extends Route {

  model(_params: {}, _transition: any): RSVP.Promise<ApplicationModel> {
    return RSVP.resolve(new ApplicationModel(new Example("test")));
  }
}
```

```ts
// controllers/application.ts
export default class Application extends Controller {

  model!: ApplicationModel;

  @computed("model.example.value")
  get value() {
    return this.model.example.value;
  }

  @action
  changeExampleValue() {
    set(this.model.example, "value", String(Math.random()));
  }
}
```

```hbs
{{! templates/application.hbs }}
<div {{on "click" (fn this.changeExampleValue)}}>
  {{this.value}}
</div>
```

One possibility would be to make `example` a computed property (see below). This works and fixes the bug in this example, but in our real application, this change doesn't fix all the bugs.

```ts
export default class Application extends Controller {

  model!: ApplicationModel;

  @readOnly("model.example") example!: Example;

  @computed("example.value")
  get value() {
    return this.model.example.value;
  }

  @action
  changeExampleValue() {
    set(this.model.example, "value", String(Math.random()));
  }
}
```

We currently only see the possibility to replace all computed properties at once.

Hence our question: Is there an incremental way to gradually replace computed properties with tracked properties?

**Comment by pzuraq** [comment]
Hello!

Incremental adoption of tracked properties and Ember 3.13+ should be fully possible. There have been no intentional breaking changes, and we have worked very hard and have many tests covering the types of interop that you're describing. I've recreated your example here, and it appears to be working as expected: https://github.com/pzuraq/test-model-reactivity

It's also worth noting that the change in `model` from a standard property to a tracked property would not affect this case, since `model` is not the value that is changing. `value` is, which is a property of `example` and is not tracked. Updating it to be a tracked property allows us to remove `Ember.set`, and updates still interop with computed properties as expected, as you can see in this branch: https://github.com/pzuraq/test-model-reactivity/tree/tracked-usage

Is this example the full example you were having issues with? If so, I wonder if TypeScript has anything to do with the problem. If not, can you provide a reproduction? You can PR it onto the `test-model-reactivity` repo if that makes things easier.

**Comment by mschorsch** [comment]
Hi @pzuraq, thanks for your fast response.

> Is this example the full example you were having issues with?

Yes. We have lots of code like this.

> If so, I wonder if TypeScript has anything to do with the problem.

Good hint. I will dig into it.

**Comment by mschorsch** [comment]
Hi @pzuraq, i've checked your branch https://github.com/pzuraq/test-model-reactivity/tree/tracked-usage and you are absolutely right, the JavaScript version works like expected. 

After adding `ember-cli-typescript` and changing the code to TypeScript nothing works anymore.

So it seems to be an issue with `ember-cli-typescript` or TypeScript itself. I'll open an issue in the repository of `ember-cli-typescript`.

Thanks for your help.
