### ISSUE TITLE
ES6 Class constructor VS Ember Object init

### ISSUE THREAD

**Issue by Exelord** [emberjs/ember.js#18642]
Hi all.

Im trying to migrate my mindset from Ember Object (OOP class) to Native ES6 class and I encounter on a blocker. The guides are saying that we should use `constructor` for Glimmer components and keep using `init` for classes that inherit from Ember Object (like Ember Components). And that's fully understandable as Glimmer components are ES6 classes and don't have `init` method implemented. However, there is a huge difference between these two and I think you can only notice it during class inheritance. 

`init` method works similar to `initializer` from other OO languages. It is executed after the instance has been "constructed" (read: class fields have been assigned and new instance has been settled). In short, this is the order:
```
const instance = new MyClass();
instance.init()
```

However, as you can see, the `constructor` is called together with the `new` operator: `const instance = new MyClass();`
This behavior difference leads to an issue during inheritance and overriding class fields.

EmberObject `init` example with inheritance:
```
class Base extends EmberObject {
 count = 1;
 
 init() {
  this.increased = this.count + 1;
 }
}

Base.create().increased // returns 2 | expected 2

class MyClass extends Base {
 count = 2;
}

MyClass.create().increased // returns 3 | expected 3
```

ES6 Native Class and `constructor`:

```
class Base {
 count = 1;
 
 constructor() {
  this.increased = this.count + 1;
 }
}

new Base().increased // returns 2 | expected 2

class MyClass extends Base {
 count = 2;
}

new MyClass().increased // returns 2 | expected 3
```

As noticed, this issue is coming up only during inheritance which by many of you may be considered as "bad practice" already. However, I'm a big fan of OOP and I see cases where inheritance is more than welcome for me. One of the examples can be addons components extending or custom solutions using base classes.

Right now, the EmberObject migration is presented as a straight forward path and many devs are just renaming `init` -> `constructor`. I'm not sure if all of them are aware of this inheritance trap.
But I'm wondering if there is an option to continue the migration from EmberObject preserving the `init` effect. I know, it sounds more like a JS  topic but it's related to Octane migration and may raise some awareness during the process.

I was thinking many hours about it and developed some "intermediate solution" [https://codesandbox.io/s/amazing-smoke-m3rmj]. It's not perfect, as it requires a decorator on every class. So, I decided to reach out to you and get some opinions. Any thought or idea is more than appreciated!

Also I would suggest changing the guides (https://guides.emberjs.com/release/upgrading/current-edition/native-classes/) to not recommend migrating `init -> constructor` or explain this topic further to make it clear that they work in a different way.

**Comment by pzuraq** [comment]
Thank you for raising this issue with the documentation in the upgrade guide! The difference between `init` and `constructor` is well understood in general, which is why the native class codemod does not convert `init` to `constructor`, and we do note in the guides that `init` runs after the `constructor` which implies the ordering difference with regards to class fields, but it's not spelled out at all. I definitely think we can add a longer note that discusses the difference in inheritance a bit more in depth.

In general, the "initializer" pattern from other OO languages is not supported by JavaScript classes, and it is unclear if it ever will be supported, even with annotations/decorators. Decorators are still an in-flux spec, and their exact semantics and capabilities are not set in stone. This is why we made the decision to move away from `init`, and are recommending that users move to `constructor` and standard JS inheritance when possible, in their own time. We considered intermediate solutions, but because they have many caveats, decided against introducing them.

There will be times when this means that certain inheritance patterns that used to be possible are no longer possible, unfortunately. This is not at all because we believe OOP is a "bad practice", or that you shouldn't be relying on inheritance! It is just that the final inheritance semantics provided by JS are slightly different than the ones provided by EmberObject, and we are now moving toward native classes as a community, since that's the direction of OO inheritance in JS in general. 

In the short run, this means that Ember will interop better with the wider JS ecosystem, and new Ember users will have less unusual Ember-isms to learn. In the long run, it means that if JS adds initializer patterns, they will be supported first class, out-of-the-box in Ember, because Ember classes (and usage of classes) are "Just JavaScript".

**Comment by pzuraq** [comment]
> But I'm wondering if there is an option to continue the migration from EmberObject preserving the init effect.

It's also worth noting that while there is no _general_ way to do this, and `init` and `EmberObject` will likely be deprecated in the future, they are still fully supported on many framework classes today, and if you need to use them you can continue to do so.

**Comment by locks** [comment]
This should be resolved as per the discussion, closing. Thanks for your time everyone!
