### ISSUE TITLE
[3.15] Synchronous render bug

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#18644]
I've noted this as `3.15`, because a new deprecation warning was implemented there. Perhaps the same issue was also true before.

[Here is a reproduction](https://github.com/boris-petrov/ember-each-rerender-bug). Please checkout the second commit. The third is for [another bug](https://github.com/emberjs/ember.js/issues/18643).

Running the test `push-to-array-test` will cause a deprecation warning in the console. I think this is very strange. The test renders `<EachComponent />` (which loops over an array) and then renders a helper which pushes an item in that array. That causes the deprecation warning. I think that doesn't make sense. Is that expected behavior? How am I supposed to do something like that otherwise?

**Comment by pzuraq** [comment]
This is expected behavior. This is a stronger form of the backtracking-rerender assertion that has already existed since Ember v2, which asserts against changing state that has already been used during the course of a render. Ember does not, by default, rerender if state has changed during the course of a render, which is why usually the assertion would trigger and alert you that you need to using `run.schedule` or another method to update the state in a _new_ render.

This is also the root cause of #18643, and I would be surprised if this had worked in 3.12. There was a regression in the backtracking assertion in 3.13, so it wasn't firing as expected, and that may be why this was not throwing an error in 3.13-3.14.

**Comment by boris-petrov** [comment]
Thank you for the explanations.
