### ISSUE TITLE
Ember 3.15.0 - Classic components in an add-on mandate the @ (at) prefix for passed parameters

### ISSUE THREAD

**Issue by danr1979** [emberjs/ember.js#18687]
Hi.

After upgrading to Ember 3.15.0 (Octane) I found that one of my classic components that rendered a styled HTML header tag stopped showing the header text.  This was displayed using a parameter ("header") that was passed into the component as follows:

`<SuiHeader class="primary" @tagName="h4" @header="My header"></SuiHeader>`

The component template itself looks like:

```
<div class="content">
    {{header}}
</div>
{{yield}}
```

I figured out that if I replaced `{{header}}` with `{{@header}}` as per the new component parameters standard the header text appeared as normal.  This surprised me because as far as I knew the @ parameter syntax was recommended but not mandated as of yet.

To get around the issue I have gone through all of the classic components and prefixed the parameters in the template with the @ symbol.  This resolved the problem.

I don't know if it is significant but the affected classic components are in a private Ember add-on that we created to share them among our various Ember applications.  Furthermore, I tested calling the component with angle bracket syntax and curlies and the same faulty behaviour occurred with both.

Hope this is enough information.

Thanks.

**Comment by pzuraq** [comment]
@danr1979 is this a template only component? If not, can you also provide the class associated with the component?

If so, then this is likely a behavioral change due to the `template-only-glimmer-components` optional feature, which turns all template-only components into Glimmer components. Glimmer components do have this requirement when accessing args, in general.

The backwards compatible solution if you want to incrementally enable this flag is to add a classic component backing class that is empty to the template:

```js
import Component from '@ember/component';

export default Component.extend({});
```

I believe that we intended enabling the feature flag to add these classes automatically, so if that didn’t happen in this case we should figure out why not and try to fix it.

**Comment by danr1979** [comment]
@pzuraq Thanks for the swift response.

This classic Ember component is backed by a class.  Its content is as follows:

```
import Component from '@ember/component';
import layout from '../templates/components/sui-header';

export default Component.extend({
    layout,
    classNames: ['ui', 'header']
});
```
I did look at setting the `template-only-glimmer-components` option to false in `optional-features.json` but I then received an error along the lines of "You have chosen to have an Octane application so this value must be true", which scared me a bit because I was planning on a gradual adoption of Octane!  However, the rest of my application seems to be working fine so all is well.

**Comment by pzuraq** [comment]
Alright then that definitely does sound like a bug. Unfortunately I'm not able to reproduce the issue locally, it appears to be working in a freshly created ember-addon: https://github.com/pzuraq/classic-component-addon-args-test-repro

Can you try to reproduce the issue you are seeing in this addon and submit it as a PR? It would help a lot with diagnosing and getting to the root cause quickly 😄

**Comment by danr1979** [comment]
I suspect that might be because your addon is created using Ember 3.15.0 and/or maybe you are installing it in a fresh 3.15.0 application?

I have discovered that if I simply create a classic Ember component backed by an EmberObject Component class in my Ember 3.15.0 application (not in an add-on) the issue occurs.  So, the fact that I initially had the issue with a component in an add-on is not important.  The issue occurs with components created directly within an Ember application too.  My application is not a fresh Octane app though (it was created originally in an early version of 3.x.x and has been upgraded to 3.15.0) and has currently has all classic Ember Controllers, Routes, Components etc.  Perhaps it is these type of classic applications that experience the issue with @ parameters after upgrading to 3.15.0.

I've not contributed to Ember up to now so is this information enough for you to be going on with in terms of looking into the issue?

Thanks.

**Comment by pzuraq** [comment]
I’ve got a lot of other bugs and issues I’m dealing with at the moment, so I’m unsure when I’ll have time. We’ve successfully upgraded multiple apps and addons to Octane without encountering this issue, so something must be different here. 

A reproduction would be very helpful in speeding up the process, but we’ll be sure to look into this as soon as time permits.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. 

This issue has been open for a while without anyone jumping in to fix it. The reality is that unless you want to fix the bug itself, it will likely stay that way.

The time of core team members is very limited, and we all want them to focus  on moving the framework forward (high-leverage things), leaving fixing of edge case bugs to "fringe volunteers", such as you and me.

By closing some old issues we reduce the list of open issues to a more manageable set. Let me know if you think this is a mistake and that the issue should stay open.
