### ISSUE TITLE
isVolatile returns true when volatile is undefined

### ISSUE THREAD

**Issue by jeremylazarus** [emberjs/ember.js#18768]
This error is caused by the logic mentioned in https://github.com/emberjs/ember.js/pull/15989 as well as an issue with how `reads`/`readOnly` computed properties are created.

In ember-metal, there is a check for the volatility of a property during a lazyGet call. If the property's _volatile property is undefined, then it's considered volatile.

The `reads`/`readOnly` computed properties do not call Metal's `ComputedProperty` constructor and do not set _volatile to false.

I encountered this in some tests where it was causing a breakage while updating from ember-model to ember-data.

Setup:
I had a model set up like this:
`configuration.js`
```
sources: DS.hasMany('my-source'),
source: computed.reads('sources.firstObject')
```

In some acceptance tests, the teardown step was destroying the `configuration` model. It then tried to destroy each property. When it reached `source`, rather than destroying a cached version of `source`, it tried to fetch the value of `source`. This caused it to try to fetch the `sources` with a call to `store.findMany`. Since the `store` was already being destroyed, an error was thrown.

I worked around this issue by changing `source` to:
```
source: computed('sources', function() { return this.sources.firstObject; })
```

but this should be fixed elsewhere - possibly in both the isVolatile function and the way that computed helpers are created.

**Comment by pzuraq** [comment]
I'm not sure if this is still what's going on here. We no longer have an `isVolatile` in the codebase, and the only thing that checks for volatility is the `ComputedProperty` class.

`alias`, `reads`, and `readOnly` do not extend the `ComputedProperty` class, they instead implement their own, much more minimal implementation, the `AliasedProperty` class. It does not set `_volatile`, but it also never checks `_volatile` for any of its operations.

The reason they are still getting the value is that the logic in `AliasedProperty` _always_ gets the value: https://github.com/emberjs/ember.js/blob/master/packages/@ember/-internals/metal/lib/alias.ts#L88

It does not cache the value, and that is unfortunately not something we can change since the caching semantics of these properties have been around for a long time (pre-2.0) and even subtle changes to them can cause major issues in people's apps. 

Going to close this for now. If the teardown step was one that existed in Ember or Ember Data, I recommend opening an issue for that specifically, because it sounds like the teardown is not correct. If it's a custom teardown step, it probably needs to be rewritten to account for this behavior.

**Comment by pzuraq** [comment]
It also seems like this may specifically be an issue with teardown in an older version of Ember, given that you mention `lazyGet` being called. Upgrading Ember to the latest version should solve that, since chains and `lazyGet` are no longer part of the codebase.
