### ISSUE TITLE
Setter imported from ember object is acting weird in tests

### ISSUE THREAD

**Issue by rreckonerr** [emberjs/ember.js#18806]
`this.set` provided by test environment and `set` imported from @ember/object behave differently in tests. In particular, when I'm setting property with `set(this, 'prop', 'new value')` it gets updated only in the next tick, while `this.set('prop', 'new value')` updates value in the same tick.

I've managed to reproduce the bug, but don't know what's causing it.
[Link to reproduction](https://github.com/rreckonerr/ember-issue-reproduction/blob/master/tests/integration/components/the-component-test.js)

**Comment by pzuraq** [comment]
This is actually the intended behavior. `ember-qunit` wraps `this.set()` with a runloop to flush any asynchronous effects synchronously. But all other forms of `set()` will cause async updates.

In general, it's recommended to move to `await settled()` in your tests, since autorun during all tests (including unit tests) now works and really any async effects should be handled asynchrously.
