### ISSUE TITLE
Using DS.PromiseArray in getter creates Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by elfin-sbreuers** [emberjs/ember.js#18813]
Hello,

When using `ember-data` 3.16.2 and `ember-source` 3.16.3 I get an infinite loop with the following structure:

```
// controllers/application.js
import Controller from '@ember/controller';
import {resolve} from 'rsvp';
import DS from 'ember-data';

export default class ApplicationController extends Controller {
  appName = 'Ember Twiddle';
  get getter () {
    return DS.PromiseArray.create({promise: resolve([])});
  }
}
```
and

```
{{!-- templates/application.hbs }}
{{this.getter}}
```

Can this be explained by wrong usage or is this a bug?

Thanks in advance.

**Comment by pzuraq** [comment]
This is less of a bug, and more of a common user error with autotracking. The main issue is, this common pattern with `@computed` doesn't work the same with native getters.

`get getter()` is a plain native getter. This means that it does not cache its value - every time it is rerendered, it returns a _new instance of the PromiseArray_.

So, the order of operations looks like:

1. We create a new `DS.PromiseArray` by accessing `getter` and use it in the template.
2. Autotracking consumes the array _and its content_, such that if either of them changes, the template will rerender. 
3. The content then immediately changes in the next microtask, because the inner promise resolves and sets `content = result`. 
4. This causes autotracking to invalidate, which causes us to rerender.
5. While rerendering, we access the value of `getter` again, which causes us to start over at step 1.

In order to get around this, you could do something like this:

```js
export default class ApplicationController extends Controller {
  appName = 'Ember Twiddle';
  get getter () {
    if (!this._promiseArray) {
      this._promiseArray = DS.PromiseArray.create({promise: resolve([])});
    }

    return this._promiseArray;
  }
}
```

This does mean you'll have to manually figure out if the promise array has been invalidated, if you ever want to update it:

```js
export default class ApplicationController extends Controller {
  appName = 'Ember Twiddle';
  get getter () {
    if (!this._lastUrl !== this.url) {
      this._promiseArray = DS.PromiseArray.create({promise: fetch(this.url)});
      this._lastUrl = this.url;
    }

    return this._promiseArray;
  }
}
```

There are some other techniques that also work here, and I'm working on [a blog post series](https://www.pzuraq.com/tag/autotracking/) that will discuss some of them in the near future. In general though, it's an antipattern to assume that an object or array will be _stable_ in this way with autotracking.

**Comment by elfin-sbreuers** [comment]
Thank you for the quick response. That was helpful.

Basically I was just following the ember documentation for converting from classic components to glimmer components. Maybe it would be helpful to give a small hint there about the behaviour of the getters or this special aspect.

So if I get that right: the getter should never create something new, but assemble something out of existing values. Your caching proposal takes care of that then. I'll keep that in mind.

Thanks again, that raised my understanding of the concept.

**Comment by pzuraq** [comment]
No problem! Going to close this issue since it seems like this is resolved, let us know if that's not the case and feel free to reopen 😄
