### ISSUE TITLE
Cannot extend class and overwrite with @tracked

### ISSUE THREAD

**Issue by mydea** [emberjs/ember.js#18812]
The following:

```js
class CustomClass {
  baseProperty;
}

class ExtendedClass extends CustomClass {
  @tracked baseProperty;
}
```

Will not work - `baseProperty` is not tracked, and you get the error:

```
Error: Assertion Failed: You attempted to update [object Object].baseProperty to "Test 2", but it is being tracked by a tracking context, such as a template, computed property, or observer. In order to make sure the context updates properly, you must invalidate the property when updating it. You can mark the property as `@tracked`, or use `@ember/object#set` to do this.
```

When changing it.

Commenting out `baseProperty` from the base class makes it work.

(Tested in ember-source 3.16 and 3.17)

**Comment by pzuraq** [comment]
This is unfortunately a side effect of the way that decorators and class fields currently work, and there isn't much we can do about it. 

Class fields completely overwrite any value that is on the class instance, by defining a new field with `Object.defineProperty`. Since `@tracked` installs a getter/setter on the _prototype_ of the class, the class field ends up winning.

In general, you should avoid tracking values using inheritance like this. It sucks, but I don't believe there's a way around it due to the behavior of class fields 😕

**Comment by mydea** [comment]
Hmm, thanks for the info! I guess it is not a huge deal, but it would probably make sense to mention this somewhere in the docs, as it was rather surprising to me :)

**Comment by locks** [comment]
Closing as wontfix due to the explanation above. Thanks for the discussion!
