### ISSUE TITLE
Promise error not being caught by RSVP.on('error') or Ember.onerror ?!

### ISSUE THREAD

**Issue by akondo06** [emberjs/ember.js#18818]
Hey,

I have some issues with promise handling for some reason.

Context:
Ember version: 3.12
user presses button which triggers an action:

```
{
...
actions: {
  doUpdate() {
    this._doUpdate();
  }
}
}
```

If the promise is handled like:

```
async _doUpdate() {
  try {
    const response = await getDummyResponse();

    // doing some stuff with the response here...
  } catch(error) {
    // doing some stuff with the error locally

    throw error; // pass it to the app for error logging
  }
}
```
or:
```
async _doUpdate() {
  return getDummyResponse().then(() => {
    // doing some stuff with the response here...
  }).catch(() => {
    // doing some stuff with the error locally
    throw error; // pass it to the app for error logging
  });
}
```
the application does not catch the error but rsvpjs prints it to the console.

However, if the `return` keyword is ommited, it gets caught.
```
async _doUpdate() {
  getDummyResponse().then(() => {
    // doing some stuff with the response here...
  }).catch(() => {
    // doing some stuff with the error locally
    throw error; // pass it to the app for error logging
  });
}
```

What am I doing wrong here?

**Comment by amk221** [comment]
I think I have a similar issue.. don't want to hijack - so will just see what everyone else says first

**Comment by BlueRaja** [comment]
I can confirm this is happening in 2.18. We're upgrading to 3.16 soon, so we'll see if it's still an issue in the LTS.

**Comment by rwjblue** [comment]
`RSVP.on('error'` can only report errors for RSVP promises not **all** promises (and specifically not for native async / await style promises).  This seems most likely related to the promise being cast into a native promise (when returned) or not.

I'd have to see a demo to actually confirm though.

**Comment by akondo06** [comment]
heh I forgot to do a demo :) here it is: https://github.com/akondo06/ember-promise-handling
Look at `app/initializers/startup.js` and `app/routes/application.js`.
I tried to mimic as much as possible of what I use in my production app.

My issue is that the error doesn't get caught in any of the global handlers. (as seen in `app/initializers/startup.js`).

Hope it helps.

**Comment by rwjblue** [comment]
I haven't had a chance to run the code yet (on mobile doing a bit of baking ATM 🥖), but it seems like you are missing an event handler for `unhandledrejection`.

**Comment by akondo06** [comment]
ah damn, that might be it. Thanks. Enjoy the goodies :)

**Comment by amk221** [comment]
@rwjblue Is there any reason _for_ using `RSVP.on('error')` (and `Ember.onerror` for that matter). As opposed to `window.` equivalents?

**Comment by rwjblue** [comment]
I don't think you'd particularly need to use `RSVP.on('error'` ever actually (since RSVP errors are delivered from within the runloop, they will always end up being sent to `Ember.onerror`), seems like a good thing to test/confirm if someone has time.

RE: using `Ember.onerror` vs `window.onerror` + `window.unhandledrejection`, I haven't tested all possible permutations but I do believe that you will not _lose_ errors (meaning from an error reporting perspective) if you only used the native versions. The thing to experiment with is that in production environments _not_ having an `Ember.onerror` would result in throwing errors while looping through the queues in the runloop. Those errors should propagate to the window equivalents (hence not losing any errors for reporting), but I don't know that they will have the same characteristics WRT the application recovering / being usable.

**Comment by amk221** [comment]
Thanks for the detailed response 👍 I will have a play.

**Comment by BlueRaja** [comment]
If the native solution catches all errors, and Ember's solution does not, then what is the point of the Ember solution? It seems like it can only cause mistakes.

**Comment by rwjblue** [comment]
Well for starters it predates the `unhandledrejection` event all together.

I’m not so sure we should continue suggesting usage of Ember.onerror, but it is worth investigation to see if the native error handler only approach has the same coverage and resilience.
