### ISSUE TITLE
Infinite loop with getter and ArrayProxy in Ember Octane

### ISSUE THREAD

**Issue by scottmessinger** [emberjs/ember.js#18874]
Hi! I'm trying to convert some computed properties over to Octane and I'm running into an infinite loop. Here's a repo:

https://ember-twiddle.com/596c1767c23c4f83db84d4187434e24b

Here's the basic problem:

```js
export default class ApplicationController extends Controller {
  
  ids = [1, 2, 3]

  get models(){    
    console.log("fetching models")

    let promises = this.ids.map(id => {
      return new Promise((resolve) => {
        setTimeout(() => {
          resolve(`document-${id}`)
        }, 10 * Math.random())
      })
    })

    return ArrayPromiseProxy.create({
      promise: all(promises)
    })
  }
}
```

If you look in the console, you'll see `console.log("fetching models")` happen over and over again until the tab locks up.

However, if you add a computed decorator, the problem goes away:

```js
  @computed("ids.[]")
  get models(){ 
    //....
  }
```

Am I doing something wrong here? Is there something that happens to work with Ember Classic and Octane is just showing the problem? On a side note, I'm excited by @pzuraq's resource RFC as it will help me accomplish this much more gracefully in the future.

Let me know if I can provide any more info!

**Comment by pzuraq** [comment]
So this is expected behavior. The issue here is that `models` does not cache its result - every time the getter runs, it will return a _new_ `ArrayPromiseProxy`. This is different from getters decorated with `@computed`, which cache their result based on their dependencies.

The loop looks like:

1. Template renders
2. Getter is accessed, ArrayPromiseProxy is created
3. ArrayPromiseProxy resolves, dirtying itself
4. Template rerenders
5. Getter is accessed again, creating a _new_ ArrayPromiseProxy
6. ...loop

The [`@cached`](https://github.com/emberjs/rfcs/pull/566) decorator is meant to help here, but this pattern is definitely trickier to do in autotracking in general. For instance, if you autotrack anything during the _creation_ of the returned class/object, and then dirty _that_, it'll cause the cache to bust and create a new value. It also leads to a lot of _antipatterns_, since folks will _mutate_ the value returned from the getter a lot of times.

**Comment by scottmessinger** [comment]
That makes a ton of sense. Thanks so much for writing that up, @pzuraq. After reading this, I went back and looked at the @use/resource RFC and it makes even more sense.
