### ISSUE TITLE
default component unit test is broken for glimmer components

### ISSUE THREAD

**Issue by gabrielgrant** [emberjs/ember.js#18877]
It seems the component unit test template doesn't make any distinction between whether it is testing glimmer vs classic components, but it only actually works for classic components

<details>
<summary>The generated test (<a href="https://github.com/emberjs/ember.js/blob/master/blueprints/component-test/qunit-rfc-232-files/__root__/__testType__/__path__/__test__.js">from this template<a>)</summary>

```
import { module, test } from 'qunit';
import { setupTest } from 'ember-qunit';

module('Unit | Component | my-glimmer-component', function(hooks) {
  setupTest(hooks);

  test('it exists', function(assert) {
    let component = this.owner.factoryFor('component:my-glimmer-component').create();
    assert.ok(component);
  });
});

```

</details>

results in `Failed to create an instance of 'component:my-glimmer-component'. Most likely an improperly defined class or an invalid module export.` 

<details>
  <summary>Full traceback: </summary>

```
Died on test #1 @http://localhost:4200/assets/tests.js:344:21
processModule@http://localhost:4200/assets/test-support.js:3885:16
module$1@http://localhost:4200/assets/test-support.js:3910:17
@http://localhost:4200/assets/tests.js:342:21
Module.prototype.exports@http://localhost:4200/assets/vendor.js:118:32
requireModule@http://localhost:4200/assets/vendor.js:39:18
require@http://localhost:4200/assets/test-support.js:14293:16
loadModules@http://localhost:4200/assets/test-support.js:14286:14
loadTests@http://localhost:4200/assets/test-support.js:15306:22
start@http://localhost:4200/assets/test-support.js:14983:33
@http://localhost:4200/assets/tests.js:337:25
Module.prototype.exports@http://localhost:4200/assets/vendor.js:118:32
requireModule@http://localhost:4200/assets/vendor.js:39:18
@http://localhost:4200/assets/tests.js:539:8
: Failed to create an instance of 'component:my-glimmer-component'. Most likely an improperly defined class or an invalid module export.

Source: | create@http://localhost:4200/assets/vendor.js:1213:15 @http://localhost:4200/assets/tests.js:345:78 runTest@http://localhost:4200/assets/test-support.js:5735:30 run@http://localhost:4200/assets/test-support.js:5721:13 runTest/<@http://localhost:4200/assets/test-support.js:5952:12 processTaskQueue@http://localhost:4200/assets/test-support.js:5308:24 advanceTaskQueue@http://localhost:4200/assets/test-support.js:5293:20 advance@http://localhost:4200/assets/test-support.js:5279:4 unblockAndAdvanceQueue@http://localhost:4200/assets/test-support.js:7083:20 begin@http://localhost:4200/assets/test-support.js:7117:5 internalStart/config.timeout<@http://localhost:4200/assets/test-support.js:6349:6

```

</details>

The failure is specifically with [this line](https://github.com/emberjs/ember.js/blob/master/blueprints/component-test/qunit-rfc-232-files/__root__/__testType__/__path__/__test__.js#L33), where it tries to invoke `.create()` on the non-ember-object glimmer component class
It seems it should be doing something like this instead: 

```
module('Unit | Component | my-glimmer-component', function(hooks) {
  setupTest(hooks);

  test('it exists', function(assert) {
    let { class: componentClass } = this.owner.factoryFor('component:my-glimmer-component');
    let componentManager = this.owner.lookup('component-manager:glimmer');
    let named = {};  // your args
    let component = componentManager.createComponent(componentClass, { named });
    assert.ok(component);
  });
});
```

More info (and thanks) in [this blog post](https://timgthomas.com/)

I'm happy to submit a PR for this, but unsure what the behavior should be. A few options:
1. change the blueprint to only work with Glimmer components (unclear if having newly-generated tests not work for classic components would be considered a "breaking change"?)
2. figure out some way to detect which type of component is referred to while generating the test, and produce the correct output
3. do detection of which component type we're dealing with at runtime (likely complicating the test)
4. accept a flag to switch between component test types
5. create a separate `glimmer-component-test` blueprint
6. figure out some way to create components that works regardless of type

I'd probably be inclined to go with 4., with default being glimmer, but curious to hear what others think (particularly about whether there's a workable way to do 2. or 6.)

**Comment by pzuraq** [comment]
The `this.owner.lookup('component-manager:glimmer')` style API was an API that shipped early on, and has since changed. In Ember 3.8+ it is a _very_ different API, entirely private and not something you can lookup on the container at all.

**Comment by schleifer-john** [comment]
@pzuraq My team has been using Ember since version 1.x.  We have several enterprise level applications with 1000s of lines of code.  Most of the Ember upgrades have been fairly easy for us and we can simply run the `ember-cli-update` addon and make minor updates as needed.

I assume at some point that Classic Components are going to be dropped and we are going to be forced to use Glimmer Components?  I think we are going to have a very difficult time switching and seeing core features like component unit test support getting dropped seems like a big cause of concern for my team.

One of the precursors for refactoring / upgrades is having good test coverage.  It sounds like eventually we are going to have to convert all of our components to Glimmer components, at which point we lose the ability to run our suite of unit tests.  We will then be required to convert our suite of unit tests to integration tests.  There will be a gap where we have no coverage and are basically starting from scratch here.

I hope that I'm missing something here, but the bottom line seems that your existing Ember user base will potentially incur months worth of technical debt in order to be able to upgrade Ember versions in the future.  This seems like a drastic change in direction from how the Ember project has been run up until now with regards to version upgrades.  I implore the Ember team to please reconsider the decision to drop component unit test support.

**Comment by pzuraq** [comment]
@schleifer-john you are correct that classic components will eventually be removed from the framework, however there will be a very long timeline for that, 2-3 years minimum, possibly longer.

The expected upgrade flow would be to convert one component at a time in that period, incrementally. During the conversion process, you would have the time to consider and rethink the state flow of your component to use tracked properties, the APIs of your component to use Glimmer component APIs, and the tests of your component to use integration tests.

I would generally expect all of these changes to land in a single PR, so I’m not sure how there would be a gap in test coverage. Alternatively, you could convert your tests first, and other parts of your component such as tracked properties, and then convert to Glimmer components.

If the prospect of converting all Classic components to Glimmer components sounds like it would be too much, I think we can consider exposing a few more feature in component managers to the community can create a “Classic-like” API, which would be similar to classic components with minor differences. 

I also think we are open to the idea of allowing unit tests for components, but as I’ve said before we would need to understand the use cases and motivations. Currently, there hasn’t been a solid motivating case, and the fact is that your tests will likely need to be rewritten during this conversion either way, even if you do have unit tests, because the APIs of the component classes are pretty different. So, given most users will have to rewrite tests, and integration tests are generally better for components, it makes sense to convert to integration tests during that process. Open to more discussion on this point though, and to provide guidance on how to update specific tests.

**Comment by schleifer-john** [comment]
@pzuraq I know the speed of running the test case suite has gotten better now, but historically running integration tests was much slower performance-wise vs unit tests.  I believe this is what originally led us down the route of favoring unit tests vs integration tests at the component level.  

I also come from more of a Java / Spring background where Unit Tests are more ingrained into the regular development process, so hearing that there aren't use cases for being able to isolate and test units of code seems like a radical deviation from what the rest of the software industry as a whole is doing.

Willing to give integration tests in Glimmer components a try and I can see where only having integration tests could work very well for simple components, but I don't think this "one-size-fits-all" approach works for more complex components.  

There are plenty of articles out there explaining the benefits of Unit Testing and I believe the same applies here for components.  For more complex components in particular, we need the ability to isolate and test specific logic at the unit level without having to wire up and render the entire component.

**Comment by pzuraq** [comment]
@schleifer-john the discussions we've had on the core team generally come back to "what is the 'unit' you are testing". This is also why "integration" tests were renamed to "rendering" tests - the logic is that standalone component rendering tests _are_ unit tests, because they are testing the most fundamental unit of code.

One of the common antipatterns we've seen, for instance, is users unit testing a component on its own without considering its interactions with any of its child components. You may say that makes sense though, because that would be an integration - but when you look at a component as a _function_ that receives arguments and produces HTML, then that assumption kind of changes. If you were unit testing the following function:

```js
function someUtility() {
  let value = someOtherUtility();
  return yetAnotherUtility(value);
}
```

You wouldn't mock the `someOtherUtility` and `yetAnotherUtility` functions so that you're testing `someUtility` on its own, because you then have a test that is testing too little - it's effectively meaningless. The same goes for testing without considering lifecycle, which is pretty fundamental to components.

All that said, I do think there are places for testing business logic independent of rendering. There are a few options there:

1. Pull the code out into a utility function, which can be tested separately
2. If the code is stateful, create a delegate class that contains the logic and state separately and make an instance of it on the component:
   ```js
   // before
   class MyComponent {
     @tracked state = 123;

     doSomething() {
       this.state++;
     }
   }

   class MyDelegate {
     @tracked state = 123;

     doSomething() {
       this.state++;
     }
   }

   class MyComponent {
     delegate = new MyDelegate();

     get state() {
       return this.delegate.state;
     }

     doSomething() {
       this.delegate.doSomething();
     }
   }
   ```
3. Extract the functionality to a service if it involves DI and other shared state

I'll raise your concerns again with the core team as well to keep the conversation going, I do want to make sure your concerns are addressed and your team feels like they have a solid, well thought out path forward.

**Comment by schleifer-john** [comment]
Thanks for all of the information and examples @pzuraq.  I'll have my team try to work with integration tests & glimmer components for any new development work going forward.  It could be that this new convention just takes some getting used to.

**Comment by wongpeiyi** [comment]
> We've discussed this and generally found it isn't a priority, since simple rendering tests usually test things in a much more cohesive way. When business logic does need to be unit tested, it can be broken out into a utility functions which can be tested on their own more thoroughly, without the need to create a class

Hi @pzuraq, while I understand the principle behind this decision, I do find situations where rendering tests are simply not feasible. For example, I have a variety of chart components and there is is no good way to make assertions on rendered Canvas elements. As a next best alternative, I would instead like to make assertions on the data and options being fed to the chart library, based on different args being fed to the component.

I can as you say, extract out the logic into utility functions, but it really is logic that I feel belongs on the component. Doing so also forces me away from an OOP pattern. And if to get an OOP pattern I use a state delegate class as your example, I'll then have to deal with passing the component args into the delegate on update, which has its own set of limitations, and ends up being a lot of wiring and spaghetti just so tests can be written

**Comment by gabrielgrant** [comment]
FWIW, since opening this issue, I've implemented a number of would-be "component unit test" by moving utility functions out of the component class. Agree it felt a bit weird at first, but in general, I've found that separating the more complex business logic into stateless functions that are completely separate from the component's rendering/event-handling logic has made the code easier to reason about, and correspondingly more correct. For those "computation methods" that do have more complex logic, but are really only related to the one specific component, i've just been keeping the helper function in the component file (rather than a separate util module) and still calling the test a "component unit test", but the test just imports the relevant helper function(s), and generally doesn't touch the component class at all

@pzuraq thanks for the pointer

**Comment by wongpeiyi** [comment]
@gabrielgrant yes that's what I've done too, and there definitely are situations where this is beneficial. There are also others where it's not. The choice of whether to use a functional approach or a stateful OOP approach should be left to the developer, or at least consistent within the framework, and not forced upon simply because one needs to write tests

Essentially, the "Ember way" prescribed in guides:
- Use `@tracked`!
- Use getters!
- Use args and actions on your component

BUT... you want to write tests?
- Drop all the above and use stateless functions 

The situations where doing this is unwieldy are when the component has complex state due to its args and tracked properties, but then you have simultaneously force a "stateless" approach on it by having a bunch of getters call extracted functions:

```js
get chartData() {
  return computeResult(this.args.data, this.trackedSettings);
}
```

It adds no value because it _is_ actually very dependent on state, but then the code is all over the place just for the sake of tests

**Comment by gabrielgrant** [comment]
@wongpeiyi agree that creating a bunch of these stub functions can be annoying in a few cases, but in general, what i've found useful is precisely this separation of the tests for how that stateful data gets computed/used in computation (unit tests on stateless functions) vs how the state gets established and how the results of those computations are used (through simple rendering tests).

In what you're calling the "OOP" approach, testing the computation method on a component requires the test to know about, and properly set up, all the required internal state of the component. This kind of poking around internal object state from a test feels like it creates an unnecessary coupling between test and implementation. The stateless computation approach keeps those implementation details out of the tests -- the knowledge of what state is used in a given method doesn't need to leak outside of the method's own implementation, and tests can focus on testing behavior

**Comment by wongpeiyi** [comment]
@gabrielgrant I did hear what you were saying earlier and I understand that, and I'm not refuting your good experience. However just because it turned out good in your case doesn't mean it's good in all cases. Please don't invalidate other people's experiences because it happened to to turn out good for your personal situation

Do all your component getters call separate, external functions? I'm assuming not – because in some cases it doesn't make sense to. In your case it was a better refactor AND it allowed it to be tested. I'm saying there are cases where extracting it out allows it to be tested BUT is not a better refactor because of the dependency on args and states.

You changed your code to allow it to be tested, and coincidentally that was a better refactor – that's great. However, the decision to extract code into functions should be separate from whether code can be tested or not, because in some cases this is not a better refactor:

```js
// Typical chart component
export default class ChartComponent extends Component {
  get data() {
    const { data, options } = this.args;

    return options.showSpecial ? data.concat(this.specialDataset) : data;
  }
}

// Refactor so it can be tested
export default class ChartComponent extends Component {
  get data() {
    const { data, options } = this.args;

    return computeData(data, options, this.specialDataset);
  }
}

function computeData(data, options, specialDataset) {
  return options.showSpecial ? data.concat(specialDataset) : data;
}
```

Imagine having to do this for more than one getter. There is no meaningful refactor here by extracting the code. If I had multiple getters written this way, the first question someone would ask reading the code would be "why are these extracted?" and the response "just so they can be tested" would undoubtedly illicit a facepalm

I would want to just use an integration test and be done with this argument but I can't. Would love to see how you would handle this.

**Comment by laynegt** [comment]
I'm in a similar boat with @wongpeiyi.  I have unit tests written against newly-converted Glimmer components that render Chart.js canvas elements.  The tests are on certain computed property chains that affect the rendering options for the charts (axes labels, tooltips, etc.).  Since this is rendering-related logic, I want to keep it inside the component.

Though I would be open to extracting out logic to make this work, it's just not feasible right now to do that kind of refactor, and I agree with Wong's point earlier that it seems against standard Ember patterns.

**Comment by amauryt** [comment]
I am in the middle of refactoring classic components to glimmer ones for an app focused on music interaction. So far the refactoring has been worth it, albeit time consuming, but the lack of official support of unit tests for glimmer components may be a blocker.

I am in a similar situation to that of @wongpeiyi. For some components I am using Pixi.js to render part of the GUI via WebGL, together with some DOM elements provided by the component itself. The Pixi.js apps are only used inside their respective components and they depend on the components' state and on several ember services, either from add-ons (e.g., ember-intl) or custom-made (e.g., WebMIDI control), which are already used across the app. I use rendering tests for the behaviour of the component and their DOM elements, whereas I use unit tests for the behaviour of the components' Pixi.js app.

For the moment I resorted to the [solution](https://timgthomas.com/) proposed by @timgthomas to use my unit tests for glimmer components, but it seems that this approach will likely break in a future release.

I agree with @pzuraq on the unsuitability of unit tests for components in the great majority of cases. However, in the case of developing components that depend on libraries such as Pixi.js, the development experience and upgrade path becomes much easier if unit tests for glimmer components continue to be possible.

**Comment by akauffmanGG** [comment]
Edge cases that arise from complex data scenarios, subtle timing differences, interactions with 3rd party UI, and others can be extremely difficult to test using rendering tests, but are not problems at all with unit tests. 

While it is true that all business logic could be extracted out of the component, that isn't really a practical solution nor is that pattern reflected anywhere in the ember guides.

It really seems we're being told there is no compelling reason to have automobiles because bicycles exist.

**Comment by rwjblue** [comment]
> It really seems we're being told there is no compelling reason to have automobiles because bicycles exist.

FWIW, you've got this backwards 😜. Rendering tests are obviously the automobile... 😼

**Comment by rwjblue** [comment]
OK, seriously though: The patterns that exist that let you gain access to the component instance from your rendering tests are expressive enough for these use cases without forcing component's to be instantiated in a completely foreign and unnatural way.

For example:

```js
module('my-thing', function(hooks) {
  setupRenderingTest(hooks);

  test('something that wants to exercise an internal method', async function(assert) {
    let component;

    this.owner.register('component:my-thing', class extends MyThing {
       constructor(owner, args) {
         super(owner, args);
         component = this;
       }
    });
    
    await render(hbs`<MyThing />`);

    // now I can interact with `component` without issue
  });
});
```

This pattern can easily be moved into something more easily shared if you have more than one test that uses it:

```js
module('my-thing', function(hooks) {
  setupRenderingTest(hooks);

  hooks.beforeEach(function() {
    let testContext = this;
    this.owner.register('component:my-thing', class extends MyThing {
       constructor(owner, args) {
         super(owner, args);
         testContext.component = this;
       }
    });
  });

  test('something that wants to exercise an internal method', async function(assert) {
    await render(hbs`<MyThing />`);

    // now I can interact with `this.component` without issue
  });
});
```

**Comment by akauffmanGG** [comment]
To be clear, I think rendering tests are great. I simply meant it's not the right tool for every job and as a work around we're being asked to use a much more cumbersome alternative.

The solution you provided is far more reasonable. It should suit most use cases and make it easier to migrate existing unit tests. Thanks!

**Comment by rwjblue** [comment]
> The solution you provided is far more reasonable. It should suit most use cases and make it easier to migrate existing unit tests.

👍👍 going to close now, as I think my suggestion in https://github.com/emberjs/ember.js/issues/18877#issuecomment-675758868 is the path forward when you **absolutely must** have this functionality.

**Comment by lifeart** [comment]
One more option - using debug API - https://gist.github.com/lifeart/0484b374a3712d96f393cdd5d7c9cd49

**Comment by numan-ahmad** [comment]
@rwjblue in my case  'class extends MyThing' the name of component is not define error show
