### ISSUE TITLE
webpack returned errors to ember-auto-import

### ISSUE THREAD

**Issue by YanJie-001** [emberjs/ember.js#18950]
I have a problem build error like title of my topic, anyone can help me?

Build Error (Bundler)
webpack returned errors to ember-auto-import

**Comment by rwjblue** [comment]
This doesn't really seem like a bug in Ember itself (which is what we use this issue tracker for).  I'd suggest that you search the ember-auto-import issue tracker, post on StackOverflow, the community discuss.emberjs.com, or other common question and answer venues to see if anyone has an idea of what is going on.

Since this isn't really an issue with Ember, I'm going to go ahead and close this issue.
