### ISSUE TITLE
Using @alias on a getter does not update if the managed value is changed

### ISSUE THREAD

**Issue by elfin-sbreuers** [emberjs/ember.js#18985]
Hey there,

during the process of upgrading to Ember 3.16 from 2.18, we stumbled across this issue. We want to replace `computed`s with getters. We made heavy use in our application of this feature. Also using the computed helper functions, that can slim down the code significantly.

We replaced `computed` with their getter counterparts. We now see that the getter does not behave the same as the computed, when it comes to `alias`ing. The value stays as it was initially. I prepared an Ember Twiddle [here](https://ember-twiddle.com/c05ecb4599915cb3e69632c65b9e58d9?openFiles=services.my-service%5C.js%2Ctemplates.components.my-component%5C.hbs)

Is that the intended behaviour? Is there a way to use `alias` with a getter that updates when the getter changes?

Cheers and thanks in advance.

**Comment by pzuraq** [comment]
This is unfortunately not supported functionality. `@alias` and other computed property macros cannot depend directly on getters, because they cannot autotrack. We found that autotracking would be a breaking change in many applications.

You can use the [@dependentKeyCompat](https://api.emberjs.com/ember/3.18/functions/@ember%2Fobject%2Fcompat/dependentKeyCompat) decorator to expose native getters directly to other computed properties. Alternatively, you could consider changing over to a library like [macro-decorators](https://github.com/pzuraq/macro-decorators), which does not cache based on dependencies and doesn't have this issue.

**Comment by pzuraq** [comment]
Closing this issue for now, let us know if you have any further questions!
