### ISSUE TITLE
Is RouterService#isActive(someRoute) supposed to entagle with tracking?

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember.js#19004]
Just noticed that if I have:

```ts
@service router;

get isTabActive() {
  return this.router.isActive(this.args.route); // route is static for this scenario
}
```
isTabActive never updates when the URL changes / a router transition occurs

**Comment by rwjblue** [comment]
@NullVoxPopuli - FWIW, I dealt with these exact issues in https://github.com/rwjblue/ember-router-helpers/pull/263 by just accessing `routerService.currentURL` and `routerService.currentRouteName` which _do_ properly entangle things with tracking. Note in that PR there is a minor bit of "trickiness" with regards to checking both `.currentURL` and `.currentRouteName`, neither of those fields are "good enough" on their own (because loading states would not change url but would change route name, and changed model values wouldn't change route name but would change URL).

I think it would be good to access those two properties from within `isActive` to  prevent folks from having to do the kinds of work arounds I did in the PR above.

**Comment by johngibbons** [comment]
> @NullVoxPopuli - FWIW, I dealt with these exact issues in [rwjblue/ember-router-helpers#263](https://github.com/rwjblue/ember-router-helpers/pull/263) by just accessing `routerService.currentURL` and `routerService.currentRouteName` which _do_ properly entangle things with tracking. Note in that PR there is a minor bit of "trickiness" with regards to checking both `.currentURL` and `.currentRouteName`, neither of those fields are "good enough" on their own (because loading states would not change url but would change route name, and changed model values wouldn't change route name but would change URL).
> 
> I think it would be good to access those two properties from within `isActive` to prevent folks from having to do the kinds of work arounds I did in the PR above.

It looks like the merged solution ended up only accessing `currentUrl`, which does create an issue when transitioning between a parent route's loader to the child route, e.g. `accounts.item.campaigns.loading` => `accounts.item.campaigns.item`.  A getter based on this route will only fire during the loading phase since the url does not change, and would return `false` for `isActive('accounts.item.campaigns.item')` during that phase, even though ultimately it should return `true`.
