### ISSUE TITLE
[Bug] Component dependency Injection not working v3.15

### ISSUE THREAD

**Issue by svkangal** [emberjs/ember.js#19008]
Hi,
We use ember initializer to inject some data which should be available everywhere in the app. The issues is it works everywhere except the components. For some reason that data is not available/injected in the components. This is working fine for one of our other app which is on Ember 2.13. 
Our new app is using 3.15 and I am wondering if it has anything to do with Glimmer components.
I stepped through the following inject code looks like it properly registering under _typeInjections.   

```
  Sample from initialzier - 
  application.inject('controller', 'appServerData', 'appServerData:global');
  application.inject('route', 'appServerData', 'appServerData:global');
  application.inject('component', 'appServerData', 'appServerData:global');
```
Ember Twiddle link
3.15
https://ember-twiddle.com/26246f02d8d89f3ca2faea9ff3773b58?openFiles=components.my-component%5C.js%2Ctemplates.components.my-component%5C.hbs

2.18
https://ember-twiddle.com/d5fc1544ea138d4873b921726922e293?openFiles=templates.application%5C.hbs%2Ctemplates.components.new-component%5C.hbs

**Comment by svkangal** [comment]
Any help would be greatly appreciated.

**Comment by richard-viney** [comment]
I doubt that you're able to globally pollute Glimmer components in this way (which is a good thing).

If you have some shared data that you want to be available in the app then it either belongs in a service, or in an ES6 module that's imported where needed.

**Comment by svkangal** [comment]
Well it was possible before and documentation does suggest to you can use it now. I dont see it as polluting if it some app config data that you need it everywhere. If the support for this has been removed, at least I would like to know so I can look for other options.

**Comment by richard-viney** [comment]
Good point re. the docs for https://api.emberjs.com/ember/3.18/classes/Application/methods/inject?anchor=inject stating that this works for "components". This probably needs correcting to say "classic components" instead.

Glimmer components do not inherit from `EmberObject` and when they are instantiated it's therefore done with the usual `new MyComponentClass(...)` syntax. This is why they don't participate in these kind of injections (and also lack other features from `EmberObject`), because those are specific to types that extend from `EmberObject`. The rationale for not using `EmberObject` in Glimmer components is outlined in the [Glimmer components RFC](https://emberjs.github.io/rfcs/0416-glimmer-components.html).

Long-term the plan is to use native classes everywhere and to deprecate `EmberObject` entirely. This means that eventually these injections will likely stop working for routes/services/controllers as well, though there's no current timeline for this that I'm aware of.

Using a dedicated service or ES6 module for config data seems the most idiomatic and future-proof approach. Alternatively, if it's static app config then you could also put it in `config/environment.js` and access it from there as described in https://guides.emberjs.com/release/configuring-ember/.

**Comment by svkangal** [comment]
Thanks for the clarification, makes sense. Given that initializers are mainly used for these kind of runtime injections what do you think will happen to them? Are they also on path of getting deprecated? 
Will close this issue.

**Comment by richard-viney** [comment]
I've not read anything about initializers being deprecated. It might make sense to do so, but if it were to happen it would be quite a while away indeed. Still, my take is that these sorts of automatic injections aren't going to be favoured as Ember moves forward, and that users will instead be steered towards writing code that's more explicit (and also more compatible with type-checking as an added bonus). However, I'm not sure how widespread the use of initializers is in the ecosystem, or other use cases that they may have.
