### ISSUE TITLE
Modifier Managers should not re-consume their args on destroy

### ISSUE THREAD

**Issue by NullVoxPopuli** [emberjs/ember.js#19162]
According to the [current modifier manager spec](https://github.com/emberjs/rfcs/blob/master/text/0373-Element-Modifier-Managers.md#destroymodifier): 

> destroyModifier will be called when the modifier is no longer needed. This is intended for performing object-model level cleanup.

then, in the following code example:
```ts
 destroyModifier(instance, args) {
    if (instance.willDestroyDOM !== undefined) {
      instance.willDestroyDOM();
    }
  }
```
args are passed to `destroyModifier`.

I think this is a bug because:
 - it means that args are all re-consumed on _destruction_ of a render / component tree
 - `if` guards in templates no longer can guarantee the safety of the shape of data
 - in order for modifiers' destruction to not trigger exceptions wherever args' derived data is derived, you need to add additional guards all over your code, or do `foo?.bar?.bax` everywhere (this generates a lot of boilerplate)
  
------------------------------

**I propose we _remove_ `args` from the `destroyModifier` hook so that** 
  - none of the above issues exist anymore
  - teardown is slightly faster due to not re-consuming args

----------------------

For example, today, the following isn't safe:

```hbs
{{#if this.data.foo}}
  <SomeComponent @data={{this.data}} />
{{/if}}
```
```ts
// some-component
export default setComponentTemplate(hbs`
  <span {{some-modifier this.nestedData}}>breaks</span>
`, class extends Component {
  get nestedData() {
    // you should be able to assume foo exists, because of the condition in the previous template
    // but today, you can't assume that :(
    return this.args.data.foo.dataOnFoo;
  }
});
```

Minimal Reproduction / Description of the Problem: https://ember-twiddle.com/5a3fa797b26e8807869340792219a5ee?openFiles=components.demo%5C.hbs%2Ccomponents.demo%5C.hbs

Relevant Discord Threads:
 - [one](https://discordapp.com/channels/480462759797063690/485447409296736276/722483725157400576)
 - [two](https://discordapp.com/channels/480462759797063690/608346628163633192/743649497518702613)

**Comment by rwjblue** [comment]
The path forward here is to make this code sharable between the various manager types (modifier and component now, but soon helpers):

https://github.com/emberjs/ember.js/blob/984e69c2be41acc243805aae339cb7499fa2d9cc/packages/%40ember/-internals/glimmer/lib/component-managers/custom.ts#L159-L238

* Extract ^ to a utility (it should be "primed and ready" I think)
* Update custom modifier manager to do something more like this:

https://github.com/emberjs/ember.js/blob/984e69c2be41acc243805aae339cb7499fa2d9cc/packages/%40ember/-internals/glimmer/lib/component-managers/custom.ts#L284-L289

Instead of always reifying:

https://github.com/emberjs/ember.js/blob/984e69c2be41acc243805aae339cb7499fa2d9cc/packages/%40ember/-internals/glimmer/lib/modifiers/custom.ts#L149

https://github.com/emberjs/ember.js/blob/984e69c2be41acc243805aae339cb7499fa2d9cc/packages/%40ember/-internals/glimmer/lib/modifiers/custom.ts#L161

https://github.com/emberjs/ember.js/blob/master/packages/%40ember/-internals/glimmer/lib/modifiers/custom.ts#L66

**Comment by rwjblue** [comment]
I've pushed up a quick stab of this over in https://github.com/emberjs/ember.js/pull/new/modifier-args-proxy.
