### ISSUE TITLE
[Bug] PerformanceObserver is not defined on UXP browsers, makes framework fail.

### ISSUE THREAD

**Issue by wolfbeast** [emberjs/ember.js#19186]
### 🐞 Describe the Bug
You seem to be using the PerformanceObserver API in your framework without doing feature detection, resulting in JS erroring and aborting.

### 🔬 Minimal Reproduction
reproducing URL: https://music.apple.com/il/album/sentinel/1528162085

1. install [Pale Moon](http://www.palemoon.org), [Basilisk](http://www.basilisk-browser.org), or any other UXP-based browser
2. Visit the URL above

The website errors after briefly showing content.
Web console displays:
> Error: Error while processing route: album,PerformanceObserver is not defined,e/<@https://music.apple.com/assets/vendor-a52976b8f21a708bd66c1cd01d537716.js:4338:947
c@https://music.apple.com/assets/vendor-a52976b8f21a708bd66c1cd01d537716.js:83:151
l/o._invoke</<@https://music.apple.com/assets/vendor-a52976b8f21a708bd66c1cd01d537716.js:80:32
h/</e[t]@https://music.apple.com/assets/vendor-a52976b8f21a708bd66c1cd01d537716.js:83:328
w@https://music.apple.com/assets/vendor-a52976b8f21a708bd66c1cd01d537716.js:4305:46
a@https://music.apple.com/assets/vendor-a52976b8f21a708bd66c1cd01d537716.js:4307:15
Source File: https://music.apple.com/assets/vendor-a52976b8f21a708bd66c1cd01d537716.js
Line: 1424

Which points to the Ember framework.

### 😕 Actual Behavior
Site loads, then blanks and errors, throws error in the console as above.

### 🤔 Expected Behavior
Site should be usable.

### 🌍 Environment

- Ember: - Unknown
- Node.js/npm: - Unknown
- OS: - Windows 10
- Browser: - Pale Moon 28.14.2

### ➕ Additional Context
It seems your outsourcing to Browserstack for testing is biting you here. Browserstack is clearly ignoring a good chunk of alternate browser choices, and falls woefully short on Windows-browsers.

**Comment by pzuraq** [comment]
Thank you for reporting this @wolfbeast! I just did a search in the Ember, Ember Data, and Glimmer codebases and did not see any instances of using `PerformanceObserver`. We also typically remove instrumentation like that in our production builds, since it adds extra overhead.

I believe this may be being added by a different library, which would be the culprit here.

**Comment by wolfbeast** [comment]
Ah, sorry if this was posted to the wrong repo then - the immediately surrounding code _strongly_ suggested it was Ember, though. Do you have any idea how to move forward with this and find out the correct library owner(s) to contact?

**Comment by pzuraq** [comment]
No worries! Apple Music does use Ember for their application, so it's likely that the code surrounding it will either be related to Ember, or use Ember constructs, but based on searching through our codebase I think the problem is on their end. It could either be an open source library they are using, or a closed source one they've written. I recommend reaching out to Apple support, their support website is [here](https://support.apple.com/guide/music-web/welcome/1.0/web/1.0).

I'm going to close this issue as I don't think there's anything else to be done here.

**Comment by wolfbeast** [comment]
I've been in touch with Apple as they reached out directly and confirmed it's on their end -- and promised to have a fix out in a week or so. So nothing to be done here for you. Closing :)
