### ISSUE TITLE
Eagerly executed block params

### ISSUE THREAD

**Issue by skaterdav85** [emberjs/ember.js#19217]
I noticed that there was a change between Ember 3.16.10 and 3.17.0 that causes yielded params to be eagerly executed. I reproduced the issue in Ember Twiddle.

Ember 3.16.10: https://ember-twiddle.com/6f774113b074ab8a890d0e9c383ded06?openFiles=templates.application%5C.hbs%2Ctemplates.components.my-component%5C.hbs

Ember 3.17.0: https://ember-twiddle.com/739a09fbabd3a84662ed5b0c41760431?openFiles=templates.application%5C.hbs%2Ctemplates.components.my-component%5C.hbs

In the `my-component` `yield`, you'll see how the `log` statement is executed in 3.17.0 and not in 3.16.10. In both cases, that block param isn't used.

Was this intended or is this a bug?

**Comment by pzuraq** [comment]
This was intended as part of an optimization where we were eagerly executing helpers in order to determine if they would ever update, and do less work if not. This optimization is refined moreso in more recent versions so that only helpers which are actually used/executed will be checked, but in general we don't guarantee if/when helper values execute in templates, so it may change over time as we hone their performance characteristics.

**Comment by skaterdav85** [comment]
@pzuraq thanks!
