### ISSUE TITLE
How to set glimmer DEBUG separately

### ISSUE THREAD

**Issue by BryanCrotaz** [emberjs/ember.js#19383]
Glimmer tracking debugging is SLOW (1.4ms for adding a single tag) in 
```javascript
if (DEBUG) {
      markTagAsConsumed(tag);
    }
```

In a development build, the Ember debug flag is set. How do we stop this flowing down to glimmer, so as to better see performance issues in the application code?

**Comment by pzuraq** [comment]
In more recent versions of Ember we sped this up moreso, there was an issue with creating a full error stack each time a tag was consumed.

As for switching the DEBUG flag, you can do that by making production build. If the issue is that you find a production build difficult to debug, you can disable terser/uglification in production builds and that should make it much easier to debug, while giving you an accurate production build. DEBUG is not the only change in production builds, and when debugging performance issues you should always use production builds because of this.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. It seems outdated and likely no longer relevant.

By closing some old issues we reduce the list of open issues to a more manageable set. Let me know if you think this is a mistake and that the issue should stay open.
