### ISSUE TITLE
[Documentation] `templateOnly` documentation is missing

### ISSUE THREAD

**Issue by Windvis** [emberjs/ember.js#19520]
### 📙 Describe the Issue
I was looking for the import path for [`templateOnlyComponent`](https://emberjs.github.io/rfcs/0481-component-templates-co-location.html#template-only-components) but I couldn't find it in the API docs. The package is listed, but it [shows a blank page](https://api.emberjs.com/ember/release/modules/@ember%2Fcomponent%2Ftemplate-only).

### 🔬 Minimal Reproduction
https://api.emberjs.com/ember/release/modules/@ember%2Fcomponent%2Ftemplate-only

### 😕 Actual Behavior
The API docs don't contain any information about `templateOnlyComponent`.

### 🤔 Expected Behavior
Have some documentation available.
### ➕ Additional Context
The RFC has some good information, maybe some of that can be converted to API docs?

**Comment by rwjblue** [comment]
These docs should be showing up:

https://github.com/emberjs/ember.js/blob/v3.27.1/packages/@ember/component/template-only.ts

I think the issue is that this line should be removed:

https://github.com/emberjs/ember.js/blob/d28a09c81a07cead58959fff0ee7e072ce27501e/packages/%40ember/component/template-only.ts#L28

**Comment by Windvis** [comment]
@rwjblue I totally lost track of this issue. The docs do indeed exist, but they appear in a completely different place :smile: :

https://github.com/emberjs/ember.js/issues/19325
