### ISSUE TITLE
[Bug] Transitioning to a redirecting route inside an async function causes a `TransitionAbortedError` error

### ISSUE THREAD

**Issue by abulrim** [emberjs/ember.js#19604]
Awaiting a route transition inside an async function, when the target route redirects to a different route, will cause a `TransitionAbortedError` error.

The initial transition needs to be `awaited` for the error to happen like so:
```js
async login() {
  await this.router.transitionTo('route-1');
}
```
while `route-1` redirects in the `beforeModel` hook like so:
```js
beforeModel() {
  this.router.transitionTo('route-2');
}
```

A full reproduction of the scenario can be seen in [this twiddle](https://ember-twiddle.com/df4536befc160a347f17b6432df37267)

### Environment

- Ember: 3.26.1
- Node.js/npm: 14.15.1/6.14.8
- OS: macOS Big Sur
- Browser: Chrome

**Comment by bertdeblock** [comment]
I could be wrong, but I think that using `await` calls [then](https://api.emberjs.com/ember/3.25/classes/Transition/methods/then?anchor=then) on the returned [Transition](https://api.emberjs.com/ember/3.25/classes/Transition) object?

Taken from `then`'s docs:
> A standard promise hook that resolves if the transition succeeds and rejects if it fails/redirects/aborts.

So, I guess this is expected behaviour?

**Comment by abulrim** [comment]
You're right @bertdeblock, I didn't expect a redirect to make it fail. Thank you. I will close this now.
