### ISSUE TITLE
[Bug] implicit-injections deprecation

### ISSUE THREAD

**Issue by yratanov** [emberjs/ember.js#19727]
### 🐞 Describe the Bug
`implicit-injections` deprecation is being triggered even if I explicitly define service in parent object

### 🔬 Minimal Reproduction
Create a route file with `@service store;`, Create another route and inherit it from the first one. Use `this.store`. See that deprecation warning is shown.

### 😕 Actual Behavior
Deprecation warning is shown.

### 🤔 Expected Behavior
I expect to see no deprecation warnings.

### 🌍 Environment

- Ember: 3.27.2
- Node.js/npm: 14.17.5
- OS: -
- Browser: -

**Comment by snewcomer** [comment]
@yratanov Thank you for laying out the issue here.  This seems possible.  We could build on this [PR](https://github.com/emberjs/ember.js/pull/19358) to add a test case and fix.  4.0 ultimately removed the ability to implicitly inject.  Users could live with this deprecation for as long as they don't upgrade to 4.0.  It doesn't break nor is shipped to production but is an annoyance that may leave users needlessly searching for it.

Overall I think the answer is, yes we should fix and backport to 3.27.x.  The work probably isn't very intensive.  Just laying out some thoughts if somebody wanted to contribute a different opinion.

**Comment by snewcomer** [comment]
Just coming back to this issue.  While I really appreciate this issue, it seems low priority enough to avoid back porting to 3.28.  The fix is probably not very impressive and is not terribly critical for users.  What do you think @yratanov?  While 4.0 might be a big leap for folks from 3.28, I imagine people are working to get to 4.0 anyways where this deprecation is not present.

**Comment by gzurbach** [comment]
I spent the last 30 minutes wondering where this deprecation warning was coming from... now I know 😄

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue.

Closing for this reason:

> Just coming back to this issue. While I really appreciate this issue, it seems low priority enough to avoid back porting to 3.28. The fix is probably not very impressive and is not terribly critical for users. What do you think @yratanov?

By closing some old issues we reduce the list of open issues to a more manageable set. 

This can still be indexed by google, so people can find it if needed, even if it's closed.
