### ISSUE TITLE
`Ember.sortBy` does not work with Norwegian/Danish alphabet

### ISSUE THREAD

**Issue by kboucher** [emberjs/ember.js#19859]
When using `Ember.sortBy` to sort strings in the Norwegian/Danish alphabet the order is incorrect. This is because the `CompareUtil` employs `localeCompare` without passing in the desired locale identifier:

https://github.com/emberjs/ember.js/blob/v3.25.1/packages/%40ember/-internals/runtime/lib/compare.js

```
    case 'string':
      return spaceship(v.localeCompare(w), 0);
```

It is unclear to me if this used to work in previous client implementations of `localeCompare` but it does not work in modern browsers. I _think_ what is desired here is that `navigator.language` is passed to this instance of `localeCompare`:

```
    case 'string':
      return spaceship(v.localeCompare(w, navigator.language), 0);
```

`localeCompare`: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

### 🔬 Minimal Reproduction
The issue can be observed in this EmberTwiddle: https://ember-twiddle.com/cdb105807ff944b55cf14bdc7e37f9d7

### 😕 Actual Behavior
`Ember.sortBy` incorrectly orders strings beginning with additional Norwegian/Danish characters. (_å_ & _æ_ are sorted as _a_ and _ø_ is sorted as _o_)

### 🤔 Expected Behavior
These characters should be sorted according to the Norwegian/Danish alphabet with those extra characters after a-z and in this order: æ ø å.

### 🌍 Environment

- Ember: - All
- Node.js/npm: - N/A
- OS: - N/A
- Browser: - All

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue.

According to the spec:

> This method may rely on whatever language- and/or locale-sensitive comparison functionality is available to the ECMAScript environment from the [host environment](https://tc39.es/ecma262/multipage/overview.html#host-environment), and is intended to compare according to the conventions of the [host environment](https://tc39.es/ecma262/multipage/overview.html#host-environment)'s current locale.

Also: 

https://stackoverflow.com/questions/55385129/javascripts-standard-api-to-get-the-runtimes-default-locale

If you want to change the behavior, I'd open an issue in the RFC repo to discuss.

However, I think ember is moving away from some of these helper methods, so I'm not sure they'd be open to fix it.

I'll close this for now, because I don't think it's a bug (though I can understand the problem, I'm Swedish myself -- åäö).

By closing some old issues we reduce the list of open issues to a more manageable set. Let me know if you think this is a mistake and that the issue should stay open.
