### ISSUE TITLE
[Bug] Injecting Ember Data Store to Avoid Implicit Injection is Broken

### ISSUE THREAD

**Issue by jherdman** [emberjs/ember.js#19867]
### 🐞 Describe the Bug

In advance of implicit injections of the Ember Data's Store being removed we've been refactoring to explicit injections of the store when we need it. As of Ember v3.28.7 we're seeing errors to this effect:

```
this.store.findAll is not a function
```

Note that this is not unique to `findAll` — any method on Store will fail.

### 🔬 Minimal Reproduction

1. Clone https://github.com/jherdman/ember-data-store-sadness
2. `npm install && npm start`
3. Visit `http://localhost:4200`
4. Open your dev console, see error

### 😕 Actual Behavior

Page does not load, an error is raised as described above.

### 🤔 Expected Behavior

1. No deprecation warning is raised
2. Store works as expected

### 🌍 Environment

- Ember: - 3.28.7
- Node.js/npm: - v16.13.0
- OS: - macOS 12.0.1
- Browser: - Firefox 94.0.2

### ➕ Additional Context

Bug does not occur in Ember v3.28.6

**Comment by jherdman** [comment]
cc @SergeAstapov

**Comment by kpfefferle** [comment]
I'm also seeing this in my app. When I added an explicit injection to these routes, I get a confusing deprecation message:

```
WARN: DEPRECATION: You have explicitly defined a service injection for the 'store' property on <(route)>. However, a different service or value was injected via implicit injections which overrode your explicit injection. Implicit injections have been deprecated, and will be removed in the near future. In order to prevent breakage, you should inject the same value explicitly that is currently being injected implicitly. [deprecation id: implicit-injections] See https://deprecations.emberjs.com/v3.x#toc_implicit-injections for more details.
```

It seems to be simultaneously telling me that the implicit `store` injection is overriding my explicit `store` injection *and* that the fix would be to add an explicit `store` injection? 🤔

cc: @mixonic

**Comment by rwjblue** [comment]
Thanks for the reproduction @jherdman!

**Comment by mixonic** [comment]
It seems the way most Ember apps are setup in late 3.28 (an implicit injection of `store` but also an explicit injection) is not under test. In https://github.com/emberjs/ember.js/pull/19868 I added a test reproducing that state.

The problem here seems to be the deprecation system on CoreObject for the deprecation (warning/assert?) of mis-matched implicit/explicit injections interferes with the deprecation system added in https://github.com/emberjs/ember.js/pull/19854.

Resolution paths could include special-casing the `DeprecatedStoreInjection` value in the CoreObject system (maybe that is fine since this is all dev-only deprecation code in a legacy release), or refactoring the `DeprecatedStoreInjection` wrapper to instead use a WeakSet to track injected instances. Hope to hack on it this evening, but hopefully this context is useful to anyone who might want to expedite.

**Comment by mansona** [comment]
Yea I just hit this one too 🙈 I have a litmus test for this in this PR https://github.com/empress/empress-blog/pull/147

Essentially I expect the `Tests` job to pass and the `no-deprecations` job to fail as it's configured to just throw an error when it hits a deprecation. I know plenty of people noticed this issue before I got a chance to update my PR (timezones am i right!?) but let me know if you want me to test anything on that branch 👍

**Comment by mixonic** [comment]
3.28.8 is out which should address this bug. Thank you for the excellent write up and reproduction @jherdman, they really helped focus the conversation! 🍻

**Comment by mansona** [comment]
Thanks so much for working through this @mixonic 🎉  It's working exactly as it should now 😍
