### ISSUE TITLE
vulnerable dependency in ember 3.24

### ISSUE THREAD

**Issue by AnkitMadhwani93** [emberjs/ember.js#20085]
Hi 

We are getting a vulnerable dependency while doing the npm audit in the ember 3.24 its for the minimist 0.2.1 
Path of the dependency is ember-cli/3.24.0/bower-config/1.4.3/minimist/0.2.1 this one is the critical warning 

Please help us in resolve this 

Thanks in advance

**Comment by chancancode** [comment]
Please report security issues according to the [security policy](https://emberjs.com/security/).

**Comment by chancancode** [comment]
For the record, 3.24 is EOL according to our [support policy](https://emberjs.com/releases/lts/), it will not receive further security patches. Furthermore, this is likely not a "real" security issue, see @ef4's comment [here](https://github.com/ember-cli/ember-cli/issues/9901#issuecomment-1132300637) for details.

That being said, for future reports, please do send suspected security reports through the [proper channels](https://emberjs.com/security/) to ensure a timely response and so that we can avoid discussing/disclosing any sensitive details in public until we have a resolution.
