### ISSUE TITLE
[Bug] Dependency injection doesn't work with javascript Native Classes

### ISSUE THREAD

**Issue by colenso** [emberjs/ember.js#20112]
### 🐞 Describe the Bug
Tried to do a factory injection using native classes instead of ember objects like: https://guides.emberjs.com/release/applications/dependency-injection/#toc_factory-injections

### 🔬 Minimal Reproduction
Here's my test repo: https://github.com/colenso/ember-test
On running the project you'll find an error popping up in the console.
Look at: 
https://github.com/colenso/ember-test/blob/main/app/initializers/logger.js#L4

### 😕 Actual Behavior
Ember is not able to create an instance of the class when injecting the dependency.

### 🤔 Expected Behavior
We should receive a instantiated copy of the object.

### 🌍 Environment

- Ember: - 4.2.0
- Node.js/npm: - 14.19.0
- OS: - Mac
- Browser: - Chrome

**Comment by kategengler** [comment]
This was deprecated in 3.x and removed in 4.x https://deprecations.emberjs.com/v3.x#toc_implicit-injections 

I believe the bug in this case is the documentation in the guides, can you confirm @locks?

**Comment by chancancode** [comment]
I think the _registration_ part is okay (you can do `owner.lookup('logger:main')` to get it):

```js
application.register('logger:main', Logger);
```

but yeah the "implicit injection" part is deprecated and removed so at least that should be removed from the guides:

```js
application.inject('route', 'logger', 'logger:main');
```

That being said I believe the actual contract for register is "something with a create method on it", so this would work:

```js
class Logger {
  static create() {
    return new Logger();
  }

  log(m) {
    console.log(m);
  }
}

application.register('logger:main', Logger);
```

and so would this:

```js
class Logger {
  log(m) {
    console.log(m);
  }
}

application.register('logger:main', new Logger(), { instantiate: false });
```

**However** I am not sure most of this content have a place in the guides anymore. In modern Ember these APIs are almost never the right answer and have very little real world use (just use a service, etc).

So I don't think there is an actual bug here, except perhaps some documentation fixes, but mostly IMO a lot of these should just be removed or demoted to API level docs only.

@colenso I suggest that you ask/discuss your actual use case in Discord and you may be able to get better suggestions on some better patterns to do it in modern Ember.
