### ISSUE TITLE
[Bug] COMPUTED_DECORATOR might be undefined when assertion check

### ISSUE THREAD

**Issue by oriSomething** [emberjs/ember.js#20266]
Sorry for the less using the whole format, I've just encounter this bug while trying to make Ember run via ESBuild.

### 😕 Actual Behavior

In:

https://github.com/emberjs/ember.js/blob/16136bfcb6a0242d9c55ca7023ab8ea317167c71/packages/%40ember/-internals/metal/lib/decorator.ts#L129

```js
 assert(
      `Only one computed property decorator can be applied to a class field or accessor, but '${key}' was decorated twice. You may have added the decorator to both a getter and setter, which is unnecessary.`,
      isClassicDecorator ||
        !propertyDesc ||
        !propertyDesc.get ||
        !COMPUTED_GETTERS.has(propertyDesc.get)
    );
```

`COMPUTED_GETTERS` might not be defined, since in https://github.com/emberjs/ember.js/blob/16136bfcb6a0242d9c55ca7023ab8ea317167c71/packages/%40ember/-internals/metal/lib/decorator.ts#L80 it might not created, when not in DEBUG

```
export let COMPUTED_GETTERS: WeakSet<() => unknown>;

if (DEBUG) {
  COMPUTED_GETTERS = new WeakSet();
}
```

### 🤔 Expected Behavior

`COMPUTED_GETTERS` should be check only if `DEBUG` is `true`?

**Comment by chriskrycho** [comment]
Thanks for the report. This is expected behavior: Ember's build pipeline currently assumes a bunch of things are managed via Ember CLI and Babel. Accordingly, I'm going to close this (but we can keep chatting here anyway!). The `DEBUG` flag here is set up such that it is always `true` in development builds and always `false` in production builds, using [a Babel plugin](https://www.npmjs.com/package/babel-plugin-debug-macros). In a production build, `terser` will notice that the result of Babel is `if (false) { ... }` and eliminate it as dead code. ESBuild likely has similar tooling available via plugin—it's not quite the same, but you may be able to get the same basic behavior using [esbuild-plugin-drop](https://github.com/pirxpilot/esbuild-plugin-drop).
