### ISSUE TITLE
Multiple Query Params retaining issue in Ember 3.3.0

### ISSUE THREAD

**Issue by vinothkumarkp** [emberjs/ember.js#20265]
"router.js" entry: 
this.route('commits/list', {path: 'commits/:branch_name/*file_path'});

'commits/list' route queryparams details:  ['changeset', 'searchKey']

Usecase : 

Step 1 : When I navigate commits/list route at first time in UI, I can append multiple queryparams like this
https://myurl.com#/commits/master/testrepository?changeset=a8d6f9484c7867706d43650bf1867217c53598c8&searchKey=issue

Step 2 : In commits/list route page, after I navigate same route, I could not append multiple queryparams. At a time only single queryparams is coming. Previous one is replaced and going to null.

Demo: 
commitsListController.set("changeset", "a8d6f9484c7867706d43650bf1867217c53598c8");
commitsListController.set("searchKey", "issue");

URL will be like this : 
https://myurl.com#/commits/master/testrepository?changeset=a8d6f9484c7867706d43650bf1867217c53598c8&searchKey=issue

After I use like this : 
commitsListController.transitionToRoute('commits/list', 'BUG_FIX', 'testrepository');

commitsListController.set("changeset", "a8d6f9484c7867706d43650bf1867217c53598c8");
commitsListController.set("searchKey", "issue");

URL will be only like this : 
Either this
https://myurl.com#/commits/master/testrepository?changeset=a8d6f9484c7867706d43650bf1867217c53598c8
(OR) this:
https://myurl.com#/commits/master/testrepository?searchKey=issue

Multiple queryparam did not update.

**Comment by chriskrycho** [comment]
Hi @vinothkumarkp – sorry you're having issues here. Unfortunately, I don't think we're going to be able to identify what the issue is here without much more information, but from what you have shared here it looks like it's an issue in how you have things configured not a bug in Ember. We don't use GitHub issues for general Q&A, only for bug reports, feature requests, etc., so you might ask this on [the forum](http://discuss.emberjs.com/) or [in Discord](https://discord.gg/emberjs). As a starting point, I would look at [the docs for query params](https://guides.emberjs.com/v4.7.0/routing/query-params/). Good luck!
