### ISSUE TITLE
[Bug] Not possible to have an `append` method in a classic component with the stable types

### ISSUE THREAD

**Issue by boris-petrov** [emberjs/ember.js#20484]
### 🐞 Describe the Bug
Check the repro. An `append` method leads to an error:

```
app/components/foo-component.ts:8:10 - error TS2416: Property 'append' in type 'FooComponent' is not assignable to the same property in base type 'Component<unknown>'.
  Type '() => void' is not assignable to type '() => this'.
    Type 'void' is not assignable to type 'this'.
      'this' could be instantiated with an arbitrary type which could be unrelated to 'void'.

8   public append() {
           ~~~~~~
```

### 🔬 Minimal Reproduction
[Repo](https://github.com/boris-petrov/ember-type-bugs).

Run `npm install` and then `./node_modules/.bin/tsc`.

### 😕 Actual Behavior
Type error on `append`.

### 🤔 Expected Behavior
No error. Removing the last commit (which upgrades Ember) and rerunning `npm install` and then `tsc` will remove the errors.

### 🌍 Environment

- Ember: 5.1.0
- Node.js/npm: 20.3.1/9.7.2
- OS: Linux
- Browser: N/A

cc @chriskrycho

**Comment by chriskrycho** [comment]
This is expected behavior, although annoying: the `ViewMixin.prototype.append` method is private API (and [is documented][docs] as such!) and *should not* be overridden. The types are capturing this and letting you know!

[docs]: https://github.com/emberjs/ember.js/blob/8123d562c13d733e5509682a655f7187bcc6b55b/packages/%40ember/-internals/views/lib/mixins/view_support.ts#L261
