### ISSUE TITLE
Unexpected/Duplicate Inclusion CSS in Build Output even without Importing in ember 5.9

### ISSUE THREAD

**Issue by zaffar415** [emberjs/ember.js#20706]
### 🔬 Minimal Reproduction
I have updated my project from ember version 5.4 to 5.9.

Install ember-power-select or any addon which contains css
``` ember install ember-power-select```

And then build project using the cmd
```npm run build ```

And then i can see that chunk files are being created with the addon css even it is not imported in app.css file
Moreover, the scss files from my addon is also exported to the dist folder.
![image](https://github.com/emberjs/ember.js/assets/74136549/30d08ae8-fdc1-456a-99df-cd06f44a50b9)

### 🤔 Expected Behavior
The dist folder should only contain the plain css and js which is required.
It should not have any duplicate css files with the name of chunk-*.css.

### 🌍 Environment

- Ember: 5.9
- Ember-CLI: - 5.9
- Node.js/npm: - 20.14.0
- OS: - Ubuntu
- Browser: - Chrome

**Comment by kategengler** [comment]
@zaffar415 Are you using embroider or only ember-auto-import?

**Comment by zaffar415** [comment]
> kategengler

I am using the default "ember-auto-import": ^2.7.3

**Comment by kategengler** [comment]
I'm not sure this is a bug -- files may be generated that aren't referenced or used by the project.

cc @ef4

**Comment by ef4** [comment]
Yeah I don't see any bugs here. If an addon has a component that imports CSS, you don' get to pick whether the CSS gets included. It will get included if the component is included (and in a classic build, all components are always included. Under embroider only used components are included).

If an addon author wants to make their CSS optional, instead of importing it from their own component they should tell app authors to import it directly if they want it.

**Comment by kategengler** [comment]
This not an ember-source issue.
