### ISSUE TITLE
Weird behaviour when deleting the last element in an ArrayProxy

### ISSUE THREAD

**Issue by victorsavu3** [emberjs/ember.js#4306]
JSBin that shows the problem (click remove and then add):

http://jsbin.com/eYonAsA/1/edit

After removing and adding a new element 3 items appear (the old one and the new one twice). There is an exception when the last element is removed.

**Comment by drogus** [comment]
I ran into this bug and I spent some time investigating it today. The underlying issue is that `CollectionView` adds an array observer on content and it depends on 2 things:

* array proxy content items being changed
* array proxy content being changed

This results in 2 calls to `arrayWillChange` before any of the calls to `arrayDidChange` can be done. `arrayWillChange` is first invoked as a result of `dependentKeysWillChange` and then `chainsWillChange`. 

I believe that it could be fixed by keeping meta information on a number of running array observers and skipping `arrayWillChange` runs if it was already ran. I'll try to come up with an example solution, but if you have any other ideas, please let me know.

**Comment by drogus** [comment]
I forgot about an example setup without a `CollectionView`:

```javascript
  var arrayProxy = ArrayProxy.extend({
    arrangedContent: Ember.computed('content.[]', function() {
      return this.get('content');
    })
  }).create(Ember.A(['first-item']));

  var wrapper = Ember.ArrayProxy.extend({
    content: arrayProxy,

    init: function() {
      var ret = this._super();
      this._contentDidChange();
      return ret;
    },
    _contentDidChange: function() {
      var content = get(this, 'content');
      if (content) {
        content.addArrayObserver(this);
      }
    },
    arrayWillChange: function(content, start, removedCount, addedCount) {
      console.log('arrayWillChange', start, removedCount, addedCount);
    },
    arrayDidChange: function(content, start, removed, added) {
      console.log('arrayDidChange', start, removed, added);
    }
  }).create();

  run(function() {
    arrayProxy.set('content', Ember.A(['new-first-item']));
  });
```

**Comment by rwjblue** [comment]
Seems to be working correctly now ([demo here](http://rwjblue.jsbin.com/veyeye/edit?html,js,output)).  Closing for now, we can open a new issue with reproduction steps.
