### ISSUE TITLE
Named vs Unnamed iterator in {{#each}} block

### ISSUE THREAD

**Issue by mehulkar** [emberjs/ember.js#4863]
Not sure if this is intended or not, but I found that if I name the iterator in my {{#each}} block and use the `{{render}}` helper inside the loop, the iterator is available in the rendered controller. If I don't name it, it is not available. Not sure if this is intended or not, but it can be confusing. 

Example:

```handlebars
{{#each thing in controller}}
  {{render 'foo' thing}}
{{/each}}
```

versus

```handlebars
{{#each controller}}
  {{render 'foo' this}}
{{/each}}
```

In the first example, the  `foo` controller has a `thing` property defined that is the same as the model. In the second example, there is no `thing` property. 

~~JSBIN: http://emberjs.jsbin.com/migub/1/edit?html,js,output~~

**UPDATE**: It seems that the problem is more about properties not being read from the rendered controller and coming from the parent controller instead. Here's a better JSBIN to demonstrate:

http://emberjs.jsbin.com/migub/3/edit?html,js,output

**Comment by rwjblue** [comment]
The issue is that the `user` keyword scope is being hit before the local path lookup (see [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/streams/context_stream.js#L30)).  `Ember.View` sets `this._keywords` up to initially inherit from the parent template scope [here](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/views/view.js#L1072-1078) (in this case the outer context where `render` helper is being called).

**Comment by stefanpenner** [comment]
we now jsut support `{{#each something as |entry|}}`
