### ISSUE TITLE
New Ember Select

### ISSUE THREAD

**Issue by wagenet** [emberjs/ember.js#5259]
The existing Ember.Select has many known issues. The eventual plan is to create a new simpler version and deprecate the old one.

@rwjblue has some preliminary work on this.

**Comment by lolmaus** [comment]
Many issues were closed in favor of this one.

But this issue lacks specificity. It just says "make Ember.Select better", and there's no plan what exactly should be done.

So it looks like nobody solves former Ember.Select issues because all the tickets are closed, and nobody works on the new Ember.Select because there are no details.

**Comment by knownasilya** [comment]
@rwjblue will tell you exactly what's wrong with the old one.

Mainly performance, like 400-600ms performance drains, and it's not a component.

**Comment by cowboyd** [comment]
FWIW, we just wrap `<select>` elements and `<option>` elements in components that select objects instead of strings. Here it is as an ember-cli addon:

https://github.com/thefrontside/emberx-select

**Comment by lolmaus** [comment]
@knownasilya, i'm not asking out of curiosity. I want to see a roadmap list, so that no closed issue is forgotten.

**Comment by wagenet** [comment]
@lolmaus We specifically aren't guaranteeing that the new version will attempt to do as much as the old one. It's going to be a start from scratch, likely with fewer features and less complexity.

**Comment by atomkirk** [comment]
If you bind the value of the select to a computed property that can be set, and you set that value to, in my case `undefined`, the underlying value backing the computed property gets set to `undefined`, which triggers an update to the Ember.Select component, and if, as a result of that update, it changes the selected value of the Ember.Select, it bounces back, setting the computed property to whatever the new value of the Ember.Select is. So:
1. Ember.Select value is bound to computed property
2. Computed property is settable and has a complex dynamic property backing it.
3. Set the computed property to `undefined`
4. the computed property is called with `value = undefined` `previousValue = 0.7` (for example)
5. the computed property is called again with `value = 0.7` `previousValue = 0.7`
6. The backing value of the computed property is set to `0.7` rather than `undefined` as it should be.

Should I make an issue for this or should I wait for the new Ember.Select?

**Comment by stefanpenner** [comment]
You can now implement select in the following way: (note, you can make it as complex or as simple as you want, its just DOM)

```hbs
    <select onchange={{action "changed" value="target.value"}}>
        {{#each model.choices key="@identity" as |choice|}}
          <option value={{choice}} selected={{is-equal currentValue choice}}>{{choice}}</option>
        {{/each}}
      </select>    
```
example:  http://jsbin.com/xalujucona/edit?html,css,js,output

Also Ember.Select is deprecated.
