### ISSUE TITLE
Deprecate slash as namespace

### ISSUE THREAD

**Issue by wagenet** [emberjs/ember.js#5260]
Currently a slash in lookups is used for namespaces. We'll be deprecating this.

- [ ] next release: deprecate
- [ ] subsequent release: remove code

**Comment by machty** [comment]
Just to clarify so that I might not confuse myself about this in the future: namespace in this context refers to global namespaces; it does not refer to route "namespaces". In the case of routes, we want to support `this.resource('foo/bar')` and deprecate `this.resource('foo.bar')` (please someone correct me if I'm wrong).

**Comment by stefanpenner** [comment]
> In the case of routes, we want to support this.resource('foo/bar') and deprecate this.resource('foo.bar') (please someone correct me if I'm wrong).

you are correct

**Comment by stefanpenner** [comment]
We MUST kill this for 2.0 this time. I will basically quit computers if we dont

**Comment by stefanpenner** [comment]
https://github.com/emberjs/ember.js/blob/dc0938c84d4de3cd6a2af29e3e327a7b107f15ae/packages/ember-routing-htmlbars/lib/keywords/render.js#L76-L78 cc @martndemus
