### ISSUE TITLE
replaceWith() loses query-params

### ISSUE THREAD

**Issue by H1D** [emberjs/ember.js#5526]
Seems like `replaceWith()` don't respect `query-params`. When redirecting from one subroute to another using `replaceWith()` query-params of a **parent** route gets lost. 

**JSBin:** http://jsbin.com/kinov/4
**Example**
Here is minimal code to reproduce:

```
App = Ember.Application.create()

App.Router.map ->
  @resource "lesson", ->
    @resource "slide"

App.LessonIndexRoute = Ember.Route.extend
  redirect: ->
    @replaceWith 'slide'

App.LessonController = Ember.Controller.extend
  queryParams: [ 'course' ]
```

index.hbs:

```
   {{#link-to 'lesson' (query-params course="bla-bla")}}
     lesson
   {{/link-to}}
```

slide.hbs

```
   <b>Slide template rendered. Attention to the URL.</b>
```

**Comment by dschmidt** [comment]
I see the very same behaviour with `this.redirectTo` in 1.11.1.

**Comment by seawatts** [comment]
I am also seeing this in 1.11.x

**Comment by bladnman** [comment]
Feature still needed and this is still happening in Ember  : 2.4.6

**Comment by john-kurkowski** [comment]
`replaceWith` does seem to honor the same, final "options" object as `transitionTo`. Ember/CLI 2.x workaround:

```js
beforeModel(transition) {
  let { queryParams } = transition;
  this.replaceWith('your-next-route', { queryParams });
},
```

(Maybe you could just pass the `transition` directly. I worry that being interpreted as a model rather than an "options" object. And this is more explicit what problem you're working around.)

**Comment by pixelhandler** [comment]
@H1D @bladnman @seawatts @john-kurkowski is this still an issue, perhaps we should close or create a new reproduction of this, what do you think?

**Comment by H1D** [comment]
@pixelhandler seems like this is not an issue anymore  – https://ember-twiddle.com/2c2b711d799e789ad7043eaf94924108

---

But I've noticed something else
 - when "lesson" link clicked for the first time route `lesson.slide` became active due to `redirect()` in lesson route
 - if link clicked again route 'lesson' became active. Seems like `redirect()` wasn't called

Is this a correct routing behaviour?

**Comment by pixelhandler** [comment]
@H1D I'll close this issue for now, perhaps reach out on the Ember Discord help channel to discuss further.

**Comment by sevab** [comment]
I'm having a similar issue. Unless a queryParam is defined on the destination controller, it is currently removed by `replaceWith`. Unsure if it's expected behaviour or not.

In the example below (full [ember-twiddle here](https://ember-twiddle.com/67fbab56cd02d9b6016c3299b0445c00?openFiles=controllers.application.js%2C)), landing on the redirect route, takes you to the destination route, but only keeps the query param that is defined on destination controller (`utm_medium`), and removes the other (`utm_source`):

 
```javascript
// routes/redirect-page.js 
export default Ember.Route.extend({
  beforeModel(transition) {
    this.replaceWith('/destination?utm_medium=email&utm_source=newsletter')
  }
});

// controller/destination.js 
export default Ember.Controller.extend({
  queryParams: [ 'utm_medium' ], // omit utm_source on purpose
});

// Final url: 
// /destination?utm_medium=email
```
