### ISSUE TITLE
Ember 1.8.1 breaks inserting <script> tags with {{{tripleBraces}}}

### ISSUE THREAD

**Issue by Kerrick** [emberjs/ember.js#9557]
Reduced Test Cases: [1.7.0, working](http://emberjs.jsbin.com/sukaqizutu/1/edit?html,output) and [1.8.1, not working](http://emberjs.jsbin.com/qelafiqiku/1/edit?html,output).

It seems the browse never even attempts to GET the referenced script.

**Comment by stefanpenner** [comment]
I believe this works now.

**Comment by Kerrick** [comment]
It still does not work [as of 2.3.0](http://emberjs.jsbin.com/xeqihovuvu/1/edit?html,css,js,output) and [1.13.13](http://emberjs.jsbin.com/pihuvexewu/1/edit?html,css,js,output).

**Comment by rwjblue** [comment]
I'm not really sure this is intended to work.

**Comment by Kerrick** [comment]
If it doesn't work, that means any sort of script-based embedded content won't work. For example, in a CMS that allows users to edit a page or post, rendering it with triple braces would need this functionality for the public site or the admin preview.

**Comment by appleguy19** [comment]
We need this functionality too. Is this a "won't fix" issue?

**Comment by locks** [comment]
@appleguy19 what version of Ember are you using?

**Comment by appleguy19** [comment]
@locks It is not working on [2.10.0](http://jsbin.com/boculihiwi/edit?html,js,output). I'm guessing it has something to do with ['Metal-Views' that happened in 1.8.0](http://emberjs.com/blog/2014/10/26/ember-1-8-0-released.html#toc_major-rendering-layer-refactor-metal-views)

**Comment by ef4** [comment]
The current behavior is consistent with how browsers behave if you try to put `<script>` tags in `innerHTML`. They don't run. Because most of the time when people do this, they're introducing major security vulnerabilities.

If you really want to run javascript embedded in HTML coming out of your CMS (allowing anyone who can edit the content to steal any other user's identity!), you can implement it yourself via [DOMParser](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser) and [eval](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval).

**Comment by Kerrick** [comment]
The argument about security vulnerabilities seems a little off-base, because triple braces are a security opt-out that already open you up to vulnerabilities through images and iframes and other insecure elements.

This functionality is pretty basic -- things like [embedding a tweet](http://jsbin.com/boculihiwi/edit?html,js,output) in a blog post are broken because script tags aren't evaluated. Too many social site embeds rely on `<script>` tags being evaluated to have this be broken in Ember core and leave it up to each app developer to fix.

**Comment by ef4** [comment]
> The argument about security vulnerabilities seems a little off-base, because triple braces are a security opt-out that already open you up to vulnerabilities through images and iframes and other insecure elements.

I agree that triple curlies already offer attack vectors. But there is still an important distinction in terms of the developer ergonomics.

When a random developer is tasked with "allow people to embed tweets in their posts", they will probably try using triple curlies. *I don't want that to succeed!* Because triple curlies are the wrong implementation for that feature, because it's too dangerous. The right implementation is Twitter's oEmbed API.

I'm not claiming this is a panacea. People will obviously try to use triple curlies for other reasons too, and sometimes it will appear to do what they want, and they will leave their users vulnerable. But I am unsympathetic to any argument for making triple curlies even more useful. I would make them feel more broken if I could.
