### ISSUE TITLE
Transitioning to same route/model can break queryParams cache

### ISSUE THREAD

**Issue by awaer** [emberjs/ember.js#9579]
There seems to be an issue with `queryParams` being cached on the route when transitioning to the same route using the same model. For example, when using a catch all route `{path: '*path'}`

When entering a second time, the cached `queryParams` are not found.

http://emberjs.jsbin.com/wunadi/edit?js,output

**Steps to reproduce the issue:**

1. Click "zip"
2. Click the "Randomize bar" and "Randomize baz" buttons, notice both params update accordingly
3. Click "zam"
4. Click the "Randomize bar" and "Randomize baz" buttons, notice that one will update, but clear the other

If you change the model (click index), then enter one of those routes, the `queryParams` update properly.

After some digging in, it looks to be in the route caching (specifically in the `_qpChanged` and the `_updateCacheParams` methods), which sticks with the initial setup of the route and its `bucketKey`. Subsequent attempts to stash the cache use the current path, causing a mismatch. Or something.

** *Tested and verified using latest master release.*

**Comment by rwjblue** [comment]
Updated the JSBin to work on canary: http://rwjblue.jsbin.com/sepusu/edit?html,js

Seems to be working properly (or I misunderstand the bug).  Happy to reopen if I misunderstood (or broke the JSBin while updating it).

**Comment by maxmalov** [comment]
It seems there is a case when query params won't be cached in the way I was expecting, at least. I've prepared a little quick demo to show the case, you can checkout it here: http://maxmalov.github.io/ember-query-params-cache-miss/#/parent/hello

Steps to reproduce:

1. First of all we need to initialize query parameters on this route by clicking "Set query params" button. It will take a little bit of time, because **query param was setup to refresh route model** (there is a delay in the `model` hook to simulate heavy http request). Make sure query was changed.
2. Try to navigate between child routes by clicking "To child 1" and "To child 2" links. Query param will be picked up from cache _as expected_.
3. Now lets make transition to the same route, **`transitionToRoute` call was used intentionally in this case**, but **change route and query params** by clicking "Transition to this route with different query" button. It again will take some time, make route and query params were updated.
4. Now lets navigate between child routes by clicking "To child 1" and "To child 2" links. Query param won't be picked up from cache and url won't contain any query at all. That's kind of unexpected.

I was diving into a debug and noticed that query params change action was called before the transition to the same route at step 3, so new query param was cached to an old route.

Sources are here: https://github.com/maxmalov/ember-query-params-cache-miss

_** Tested and verified against 2.0.2 and 2.1_
