### ISSUE TITLE
transitionTo in afterModel with object param causes infinite loop

### ISSUE THREAD

**Issue by EndangeredMassa** [emberjs/ember.js#9715]
In a route's `afterModel` hook, if you `transitionTo` another route by providing an object param, the app locks up in an infinite loop. As you can see in the image below, the transition is aborted, but the previous route tries to redirect straight back to the problem route.

![console-infinite-loop](https://cloud.githubusercontent.com/assets/41545/5188588/f38d76bc-749b-11e4-940a-fd903b35fd39.png)

If you use a string value instead of an object value for the `transitionTo` param, this works fine. If you use the `redirect` hook instead of the `afterModel` hook, this will work fine.

[The documentation](http://emberjs.com/guides/routing/redirection/#toc_after-the-model-is-known) appears to recommend this currently broken approach.

You can try this for yourself with this [jsbin](http://jsbin.com/satapififo/1).

---

What should be done about this? It seems like a bug. I'm happy to start a fix, but I'd like some direction on what needs to change and how.

**Comment by rwjblue** [comment]
The issue here is that you are transitioning into a child route in the parent routes `afterModel`.

1. The `post` `afterModel` transitions to `comments`
2. To transition into `comments` we have to traverse through `post`
3. `post` `afterModel` is called again
4. repeat

I do not think this is a bug....
