### ISSUE TITLE
Mixin#detect should work like CoreObject#detect

### ISSUE THREAD

**Issue by Herriau** [emberjs/ember.js#9799]
It looks like `CoreObject` provides `detect(class)` and `detectInstance(instance)` that can be used like so:

```javascript
var Vehicle = Em.Object.extend();
var Car = Vehicle.extend();

console.log(Vehicle.detect(Car)); // true
console.log(Vehicle.detectInstance(Car.create())); // true
```

On the other hand `Mixin` seems to only provide `detect(instance)`:

```javascript
var Movable = Em.Mixin.create();
var Vehicle = Em.Object.extend(Movable);
var Car = Vehicle.extend();

console.log(Movable.detect(Car.create())); // true
console.log(Movable.detect(Car)); // false :(
console.log(Movable.detect(Vehicle)); // false as well :(
```

After some looking around I came to the conclusion that there is no public API to check whether a class uses a given mixin (either directly or indirectly). In my opinion `Mixin#detect` should be renamed `Mixin#detectInstance` and have `Mixin#detect` work like `CoreObject#detect` to make it consistent. Thoughts?

**Comment by stefanpenner** [comment]
this is working as expected

**Comment by Herriau** [comment]
@stefanpenner If like you said `Class` inherits from `Mixin`, then wouldn't it make sense that they fulfill the same API? As highlighted in my original post, `Mixin.detect()` != `Class.detect()`, which IMO violates the inheritance. If you guys are happy with this discrepancy then great, otherwise please consider re-opening this issue because this is confusing as hell.

**Comment by stefanpenner** [comment]
There is no discrepancy. JavaScript has accomplishes inheritance via two prototype chains (class side, and instance side);

```js
function PromiseSubclass() {

}

PromiseSubclass.prototype = Object.create(Promise.prototype) // instance side (then/catch)
PromiseSubclass.__proto__ = Promise // class side (resolve/reject/race/all)
Object.setPrototypeOf(PromiseSubclass, Object.getPrototypeOf(Promise)) // class side (resolve/reject/race/all)
```

Unfortunately ember predates `__proto__` and `getPrototypeOf`, and as such accomplishes this exact JS feature somewhat more manually, by creating two first class prototype chains. Mixin for Class, and Mixin for instance (`Class.InstanceMixin`)... (as semver allows and as platforms improve, we plan to just use the platform provided machinery).

```
A.detect(otherThing)// detects if otherThing is a descendent of the classSide of A
A.InstanceMixin.detect(otherThing) // detects if otherThing is a descendent of the instanceSide of A
// but a nicer public API is:
A.detectInstance(otherThing) // detects if otherThing is a descendent of the instanceSide of A
```

a more full example

```js
A = Ember.Object.extend()
A.detectInstance(A.create())
> true
A.detect(A.create())
> false
A.detect(A)
> true
B = A.extend()
B.detect(A)
> false
A.detect(B)
> true
A.detectInstance(B.create())
> true
B.detectInstance(B.create())
```

**Comment by stefanpenner** [comment]
I should actually say, the above I believe demonstrates no observable discrepancy. But given the above examples feel free to point out issues, or additional scenarios that do not fit the described model.

**Comment by Herriau** [comment]
@stefanpenner I really appreciate your comprehensive answer, however I don't believe it addresses the inconsistency mentioned previously.

I perfectly understand the need for two prototype chains and as a consequence the need for two APIs to check inheritance:

* On the class side (`detect(class)`) 
* On the instance side (`detectInstance(instance)`).

No questions asked.

However, if `Class` is a `Mixin`-like object, at least conceptually (to quote your words "Class inherits from Mixin"), then it would only make sense that `Class` embraces the `Mixin` API to its fullest extent (this would otherwise constitute a violation of the contract set forth by `Mixin`, albeit conceptual). This does not seem to be the case today:

`Mixin` provides the following API:
```
detect(instance)
```

`Class` provides the following API:
```
detect(class)
detectInstance(instance)
```

(Notice how the signature of `detect()` has changed from accepting an `instance` to accepting a `class`, which is __the inconsistency I have been trying to highlight__)

Why wouldn't it be possible for both Mixins and Classes to implement the following API:
```
detect(class)
detectInstance(instance)
```

**Comment by stefanpenner** [comment]
> (Notice how the signature of detect() has changed from accepting an instance to accepting a class, which is the inconsistency I have been trying to highlight)

The signature has not changed, the example uses `class` and `instance` to disambiguate between the two separate mixin hierarchies.

`detect` accepts any object, and returns true if that object is descendent of the given `Mixin`, and false if it is not.
https://github.com/emberjs/ember.js/blob/master/packages/ember-metal/lib/mixin.js#L604-L610

> Why wouldn't it be possible for both Mixins and Classes to implement the following API:

Mixins are the building block used to implement classes. More specifically, a Mixin has no concept of `instance`, that construct is an [implementation detail of `Class`](https://github.com/emberjs/ember.js/blob/master/packages/ember-runtime/lib/system/core_object.js#L638-L639). Note, `Class` is a composition of several Mixin hierarchies.

An analogy could be edge vs polygon, it is true they are related, polygons are composed of edges, but an edge itself has no concept of multiple edges or how they could be composed to create a polygon. That relationship defines polygon.

If we look at Class (or CoreObject) today we see `Class` has many mixin, and describes the relationship between them. That relationship essentially defines what a class is. 

Although it is plausible to consider mixins morphing into something else, it is unlikely we will pursue this. Mixins in ember exist largely due to `descriptors`,  `__proto__`, `getPrototypeOf`, `setPrototypeOf`, & `super` not existing in runtimes. As these features have landed (or continue to land in the case of `super`) the need for our own dual inheritance (class side / instance side) and user-land super chains should evaporate. We are active on TC39 aligning new features of JS and Ember, so someday (hopefully sooner rather then later) we can remove more and more of ember.

**Comment by Herriau** [comment]
@stefanpenner Again, I understand the concept, but I still believe that the way the internals are laid out should not preclude a good public API. Remember that most Ember users are not aware of these internals, nor should they have to be aware of it, and use Mixins as interfaces and/or traits (and Ember itself sets the example: `Em.Comparable`, `Em.Enumerable`, `Em.Copyable`, etc.).

Let me conclude by rephrasing my original request in yet another form: How am I suppose to achieve the following without using private APIs:

```javascript
// Test whether `FooClass` implements the `Em.Observable` interface
Em.Observable.detect(FooClass.PrototypeMixin)
```
