### ISSUE TITLE
input type=submit default value regression

### ISSUE THREAD

**Issue by knownasilya** [emberjs/ember.js#9809]
So before Ember 1.8, the following code:

```hbs
{{input type='submit'}}
```

Returned a button with the default value of "Submit", now it has no value.

Working: http://emberjs.jsbin.com/keyefolate/1/
Broken: http://emberjs.jsbin.com/keyefolate/2/

**Comment by rwjblue** [comment]
Why would you want to use `{{input type="submit"}}` without a specified `value`? In that case why not just use `<input type="submit">`?

**Comment by knownasilya** [comment]
Not sure :smile_cat: but it's still a regression lol

**Comment by rwjblue** [comment]
Some research:

The `value` attribute is being set because it is initialized to an empty string (both in [Ember.TextSupport](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/mixins/text_support.js#L106) and [Ember.TextField](https://github.com/emberjs/ember.js/blob/master/packages/ember-views/lib/views/text_field.js#L65)).  Removing those default values fixes the issue reported.

It is odd that we are using `Ember.TextField` in the case where `type="submit"` was specified, but we assume that any input other than checkbox is an `Ember.TextField` ([here](https://github.com/emberjs/ember.js/blob/master/packages/ember-htmlbars/lib/helpers/input.js#L196)).

**Comment by rwjblue** [comment]
We can create another component for `type="submit"` that we use instead of `Ember.TextField` that does not inherit from `Ember.TextSupport` or `Ember.TextField` (possibly making them both inherit from a common base `Ember.InputField` or something).

@mixonic - Thoughts?

**Comment by knownasilya** [comment]
Very weird indeed. That sounds a little more logical.

**Comment by mixonic** [comment]
@rwjblue or a general button class. These seem ripe to become a series of mixins (as views in general are).

Working on the changes to attribute bindings I've definitely noted other places where we have bindings that seem un-expected. With a test I can see if my changes there address the issue.

But regardless a slimmer view/component makes sense.

**Comment by stefanpenner** [comment]
i believe this is fixed, if not `<input type="submit" value={{value}} oninput={{action changed value="target.value"}}>` now works as expected
