### ISSUE TITLE
Query Params - broken mapping

### ISSUE THREAD

**Issue by gagoman** [emberjs/ember.js#9860]
Good day.

When using `queryParams` mapping, as shown below, it is unclear what should be used in
`Route`s `model` hook.

Example: http://emberjs.jsbin.com/balewu/3/edit

If you'll open jsbin, you'll see that:

* `transition.queryParams` support names mapping while `params` contains keys from controller
* `transition.queryParams` are not updated when extra action is fired from controller's action.
* `queryParams` are always undefined while [doc](http://emberjs.com/api/classes/Ember.Route.html#method_model) says it should

You can check it like this:

* add some strings to array via input
* click `Filter` (`params` and `transition.queryParams` would be simillar)
* click `Clear` (`params` would be empty array while `transition.queryParams` - not)

Please, advice.

Thank you.

**Comment by machty** [comment]
I think the docs have been fixed for this. `transition.queryParams` I don't think is mentioned in the docs anywhere and is private API (internally used by router.js microlib). I'm closing this because these bugs and similar are likely not going to be fixed before query params API shifts to route-driven components.
